# Generated by Django 4.2.9 on 2026-01-30 22:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sube', '0001_initial'),
        ('egitim_tanimlari', '0001_initial'),
        ('egitim_yili', '0001_initial'),
        ('kurum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_kimlik_no', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='TC Kimlik No 11 haneli olmalıdır', regex='^\\d{11}$')], verbose_name='TC Kimlik No')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyad')),
                ('dogum_tarihi', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('cinsiyet', models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kadın')], max_length=1, null=True, verbose_name='Cinsiyet')),
                ('gorev_turu', models.CharField(choices=[('OGRETMEN', 'Öğretmen'), ('KOC', 'Koç'), ('DANISMAN', 'Danışman'), ('IDARI', 'İdari Personel')], default='OGRETMEN', max_length=20, verbose_name='Görev Türü')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('adres', models.TextField(blank=True, verbose_name='Adres')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('brans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personeller', to='egitim_tanimlari.ders', verbose_name='Branş')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personeller', to='kurum.kurum', verbose_name='Kurum')),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personeller', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personeller',
                'db_table': 'personel',
                'ordering': ['soyad', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='KocAtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atama_tarihi', models.DateField(auto_now_add=True, verbose_name='Atama Tarihi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koc_atamalari', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('koc', models.ForeignKey(limit_choices_to={'gorev_turu': 'KOC'}, on_delete=django.db.models.deletion.CASCADE, related_name='koc_atamalari', to='personel.personel', verbose_name='Koç')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koc_atamalari', to='kurum.kurum', verbose_name='Kurum')),
            ],
            options={
                'verbose_name': 'Koç Ataması',
                'verbose_name_plural': 'Koç Atamaları',
                'db_table': 'koc_atama',
                'ordering': ['-egitim_yili', 'sinif'],
            },
        ),
    ]
