# Generated by Django 4.2.9 on 2026-01-30 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sinif', '0001_initial'),
        ('sube', '0001_initial'),
        ('personel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kocatama',
            name='sinif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koc_atamalari', to='sinif.sinif', verbose_name='Sınıf'),
        ),
        migrations.AddField(
            model_name='kocatama',
            name='sube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koc_atamalari', to='sube.sube', verbose_name='Şube'),
        ),
        migrations.AddIndex(
            model_name='personel',
            index=models.Index(fields=['kurum', 'sube', 'aktif_mi'], name='personel_kurum_i_281c91_idx'),
        ),
        migrations.AddIndex(
            model_name='personel',
            index=models.Index(fields=['gorev_turu'], name='personel_gorev_t_e4be7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='personel',
            constraint=models.UniqueConstraint(condition=models.Q(('tc_kimlik_no__isnull', False)), fields=('kurum', 'tc_kimlik_no'), name='unique_kurum_personel_tc'),
        ),
        migrations.AddIndex(
            model_name='kocatama',
            index=models.Index(fields=['kurum', 'sube', 'egitim_yili', 'aktif_mi'], name='koc_atama_kurum_i_4a302d_idx'),
        ),
        migrations.AddIndex(
            model_name='kocatama',
            index=models.Index(fields=['koc', 'egitim_yili'], name='koc_atama_koc_id_51b12b_idx'),
        ),
        migrations.AddConstraint(
            model_name='kocatama',
            constraint=models.UniqueConstraint(fields=('sinif', 'egitim_yili'), name='unique_koc_per_sinif_year'),
        ),
    ]
