# Generated by Django 4.2.27 on 2026-02-02 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_tanimlari', '0009_merge_20260201_0154'),
        ('sube', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kurum', '0001_initial'),
        ('egitim_yili', '0001_initial'),
        ('sinif', '0001_initial'),
        ('personel', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonelGorevlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorev_baslangic', models.DateField(blank=True, null=True, verbose_name='Görev Başlangıcı')),
                ('gorev_bitis', models.DateField(blank=True, null=True, verbose_name='Görev Bitişi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Personel Görevlendirme',
                'verbose_name_plural': 'Personel Görevlendirmeleri',
                'db_table': 'personel_gorevlendirme',
                'ordering': ['-egitim_yili', 'personel__soyad', 'personel__ad'],
            },
        ),
        migrations.CreateModel(
            name='PersonelRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Rol Adı')),
                ('kod', models.CharField(help_text='Örn: OGRETMEN, KOC, MUDUR', max_length=50, verbose_name='Rol Kodu')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('sistem_rolu', models.BooleanField(default=False, help_text='Sistem tarafından oluşturulan roller silinemez', verbose_name='Sistem Rolü')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Personel Rolü',
                'verbose_name_plural': 'Personel Rolleri',
                'db_table': 'personel_rol',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.RemoveField(
            model_name='kocatama',
            name='egitim_yili',
        ),
        migrations.RemoveField(
            model_name='kocatama',
            name='koc',
        ),
        migrations.RemoveField(
            model_name='kocatama',
            name='kurum',
        ),
        migrations.RemoveField(
            model_name='kocatama',
            name='sinif',
        ),
        migrations.RemoveField(
            model_name='kocatama',
            name='sube',
        ),
        migrations.RemoveIndex(
            model_name='personel',
            name='personel_gorev_t_e4be7c_idx',
        ),
        migrations.RemoveField(
            model_name='personel',
            name='brans',
        ),
        migrations.RemoveField(
            model_name='personel',
            name='gorev_turu',
        ),
        migrations.AddField(
            model_name='personel',
            name='acil_durum_kisi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Acil Durum Kişisi'),
        ),
        migrations.AddField(
            model_name='personel',
            name='acil_durum_telefon',
            field=models.CharField(blank=True, max_length=20, verbose_name='Acil Durum Telefonu'),
        ),
        migrations.AddField(
            model_name='personel',
            name='cep_telefon',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cep Telefonu'),
        ),
        migrations.AddField(
            model_name='personel',
            name='il',
            field=models.CharField(blank=True, max_length=50, verbose_name='İl'),
        ),
        migrations.AddField(
            model_name='personel',
            name='ilce',
            field=models.CharField(blank=True, max_length=50, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='personel',
            name='notlar',
            field=models.TextField(blank=True, help_text='Personel hakkında özel notlar', verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='personel',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Personelin sisteme giriş yapabileceği kullanıcı hesabı', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personel', to=settings.AUTH_USER_MODEL, verbose_name='Sistem Kullanıcısı'),
        ),
        migrations.AddIndex(
            model_name='personel',
            index=models.Index(fields=['ad', 'soyad'], name='personel_ad_f06240_idx'),
        ),
        migrations.AddIndex(
            model_name='personel',
            index=models.Index(fields=['tc_kimlik_no'], name='personel_tc_kiml_c45abe_idx'),
        ),
        migrations.DeleteModel(
            name='KocAtama',
        ),
        migrations.AddField(
            model_name='personelrol',
            name='kurum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personel_rolleri', to='kurum.kurum', verbose_name='Kurum'),
        ),
        migrations.AddField(
            model_name='personelgorevlendirme',
            name='brans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personel_gorevlendirmeleri', to='egitim_tanimlari.ders', verbose_name='Branş'),
        ),
        migrations.AddField(
            model_name='personelgorevlendirme',
            name='egitim_yili',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personel_gorevlendirmeleri', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı'),
        ),
        migrations.AddField(
            model_name='personelgorevlendirme',
            name='gorev_sube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personel_gorevlendirmeleri', to='sube.sube', verbose_name='Görev Şubesi'),
        ),
        migrations.AddField(
            model_name='personelgorevlendirme',
            name='kurum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personel_gorevlendirmeleri', to='kurum.kurum', verbose_name='Kurum'),
        ),
        migrations.AddField(
            model_name='personelgorevlendirme',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorevlendirmeler', to='personel.personel', verbose_name='Personel'),
        ),
        migrations.AddField(
            model_name='personelgorevlendirme',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gorevlendirmeler', to='personel.personelrol', verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='personelgorevlendirme',
            name='siniflar',
            field=models.ManyToManyField(blank=True, related_name='gorevli_personeller', to='sinif.sinif', verbose_name='Atanan Sınıflar'),
        ),
        migrations.AddConstraint(
            model_name='personelrol',
            constraint=models.UniqueConstraint(fields=('kurum', 'kod'), name='unique_kurum_rol_kod'),
        ),
        migrations.AddIndex(
            model_name='personelgorevlendirme',
            index=models.Index(fields=['kurum', 'egitim_yili', 'aktif_mi'], name='personel_go_kurum_i_090fca_idx'),
        ),
        migrations.AddIndex(
            model_name='personelgorevlendirme',
            index=models.Index(fields=['personel', 'egitim_yili'], name='personel_go_persone_e8d39e_idx'),
        ),
        migrations.AddIndex(
            model_name='personelgorevlendirme',
            index=models.Index(fields=['gorev_sube', 'egitim_yili', 'rol'], name='personel_go_gorev_s_a6128e_idx'),
        ),
        migrations.AddConstraint(
            model_name='personelgorevlendirme',
            constraint=models.UniqueConstraint(fields=('personel', 'egitim_yili', 'gorev_sube', 'rol'), name='unique_personel_yil_sube_rol'),
        ),
    ]
