# Generated by Django 4.2.27 on 2026-02-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0003_update_personel_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='fotograf',
            field=models.ImageField(blank=True, help_text='Personelin profil fotoğrafı', null=True, upload_to='personel/fotograflar/', verbose_name='Profil Fotoğrafı'),
        ),
    ]
