# Generated by Django 4.2.27 on 2026-02-03 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurum', '0001_initial'),
        ('personel', '0004_add_fotograf_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Birim Adı')),
                ('kod', models.CharField(blank=True, help_text='Örn: IDARI, EGITIM_KOORD, REHBERLIK', max_length=50, verbose_name='Birim Kodu')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birimler', to='kurum.kurum', verbose_name='Kurum')),
                ('ust_birim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_birimler', to='personel.birim', verbose_name='Üst Birim')),
                ('yonetici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yonettigi_birimler', to='personel.personel', verbose_name='Birim Yöneticisi')),
            ],
            options={
                'verbose_name': 'Birim',
                'verbose_name_plural': 'Birimler',
                'db_table': 'personel_birim',
                'ordering': ['sira', 'ad'],
                'indexes': [models.Index(fields=['kurum', 'aktif_mi'], name='personel_bi_kurum_i_e105cb_idx'), models.Index(fields=['ust_birim'], name='personel_bi_ust_bir_38ca69_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='birim',
            constraint=models.UniqueConstraint(condition=models.Q(('kod__isnull', False), models.Q(('kod', ''), _negated=True)), fields=('kurum', 'kod'), name='unique_kurum_birim_kod'),
        ),
    ]
