# Generated by Django 4.2.27 on 2026-02-03 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0006_personelgorevlendirme_birim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personelgorevlendirme',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gorevlendirmeler', to='personel.personelrol', verbose_name='Rol'),
        ),
    ]
