# Generated by Django 4.2.27 on 2026-02-04 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0008_update_gorevlendirme_role_and_remove_birim'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonelAktiviteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eylem', models.CharField(choices=[('LOGIN', 'Giriş'), ('LOGOUT', 'Çıkış'), ('LOGIN_FAILED', 'Başarısız Giriş'), ('PASSWORD_CHANGE', 'Şifre Değiştirme'), ('PASSWORD_RESET', 'Şifre Sıfırlama'), ('PROFILE_VIEW', 'Profil Görüntüleme'), ('PROFILE_UPDATE', 'Profil Güncelleme'), ('PAGE_VIEW', 'Sayfa Görüntüleme'), ('DATA_CREATE', 'Veri Oluşturma'), ('DATA_UPDATE', 'Veri Güncelleme'), ('DATA_DELETE', 'Veri Silme'), ('EXPORT', 'Veri Dışa Aktarma'), ('IMPORT', 'Veri İçe Aktarma'), ('OTHER', 'Diğer')], max_length=20, verbose_name='Eylem')),
                ('detay', models.TextField(blank=True, help_text='Eylem hakkında ek bilgi', verbose_name='Detay')),
                ('ip_adresi', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, verbose_name='Tarayıcı Bilgisi')),
                ('sayfa_url', models.CharField(blank=True, max_length=500, verbose_name='Sayfa URL')),
                ('oturum_id', models.CharField(blank=True, help_text='Session ID - Oturum takibi için', max_length=100, verbose_name='Oturum ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktivite_loglari', to='personel.personel', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Personel Aktivite Logu',
                'verbose_name_plural': 'Personel Aktivite Logları',
                'db_table': 'personel_aktivite_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['personel', '-created_at'], name='personel_ak_persone_3c096f_idx'), models.Index(fields=['eylem', '-created_at'], name='personel_ak_eylem_14fbc4_idx'), models.Index(fields=['personel', 'eylem'], name='personel_ak_persone_7acf32_idx')],
            },
        ),
    ]
