# Generated by Django 4.2.9 on 2026-03-14 22:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_yili', '0001_initial'),
        ('egitim_tanimlari', '0009_merge_20260201_0154'),
        ('kurum', '0001_initial'),
        ('personel', '0009_personel_aktivite_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonelSozlesme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sozlesme_turu', models.CharField(choices=[('TAM_ZAMANLI', 'Tam Zamanlı (Maaşlı)'), ('DERS_UCRETLI', 'Ders Ücretli'), ('KARMA', 'Karma (Maaş + Ders Ücreti)')], default='TAM_ZAMANLI', max_length=20, verbose_name='Sözleşme Türü')),
                ('durum', models.CharField(choices=[('TASLAK', 'Taslak'), ('AKTIF', 'Aktif'), ('ASKIDA', 'Askıda'), ('SONA_ERDI', 'Sona Erdi'), ('FESHEDILDI', 'Feshedildi')], default='TASLAK', max_length=20, verbose_name='Durum')),
                ('baslangic_tarihi', models.DateField(verbose_name='Sözleşme Başlangıcı')),
                ('bitis_tarihi', models.DateField(verbose_name='Sözleşme Bitişi')),
                ('brut_maas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Brüt Maaş (₺)')),
                ('net_maas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Net Maaş (₺)')),
                ('sgk_gun', models.PositiveSmallIntegerField(default=30, help_text='Aylık SGK gün sayısı (0-30)', verbose_name='SGK Gün Sayısı')),
                ('ders_ucreti_aktif', models.BooleanField(default=False, help_text='Sözleşmede ek ders ücreti var mı?', verbose_name='Ders Ücreti Aktif mi?')),
                ('sozlesme_dosya', models.FileField(blank=True, help_text='Sözleşme PDF / taranmış belge', null=True, upload_to='personel/sozlesmeler/%Y/', verbose_name='Sözleşme Dosyası')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personel_sozlesmeleri', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personel_sozlesmeleri', to='kurum.kurum', verbose_name='Kurum')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sozlesmeler', to='personel.personel', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Personel Sözleşme',
                'verbose_name_plural': 'Personel Sözleşmeleri',
                'db_table': 'personel_sozlesme',
                'ordering': ['-egitim_yili__baslangic_yil', 'personel__soyad'],
            },
        ),
        migrations.CreateModel(
            name='DersUcretTanim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucret_tipi', models.CharField(choices=[('SAAT_BASI', 'Saat Başı'), ('DERS_BASI', 'Ders Başı'), ('AYLIK_PAKET', 'Aylık Paket')], default='SAAT_BASI', max_length=20, verbose_name='Ücret Tipi')),
                ('birim_ucret', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Birim Ücret (₺)')),
                ('haftalik_saat', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Haftalık Planlanan Saat')),
                ('min_saat', models.DecimalField(blank=True, decimal_places=1, help_text='Garanti edilen minimum aylık saat', max_digits=5, null=True, verbose_name='Aylık Min Saat')),
                ('max_saat', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Aylık Max Saat')),
                ('notlar', models.CharField(blank=True, max_length=255, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ders_ucret_tanimlari', to='egitim_tanimlari.brans', verbose_name='Branş / Ders')),
                ('sozlesme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ders_ucretleri', to='personel.personelsozlesme', verbose_name='Sözleşme')),
            ],
            options={
                'verbose_name': 'Ders Ücreti Tanımı',
                'verbose_name_plural': 'Ders Ücreti Tanımları',
                'db_table': 'personel_ders_ucret_tanim',
                'ordering': ['sozlesme', 'brans__ad'],
            },
        ),
        migrations.CreateModel(
            name='AylikHakedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.PositiveSmallIntegerField(help_text='Ör: 2026', verbose_name='Yıl')),
                ('ay', models.PositiveSmallIntegerField(help_text='1-12', verbose_name='Ay')),
                ('sabit_maas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Sabit Maaş (₺)')),
                ('toplam_ders_saati', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=7, verbose_name='Toplam Ders Saati')),
                ('ders_ucreti_toplam', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Ders Ücreti Toplamı (₺)')),
                ('ek_odeme', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prim, ikramiye vb.', max_digits=12, verbose_name='Ek Ödemeler (₺)')),
                ('kesintiler', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SGK, vergi, avans vb.', max_digits=12, verbose_name='Kesintiler (₺)')),
                ('brut_toplam', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Brüt Toplam (₺)')),
                ('net_hakedis', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Net Hakediş (₺)')),
                ('durum', models.CharField(choices=[('HESAPLANDI', 'Hesaplandı'), ('ONAYLANDI', 'Onaylandı'), ('ODENDI', 'Ödendi'), ('IPTAL', 'İptal')], default='HESAPLANDI', max_length=20, verbose_name='Durum')),
                ('odeme_tarihi', models.DateField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sozlesme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hakedisler', to='personel.personelsozlesme', verbose_name='Sözleşme')),
            ],
            options={
                'verbose_name': 'Aylık Hakediş',
                'verbose_name_plural': 'Aylık Hakedişler',
                'db_table': 'personel_aylik_hakedis',
                'ordering': ['-yil', '-ay'],
            },
        ),
        migrations.AddIndex(
            model_name='personelsozlesme',
            index=models.Index(fields=['kurum', 'egitim_yili', 'durum'], name='personel_so_kurum_i_c77fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='personelsozlesme',
            index=models.Index(fields=['personel', 'egitim_yili'], name='personel_so_persone_f62ba4_idx'),
        ),
        migrations.AddConstraint(
            model_name='personelsozlesme',
            constraint=models.UniqueConstraint(condition=models.Q(('durum__in', ['TASLAK', 'AKTIF', 'ASKIDA'])), fields=('personel', 'egitim_yili'), name='unique_aktif_sozlesme_per_yil'),
        ),
        migrations.AddIndex(
            model_name='aylikhakedis',
            index=models.Index(fields=['sozlesme', 'yil', 'ay'], name='personel_ay_sozlesm_83007b_idx'),
        ),
        migrations.AddIndex(
            model_name='aylikhakedis',
            index=models.Index(fields=['durum'], name='personel_ay_durum_68c053_idx'),
        ),
        migrations.AddConstraint(
            model_name='aylikhakedis',
            constraint=models.UniqueConstraint(fields=('sozlesme', 'yil', 'ay'), name='unique_hakedis_sozlesme_ay'),
        ),
    ]
