# Generated by Django 4.2.9 on 2026-03-15 01:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0010_add_sozlesme_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='aylikhakedis',
            name='avans',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Daha önce yapılan ön ödeme', max_digits=12, verbose_name='Avans / Ön Ödeme (₺)'),
        ),
        migrations.AddField(
            model_name='aylikhakedis',
            name='ders_basi_ucret',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sözleşmeden otomatik gelir', max_digits=10, verbose_name='Ders Başı Birim Ücret (₺)'),
        ),
        migrations.AddField(
            model_name='aylikhakedis',
            name='fazla_mesai',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Fazla Mesai (₺)'),
        ),
        migrations.AddField(
            model_name='aylikhakedis',
            name='prim',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Performans primi, hedef primi vb.', max_digits=12, verbose_name='Prim (₺)'),
        ),
        migrations.AlterField(
            model_name='aylikhakedis',
            name='ek_odeme',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='İkramiye, yol yardımı vb.', max_digits=12, verbose_name='Ek Ödemeler (₺)'),
        ),
        migrations.AlterField(
            model_name='aylikhakedis',
            name='kesintiler',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SGK, vergi, ceza vb.', max_digits=12, verbose_name='Diğer Kesintiler (₺)'),
        ),
        migrations.AlterField(
            model_name='aylikhakedis',
            name='sabit_maas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Aylık Maaş (₺)'),
        ),
    ]
