# Generated by Django 4.2.27 on 2026-06-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0013_ucret_donemi_fesih_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='avanskaydi',
            new_name='personel_av_sozlesm_90efc1_idx',
            old_name='personel_av_sozlesm_idx',
        ),
        migrations.RenameIndex(
            model_name='ucretdonemi',
            new_name='personel_uc_sozlesm_6d9322_idx',
            old_name='personel_uc_sozlesm_idx',
        ),
        migrations.AlterField(
            model_name='avanskaydi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personelsozlesme',
            name='fesih_sebebi',
            field=models.TextField(blank=True, help_text='Fesih gerekçesi / açıklaması', verbose_name='Fesih Sebebi'),
        ),
    ]
