# Generated by Django 4.2.27 on 2026-07-06 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kimlik', '0001_initial'),
        ('personel', '0014_rename_personel_av_sozlesm_idx_personel_av_sozlesm_90efc1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='kisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personel_kayitlari', to='kimlik.kisi', verbose_name='Merkezi Kişi'),
        ),
    ]
