# Generated by Django 4.2.27 on 2026-07-10 15:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from calendar import monthrange
from datetime import date, timedelta, time


def _month_end(d):
    return date(d.year, d.month, monthrange(d.year, d.month)[1])


def _add_months(d, months):
    month_index = d.month - 1 + months
    year = d.year + month_index // 12
    month = month_index % 12 + 1
    day = min(d.day, monthrange(year, month)[1])
    return date(year, month, day)


def migrate_contract_v2_data(apps, schema_editor):
    PersonelSozlesme = apps.get_model('personel', 'PersonelSozlesme')
    UcretDonemi = apps.get_model('personel', 'UcretDonemi')
    MaasPlaniSatiri = apps.get_model('personel', 'MaasPlaniSatiri')
    SozlesmeMesaiSaati = apps.get_model('personel', 'SozlesmeMesaiSaati')
    PersonelGorevlendirme = apps.get_model('personel', 'PersonelGorevlendirme')

    # Durum eşleme
    PersonelSozlesme.objects.filter(durum='ASKIDA').update(durum='PASIF')
    PersonelSozlesme.objects.filter(durum='SONA_ERDI').update(durum='SURESI_DOLMU')

    seq_by_prefix = {}
    for s in PersonelSozlesme.objects.select_related('personel', 'egitim_yili').order_by('id'):
        changed = False
        if not s.sozlesme_no:
            yil = getattr(s.egitim_yili, 'baslangic_yil', date.today().year)
            prefix = f'PS-{yil}-'
            seq = seq_by_prefix.get(prefix, 0) + 1
            seq_by_prefix[prefix] = seq
            s.sozlesme_no = f'{prefix}{seq:04d}'
            changed = True
        if not s.personel_no_snapshot:
            s.personel_no_snapshot = f'P-{s.personel_id:06d}'
            changed = True
        if not s.sube_id and s.personel_id:
            s.sube_id = s.personel.sube_id
            changed = True
        if not s.duzenlenme_tarihi:
            s.duzenlenme_tarihi = s.baslangic_tarihi
            changed = True

        gorev = PersonelGorevlendirme.objects.filter(
            personel_id=s.personel_id,
            egitim_yili_id=s.egitim_yili_id,
            aktif_mi=True,
        ).select_related('brans', 'rol').first()
        if gorev:
            if not s.gorevlendirme_id:
                s.gorevlendirme_id = gorev.id
                changed = True
            if not s.brans_snapshot and gorev.brans_id:
                s.brans_snapshot = gorev.brans.ad if gorev.brans else ''
                changed = True
            if not s.gorev_snapshot and gorev.rol_id:
                s.gorev_snapshot = gorev.rol.name if gorev.rol else ''
                changed = True

        if changed:
            s.save()

        # UcretDonemi → MaasPlaniSatiri
        if not MaasPlaniSatiri.objects.filter(sozlesme_id=s.id).exists():
            donemler = list(UcretDonemi.objects.filter(sozlesme_id=s.id).order_by('baslangic_ay'))
            if donemler:
                start = s.baslangic_tarihi or date.today()
                sira = 1
                for d in donemler:
                    bitis_ay = d.bitis_ay if d.bitis_ay else d.baslangic_ay
                    for ay_offset in range(d.baslangic_ay - 1, bitis_ay):
                        b = _add_months(start, ay_offset)
                        e = _month_end(b)
                        MaasPlaniSatiri.objects.create(
                            sozlesme_id=s.id,
                            sira_no=sira,
                            baslangic_tarihi=b,
                            bitis_tarihi=e,
                            calisilan_gun=(e - b).days + 1,
                            maas=d.brut_maas,
                            aciklama=d.aciklama or '',
                        )
                        sira += 1
            elif s.brut_maas and s.brut_maas > 0:
                start = s.baslangic_tarihi or date.today()
                end = s.bitis_tarihi or _add_months(start, 11)
                months = max(1, (end.year - start.year) * 12 + end.month - start.month + 1)
                for i in range(months):
                    b = _add_months(start, i)
                    e = _month_end(b)
                    if e > end:
                        e = end
                    MaasPlaniSatiri.objects.create(
                        sozlesme_id=s.id,
                        sira_no=i + 1,
                        baslangic_tarihi=b,
                        bitis_tarihi=e,
                        calisilan_gun=(e - b).days + 1,
                        maas=s.brut_maas,
                        aciklama='',
                    )

        # Varsayılan mesai
        if not SozlesmeMesaiSaati.objects.filter(sozlesme_id=s.id).exists():
            for gun in range(1, 8):
                aktif = gun <= 5
                SozlesmeMesaiSaati.objects.create(
                    sozlesme_id=s.id,
                    gun=gun,
                    baslangic=time(9, 0) if aktif else None,
                    bitis=time(18, 0) if aktif else None,
                    mola_dakika=0,
                    aktif=aktif,
                )


def reverse_migrate_contract_v2_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sube', '0003_sube_branding'),
        ('personel', '0015_personel_kisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaasPlaniSatiri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira_no', models.PositiveSmallIntegerField(help_text='1, 2, 3 …', verbose_name='Ay Sırası')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(verbose_name='Bitiş Tarihi')),
                ('calisilan_gun', models.PositiveSmallIntegerField(default=0, verbose_name='Çalışılan Gün')),
                ('maas', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Maaş (₺)')),
                ('aciklama', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maaş Planı Satırı',
                'verbose_name_plural': 'Maaş Planı Satırları',
                'db_table': 'personel_maas_plani_satiri',
                'ordering': ['sozlesme', 'sira_no'],
            },
        ),
        migrations.CreateModel(
            name='SozlesmeMadde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.PositiveSmallIntegerField(verbose_name='Sıra')),
                ('metin', models.TextField(verbose_name='Madde Metni')),
            ],
            options={
                'verbose_name': 'Sözleşme Maddesi',
                'verbose_name_plural': 'Sözleşme Maddeleri',
                'db_table': 'personel_sozlesme_madde',
                'ordering': ['sozlesme', 'sira'],
            },
        ),
        migrations.CreateModel(
            name='SozlesmeMesaiSaati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.PositiveSmallIntegerField(help_text='1=Pazartesi … 7=Pazar', verbose_name='Gün')),
                ('baslangic', models.TimeField(blank=True, null=True, verbose_name='Başlangıç')),
                ('bitis', models.TimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('mola_dakika', models.PositiveSmallIntegerField(default=0, verbose_name='Mola (dk)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Çalışma Günü')),
            ],
            options={
                'verbose_name': 'Mesai Saati',
                'verbose_name_plural': 'Mesai Saatleri',
                'db_table': 'personel_sozlesme_mesai',
                'ordering': ['sozlesme', 'gun'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='personelsozlesme',
            name='unique_aktif_sozlesme_per_yil',
        ),
        migrations.AddField(
            model_name='personelsozlesme',
            name='auto_save_rev',
            field=models.PositiveIntegerField(default=0, verbose_name='Auto Save Rev'),
        ),
        migrations.AddField(
            model_name='personelsozlesme',
            name='brans_snapshot',
            field=models.CharField(blank=True, max_length=200, verbose_name='Branş'),
        ),
        migrations.AddField(
            model_name='personelsozlesme',
            name='departman_snapshot',
            field=models.CharField(blank=True, max_length=200, verbose_name='Departman'),
        ),
        migrations.AddField(
            model_name='personelsozlesme',
            name='ders_birim_ucret',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ders/Saat Birim Ücret (₺)'),
        ),
        migrations.AddField(
            model_name='personelsozlesme',
            name='ders_ucret_tipi',
            field=models.CharField(blank=True, choices=[('SAAT_BASI', 'Saat Başı'), ('DERS_BASI', 'Ders Başı')], max_length=20, verbose_name='Ders Ücret Tipi'),
        ),
        migrations.AddField(
            model_name='personelsozlesme',
            name='duzenlenme_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Düzenlenme Tarihi'),
        ),
        migrations.AddField(
            model_name='personelsozlesme',
            name='gorev_snapshot',
            field=models.CharField(blank=True, max_length=200, verbose_name='Görev'),
        ),
        migrations.AddField(
            model_name='personelsozlesme',
            name='gorevlendirme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sozlesmeler', to='personel.personelgorevlendirme', verbose_name='Görevlendirme'),
        ),
        migrations.AddField(
            model_name='personelsozlesme',
            name='haftalik_calisma_gun_sayisi',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Haftalık Çalışma Gün Sayısı'),
        ),
        migrations.AddField(
            model_name='personelsozlesme',
            name='haftalik_izin_gunleri',
            field=models.JSONField(blank=True, default=list, help_text='1=Pazartesi … 7=Pazar', verbose_name='Haftalık İzin Günleri'),
        ),
        migrations.AddField(
            model_name='personelsozlesme',
            name='personel_no_snapshot',
            field=models.CharField(blank=True, max_length=32, verbose_name='Personel No'),
        ),
        migrations.AddField(
            model_name='personelsozlesme',
            name='sozlesme_no',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Sözleşme No'),
        ),
        migrations.AddField(
            model_name='personelsozlesme',
            name='sube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personel_sozlesmeleri', to='sube.sube', verbose_name='Şube'),
        ),
        migrations.AddField(
            model_name='personelsozlesme',
            name='toplam_calisma_suresi_ay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Toplam Çalışma Süresi (Ay)'),
        ),
        migrations.AddField(
            model_name='personelsozlesme',
            name='toplam_sozlesme_bedeli',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Toplam Sözleşme Bedeli (₺)'),
        ),
        migrations.AlterField(
            model_name='personelsozlesme',
            name='durum',
            field=models.CharField(choices=[('TASLAK', 'Taslak'), ('AKTIF', 'Aktif'), ('PASIF', 'Pasif'), ('FESHEDILDI', 'Feshedildi'), ('SURESI_DOLMU', 'Süresi Doldu'), ('ASKIDA', 'Askıda'), ('SONA_ERDI', 'Sona Erdi')], default='TASLAK', max_length=20, verbose_name='Durum'),
        ),
        migrations.AddConstraint(
            model_name='personelsozlesme',
            constraint=models.UniqueConstraint(condition=models.Q(('durum__in', ['TASLAK', 'AKTIF', 'PASIF', 'ASKIDA'])), fields=('personel', 'egitim_yili'), name='unique_aktif_sozlesme_per_yil'),
        ),
        migrations.AddField(
            model_name='sozlesmemesaisaati',
            name='sozlesme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesai_saatleri', to='personel.personelsozlesme', verbose_name='Sözleşme'),
        ),
        migrations.AddField(
            model_name='sozlesmemadde',
            name='sozlesme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maddeler', to='personel.personelsozlesme', verbose_name='Sözleşme'),
        ),
        migrations.AddField(
            model_name='maasplanisatiri',
            name='sozlesme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maas_plani', to='personel.personelsozlesme', verbose_name='Sözleşme'),
        ),
        migrations.AddConstraint(
            model_name='sozlesmemesaisaati',
            constraint=models.UniqueConstraint(fields=('sozlesme', 'gun'), name='unique_sozlesme_mesai_gun'),
        ),
        migrations.AddConstraint(
            model_name='sozlesmemadde',
            constraint=models.UniqueConstraint(fields=('sozlesme', 'sira'), name='unique_sozlesme_madde_sira'),
        ),
        migrations.AddIndex(
            model_name='maasplanisatiri',
            index=models.Index(fields=['sozlesme', 'sira_no'], name='personel_ma_sozlesm_230107_idx'),
        ),
        migrations.AddConstraint(
            model_name='maasplanisatiri',
            constraint=models.UniqueConstraint(fields=('sozlesme', 'sira_no'), name='unique_maas_plani_sira'),
        ),
        migrations.RunPython(migrate_contract_v2_data, reverse_migrate_contract_v2_data),
    ]
