# Generated by Django 4.2.27 on 2026-07-25 18:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0017_sozlesme_unique_per_sube'),
    ]

    operations = [
        migrations.AddField(
            model_name='aylikhakedis',
            name='ozel_ders_hakedis_toplam',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Onaylanmış birebir/özel ders hakedişlerinin bordroya aktarılan tutarı', max_digits=12, verbose_name='Özel Ders Hakediş Toplamı (₺)'),
        ),
    ]
