# Generated by Django 4.2.27 on 2026-07-04 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('storage_key', models.CharField(max_length=512, unique=True, verbose_name='Depolama Anahtarı')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Boyut (byte)')),
                ('checksum', models.CharField(blank=True, default='', max_length=64, verbose_name='SHA-256')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='Durum')),
                ('trigger', models.CharField(choices=[('manual', 'Manuel'), ('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık')], default='manual', max_length=20, verbose_name='Tetikleyici')),
                ('components', models.JSONField(blank=True, default=dict, verbose_name='Bileşenler')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Süre (ms)')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Hata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_artifacts', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Yedek Dosyası',
                'verbose_name_plural': 'Yedek Dosyaları',
                'db_table': 'yedekleme_artifact',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('manual', 'Manuel'), ('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık')], default='daily', max_length=20, verbose_name='Sıklık')),
                ('hour', models.PositiveSmallIntegerField(default=3, verbose_name='Saat')),
                ('minute', models.PositiveSmallIntegerField(default=0, verbose_name='Dakika')),
                ('enabled', models.BooleanField(default=False, verbose_name='Aktif')),
                ('include_logs', models.BooleanField(default=False, verbose_name='Logları Dahil Et')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Çalışma')),
                ('retention_override', models.JSONField(blank=True, null=True, verbose_name='Retention Override')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yedek Zamanlaması',
                'verbose_name_plural': 'Yedek Zamanlamaları',
                'db_table': 'yedekleme_schedule',
            },
        ),
        migrations.CreateModel(
            name='BackupOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('action', models.CharField(choices=[('create', 'Yedek Oluştur'), ('download', 'İndir'), ('validate', 'Doğrula'), ('restore', 'Geri Yükle'), ('delete', 'Sil'), ('schedule_update', 'Zamanlama Güncelle'), ('purge', 'Temizlik')], max_length=32, verbose_name='İşlem')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Süre (ms)')),
                ('success', models.BooleanField(default=True, verbose_name='Başarılı')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Hata')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='yedekleme.backupartifact')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yedekleme İşlem Logu',
                'verbose_name_plural': 'Yedekleme İşlem Logları',
                'db_table': 'yedekleme_operation_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
