# Generated by Django 4.2.27 on 2026-07-12 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yedekleme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=255, verbose_name='Kaynak Adı')),
                ('resource_type', models.CharField(choices=[('database_table', 'Database Table'), ('file_directory', 'File Directory'), ('configuration', 'Configuration'), ('media', 'Media'), ('logs', 'Logs'), ('cache', 'Cache'), ('export', 'Export'), ('other', 'Other')], default='other', max_length=32, verbose_name='Tür')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('handler_key', models.CharField(default='other', max_length=64, verbose_name='Handler')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Yapılandırma')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_default', models.BooleanField(default=True, verbose_name='Varsayılan')),
                ('encrypt', models.BooleanField(default=False, verbose_name='Şifrele')),
                ('compress', models.BooleanField(default=True, verbose_name='Sıkıştır')),
                ('priority', models.IntegerField(default=100, verbose_name='Öncelik')),
                ('is_restorable', models.BooleanField(default=True, verbose_name='Geri Yüklenebilir')),
                ('source_app', models.CharField(blank=True, default='', max_length=128, verbose_name='Kaynak App')),
                ('is_system', models.BooleanField(default=False, verbose_name='Sistem Kaynağı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yedek Kaynağı',
                'verbose_name_plural': 'Yedek Kaynakları',
                'db_table': 'yedekleme_resource',
                'ordering': ['priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryption_enabled', models.BooleanField(default=False, verbose_name='Şifreleme Aktif')),
                ('default_encrypt', models.BooleanField(default=False, verbose_name='Varsayılan Şifrele')),
                ('default_compress', models.BooleanField(default=True, verbose_name='Varsayılan Sıkıştır')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yedekleme Ayarı',
                'verbose_name_plural': 'Yedekleme Ayarları',
                'db_table': 'yedekleme_settings',
            },
        ),
        migrations.RemoveField(
            model_name='backupartifact',
            name='components',
        ),
        migrations.RemoveField(
            model_name='backupschedule',
            name='include_logs',
        ),
        migrations.RemoveField(
            model_name='backupschedule',
            name='retention_override',
        ),
        migrations.AddField(
            model_name='backupartifact',
            name='encrypted',
            field=models.BooleanField(default=False, verbose_name='Şifreli'),
        ),
        migrations.AddField(
            model_name='backupartifact',
            name='format_version',
            field=models.CharField(default='2.0', max_length=16, verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='backupartifact',
            name='kind',
            field=models.CharField(choices=[('full', 'Tam Sistem'), ('database', 'Veritabanı'), ('files', 'Dosyalar'), ('settings', 'Ayarlar'), ('selected', 'Seçili Kaynaklar')], default='full', max_length=20, verbose_name='Tür'),
        ),
        migrations.AddField(
            model_name='backupartifact',
            name='manifest',
            field=models.JSONField(blank=True, default=dict, verbose_name='Manifest'),
        ),
        migrations.AddField(
            model_name='backupartifact',
            name='resource_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='Kaynak Kodları'),
        ),
        migrations.AddField(
            model_name='backupoperationlog',
            name='step',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Adım'),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='auto_delete_old',
            field=models.BooleanField(default=True, verbose_name='Eski Yedekleri Sil'),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='encrypt',
            field=models.BooleanField(default=False, verbose_name='Şifrele'),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='kind',
            field=models.CharField(choices=[('full', 'Tam Sistem'), ('database', 'Veritabanı'), ('files', 'Dosyalar'), ('settings', 'Ayarlar'), ('selected', 'Seçili Kaynaklar')], default='full', max_length=20, verbose_name='Yedek Türü'),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='max_artifacts',
            field=models.PositiveIntegerField(default=10, verbose_name='Maksimum Yedek'),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='resource_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='Seçili Kaynaklar'),
        ),
        migrations.AlterField(
            model_name='backupartifact',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('cancelled', 'İptal')], default='pending', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='backupoperationlog',
            name='action',
            field=models.CharField(choices=[('create', 'Yedek Oluştur'), ('download', 'İndir'), ('verify', 'Doğrula'), ('preview', 'Önizle'), ('analyze', 'Analiz'), ('dry_run', 'Dry-run'), ('restore', 'Geri Yükle'), ('delete', 'Sil'), ('import', 'İçe Aktar'), ('schedule_update', 'Zamanlama Güncelle'), ('settings_update', 'Ayar Güncelle'), ('resource_update', 'Kaynak Güncelle'), ('resource_sync', 'Kaynak Sync'), ('purge', 'Temizlik')], max_length=32, verbose_name='İşlem'),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='frequency',
            field=models.CharField(choices=[('off', 'Kapalı'), ('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık')], default='off', max_length=20, verbose_name='Sıklık'),
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Yedek Oluştur'), ('download', 'İndir'), ('verify', 'Doğrula'), ('preview', 'Önizle'), ('analyze', 'Analiz'), ('dry_run', 'Dry-run'), ('restore', 'Geri Yükle'), ('delete', 'Sil'), ('import', 'İçe Aktar'), ('schedule_update', 'Zamanlama Güncelle'), ('settings_update', 'Ayar Güncelle'), ('resource_update', 'Kaynak Güncelle'), ('resource_sync', 'Kaynak Sync'), ('purge', 'Temizlik')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('cancelled', 'İptal')], default='pending', max_length=20)),
                ('phase', models.CharField(choices=[('queued', 'Kuyrukta'), ('preparing', 'Hazırlanıyor'), ('exporting', 'Dışa aktarılıyor'), ('compressing', 'Sıkıştırılıyor'), ('encrypting', 'Şifreleniyor'), ('hashing', 'Hash hesaplanıyor'), ('storing', 'Kaydediliyor'), ('analyzing', 'Analiz ediliyor'), ('dry_run', 'Dry-run'), ('restoring', 'Geri yükleniyor'), ('done', 'Tamamlandı'), ('error', 'Hata')], default='queued', max_length=32)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('message', models.CharField(blank=True, default='', max_length=512)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='yedekleme.backupartifact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'yedekleme_job',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='backupoperationlog',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='yedekleme.backupjob'),
        ),
    ]
