# Generated by Django 4.2.27 on 2026-07-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedekleme', '0003_schedule_last_run_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupsettings',
            name='notify_emails',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Bildirim E-postaları'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='notify_enabled',
            field=models.BooleanField(default=False, verbose_name='Bildirim Aktif'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='notify_on_failure',
            field=models.BooleanField(default=True, verbose_name='Hatada Bildir'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='notify_on_success',
            field=models.BooleanField(default=False, verbose_name='Başarıda Bildir'),
        ),
        migrations.AlterField(
            model_name='backupartifact',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Manuel'), ('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık'), ('pre_restore', 'Restore Öncesi Güvenlik')], default='manual', max_length=20, verbose_name='Tetikleyici'),
        ),
    ]
