# Generated by Django 4.2.9 on 2026-01-30 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kurum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Şube Adı')),
                ('kod', models.CharField(max_length=50, verbose_name='Şube Kodu')),
                ('adres', models.TextField(blank=True, verbose_name='Adres')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subeler', to='kurum.kurum', verbose_name='Kurum')),
            ],
            options={
                'verbose_name': 'Şube',
                'verbose_name_plural': 'Şubeler',
                'db_table': 'sube',
                'ordering': ['kurum', 'ad'],
                'indexes': [models.Index(fields=['kurum', 'aktif_mi'], name='sube_kurum_i_144cac_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sube',
            constraint=models.UniqueConstraint(fields=('kurum', 'kod'), name='unique_kurum_sube_kod'),
        ),
    ]
