# Generated by Django 4.2.27 on 2026-06-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sube',
            name='eposta',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-posta'),
        ),
        migrations.AddField(
            model_name='sube',
            name='kurs_muduru',
            field=models.CharField(blank=True, max_length=120, verbose_name='Kurs Müdürü'),
        ),
        migrations.AddField(
            model_name='sube',
            name='kurs_muduru_telefon',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kurs Müdürü Telefon'),
        ),
        migrations.AddField(
            model_name='sube',
            name='resmi_ad',
            field=models.CharField(blank=True, max_length=255, verbose_name='Şube Resmi Adı'),
        ),
        migrations.AddField(
            model_name='sube',
            name='ticaret_sicil_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ticaret Sicil No'),
        ),
        migrations.AddField(
            model_name='sube',
            name='ticari_unvan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ticari Ünvan'),
        ),
        migrations.AddField(
            model_name='sube',
            name='vergi_dairesi',
            field=models.CharField(blank=True, max_length=120, verbose_name='Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='sube',
            name='vergi_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Vergi Numarası'),
        ),
        migrations.AddField(
            model_name='sube',
            name='web_adresi',
            field=models.URLField(blank=True, max_length=500, verbose_name='Web Adresi'),
        ),
    ]
