# Generated by Django 4.2.9 on 2026-02-15 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ogrenci', '0005_add_profil_foto'),
        ('egitim_tanimlari', '0009_merge_20260201_0154'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment_manual', '0009_fix_resource_book_set_null_and_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Haftanın Pazartesi günü', verbose_name='Hafta Başlangıcı')),
                ('week_end', models.DateField(help_text='Haftanın Pazar günü', verbose_name='Hafta Bitişi')),
                ('total_question_count', models.PositiveIntegerField(default=0, verbose_name='Toplam Soru')),
                ('total_block_count', models.PositiveIntegerField(default=0, verbose_name='Toplam Blok')),
                ('completion_percent', models.PositiveIntegerField(default=0, verbose_name='Tamamlanma %')),
                ('is_template', models.BooleanField(default=False, help_text='Tekrar kullanılmak üzere şablon olarak kaydedildi mi?', verbose_name='Şablon mı?')),
                ('template_name', models.CharField(blank=True, max_length=120, verbose_name='Şablon Adı')),
                ('coach_note', models.TextField(blank=True, help_text='Haftaya özel motivasyon / strateji notu', verbose_name='Koç Haftalık Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL, verbose_name='Koç')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_programs', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Haftalık Çalışma Programı',
                'verbose_name_plural': 'Haftalık Çalışma Programları',
                'db_table': 'study_weekly_program',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_date', models.DateField(verbose_name='Tarih')),
                ('weekday', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Gün')),
                ('total_question_count', models.PositiveIntegerField(default=0, verbose_name='Toplam Soru')),
                ('total_block_count', models.PositiveIntegerField(default=0, verbose_name='Blok Sayısı')),
                ('completion_percent', models.PositiveIntegerField(default=0, verbose_name='Tamamlanma %')),
                ('load_level', models.CharField(choices=[('IDEAL', 'İdeal'), ('YOGUN', 'Yoğun'), ('ASIRI', 'Aşırı')], default='IDEAL', max_length=10, verbose_name='Yük Seviyesi')),
                ('coach_note', models.TextField(blank=True, help_text='Koçun o güne özel motivasyon notu', verbose_name='Koç Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='study_program.weeklyprogram', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Program Günü',
                'verbose_name_plural': 'Program Günleri',
                'db_table': 'study_program_day',
                'ordering': ['day_date'],
            },
        ),
        migrations.CreateModel(
            name='ProgramBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('topic_name', models.CharField(blank=True, max_length=255, verbose_name='Konu')),
                ('resource_name', models.CharField(blank=True, help_text='Kitap / fasikül adı', max_length=255, verbose_name='Kaynak')),
                ('block_type', models.CharField(choices=[('KONU_OGRENME', '📖 Konu Öğrenme'), ('TEKRAR', '🔁 Tekrar'), ('SORU_COZUMU', '📝 Soru Çözümü'), ('BRANS_DENEMESI', '🎯 Branş Denemesi'), ('MINI_TEST', '⚡ Mini Test'), ('ANALIZ', '📊 Analiz'), ('ZAYIF_KONU', '🧠 Zayıf Konu Çalışması')], default='SORU_COZUMU', max_length=30, verbose_name='Blok Tipi')),
                ('goal_type', models.CharField(blank=True, choices=[('NET_ARTIRMA', 'Net Artırma'), ('KONU_TAMAMLAMA', 'Konu Tamamlama'), ('DENEME_HAZIRLIK', 'Deneme Hazırlık'), ('EKSIK_KAPATMA', 'Eksik Kapatma'), ('SURE_HIZLANDIRMA', 'Süre Hızlandırma')], max_length=30, verbose_name='Hedef Türü')),
                ('question_count', models.PositiveIntegerField(default=0, verbose_name='Soru Sayısı')),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tahmini Süre (dk)')),
                ('priority', models.CharField(choices=[('LOW', 'Düşük'), ('MEDIUM', 'Orta'), ('HIGH', 'Yüksek'), ('URGENT', 'Acil')], default='MEDIUM', max_length=10, verbose_name='Öncelik')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlandı mı?')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Zamanı')),
                ('actual_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Gerçek Süre (dk)')),
                ('color', models.CharField(blank=True, help_text='hex (#3b82f6) veya tailwind renk adı', max_length=20, verbose_name='Renk Kodu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='study_program.programday', verbose_name='Gün')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_blocks', to='egitim_tanimlari.ders', verbose_name='Ders')),
                ('source_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_blocks', to='assignment_manual.manualassignment', verbose_name='Kaynak Ödev')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_blocks', to='assignment_manual.assignmenttask', verbose_name='Kaynak Görev')),
            ],
            options={
                'verbose_name': 'Çalışma Bloğu',
                'verbose_name_plural': 'Çalışma Blokları',
                'db_table': 'study_program_block',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('struggled', models.BooleanField(blank=True, null=True, verbose_name='Zorlandı mı?')),
                ('time_enough', models.BooleanField(blank=True, null=True, verbose_name='Süre yetti mi?')),
                ('unclear_topic', models.CharField(blank=True, max_length=255, verbose_name='Anlamadığı konu')),
                ('comment', models.TextField(blank=True, verbose_name='Ek Yorum')),
                ('energy_level', models.CharField(choices=[('YUKSEK', 'Yüksek'), ('NORMAL', 'Normal'), ('DUSUK', 'Düşük')], default='NORMAL', max_length=10, verbose_name='Enerji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='study_program.programday', verbose_name='Gün')),
            ],
            options={
                'verbose_name': 'Günlük Geri Bildirim',
                'verbose_name_plural': 'Günlük Geri Bildirimler',
                'db_table': 'study_daily_feedback',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('EKSIKSIZ_GUN', 'Eksiksiz Gün'), ('SERI_3', '3 Gün Seri'), ('SERI_5', '5 Gün Seri'), ('SERI_7', '7 Gün Seri'), ('HAFTA_SAMPIYONU', 'Hafta Şampiyonu'), ('SORU_AVCISI', 'Soru Avcısı'), ('ERKEN_KUSU', 'Erken Kuşu')], max_length=30, verbose_name='Rozet Kodu')),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('icon', models.CharField(blank=True, help_text='Emoji veya ikon kodu', max_length=10, verbose_name='İkon')),
                ('earned_date', models.DateField(default=django.utils.timezone.now, verbose_name='Kazanma Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='study_program.weeklyprogram', verbose_name='Program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_badges', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Rozet',
                'verbose_name_plural': 'Rozetler',
                'db_table': 'study_badge',
                'ordering': ['-earned_date'],
            },
        ),
        migrations.AddIndex(
            model_name='weeklyprogram',
            index=models.Index(fields=['student', 'week_start'], name='sp_student_week_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyprogram',
            index=models.Index(fields=['coach'], name='sp_coach_idx'),
        ),
        migrations.AddConstraint(
            model_name='weeklyprogram',
            constraint=models.UniqueConstraint(fields=('student', 'week_start'), name='unique_student_week'),
        ),
        migrations.AddIndex(
            model_name='programday',
            index=models.Index(fields=['program', 'weekday'], name='sp_day_weekday_idx'),
        ),
        migrations.AddConstraint(
            model_name='programday',
            constraint=models.UniqueConstraint(fields=('program', 'weekday'), name='unique_program_weekday'),
        ),
        migrations.AddIndex(
            model_name='programblock',
            index=models.Index(fields=['day', 'order'], name='sp_block_order_idx'),
        ),
        migrations.AddIndex(
            model_name='programblock',
            index=models.Index(fields=['block_type'], name='sp_block_type_idx'),
        ),
        migrations.AddIndex(
            model_name='programblock',
            index=models.Index(fields=['lesson'], name='sp_block_lesson_idx'),
        ),
    ]
