# Generated by Django 4.2.9 on 2026-02-15 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_manual', '0009_fix_resource_book_set_null_and_validators'),
        ('study_program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programblock',
            name='source_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_blocks', to='assignment_manual.assignmentlesson', verbose_name='Kaynak Ödev Dersi'),
        ),
        migrations.AlterField(
            model_name='programblock',
            name='block_type',
            field=models.CharField(choices=[('KONU_OGRENME', '📖 Konu Öğrenme'), ('TEKRAR', '🔁 Tekrar'), ('SORU_COZUMU', '📝 Soru Çözümü'), ('BRANS_DENEMESI', '🎯 Branş Denemesi'), ('MINI_TEST', '⚡ Mini Test'), ('ANALIZ', '📊 Analiz'), ('ZAYIF_KONU', '🧠 Zayıf Konu Çalışması'), ('DENEME', '📋 Deneme')], default='SORU_COZUMU', max_length=30, verbose_name='Blok Tipi'),
        ),
    ]
