# Generated by Django 4.2.9 on 2026-02-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0002_add_source_lesson_to_block'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='programday',
            name='unique_program_weekday',
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='week_end',
            field=models.DateField(help_text='Program bitiş tarihi', verbose_name='Hafta Bitişi'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='week_start',
            field=models.DateField(help_text='Program başlangıç tarihi', verbose_name='Hafta Başlangıcı'),
        ),
        migrations.AddConstraint(
            model_name='programday',
            constraint=models.UniqueConstraint(fields=('program', 'day_date'), name='unique_program_day_date'),
        ),
    ]
