# Generated by Django 4.2.27 on 2026-09-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0005_block_goal_labels_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyprogram',
            name='week_end',
            field=models.DateField(help_text='Ödev kontrol günü (tarih aralığının son günü)', verbose_name='Hafta Bitişi'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='week_start',
            field=models.DateField(help_text='İlk çalışma günü (ödev verilme gününün ertesi)', verbose_name='Hafta Başlangıcı'),
        ),
    ]
