# Generated by Django 4.2.27 on 2026-06-30 18:31

import apps.website.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.CharField(max_length=300, verbose_name='Soru')),
                ('cevap', models.TextField(verbose_name='Cevap')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sss_listesi', to='kurum.kurum')),
            ],
            options={
                'verbose_name': 'SSS',
                'verbose_name_plural': 'SSS',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp')], max_length=30, verbose_name='Platform')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_social_links', to='kurum.kurum')),
            ],
            options={
                'verbose_name': 'Sosyal Medya',
                'verbose_name_plural': 'Sosyal Medya',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefon')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=30, verbose_name='WhatsApp')),
                ('eposta', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-posta')),
                ('adres', models.TextField(blank=True, default='', verbose_name='Adres')),
                ('calisma_saatleri', models.TextField(blank=True, default='', verbose_name='Çalışma Saatleri')),
                ('hero_baslik', models.CharField(blank=True, default='3K Kampüs', max_length=200, verbose_name='Hero Başlık')),
                ('hero_alt_baslik', models.CharField(blank=True, default='', max_length=300, verbose_name='Hero Alt Başlık')),
                ('hero_slogan', models.CharField(blank=True, default='', max_length=400, verbose_name='Hero Slogan')),
                ('hero_maddeler', models.JSONField(blank=True, default=list, verbose_name='Hero Maddeler')),
                ('tanitim_baslik', models.CharField(blank=True, default='', max_length=200, verbose_name='Tanıtım Başlık')),
                ('tanitim_icerik', models.TextField(blank=True, default='', verbose_name='Tanıtım İçerik')),
                ('youtube_video_id', models.CharField(blank=True, default='', max_length=50, verbose_name='YouTube Video ID')),
                ('harita_embed_url', models.TextField(blank=True, default='', verbose_name='Harita Embed URL')),
                ('footer_copyright', models.CharField(blank=True, default='© 2026 3K Kampüs', max_length=200, verbose_name='Footer Telif')),
                ('seo_baslik', models.CharField(blank=True, default='', max_length=200, verbose_name='SEO Başlık')),
                ('seo_aciklama', models.CharField(blank=True, default='', max_length=400, verbose_name='SEO Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kurum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_settings', to='kurum.kurum')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='SiteFooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolon', models.CharField(choices=[('kurumsal', 'Kurumsal'), ('hizli', 'Hızlı Bağlantılar'), ('yasal', 'Yasal'), ('sosyal', 'Sosyal Medya')], max_length=20, verbose_name='Kolon')),
                ('etiket', models.CharField(max_length=120, verbose_name='Etiket')),
                ('url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_footer_links', to='kurum.kurum')),
            ],
            options={
                'verbose_name': 'Footer Bağlantısı',
                'verbose_name_plural': 'Footer Bağlantıları',
                'ordering': ['kolon', 'sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SinavTakvim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('LGS', 'LGS'), ('TYT', 'TYT'), ('AYT', 'AYT')], max_length=10, verbose_name='Tür')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('saat', models.TimeField(blank=True, null=True, verbose_name='Saat')),
                ('kapsam', models.CharField(choices=[('turkiye_geneli', 'Türkiye Geneli'), ('yerel', 'Yerel')], default='turkiye_geneli', max_length=20, verbose_name='Kapsam')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('gorsel', models.ImageField(blank=True, null=True, upload_to=apps.website.models.sinav_gorsel_upload_to, verbose_name='Görsel')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinav_takvim', to='kurum.kurum')),
            ],
            options={
                'verbose_name': 'Sınav Takvimi',
                'verbose_name_plural': 'Sınav Takvimi',
                'ordering': ['tarih', 'saat'],
            },
        ),
        migrations.CreateModel(
            name='OgrenciYorumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('rol', models.CharField(blank=True, default='', max_length=100, verbose_name='Rol')),
                ('puan', models.PositiveSmallIntegerField(default=5, verbose_name='Puan')),
                ('yorum', models.TextField(verbose_name='Yorum')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogrenci_yorumlari', to='kurum.kurum')),
            ],
            options={
                'verbose_name': 'Öğrenci Yorumu',
                'verbose_name_plural': 'Öğrenci Yorumları',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NedenKart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ikon', models.CharField(blank=True, default='star', max_length=50, verbose_name='İkon')),
                ('baslik', models.CharField(max_length=120, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neden_kartlari', to='kurum.kurum')),
            ],
            options={
                'verbose_name': 'Neden Kart',
                'verbose_name_plural': 'Neden Kartları',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IletisimMesaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('telefon', models.CharField(max_length=30, verbose_name='Telefon')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('okundu', models.BooleanField(default=False, verbose_name='Okundu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iletisim_mesajlari', to='kurum.kurum')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorsel', models.ImageField(blank=True, null=True, upload_to=apps.website.models.hero_slide_upload_to, verbose_name='Görsel')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='kurum.kurum')),
            ],
            options={
                'verbose_name': 'Hero Slayt',
                'verbose_name_plural': 'Hero Slaytlar',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BasariIstatistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiket', models.CharField(max_length=120, verbose_name='Etiket')),
                ('deger', models.CharField(max_length=50, verbose_name='Değer')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basari_istatistikleri', to='kurum.kurum')),
            ],
            options={
                'verbose_name': 'Başarı İstatistiği',
                'verbose_name_plural': 'Başarı İstatistikleri',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='YasalMetin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('kvkk', 'KVKK Aydınlatma Metni'), ('gizlilik', 'Gizlilik Politikası'), ('kullanim', 'Kullanım Koşulları'), ('cerez', 'Çerez Politikası')], max_length=30, verbose_name='Tür')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yasal_metinler', to='kurum.kurum')),
            ],
            options={
                'verbose_name': 'Yasal Metin',
                'verbose_name_plural': 'Yasal Metinler',
                'unique_together': {('kurum', 'tur')},
            },
        ),
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='Slug')),
                ('ozet', models.TextField(blank=True, default='', verbose_name='Özet')),
                ('icerik', models.TextField(blank=True, default='', verbose_name='İçerik')),
                ('kapak_gorseli', models.ImageField(blank=True, null=True, upload_to=apps.website.models.duyuru_kapak_upload_to, verbose_name='Kapak Görseli')),
                ('yayin_tarihi', models.DateField(blank=True, null=True, verbose_name='Yayın Tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duyurular', to='kurum.kurum')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-yayin_tarihi', '-created_at'],
                'unique_together': {('kurum', 'slug')},
            },
        ),
    ]
