# Generated by Django 4.2.9 on 2026-07-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_cms_v2_page_builder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contententry',
            options={'ordering': ['sira', '-is_pinned', '-publish_at', '-created_at'], 'verbose_name': 'İçerik', 'verbose_name_plural': 'İçerikler'},
        ),
        migrations.AddField(
            model_name='contententry',
            name='sira',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sıra'),
        ),
    ]
