# Generated by Django 4.2.9 on 2026-07-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_contententry_options_contententry_sira'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_gallery',
            field=models.JSONField(blank=True, default=list, verbose_name='Hero Galeri Görselleri'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_rotating_words',
            field=models.JSONField(blank=True, default=list, verbose_name='Hero Dönen Kelimeler'),
        ),
    ]
