# Generated by Django 4.2.27 on 2026-07-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_sitesettings_hero_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ders_formatlari_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ders Formatları'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_bolumleri',
            field=models.JSONField(blank=True, default=list, verbose_name='Ek Anasayfa Bölümleri'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='neden_alt_baslik',
            field=models.CharField(blank=True, default='Başarıya giden yolda fark yaratan hizmetlerimiz', max_length=300, verbose_name='Neden Alt Başlık'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='neden_baslik',
            field=models.CharField(blank=True, default='Neden 3K Kampüs?', max_length=200, verbose_name='Neden Başlık'),
        ),
    ]
