# Generated by Django 4.2.27 on 2026-07-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_sitesettings_landing_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='landing_section_order',
            field=models.JSONField(blank=True, default=list, verbose_name='Anasayfa Bölüm Sırası'),
        ),
    ]
