# Generated by Django 4.2.27 on 2026-07-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_sitesettings_landing_section_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sss_goster',
            field=models.BooleanField(default=True, verbose_name='SSS Anasayfada'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yorumlar_goster',
            field=models.BooleanField(default=True, verbose_name='Öğrenci Yorumları Anasayfada'),
        ),
    ]
