# Generated by Django 4.2.27 on 2026-07-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_sitesettings_section_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='landing_sections_hidden',
            field=models.JSONField(blank=True, default=list, verbose_name='Gizli Anasayfa Bölümleri'),
        ),
    ]
