# Generated by Django 4.2.27 on 2026-07-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_sitesettings_landing_sections_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='search_console_html_filename',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Search Console HTML dosyası'),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='search_console_html_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
