# Generated by Django 4.2.27 on 2026-07-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_sitesettings_company_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='eposta',
            field=models.EmailField(blank=True, default='info@3kkampus.com', max_length=254, verbose_name='E-posta'),
        ),
    ]
