# Generated by Django 4.2.27 on 2026-07-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_sitesettings_eposta_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='harita_goster',
            field=models.BooleanField(default=True, help_text='Kapalıyken iletişim sayfasında Google Harita gömülüsü gösterilmez; URL saklanır.', verbose_name='Haritayı Göster'),
        ),
    ]
