# Generated by Django 4.2.27 on 2026-08-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_sitesettings_harita_goster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='telefon',
            field=models.TextField(blank=True, default='', help_text='Birden fazla numara için her satıra bir telefon yazın (sabit / cep).', verbose_name='Telefon(lar)'),
        ),
    ]
