# Generated by Django 4.2.27 on 2026-02-04 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kurum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Benzersiz yetki kodu, örn: ogrenci.read', max_length=100, unique=True, verbose_name='Yetki Kodu')),
                ('name', models.CharField(help_text='Kullanıcı arayüzünde görünen ad', max_length=200, verbose_name='Yetki Adı')),
                ('description', models.TextField(blank=True, help_text='Yetkinin ne yaptığını açıklar', verbose_name='Açıklama')),
                ('module', models.CharField(help_text='Yetkinin ait olduğu modül, örn: ogrenci, personel, finans', max_length=50, verbose_name='Modül')),
                ('permission_type', models.CharField(choices=[('read', 'Okuma'), ('write', 'Yazma'), ('delete', 'Silme'), ('manage', 'Yönetme'), ('admin', 'Tam Yetki')], default='read', max_length=20, verbose_name='Yetki Türü')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Yetki',
                'verbose_name_plural': 'Yetkiler',
                'db_table': 'system_permission',
                'ordering': ['module', 'permission_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Benzersiz rol kodu, örn: super_admin, ogretmen', max_length=50, unique=True, verbose_name='Rol Kodu')),
                ('name', models.CharField(help_text='Kullanıcı arayüzünde görünen ad', max_length=100, verbose_name='Rol Adı')),
                ('description', models.TextField(blank=True, help_text='Rolün ne yaptığını ve hangi yetkilere sahip olduğunu açıklar', verbose_name='Açıklama')),
                ('is_system_role', models.BooleanField(default=False, help_text='Sistem rolleri silinemez ve kodu değiştirilemez', verbose_name='Sistem Rolü')),
                ('level', models.IntegerField(default=100, help_text='Düşük değer = yüksek öncelik. super_admin=0, ogrenci=1000', verbose_name='Seviye')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roller',
                'db_table': 'system_role',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Atanma Tarihi')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='Atayan')),
                ('kurum', models.ForeignKey(blank=True, help_text='Boş ise global rol', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='kurum.kurum', verbose_name='Kurum')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_roles', to='roller.role', verbose_name='Rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Rolü',
                'verbose_name_plural': 'Kullanıcı Rolleri',
                'db_table': 'system_user_role',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Verilme Tarihi')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Veren')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='roller.permission', verbose_name='Yetki')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='roller.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol Yetkisi',
                'verbose_name_plural': 'Rol Yetkileri',
                'db_table': 'system_role_permission',
                'ordering': ['role', 'permission'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='roller.RolePermission', to='roller.permission', verbose_name='Yetkiler'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['module'], name='system_perm_module_cfd533_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['permission_type'], name='system_perm_permiss_25fea1_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['is_active'], name='system_perm_is_acti_2ed69b_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['kurum'], name='system_user_kurum_i_d9d811_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['code'], name='system_role_code_620ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_system_role'], name='system_role_is_syst_4071ff_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_active'], name='system_role_is_acti_debf45_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['level'], name='system_role_level_47eb10_idx'),
        ),
    ]
