# Generated by Django 4.2.27 on 2026-02-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Kullanıcının ilk girişte şifre değiştirmesi gerekiyor mu?', verbose_name='Şifre Değişikliği Zorunlu'),
        ),
    ]
