# Generated by Django 4.2.27 on 2026-06-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roller', '0002_personel_aktivite_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='silindi_mi',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Silindi'),
        ),
        migrations.AddField(
            model_name='role',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(help_text='Benzersiz rol kodu, örn: super_admin, ogretmen', max_length=50, verbose_name='Rol Kodu'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['silindi_mi'], name='system_role_silindi_d02ed9_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi_mi', False)), fields=('code',), name='unique_active_role_code'),
        ),
    ]
