# Generated by Django 4.2.27 on 2026-02-19 21:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ogrenci_id', models.IntegerField(verbose_name='Öğrenci ID')),
                ('durum', models.CharField(choices=[('PRESENT', 'Geldi'), ('LATE', 'Geç Geldi'), ('ABSENT', 'Gelmedi'), ('NOT_AT_DESK', 'Masada Yok'), ('EXCUSED', 'İzinli')], default='PRESENT', max_length=20, verbose_name='Durum')),
                ('giris_saati', models.TimeField(blank=True, null=True, verbose_name='Giriş Saati')),
                ('izinli_mi', models.BooleanField(default=False, help_text='Öğrenci izin kaydı nedeniyle otomatik olarak EXCUSED yapıldı mı', verbose_name='Otomatik İzinli mi')),
                ('kaydeden_id', models.IntegerField(verbose_name='Kaydeden Personel ID')),
                ('kayit_zamani', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Zamanı')),
                ('notlar', models.CharField(blank=True, default='', max_length=200, verbose_name='Notlar')),
            ],
            options={
                'verbose_name': 'Yoklama Kaydı',
                'verbose_name_plural': 'Yoklama Kayıtları',
                'db_table': 'kutuphane_yoklama_kayit',
                'ordering': ['ogrenci_id'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periyot_kodu', models.CharField(choices=[('MORNING', 'Sabah'), ('AFTERNOON', 'Öğle'), ('EVENING', 'Akşam'), ('CUSTOM', 'Özel')], default='MORNING', help_text='Yoklama periyodu: MORNING, AFTERNOON, EVENING, CUSTOM', max_length=20, verbose_name='Periyot Kodu')),
                ('tarih', models.DateField(verbose_name='Yoklama Tarihi')),
                ('yoklama_tipi', models.CharField(choices=[('PERIOD', 'Periyot Yoklaması'), ('LESSON', 'Ders Bazlı Yoklama')], default='PERIOD', help_text='PERIOD=Tüm periyot için tek yoklama, LESSON=Ders bazlı yoklama', max_length=20, verbose_name='Yoklama Tipi')),
                ('ders_no', models.PositiveIntegerField(blank=True, help_text='Ders bazlı yoklama ise ders numarası (1,2,3...). Periyot yoklaması ise null.', null=True, verbose_name='Ders Numarası')),
                ('durum', models.CharField(choices=[('OPEN', 'Açık'), ('CLOSED', 'Kapalı'), ('CANCELLED', 'İptal')], default='OPEN', max_length=20, verbose_name='Durum')),
                ('acan_id', models.IntegerField(verbose_name='Açan Personel ID')),
                ('acilis_zamani', models.DateTimeField(auto_now_add=True, verbose_name='Açılış Zamanı')),
                ('kapatan_id', models.IntegerField(blank=True, null=True, verbose_name='Kapatan Personel ID')),
                ('kapanis_zamani', models.DateTimeField(blank=True, null=True, verbose_name='Kapanış Zamanı')),
                ('notlar', models.TextField(blank=True, default='', verbose_name='Notlar')),
            ],
            options={
                'verbose_name': 'Yoklama Oturumu',
                'verbose_name_plural': 'Yoklama Oturumları',
                'db_table': 'kutuphane_yoklama_oturum',
                'ordering': ['-tarih', '-acilis_zamani'],
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kurum_id', models.IntegerField(verbose_name='Kurum ID')),
                ('ad', models.CharField(max_length=150, verbose_name='Salon Adı')),
                ('kod', models.CharField(max_length=20, verbose_name='Salon Kodu')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('kapasite', models.PositiveIntegerField(verbose_name='Toplam Kapasite')),
                ('durum', models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Pasif'), ('MAINTENANCE', 'Bakımda')], default='ACTIVE', max_length=20, verbose_name='Durum')),
                ('calisma_saatleri', models.JSONField(default=dict, verbose_name='Çalışma Saatleri')),
                ('dolap_var_mi', models.BooleanField(default=False, verbose_name='Dolap Alanı Var mı')),
                ('dolap_sayisi', models.PositiveIntegerField(default=0, verbose_name='Dolap Sayısı')),
                ('max_gecici_sure_saat', models.PositiveIntegerField(default=4, verbose_name='Maks Geçici Süre (Saat)')),
                ('kurallar', models.TextField(blank=True, default='', verbose_name='Kütüphane Kuralları')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='Oluşturan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Kütüphane Salonu',
                'verbose_name_plural': 'Kütüphane Salonları',
                'db_table': 'kutuphane_salon',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='LibraryAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50, verbose_name='Varlık Tipi')),
                ('entity_id', models.UUIDField(verbose_name='Varlık ID')),
                ('action', models.CharField(choices=[('CREATE', 'Oluşturma'), ('UPDATE', 'Güncelleme'), ('DELETE', 'Silme'), ('STATUS_CHANGE', 'Durum Değişikliği')], max_length=20, verbose_name='İşlem')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Eski Değerler')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Yeni Değerler')),
                ('performed_by', models.IntegerField(blank=True, null=True, verbose_name='İşlemi Yapan')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Zamanı')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Denetim Logu',
                'verbose_name_plural': 'Denetim Logları',
                'db_table': 'kutuphane_denetim_log',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kurum_id', models.IntegerField(verbose_name='Kurum ID')),
                ('dolap_no', models.CharField(max_length=20, verbose_name='Dolap Numarası')),
                ('boyut', models.CharField(choices=[('STANDARD', 'Standart'), ('SMALL', 'Küçük'), ('MEDIUM', 'Orta'), ('LARGE', 'Büyük')], default='STANDARD', max_length=10, verbose_name='Boyut')),
                ('kilit_tipi', models.CharField(choices=[('KEY', 'Anahtar'), ('COMBINATION', 'Şifreli'), ('ELECTRONIC', 'Elektronik')], default='KEY', max_length=20, verbose_name='Kilit Tipi')),
                ('anahtar_no', models.CharField(blank=True, default='', max_length=20, verbose_name='Anahtar No')),
                ('durum', models.CharField(choices=[('AVAILABLE', 'Boş'), ('ASSIGNED', 'Atanmış'), ('MAINTENANCE', 'Bakımda')], default='AVAILABLE', max_length=20, verbose_name='Durum')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('son_bosaltma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Son Boşaltma Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Dolap',
                'verbose_name_plural': 'Dolaplar',
                'db_table': 'kutuphane_dolap',
                'ordering': ['kurum_id', 'dolap_no'],
            },
        ),
        migrations.CreateModel(
            name='LockerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kurum_id', models.IntegerField(verbose_name='Kurum ID')),
                ('ogrenci_id', models.IntegerField(verbose_name='Öğrenci ID')),
                ('atama_tipi', models.CharField(choices=[('PERMANENT', 'Kalıcı'), ('TEMPORARY', 'Geçici')], default='PERMANENT', max_length=20, verbose_name='Atama Tipi')),
                ('depozit_odendi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Ödenen Depozit')),
                ('depozit_iade_edildi', models.BooleanField(default=False, verbose_name='Depozit İade Edildi mi')),
                ('depozit_iade_tarihi', models.DateField(blank=True, null=True, verbose_name='İade Tarihi')),
                ('anahtar_verildi', models.BooleanField(default=False, verbose_name='Anahtar Verildi mi')),
                ('anahtar_no', models.CharField(blank=True, default='', max_length=20, verbose_name='Anahtar No')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('durum', models.CharField(choices=[('ACTIVE', 'Aktif'), ('ENDED', 'Sona Erdi'), ('SUSPENDED', 'Askıya Alındı')], default='ACTIVE', max_length=20, verbose_name='Durum')),
                ('atayan_id', models.IntegerField(blank=True, null=True, verbose_name='Atayan Personel ID')),
                ('notlar', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Dolap Ataması',
                'verbose_name_plural': 'Dolap Atamaları',
                'db_table': 'kutuphane_dolap_atama',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OgrenciIzin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ogrenci_id', models.IntegerField(verbose_name='Öğrenci ID')),
                ('kurum_id', models.IntegerField(verbose_name='Kurum ID')),
                ('izin_tipi', models.CharField(choices=[('PERIOD', 'Periyot İzni'), ('FULL_DAY', 'Tam Gün İzni')], default='PERIOD', max_length=20, verbose_name='İzin Tipi')),
                ('gun', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], help_text='Haftanın günü (0=Pazartesi ... 6=Pazar)', verbose_name='Gün')),
                ('periyot_kodu', models.CharField(blank=True, choices=[('MORNING', 'Sabah'), ('AFTERNOON', 'Öğle'), ('EVENING', 'Akşam'), ('CUSTOM', 'Özel')], help_text='İzin tipi PERIOD ise hangi periyot (FULL_DAY ise null)', max_length=20, null=True, verbose_name='Periyot Kodu')),
                ('baslangic_tarihi', models.DateField(help_text='İznin geçerli olduğu başlangıç tarihi', verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(blank=True, help_text='Null ise süresiz', null=True, verbose_name='Bitiş Tarihi')),
                ('sebep', models.CharField(blank=True, default='', max_length=255, verbose_name='İzin Sebebi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturan_id', models.IntegerField(blank=True, null=True, verbose_name='Oluşturan Personel ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Öğrenci İzni',
                'verbose_name_plural': 'Öğrenci İzinleri',
                'db_table': 'kutuphane_ogrenci_izin',
                'ordering': ['ogrenci_id', 'gun', 'periyot_kodu'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('masa_no', models.CharField(max_length=20, verbose_name='Masa Numarası')),
                ('etiket', models.CharField(blank=True, default='', max_length=50, verbose_name='Etiket')),
                ('bolge', models.CharField(blank=True, default='', max_length=50, verbose_name='Bölge')),
                ('masa_tipi', models.CharField(choices=[('STANDARD', 'Standart'), ('PREMIUM', 'Premium'), ('ACCESSIBLE', 'Engelli Erişimli')], default='STANDARD', max_length=20, verbose_name='Masa Tipi')),
                ('durum', models.CharField(choices=[('AVAILABLE', 'Boş'), ('OCCUPIED', 'Dolu'), ('RESERVED', 'Rezerve'), ('OUT_OF_SERVICE', 'Kullanım Dışı')], default='AVAILABLE', max_length=20, verbose_name='Durum')),
                ('priz_var_mi', models.BooleanField(default=False, verbose_name='Priz Var mı')),
                ('lamba_var_mi', models.BooleanField(default=False, verbose_name='Lamba Var mı')),
                ('pozisyon_x', models.FloatField(default=0, verbose_name='Pozisyon X')),
                ('pozisyon_y', models.FloatField(default=0, verbose_name='Pozisyon Y')),
                ('pozisyon_w', models.PositiveIntegerField(default=1, verbose_name='Genişlik')),
                ('pozisyon_h', models.PositiveIntegerField(default=1, verbose_name='Yükseklik')),
                ('notlar', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Masa',
                'verbose_name_plural': 'Masalar',
                'db_table': 'kutuphane_masa',
                'ordering': ['library', 'sira', 'masa_no'],
            },
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ogrenci_id', models.IntegerField(verbose_name='Öğrenci ID')),
                ('atama_tipi', models.CharField(choices=[('PERMANENT', 'Kalıcı'), ('TEMPORARY', 'Geçici'), ('TRIAL', 'Deneme'), ('MAKEUP', 'Telafi'), ('GUEST', 'Misafir')], default='PERMANENT', max_length=20, verbose_name='Atama Tipi')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('durum', models.CharField(choices=[('ACTIVE', 'Aktif'), ('ENDED', 'Sona Erdi'), ('SUSPENDED', 'Askıya Alındı')], default='ACTIVE', max_length=20, verbose_name='Durum')),
                ('atayan_id', models.IntegerField(blank=True, null=True, verbose_name='Atayan Personel ID')),
                ('sonlandiran_id', models.IntegerField(blank=True, null=True, verbose_name='Sonlandıran Personel ID')),
                ('sonlanma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Sonlanma Tarihi')),
                ('sonlanma_sebebi', models.CharField(blank=True, default='', max_length=200, verbose_name='Sonlanma Sebebi')),
                ('notlar', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Masa Ataması',
                'verbose_name_plural': 'Masa Atamaları',
                'db_table': 'kutuphane_masa_atama',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=50, verbose_name='Oturum Adı')),
                ('kod', models.CharField(choices=[('MORNING', 'Sabah'), ('AFTERNOON', 'Öğle'), ('EVENING', 'Akşam'), ('CUSTOM', 'Özel')], default='CUSTOM', max_length=20, verbose_name='Oturum Kodu')),
                ('baslangic_saati', models.TimeField(verbose_name='Başlangıç Saati')),
                ('bitis_saati', models.TimeField(verbose_name='Bitiş Saati')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Oturum Tanımı',
                'verbose_name_plural': 'Oturum Tanımları',
                'db_table': 'kutuphane_oturum_tanimi',
                'ordering': ['library', 'sira'],
            },
        ),
        migrations.CreateModel(
            name='TemporarySeating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ogrenci_id', models.IntegerField(verbose_name='Öğrenci ID')),
                ('sebep', models.CharField(choices=[('TRIAL', 'Deneme'), ('GUEST', 'Misafir'), ('EXAM_PREP', 'Sınav Hazırlık'), ('MAKEUP', 'Telafi'), ('OTHER', 'Diğer')], default='OTHER', max_length=20, verbose_name='Sebep')),
                ('baslangic_zamani', models.DateTimeField(verbose_name='Başlangıç Zamanı')),
                ('beklenen_bitis_zamani', models.DateTimeField(verbose_name='Beklenen Bitiş')),
                ('gercek_bitis_zamani', models.DateTimeField(blank=True, null=True, verbose_name='Gerçek Bitiş')),
                ('durum', models.CharField(choices=[('ACTIVE', 'Aktif'), ('ENDED', 'Sona Erdi'), ('EXPIRED', 'Süresi Doldu'), ('CANCELLED', 'İptal')], default='ACTIVE', max_length=20, verbose_name='Durum')),
                ('onaylayan_id', models.IntegerField(verbose_name='Onaylayan Personel ID')),
                ('notlar', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecici_oturmalar', to='kutuphane.library', verbose_name='Kütüphane')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecici_oturmalar', to='kutuphane.seat', verbose_name='Masa')),
            ],
            options={
                'verbose_name': 'Geçici Oturma',
                'verbose_name_plural': 'Geçici Oturmalar',
                'db_table': 'kutuphane_gecici_oturma',
                'ordering': ['-baslangic_zamani'],
            },
        ),
        migrations.CreateModel(
            name='SubeDersProgrami',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sube_id', models.IntegerField(verbose_name='Şube ID')),
                ('kurum_id', models.IntegerField(verbose_name='Kurum ID')),
                ('ad', models.CharField(default='Varsayılan Program', max_length=100, verbose_name='Program Adı')),
                ('ders_saatleri', models.JSONField(default=dict, help_text='Periyot bazlı ders saatleri ve molalar', verbose_name='Ders Saatleri')),
                ('gun_bazli_aktiflik', models.JSONField(default=dict, help_text='Hangi gün hangi periyotlar aktif', verbose_name='Gün Bazlı Aktiflik')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Şube Ders Programı',
                'verbose_name_plural': 'Şube Ders Programları',
                'db_table': 'kutuphane_sube_ders_programi',
                'ordering': ['sube_id', 'ad'],
                'indexes': [models.Index(fields=['sube_id'], name='kutuphane_s_sube_id_b13892_idx'), models.Index(fields=['kurum_id'], name='kutuphane_s_kurum_i_7bdf39_idx'), models.Index(fields=['kurum_id', 'aktif_mi'], name='kutuphane_s_kurum_i_efcaf7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='subedersprogrami',
            constraint=models.UniqueConstraint(condition=models.Q(('aktif_mi', True)), fields=('sube_id',), name='unique_sube_aktif_program'),
        ),
        migrations.AddField(
            model_name='sessiondefinition',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oturum_tanimlari', to='kutuphane.library', verbose_name='Kütüphane'),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masa_atamalari', to='kutuphane.library', verbose_name='Kütüphane'),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atamalar', to='kutuphane.seat', verbose_name='Masa'),
        ),
        migrations.AddField(
            model_name='seat',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masalar', to='kutuphane.library', verbose_name='Kütüphane'),
        ),
        migrations.AddField(
            model_name='ogrenciizin',
            name='library',
            field=models.ForeignKey(blank=True, help_text='Boş ise tüm salonlar için geçerli', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ogrenci_izinleri', to='kutuphane.library', verbose_name='Kütüphane'),
        ),
        migrations.AddField(
            model_name='lockerassignment',
            name='locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atamalar', to='kutuphane.locker', verbose_name='Dolap'),
        ),
        migrations.AddIndex(
            model_name='locker',
            index=models.Index(fields=['kurum_id', 'durum'], name='kutuphane_d_kurum_i_35a254_idx'),
        ),
        migrations.AddIndex(
            model_name='locker',
            index=models.Index(fields=['is_deleted'], name='kutuphane_d_is_dele_3a2573_idx'),
        ),
        migrations.AddConstraint(
            model_name='locker',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('kurum_id', 'dolap_no'), name='unique_kurum_dolap_no'),
        ),
        migrations.AddIndex(
            model_name='libraryauditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='kutuphane_d_entity__fd5153_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryauditlog',
            index=models.Index(fields=['performed_at'], name='kutuphane_d_perform_bd5b90_idx'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['kurum_id'], name='kutuphane_s_kurum_i_70d19d_idx'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['kod'], name='kutuphane_s_kod_095daf_idx'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['durum'], name='kutuphane_s_durum_296e83_idx'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['is_deleted'], name='kutuphane_s_is_dele_d2d8f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('kurum_id', 'kod'), name='unique_kurum_salon_kod'),
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('kurum_id', 'ad'), name='unique_kurum_salon_ad'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yoklama_oturumlari', to='kutuphane.library', verbose_name='Kütüphane'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yoklama_oturumlari', to='kutuphane.sessiondefinition', verbose_name='Oturum Tanımı'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='sube_ders_programi',
            field=models.ForeignKey(blank=True, help_text='Yoklama anındaki ders programı referansı', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yoklama_oturumlari', to='kutuphane.subedersprogrami', verbose_name='Ders Programı'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='attendance_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kayitlar', to='kutuphane.attendancesession', verbose_name='Yoklama Oturumu'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yoklama_kayitlari', to='kutuphane.seat', verbose_name='Masa'),
        ),
        migrations.AddIndex(
            model_name='temporaryseating',
            index=models.Index(fields=['library', 'durum'], name='kutuphane_g_library_2cebf8_idx'),
        ),
        migrations.AddIndex(
            model_name='temporaryseating',
            index=models.Index(fields=['seat', 'durum'], name='kutuphane_g_seat_id_d06afc_idx'),
        ),
        migrations.AddIndex(
            model_name='temporaryseating',
            index=models.Index(fields=['ogrenci_id'], name='kutuphane_g_ogrenci_cc06a1_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiondefinition',
            index=models.Index(fields=['library', 'aktif_mi'], name='kutuphane_o_library_4e28ba_idx'),
        ),
        migrations.AddIndex(
            model_name='seatassignment',
            index=models.Index(fields=['library', 'durum'], name='kutuphane_m_library_b2c77e_idx'),
        ),
        migrations.AddIndex(
            model_name='seatassignment',
            index=models.Index(fields=['seat', 'durum'], name='kutuphane_m_seat_id_a28666_idx'),
        ),
        migrations.AddIndex(
            model_name='seatassignment',
            index=models.Index(fields=['ogrenci_id', 'durum'], name='kutuphane_m_ogrenci_8558b8_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['library', 'durum'], name='kutuphane_m_library_e16956_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['library', 'masa_tipi'], name='kutuphane_m_library_60e893_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['is_deleted'], name='kutuphane_m_is_dele_04efaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('library', 'masa_no'), name='unique_library_masa_no'),
        ),
        migrations.AddIndex(
            model_name='ogrenciizin',
            index=models.Index(fields=['ogrenci_id', 'aktif_mi'], name='kutuphane_o_ogrenci_6a9727_idx'),
        ),
        migrations.AddIndex(
            model_name='ogrenciizin',
            index=models.Index(fields=['kurum_id'], name='kutuphane_o_kurum_i_615419_idx'),
        ),
        migrations.AddIndex(
            model_name='ogrenciizin',
            index=models.Index(fields=['gun', 'periyot_kodu'], name='kutuphane_o_gun_3b1588_idx'),
        ),
        migrations.AddIndex(
            model_name='ogrenciizin',
            index=models.Index(fields=['library', 'gun'], name='kutuphane_o_library_56acbb_idx'),
        ),
        migrations.AddIndex(
            model_name='lockerassignment',
            index=models.Index(fields=['kurum_id', 'durum'], name='kutuphane_d_kurum_i_04680c_idx'),
        ),
        migrations.AddIndex(
            model_name='lockerassignment',
            index=models.Index(fields=['locker', 'durum'], name='kutuphane_d_locker__2d4742_idx'),
        ),
        migrations.AddIndex(
            model_name='lockerassignment',
            index=models.Index(fields=['ogrenci_id', 'durum'], name='kutuphane_d_ogrenci_aa7ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['library', 'tarih'], name='kutuphane_y_library_24052c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['durum'], name='kutuphane_y_durum_abfc5d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['tarih', 'yoklama_tipi'], name='kutuphane_y_tarih_b0a614_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('yoklama_tipi', 'PERIOD')), fields=('library', 'periyot_kodu', 'tarih'), name='unique_yoklama_period'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('yoklama_tipi', 'LESSON')), fields=('library', 'periyot_kodu', 'tarih', 'ders_no'), name='unique_yoklama_lesson'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['attendance_session', 'ogrenci_id'], name='kutuphane_y_attenda_c127cb_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['ogrenci_id', 'durum'], name='kutuphane_y_ogrenci_b3b344_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('attendance_session', 'ogrenci_id'), name='unique_yoklama_kayit_ogrenci'),
        ),
    ]
