# Generated by Django 4.2.27 on 2026-09-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0005_ogrenciizin_tekrar_modu'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancenotificationlog',
            new_name='kutuphane_y_attenda_bb6776_idx',
            old_name='kutuphane_y_attenda_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancenotificationlog',
            new_name='kutuphane_y_ogrenci_ceb577_idx',
            old_name='kutuphane_y_ogrenci_idx',
        ),
        migrations.RenameIndex(
            model_name='ogrenciizin',
            new_name='kutuphane_o_tekrar__0d3414_idx',
            old_name='kutuphane_o_tekrar__idx',
        ),
    ]
