# Generated by Django 4.2.27 on 2026-07-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci_kayit', '0002_draftenrollment_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftguardian',
            name='telefonlar',
            field=models.JSONField(blank=True, default=list, help_text='Ek/çoklu telefonlar; telefon alanı WhatsApp varsayılanıdır.'),
        ),
    ]
