# Generated by Django 4.2.27 on 2026-06-26 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kurum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundcampaign',
            name='estimated_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Tahmini Maliyet (USD)'),
        ),
        migrations.AddField(
            model_name='outboundcampaign',
            name='repeat_rule_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='outboundcampaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zamanlanmış Gönderim'),
        ),
        migrations.AddField(
            model_name='outboundcampaign',
            name='send_options_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('deneme_sonucu', 'Deneme Sonucu'), ('haftalik_odev', 'Haftalık Ödev'), ('devamsizlik', 'Devamsızlık'), ('tebrik', 'Tebrik'), ('odeme', 'Ödeme'), ('karne', 'Karne'), ('duyuru', 'Duyuru'), ('ozel', 'Özel')], default='ozel', max_length=32, verbose_name='Kategori')),
                ('name', models.CharField(max_length=200, verbose_name='Şablon Adı')),
                ('body', models.TextField(blank=True, default='', verbose_name='Mesaj Metni')),
                ('variables_json', models.JSONField(blank=True, default=list, verbose_name='Değişkenler')),
                ('attachment_ids_json', models.JSONField(blank=True, default=list, verbose_name='Ek ID Listesi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Kullanım Sayısı')),
                ('stats_sent', models.PositiveIntegerField(default=0)),
                ('stats_read', models.PositiveIntegerField(default=0)),
                ('stats_failed', models.PositiveIntegerField(default=0)),
                ('avg_read_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates', to=settings.AUTH_USER_MODEL)),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='kurum.kurum', verbose_name='Kurum')),
            ],
            options={
                'verbose_name': 'Mesaj Şablonu',
                'verbose_name_plural': 'Mesaj Şablonları',
                'db_table': 'comm_message_template',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to='communication/campaign_attachments/%Y/%m/')),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_attachments', to='kurum.kurum', verbose_name='Kurum')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kampanya Eki',
                'verbose_name_plural': 'Kampanya Ekleri',
                'db_table': 'comm_campaign_attachment',
            },
        ),
        migrations.AddField(
            model_name='outboundcampaign',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='communication.campaignattachment', verbose_name='Ekler'),
        ),
        migrations.AddField(
            model_name='outboundcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='communication.messagetemplate', verbose_name='Mesaj Şablonu'),
        ),
    ]
