# Generated by Django 4.2.27 on 2026-07-06 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kimlik', '0002_kisi_unique_kurum_kisi_tc_and_more'),
        ('communication', '0007_sube_scoped_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactidentity',
            name='kisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_identities', to='kimlik.kisi', verbose_name='Merkezi Kişi'),
        ),
    ]
