# Generated by Django 4.2.27 on 2026-08-02 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
        ('communication', '0009_multi_whatsapp_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('MESSAGE_IN', 'Gelen mesaj'), ('MESSAGE_OUT', 'Giden mesaj'), ('CLAIMED', 'Üstlenildi'), ('RELEASED', 'Bırakıldı'), ('TRANSFERRED', 'Devredildi'), ('STATUS_CHANGED', 'Durum değişti'), ('SLA_BREACH', 'SLA ihlali'), ('ASSIGNED_COACH_SYNC', 'Koç senkron'), ('NOTE_ADDED', 'İç not'), ('TAG_CHANGED', 'Etiket değişti'), ('ARCHIVED', 'Arşivlendi'), ('UNARCHIVED', 'Arşivden çıkarıldı')], max_length=32)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sohbet Olayı',
                'verbose_name_plural': 'Sohbet Olayları',
                'db_table': 'comm_conversation_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('edit_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'İç Not',
                'verbose_name_plural': 'İç Notlar',
                'db_table': 'comm_conversation_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationRoutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('COACHING', 'Koçluk'), ('ACCOUNTING', 'Muhasebe'), ('SECRETARIAT', 'Sekreterya'), ('GUIDANCE', 'Rehberlik'), ('ADMISSIONS', 'Kayıt Ofisi'), ('MANAGEMENT', 'Yönetim')], default='COACHING', max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('actions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yönlendirme Kuralı',
                'verbose_name_plural': 'Yönlendirme Kuralları',
                'db_table': 'comm_conversation_routing_rule',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConversationTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(blank=True, default='#64748b', max_length=16)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sohbet Etiketi',
                'verbose_name_plural': 'Sohbet Etiketleri',
                'db_table': 'comm_conversation_tag',
            },
        ),
        migrations.CreateModel(
            name='ConversationTransferLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sohbet Devir',
                'verbose_name_plural': 'Sohbet Devirleri',
                'db_table': 'comm_conversation_transfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='communicationchannelconfig',
            name='department',
            field=models.CharField(choices=[('COACHING', 'Koçluk'), ('ACCOUNTING', 'Muhasebe'), ('SECRETARIAT', 'Sekreterya'), ('GUIDANCE', 'Rehberlik'), ('ADMISSIONS', 'Kayıt Ofisi'), ('MANAGEMENT', 'Yönetim')], db_index=True, default='COACHING', max_length=32, verbose_name='Departman'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arşiv Zamanı'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='claim_version',
            field=models.PositiveIntegerField(default=0, verbose_name='Claim Versiyonu'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='claimed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Üstlenen Kullanıcı'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kişi Adı'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='department',
            field=models.CharField(choices=[('COACHING', 'Koçluk'), ('ACCOUNTING', 'Muhasebe'), ('SECRETARIAT', 'Sekreterya'), ('GUIDANCE', 'Rehberlik'), ('ADMISSIONS', 'Kayıt Ofisi'), ('MANAGEMENT', 'Yönetim')], db_index=True, default='COACHING', max_length=32, verbose_name='Departman'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='first_unanswered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İlk Cevapsız'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_customer_message_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Müşteri Mesajı'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_reply_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Kurum Cevabı'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='needs_support_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Destek Gerekiyor Zamanı'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Açık'), ('AWAITING_REPLY', 'Cevap Bekliyor'), ('ARCHIVED', 'Arşiv'), ('NEW', 'Yeni'), ('READ', 'Okundu'), ('REPLIED', 'Yanıtlandı'), ('WAITING', 'Bekliyor'), ('NEEDS_SUPPORT', 'Destek Gerekiyor'), ('CLOSED', 'Kapalı')], default='OPEN', max_length=20, verbose_name='Durum'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['kurum', 'department', 'status'], name='comm_conv_dept_status_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['kurum', 'claimed_by_user'], name='comm_conv_claimed_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['kurum', 'first_unanswered_at'], name='comm_conv_sla_idx'),
        ),
        migrations.AddField(
            model_name='conversationtransferlog',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_logs', to='communication.conversation'),
        ),
        migrations.AddField(
            model_name='conversationtransferlog',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_transfers_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationtransferlog',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_transfers_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationtag',
            name='kurum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_tags', to='kurum.kurum'),
        ),
        migrations.AddField(
            model_name='conversationroutingrule',
            name='kurum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_routing_rules', to='kurum.kurum'),
        ),
        migrations.AddField(
            model_name='conversationnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationnote',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='communication.conversation'),
        ),
        migrations.AddField(
            model_name='conversationevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationevent',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='communication.conversation'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='communication.conversationtag', verbose_name='Etiketler'),
        ),
        migrations.AddConstraint(
            model_name='conversationtag',
            constraint=models.UniqueConstraint(fields=('kurum', 'slug'), name='unique_conv_tag_slug_per_kurum'),
        ),
        migrations.AddIndex(
            model_name='conversationevent',
            index=models.Index(fields=['conversation', 'created_at'], name='comm_evt_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationevent',
            index=models.Index(fields=['event_type', 'created_at'], name='comm_evt_type_created_idx'),
        ),
    ]
