# Generated by Django 4.2.27 on 2026-08-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0011_whatsapp_meta_template'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='comm_msg_conv_created_idx'),
        ),
    ]
