# Generated by Django 4.2.9 on 2026-08-02 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sube', '0003_sube_branding'),
        ('communication', '0013_outboundqueueitem_send_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplateBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(db_index=True, max_length=64, verbose_name='Olay')),
                ('recipient_type', models.CharField(choices=[('OGRENCI', 'Öğrenci'), ('VELI', 'Veli'), ('PERSONEL', 'Personel'), ('RAW_PHONE', 'Ham Telefon')], max_length=20, verbose_name='Alıcı Rolü')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'E-posta'), ('PUSH', 'Push Bildirim')], default='WHATSAPP', max_length=20, verbose_name='Kanal')),
                ('send_mode', models.CharField(choices=[('AUTO', 'Otomatik (Meta şablonu varsa onu kullan)'), ('META_ONLY', 'Yalnızca Meta şablonu'), ('FREEFORM_ONLY', 'Yalnızca serbest mesaj'), ('DISABLED', 'Kapalı (gönderme)')], default='AUTO', max_length=20, verbose_name='Gönderim Modu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_template_bindings', to='communication.communicationchannelconfig', verbose_name='WhatsApp Hesabı')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_template_bindings', to='kurum.kurum', verbose_name='Kurum')),
                ('message_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_bindings', to='communication.messagetemplate', verbose_name='LMS Şablonu')),
                ('meta_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_bindings', to='communication.whatsappmetatemplate', verbose_name='Meta Şablonu')),
                ('sube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_template_bindings', to='sube.sube', verbose_name='Şube')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_template_bindings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirim Şablon Eşlemesi',
                'verbose_name_plural': 'Bildirim Şablon Eşlemeleri',
                'db_table': 'comm_notification_template_binding',
                'ordering': ['event_key', 'recipient_type'],
                'indexes': [models.Index(fields=['kurum', 'event_key', 'recipient_type'], name='comm_notif_bind_lookup_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationtemplatebinding',
            constraint=models.UniqueConstraint(condition=models.Q(('channel_config__isnull', True), ('sube__isnull', True)), fields=('kurum', 'event_key', 'recipient_type', 'channel'), name='comm_notif_binding_kurum_uniq'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplatebinding',
            constraint=models.UniqueConstraint(condition=models.Q(('channel_config__isnull', True), ('sube__isnull', False)), fields=('kurum', 'sube', 'event_key', 'recipient_type', 'channel'), name='comm_notif_binding_sube_uniq'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplatebinding',
            constraint=models.UniqueConstraint(condition=models.Q(('channel_config__isnull', False), ('sube__isnull', True)), fields=('kurum', 'channel_config', 'event_key', 'recipient_type', 'channel'), name='comm_notif_binding_account_uniq'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplatebinding',
            constraint=models.UniqueConstraint(condition=models.Q(('channel_config__isnull', False), ('sube__isnull', False)), fields=('kurum', 'sube', 'channel_config', 'event_key', 'recipient_type', 'channel'), name='comm_notif_binding_full_uniq'),
        ),
    ]
