# Generated by Django 4.2.9 on 2026-08-03 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0015_migrate_notification_bindings'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='meta_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_templates', to='communication.whatsappmetatemplate', verbose_name='Meta Karşılığı'),
        ),
        migrations.AddField(
            model_name='whatsappmetatemplate',
            name='usage_scope',
            field=models.CharField(choices=[('ALL', 'Her yerde'), ('SYSTEM', 'Otomatik bildirimler'), ('PERSONAL', 'Sohbet — kişisel mesaj'), ('CAMPAIGN', 'Toplu duyuru')], db_index=True, default='ALL', max_length=16, verbose_name='Kullanım Alanı'),
        ),
        migrations.AlterField(
            model_name='notificationtemplatebinding',
            name='send_mode',
            field=models.CharField(choices=[('AUTO', 'Otomatik (24 saat kuralına göre seç)'), ('META_ONLY', 'Her zaman Meta şablonu'), ('FREEFORM_ONLY', 'Yalnızca serbest mesaj'), ('DISABLED', 'Kapalı (gönderme)')], default='AUTO', max_length=20, verbose_name='Gönderim Modu'),
        ),
    ]
