# Generated by Django 4.2.27 on 2026-09-02 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0026_meta_campaign_audience_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Zamanı'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı'),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Zamanı'),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_messages', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı'),
        ),
        migrations.AddField(
            model_name='message',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='communication.message', verbose_name='İletilen mesaj'),
        ),
        migrations.AddField(
            model_name='message',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yıldızlayanlar'),
        ),
        migrations.AlterField(
            model_name='whatsappmetatemplate',
            name='campaign_audience',
            field=models.CharField(blank=True, db_index=True, default='', help_text='veli / ogrenci / personel / genel. Boşsa ada göre tahmin edilir.', max_length=16, verbose_name='Toplu gönderim kitlesi'),
        ),
        migrations.CreateModel(
            name='ConversationUserState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pinned_at', models.DateTimeField(blank=True, null=True, verbose_name='Sabitlenme Zamanı')),
                ('muted_until', models.DateTimeField(blank=True, null=True, verbose_name='Bildirim Susturma Bitişi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='communication.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sohbet Kullanıcı Durumu',
                'verbose_name_plural': 'Sohbet Kullanıcı Durumları',
                'db_table': 'comm_conversation_user_state',
                'indexes': [models.Index(fields=['user', 'pinned_at'], name='comm_conv_state_pin_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='conversationuserstate',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='comm_conv_user_state_uniq'),
        ),
    ]
