# Generated by Django 4.2.27 on 2026-09-23 23:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
        ('communication', '0032_conversation_list_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignDeliveryArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('status_events_deleted', models.PositiveIntegerField(default=0)),
                ('messages_deleted', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kampanya Teslimat Arşivi',
                'verbose_name_plural': 'Kampanya Teslimat Arşivleri',
                'db_table': 'comm_campaign_delivery_archive',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.AddField(
            model_name='outboundcampaign',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundcampaign',
            name='client_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='outboundcampaign',
            name='deliveries_archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundcampaign',
            name='materialized_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outboundqueueitem',
            name='provider_call_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outboundcampaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Taslak'), ('CONFIRMED', 'Onaylandı'), ('QUEUED', 'Kuyrukta'), ('PROCESSING', 'İşleniyor'), ('COMPLETED', 'Tamamlandı'), ('PARTIAL', 'Kısmi'), ('CANCELLED', 'İptal'), ('FAILED', 'Başarısız')], default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['campaign', 'status'], name='comm_msg_camp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundcampaign',
            index=models.Index(fields=['kurum', '-created_at'], name='comm_camp_kurum_created_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundcampaign',
            index=models.Index(fields=['kurum', 'status'], name='comm_camp_kurum_status_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundqueueitem',
            index=models.Index(fields=['kurum', '-created_at'], name='comm_queue_kurum_created_idx'),
        ),
        migrations.AddIndex(
            model_name='rawwebhookevent',
            index=models.Index(fields=['kurum', 'created_at'], name='comm_rawwh_kurum_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='outboundcampaign',
            constraint=models.UniqueConstraint(condition=models.Q(('client_token__gt', '')), fields=('kurum', 'client_token'), name='comm_camp_client_token_uniq'),
        ),
        migrations.AddField(
            model_name='campaigndeliveryarchive',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_archive', to='communication.outboundcampaign'),
        ),
        migrations.AddField(
            model_name='campaigndeliveryarchive',
            name='kurum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_delivery_archives', to='kurum.kurum'),
        ),
        migrations.AddIndex(
            model_name='campaigndeliveryarchive',
            index=models.Index(fields=['kurum', 'archived_at'], name='comm_cdarch_kurum_archived_idx'),
        ),
    ]
