# Generated by Django 4.2.9 on 2026-01-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Kurum Adı')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Kurum Kodu')),
                ('telefon_sabit', models.CharField(blank=True, max_length=20, verbose_name='Sabit Telefon')),
                ('telefon_cep', models.CharField(blank=True, max_length=20, verbose_name='Cep Telefon')),
                ('yetkili_ad_soyad', models.CharField(blank=True, max_length=200, verbose_name='Yetkili Ad Soyad')),
                ('vergi_no', models.CharField(blank=True, max_length=20, verbose_name='Vergi No')),
                ('vergi_dairesi', models.CharField(blank=True, max_length=100, verbose_name='Vergi Dairesi')),
                ('adres', models.TextField(blank=True, verbose_name='Adres')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Kurum',
                'verbose_name_plural': 'Kurumlar',
                'db_table': 'kurum',
                'ordering': ['ad'],
                'indexes': [models.Index(fields=['kod'], name='kurum_kod_c227a4_idx'), models.Index(fields=['aktif_mi'], name='kurum_aktif_m_171b0e_idx')],
            },
        ),
    ]
