# Generated by Django 4.2.27 on 2026-06-30 18:31

import apps.kurum.domain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurum', '0002_kurum_branding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurum',
            name='app_logo',
            field=models.ImageField(blank=True, help_text='Sidebar ve açık zemin için renkli logo', null=True, upload_to=apps.kurum.domain.models.app_logo_upload_to, verbose_name='Uygulama Logosu'),
        ),
        migrations.AlterField(
            model_name='kurum',
            name='favicon',
            field=models.FileField(blank=True, help_text='.ico veya .png', null=True, upload_to=apps.kurum.domain.models.favicon_upload_to, verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='kurum',
            name='gorunen_ad',
            field=models.CharField(blank=True, default='', help_text='Web ve login ekranında görünen ad (boşsa kurum adı kullanılır)', max_length=200, verbose_name='Görünen Ad'),
        ),
        migrations.AlterField(
            model_name='kurum',
            name='login_arkaplan_rengi_2',
            field=models.CharField(blank=True, default='', help_text='Gradient ikinci renk', max_length=7, verbose_name='Login Arka Plan Rengi 2'),
        ),
        migrations.AlterField(
            model_name='kurum',
            name='login_logo',
            field=models.ImageField(blank=True, help_text='Koyu arka plan için (genelde beyaz/açık logo)', null=True, upload_to=apps.kurum.domain.models.login_logo_upload_to, verbose_name='Login Logosu'),
        ),
        migrations.AlterField(
            model_name='kurum',
            name='tema_rengi',
            field=models.CharField(blank=True, default='', help_text='Buton, sidebar vurgu rengi', max_length=7, verbose_name='Tema Rengi'),
        ),
    ]
