declare module 'react-datepicker' {
  import * as React from 'react';

  export interface ReactDatePickerProps {
    selected?: Date | null;
    onChange: (date: Date | null, event?: React.SyntheticEvent<any>) => void;
    dateFormat?: string | string[];
    maxDate?: Date;
    minDate?: Date;
    showMonthDropdown?: boolean;
    showYearDropdown?: boolean;
    dropdownMode?: 'scroll' | 'select';
    placeholderText?: string;
    className?: string;
    disabled?: boolean;
    readOnly?: boolean;
    required?: boolean;
    name?: string;
    id?: string;
    autoComplete?: string;
    locale?: string;
    isClearable?: boolean;
    showTimeSelect?: boolean;
    timeFormat?: string;
    timeIntervals?: number;
    timeCaption?: string;
    inline?: boolean;
    peekNextMonth?: boolean;
    showMonthYearPicker?: boolean;
    showFullMonthYearPicker?: boolean;
    showTwoColumnMonthYearPicker?: boolean;
    showFourColumnMonthYearPicker?: boolean;
    showYearPicker?: boolean;
    yearItemNumber?: number;
    calendarStartDay?: number;
    filterDate?: (date: Date) => boolean;
    excludeDates?: Date[];
    includeDates?: Date[];
    highlightDates?: Date[];
    selectsStart?: boolean;
    selectsEnd?: boolean;
    startDate?: Date | null;
    endDate?: Date | null;
    openToDate?: Date;
    onBlur?: (event: React.FocusEvent<HTMLInputElement>) => void;
    onFocus?: (event: React.FocusEvent<HTMLInputElement>) => void;
    onKeyDown?: (event: React.KeyboardEvent<HTMLInputElement>) => void;
    onClickOutside?: (event: React.MouseEvent<HTMLDivElement>) => void;
    onCalendarOpen?: () => void;
    onCalendarClose?: () => void;
    wrapperClassName?: string;
    calendarClassName?: string;
    dayClassName?: (date: Date) => string | null;
    monthClassName?: (date: Date) => string | null;
    timeClassName?: (time: Date) => string | null;
    customInput?: React.ReactNode;
    customInputRef?: string;
    portalId?: string;
    popperPlacement?: string;
    popperModifiers?: object[];
    popperProps?: object;
    preventOpenOnFocus?: boolean;
    onInputClick?: () => void;
    onInputError?: (err: { code: number; msg: string }) => void;
    renderCustomHeader?: (params: {
      date: Date;
      changeYear: (year: number) => void;
      changeMonth: (month: number) => void;
      decreaseMonth: () => void;
      increaseMonth: () => void;
      prevMonthButtonDisabled: boolean;
      nextMonthButtonDisabled: boolean;
    }) => React.ReactNode;
    renderDayContents?: (dayOfMonth: number, date?: Date) => React.ReactNode;
    withPortal?: boolean;
    shouldCloseOnSelect?: boolean;
    showPopperArrow?: boolean;
    ariaLabelClose?: string;
    ariaLabelledBy?: string;
    ariaDescribedBy?: string;
    ariaRequired?: boolean;
    ariaInvalid?: string;
    autoFocus?: boolean;
    tabIndex?: number;
    strictParsing?: boolean;
    title?: string;
    adjustDateOnChange?: boolean;
    allowSameDay?: boolean;
    useWeekdaysShort?: boolean;
    forceShowMonthNavigation?: boolean;
    showDisabledMonthNavigation?: boolean;
    formatWeekNumber?: (date: Date) => string | number;
    formatWeekDay?: (formattedDate: string) => React.ReactNode;
    onDayMouseEnter?: (date: Date) => void;
    onMonthMouseLeave?: () => void;
    onSelect?: (date: Date, event?: React.SyntheticEvent<any>) => void;
    showWeekNumbers?: boolean;
    showWeekPicker?: boolean;
    weekLabel?: string;
    fixedHeight?: boolean;
    previousMonthAriaLabel?: string;
    previousMonthButtonLabel?: string | React.ReactNode;
    previousYearAriaLabel?: string;
    previousYearButtonLabel?: string;
    nextMonthAriaLabel?: string;
    nextMonthButtonLabel?: string | React.ReactNode;
    nextYearAriaLabel?: string;
    nextYearButtonLabel?: string;
    chooseDayAriaLabelPrefix?: string;
    disabledDayAriaLabelPrefix?: string;
    monthAriaLabelPrefix?: string;
    weekAriaLabelPrefix?: string;
    focusSelectedMonth?: boolean;
    dateFormatCalendar?: string;
    calendarContainer?: (props: { children: React.ReactNode }) => React.ReactNode;
    clearButtonClassName?: string;
    clearButtonTitle?: string;
    todayButton?: React.ReactNode;
    useShortMonthInDropdown?: boolean;
    showPreviousMonths?: boolean;
    monthsShown?: number;
    children?: React.ReactNode;
    excludeScrollbar?: boolean;
    enableTabLoop?: boolean;
    yearDropdownItemNumber?: number;
    scrollableYearDropdown?: boolean;
    scrollableMonthYearDropdown?: boolean;
  }

  const DatePicker: React.FC<ReactDatePickerProps>;
  export default DatePicker;
  export function registerLocale(localeName: string, localeObj: object): void;
}
