# Generated by Django 4.2.27 on 2026-07-06 23:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_kimlik_no', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='TC Kimlik No 11 haneli olmalıdır', regex='^\\d{11}$')], verbose_name='TC Kimlik No')),
                ('telefon', models.CharField(blank=True, default='', help_text='Normalize edilmiş cep telefonu (0532...)', max_length=20, verbose_name='Telefon')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyad')),
                ('dogum_tarihi', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('cinsiyet', models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kadın')], max_length=1, null=True, verbose_name='Cinsiyet')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-posta')),
                ('adres', models.TextField(blank=True, default='', verbose_name='Adres')),
                ('il', models.CharField(blank=True, default='', max_length=50, verbose_name='İl')),
                ('ilce', models.CharField(blank=True, default='', max_length=50, verbose_name='İlçe')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kisiler', to='kurum.kurum', verbose_name='Kurum')),
            ],
            options={
                'verbose_name': 'Kişi',
                'verbose_name_plural': 'Kişiler',
                'db_table': 'kimlik_kisi',
                'ordering': ['soyad', 'ad'],
                'indexes': [models.Index(fields=['kurum', 'tc_kimlik_no'], name='kimlik_kisi_kurum_tc'), models.Index(fields=['kurum', 'telefon'], name='kimlik_kisi_kurum_tel'), models.Index(fields=['kurum', 'ad', 'soyad'], name='kimlik_kisi_kurum_ad')],
            },
        ),
    ]
