# Generated by Django 4.2.27 on 2026-07-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimlik', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='kisi',
            constraint=models.UniqueConstraint(condition=models.Q(('tc_kimlik_no__isnull', False)), fields=('kurum', 'tc_kimlik_no'), name='unique_kurum_kisi_tc'),
        ),
        migrations.AddConstraint(
            model_name='kisi',
            constraint=models.UniqueConstraint(condition=models.Q(('telefon', ''), _negated=True), fields=('kurum', 'telefon'), name='unique_kurum_kisi_telefon'),
        ),
    ]
