# Generated by Django 4.2.9 on 2026-02-05 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sube', '0001_initial'),
        ('kurum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örn: Lise Programı, Hafta Sonu Programı', max_length=100, verbose_name='Şablon Adı')),
                ('description', models.TextField(blank=True, help_text='Şablon hakkında ek bilgi', null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, help_text='Pasif şablonlar seçilemez', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='kurum.kurum', verbose_name='Kurum')),
                ('sube', models.ForeignKey(blank=True, help_text='Belirli bir şubeye özel ise seçin, boş bırakılırsa tüm şubelerde kullanılabilir', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Zaman Şablonu',
                'verbose_name_plural': 'Zaman Şablonları',
                'db_table': 'schedule_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örn: 1. Ders, Teneffüs, Öğle Arası', max_length=50, verbose_name='Slot Adı')),
                ('start_time', models.TimeField(help_text='Format: HH:MM', verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(help_text='Format: HH:MM', verbose_name='Bitiş Saati')),
                ('order', models.PositiveIntegerField(help_text='Günlük sıralama için', verbose_name='Sıra No')),
                ('is_break', models.BooleanField(default=False, help_text='Teneffüs veya öğle arası gibi molalar için işaretleyin', verbose_name='Mola mı?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('schedule_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='academic.scheduletemplate', verbose_name='Zaman Şablonu')),
            ],
            options={
                'verbose_name': 'Ders Saati',
                'verbose_name_plural': 'Ders Saatleri',
                'db_table': 'timeslot',
                'ordering': ['schedule_template', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('schedule_template', 'order'), name='unique_order_per_template'),
        ),
        migrations.AddConstraint(
            model_name='scheduletemplate',
            constraint=models.UniqueConstraint(fields=('kurum', 'sube', 'name'), name='unique_template_name_per_branch'),
        ),
    ]
