# Generated by Django 4.2.27 on 2026-02-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='unique_order_per_template',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='is_break',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slot_type',
            field=models.CharField(choices=[('LESSON', 'Ders'), ('SHORT_BREAK', 'Kısa Teneffüs'), ('LUNCH_BREAK', 'Öğle Arası'), ('EVENING_BREAK', 'Akşam Arası'), ('CUSTOM_BREAK', 'Özel Mola')], default='LESSON', help_text='Ders veya mola türünü belirler', max_length=20, verbose_name='Slot Türü'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('schedule_template', 'order'), name='unique_order_per_template_active'),
        ),
    ]
