# Generated by Django 4.2.27 on 2026-02-05 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_add_slot_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örn: Standart Hafta, A Haftası, B Haftası', max_length=100, verbose_name='Döngü Adı')),
                ('description', models.TextField(blank=True, help_text='Döngü hakkında açıklama', null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, help_text='Pasif döngüler grid oluşturmada kullanılmaz', verbose_name='Aktif mi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('schedule_template', models.ForeignKey(help_text='Bu döngünün bağlı olduğu zaman şablonu', on_delete=django.db.models.deletion.CASCADE, related_name='weekly_cycles', to='academic.scheduletemplate', verbose_name='Zaman Şablonu')),
            ],
            options={
                'verbose_name': 'Haftalık Döngü',
                'verbose_name_plural': 'Haftalık Döngüler',
                'db_table': 'academic_weekly_cycle',
                'ordering': ['schedule_template', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], help_text='0=Pazartesi, 6=Pazar', verbose_name='Haftanın Günü')),
                ('name', models.CharField(help_text='Örn: Pazartesi, Salı', max_length=50, verbose_name='Gün Adı')),
                ('order', models.PositiveIntegerField(default=1, help_text='Grid sütun sırası', verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, help_text="Pasif günler grid'de görünmez", verbose_name='Aktif mi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('weekly_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_days', to='academic.weeklycycle', verbose_name='Haftalık Döngü')),
            ],
            options={
                'verbose_name': 'Haftalık Gün',
                'verbose_name_plural': 'Haftalık Günler',
                'db_table': 'academic_weekly_day',
                'ordering': ['weekly_cycle', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramGridCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EMPTY', 'Boş'), ('LOCKED', 'Kilitli'), ('FILLED', 'Dolu'), ('HOLIDAY', 'Tatil'), ('EXAM', 'Sınav'), ('BLOCKED', 'Bloklanmış')], default='EMPTY', help_text='Hücre durumu: EMPTY, LOCKED, FILLED, HOLIDAY, EXAM, BLOCKED', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, help_text='Hücre hakkında notlar', null=True, verbose_name='Notlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('schedule_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_cells', to='academic.scheduletemplate', verbose_name='Zaman Şablonu')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_cells', to='academic.timeslot', verbose_name='Zaman Dilimi')),
                ('weekly_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_cells', to='academic.weeklycycle', verbose_name='Haftalık Döngü')),
                ('weekly_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_cells', to='academic.weeklyday', verbose_name='Haftalık Gün')),
            ],
            options={
                'verbose_name': 'Program Grid Hücresi',
                'verbose_name_plural': 'Program Grid Hücreleri',
                'db_table': 'academic_program_grid_cell',
                'ordering': ['weekly_day__order', 'timeslot__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='weeklyday',
            constraint=models.UniqueConstraint(fields=('weekly_cycle', 'day_of_week'), name='unique_day_per_cycle'),
        ),
        migrations.AddConstraint(
            model_name='weeklycycle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('schedule_template', 'name'), name='unique_cycle_name_per_template_active'),
        ),
        migrations.AddConstraint(
            model_name='programgridcell',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('schedule_template', 'weekly_cycle', 'weekly_day', 'timeslot'), name='unique_grid_cell_active'),
        ),
    ]
