# Generated by Django 4.2.27 on 2026-02-06 00:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_tanimlari', '0009_merge_20260201_0154'),
        ('personel', '0009_personel_aktivite_log'),
        ('sinif', '0002_sinif_oda'),
        ('egitim_yili', '0001_initial'),
        ('term', '0001_initial'),
        ('academic', '0003_weekly_cycle_and_grid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_hours', models.PositiveIntegerField(help_text='Haftada kaç saat ders yapılacak', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Haftalık Saat')),
                ('credit', models.PositiveIntegerField(default=0, help_text='Dersin kredi değeri', validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Kredi')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Zorunlu ders mi?', verbose_name='Zorunlu Ders')),
                ('is_double_block', models.BooleanField(default=False, help_text='Ders çift blok olarak mı programlanacak? (2 saat arka arkaya)', verbose_name='Çift Blok')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Yüksek değer = yüksek öncelik (program motorunda önce yerleştirilir)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Öncelik')),
                ('preferred_room_type', models.CharField(blank=True, help_text='Örn: lab, spor_salonu, muzik_odasi', max_length=50, null=True, verbose_name='Tercih Edilen Oda Tipi')),
                ('notes', models.TextField(blank=True, help_text='Ders planı hakkında ek notlar', null=True, verbose_name='Notlar')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete için kullanılır', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_lesson_plans', to='egitim_tanimlari.ders', verbose_name='Ders')),
                ('egitim_yili', models.ForeignKey(help_text='Aktif eğitim yılı otomatik atanır', on_delete=django.db.models.deletion.CASCADE, related_name='class_lesson_plans', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('ogretmen', models.ForeignKey(blank=True, help_text='Dersi verecek öğretmen (opsiyonel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lessons', to='personel.personel', verbose_name='Öğretmen')),
                ('sinif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='sinif.sinif', verbose_name='Sınıf')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_lesson_plans', to='term.term', verbose_name='Dönem')),
            ],
            options={
                'verbose_name': 'Sınıf Ders Planı',
                'verbose_name_plural': 'Sınıf Ders Planları',
                'db_table': 'class_lesson_plan',
                'ordering': ['sinif', 'ders__ad'],
                'indexes': [models.Index(fields=['sinif', 'is_active'], name='idx_clp_sinif'), models.Index(fields=['term', 'is_active'], name='idx_clp_term'), models.Index(fields=['ogretmen', 'is_active'], name='idx_clp_ogretmen'), models.Index(fields=['ders', 'is_active'], name='idx_clp_ders'), models.Index(fields=['egitim_yili', 'term', 'sinif'], name='idx_clp_composite')],
            },
        ),
        migrations.AddConstraint(
            model_name='classlessonplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('egitim_yili', 'term', 'sinif', 'ders'), name='unique_class_lesson_plan_active'),
        ),
    ]
