# Generated by Django 4.2.27 on 2026-02-06 17:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_yili', '0001_initial'),
        ('personel', '0009_personel_aktivite_log'),
        ('egitim_tanimlari', '0009_merge_20260201_0154'),
        ('academic', '0004_class_lesson_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLessonTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRIMARY', 'Asıl Öğretmen'), ('SECONDARY', 'Yardımcı Öğretmen'), ('ASSISTANT', 'Asistan Öğretmen'), ('CO_TEACHER', 'Ortak Öğretmen'), ('SUBSTITUTE', 'Vekil Öğretmen')], default='PRIMARY', help_text='Öğretmenin bu ders için rolü', max_length=20, verbose_name='Rol')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Öncelik sırası (1 = en yüksek)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Öncelik')),
                ('max_hours_for_class', models.PositiveIntegerField(blank=True, help_text='Bu sınıf için öğretmenin maksimum ders saati', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Maksimum Saat')),
                ('notes', models.TextField(blank=True, help_text='Atama hakkında notlar', null=True, verbose_name='Notlar')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete için kullanılır', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('class_lesson_plan', models.ForeignKey(help_text='Öğretmenin atandığı sınıf ders planı', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academic.classlessonplan', verbose_name='Sınıf Ders Planı')),
                ('egitim_yili', models.ForeignKey(help_text='Aktif eğitim yılı otomatik atanır', on_delete=django.db.models.deletion.CASCADE, related_name='class_lesson_teacher_assignments', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('ogretmen', models.ForeignKey(help_text='Atanan öğretmen', on_delete=django.db.models.deletion.CASCADE, related_name='class_lesson_assignments', to='personel.personel', verbose_name='Öğretmen')),
            ],
            options={
                'verbose_name': 'Sınıf Ders Öğretmen Ataması',
                'verbose_name_plural': 'Sınıf Ders Öğretmen Atamaları',
                'db_table': 'class_lesson_teacher_assignment',
                'ordering': ['class_lesson_plan', 'priority', 'role'],
            },
        ),
        migrations.CreateModel(
            name='LessonTeacherPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Bu öğretmenin asıl branşı mı? (Her ders için sadece bir asıl branş olabilir)', verbose_name='Asıl Branş')),
                ('max_weekly_load', models.PositiveIntegerField(blank=True, help_text='Bu ders için öğretmenin haftalık maksimum ders saati', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Maksimum Haftalık Yük')),
                ('notes', models.TextField(blank=True, help_text='Öğretmen-ders ilişkisi hakkında notlar', null=True, verbose_name='Notlar')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete için kullanılır', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('ders', models.ForeignKey(help_text='Öğretmen havuzunun ait olduğu ders', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_pool', to='egitim_tanimlari.ders', verbose_name='Ders')),
                ('egitim_yili', models.ForeignKey(help_text='Aktif eğitim yılı otomatik atanır', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_teacher_pools', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('ogretmen', models.ForeignKey(help_text='Havuza eklenen öğretmen', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_pools', to='personel.personel', verbose_name='Öğretmen')),
            ],
            options={
                'verbose_name': 'Branş Öğretmen Havuzu',
                'verbose_name_plural': 'Branş Öğretmen Havuzları',
                'db_table': 'lesson_teacher_pool',
                'ordering': ['ders__ad', '-is_primary', 'ogretmen__ad'],
                'indexes': [models.Index(fields=['ders', 'is_active'], name='idx_ltp_ders'), models.Index(fields=['ogretmen', 'is_active'], name='idx_ltp_ogretmen'), models.Index(fields=['egitim_yili', 'ders'], name='idx_ltp_yil_ders'), models.Index(fields=['is_primary', 'is_active'], name='idx_ltp_primary')],
            },
        ),
        migrations.AddConstraint(
            model_name='lessonteacherpool',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('egitim_yili', 'ders', 'ogretmen'), name='unique_lesson_teacher_pool_active'),
        ),
        migrations.AddIndex(
            model_name='classlessonteacherassignment',
            index=models.Index(fields=['class_lesson_plan', 'is_active'], name='idx_clta_plan'),
        ),
        migrations.AddIndex(
            model_name='classlessonteacherassignment',
            index=models.Index(fields=['ogretmen', 'is_active'], name='idx_clta_ogretmen'),
        ),
        migrations.AddIndex(
            model_name='classlessonteacherassignment',
            index=models.Index(fields=['role', 'is_active'], name='idx_clta_role'),
        ),
        migrations.AddIndex(
            model_name='classlessonteacherassignment',
            index=models.Index(fields=['egitim_yili', 'class_lesson_plan'], name='idx_clta_yil_plan'),
        ),
        migrations.AddIndex(
            model_name='classlessonteacherassignment',
            index=models.Index(fields=['priority'], name='idx_clta_priority'),
        ),
        migrations.AddConstraint(
            model_name='classlessonteacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('egitim_yili', 'class_lesson_plan', 'ogretmen'), name='unique_class_lesson_teacher_active'),
        ),
    ]
