# Generated by Django 4.2.9 on 2026-02-06 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_yili', '0001_initial'),
        ('ogrenci', '0005_add_profil_foto'),
        ('term', '0001_initial'),
        ('sinif', '0002_sinif_oda'),
        ('academic', '0005_add_lesson_teacher_pool_and_class_lesson_teacher_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örn: A, B, Lab-1, Etüt-2', max_length=50, verbose_name='Grup Adı')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Grup kapasitesi (boş = sınırsız)', null=True, verbose_name='Kapasite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='sinif.sinif', verbose_name='Sınıf')),
            ],
            options={
                'verbose_name': 'Sınıf Alt Grubu',
                'verbose_name_plural': 'Sınıf Alt Grupları',
                'db_table': 'academic_classroom_group',
                'ordering': ['classroom', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentClassPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_type', models.CharField(choices=[('PRIMARY', 'Asıl Öğrenci'), ('GUEST', 'Misafir Öğrenci'), ('TRANSFER', 'Nakil Öğrenci'), ('TEMPORARY', 'Geçici Yerleşim'), ('AUDIT', 'Dinleyici')], default='PRIMARY', max_length=20, verbose_name='Yerleşim Türü')),
                ('start_date', models.DateField(blank=True, help_text='Yerleşimin geçerli olduğu başlangıç tarihi', null=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, help_text='Yerleşimin geçerli olduğu bitiş tarihi', null=True, verbose_name='Bitiş Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_placements', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_placements', to='sinif.sinif', verbose_name='Sınıf')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='academic.classroomgroup', verbose_name='Alt Grup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_placements', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_placements', to='term.term', verbose_name='Dönem')),
            ],
            options={
                'verbose_name': 'Öğrenci Sınıf Yerleşimi',
                'verbose_name_plural': 'Öğrenci Sınıf Yerleşimleri',
                'db_table': 'academic_student_class_placement',
                'ordering': ['classroom__ad', 'student__ad', 'student__soyad'],
                'indexes': [models.Index(fields=['academic_year', 'term', 'is_active'], name='academic_st_academi_3512b1_idx'), models.Index(fields=['classroom', 'is_active'], name='academic_st_classro_aca795_idx'), models.Index(fields=['student', 'is_active'], name='academic_st_student_b948d6_idx'), models.Index(fields=['group', 'is_active'], name='academic_st_group_i_21ac86_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentclassplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('academic_year', 'term', 'student'), name='unique_active_student_term_placement'),
        ),
        migrations.AddIndex(
            model_name='classroomgroup',
            index=models.Index(fields=['classroom', 'is_active'], name='academic_cl_classro_57fb23_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('classroom', 'name'), name='unique_active_classroom_group'),
        ),
    ]
