# Generated by Django 4.2.9 on 2026-02-07 00:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_tanimlari', '0009_merge_20260201_0154'),
        ('sinif', '0002_sinif_oda'),
        ('personel', '0009_personel_aktivite_log'),
        ('egitim_yili', '0001_initial'),
        ('term', '0001_initial'),
        ('academic', '0006_student_class_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='programgridcell',
            name='class_lesson_plan',
            field=models.ForeignKey(blank=True, help_text='Bu yerleşimin kaynak planı', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_cells', to='academic.classlessonplan', verbose_name='Sınıf Ders Planı'),
        ),
        migrations.AddField(
            model_name='programgridcell',
            name='ders',
            field=models.ForeignKey(blank=True, help_text='Bu slota yerleştirilen ders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_cells', to='egitim_tanimlari.ders', verbose_name='Ders'),
        ),
        migrations.AddField(
            model_name='programgridcell',
            name='double_block_partner',
            field=models.ForeignKey(blank=True, help_text='Çift blok dersinin diğer hücresi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='double_block_source', to='academic.programgridcell', verbose_name='Çift Blok Partner'),
        ),
        migrations.AddField(
            model_name='programgridcell',
            name='is_double_block_start',
            field=models.BooleanField(default=False, help_text='Bu hücre çift blok dersinin başlangıcı mı?', verbose_name='Çift Blok Başlangıcı'),
        ),
        migrations.AddField(
            model_name='programgridcell',
            name='ogretmen',
            field=models.ForeignKey(blank=True, help_text='Bu slotta dersi verecek öğretmen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_cells', to='personel.personel', verbose_name='Öğretmen'),
        ),
        migrations.AddField(
            model_name='programgridcell',
            name='sinif',
            field=models.ForeignKey(blank=True, help_text='Bu hücrenin ait olduğu sınıf', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grid_cells', to='sinif.sinif', verbose_name='Sınıf'),
        ),
        migrations.CreateModel(
            name='ScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('PREVIEW', 'Önizleme'), ('EXECUTE', 'Çalıştırma'), ('RESET', 'Sıfırlama')], default='PREVIEW', max_length=20, verbose_name='Çalıştırma Tipi')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('RUNNING', 'Çalışıyor'), ('SUCCESS', 'Başarılı'), ('PARTIAL', 'Kısmen Başarılı'), ('FAILED', 'Başarısız')], default='PENDING', max_length=20, verbose_name='Durum')),
                ('total_jobs', models.PositiveIntegerField(default=0, help_text='Toplam ders yerleştirme job sayısı', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Toplam Job')),
                ('placed_jobs', models.PositiveIntegerField(default=0, help_text='Başarıyla yerleştirilen job sayısı', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Yerleştirilen')),
                ('failed_jobs', models.PositiveIntegerField(default=0, help_text='Yerleştirilemeyen job sayısı', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Başarısız')),
                ('log_json', models.JSONField(blank=True, default=dict, help_text='\n        Log yapısı:\n        {\n            "placed": [\n                {"lesson": "Matematik", "classroom": "9-A", "day": "Pazartesi", "slot": 1, "teacher": "Ahmet Hoca"},\n                ...\n            ],\n            "failed": [\n                {"lesson": "Fizik", "classroom": "9-A", "reason": "Öğretmen müsait değil", "attempted_slots": [...]},\n                ...\n            ],\n            "conflicts": [\n                {"type": "teacher", "teacher": "Ahmet Hoca", "day": "Pazartesi", "slot": 1, "classes": ["9-A", "10-B"]},\n                ...\n            ],\n            "warnings": [\n                {"message": "9-A için 5 saat Matematik planlandı ama 4 saat yerleşti"},\n                ...\n            ]\n        }\n        ', verbose_name='Log Verisi')),
                ('error_message', models.TextField(blank=True, help_text='Çalıştırma sırasında oluşan hata mesajı', null=True, verbose_name='Hata Mesajı')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Zamanı')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_runs', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('schedule_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_runs', to='academic.scheduletemplate', verbose_name='Zaman Şablonu')),
                ('sinif', models.ForeignKey(blank=True, help_text='Belirli bir sınıf için çalıştırma (boş = tüm sınıflar)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_runs', to='sinif.sinif', verbose_name='Sınıf')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_runs', to='term.term', verbose_name='Dönem')),
                ('weekly_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_runs', to='academic.weeklycycle', verbose_name='Haftalık Döngü')),
            ],
            options={
                'verbose_name': 'Program Çalıştırma Logu',
                'verbose_name_plural': 'Program Çalıştırma Logları',
                'db_table': 'schedule_run',
                'ordering': ['-created_at'],
            },
        ),
    ]
