# Generated by Django 4.2.9 on 2026-02-07 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('egitim_yili', '0001_initial'),
        ('term', '0001_initial'),
        ('academic', '0007_scheduler_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örn: Taslak v1, Onaylı 2024-25 1.Dönem', max_length=200, verbose_name='Versiyon Adı')),
                ('description', models.TextField(blank=True, help_text='Versiyon hakkında açıklama', null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=False, help_text='Aktif versiyon yoklama, görüntüleme vb. için kullanılır', verbose_name='Aktif mi')),
                ('is_locked', models.BooleanField(default=False, help_text='Kilitli versiyonlar düzenlenemez, sadece görüntülenir', verbose_name='Kilitli mi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Program Versiyonu',
                'verbose_name_plural': 'Program Versiyonları',
                'db_table': 'academic_schedule_version',
                'ordering': ['-created_at'],
            },
        ),
        # ScheduleVersion FK'ları ekle
        migrations.AddField(
            model_name='scheduleversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_versions', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='egitim_yili',
            field=models.ForeignKey(help_text='Bu versiyonun ait olduğu eğitim yılı', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_versions', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı'),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='schedule_template',
            field=models.ForeignKey(help_text='Bu versiyonun kullandığı zaman şablonu', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_versions', to='academic.scheduletemplate', verbose_name='Zaman Şablonu'),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='term',
            field=models.ForeignKey(help_text='Bu versiyonun ait olduğu dönem', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_versions', to='term.term', verbose_name='Dönem'),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='weekly_cycle',
            field=models.ForeignKey(help_text='Bu versiyonun kullandığı haftalık döngü', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_versions', to='academic.weeklycycle', verbose_name='Haftalık Döngü'),
        ),
        # ProgramGridCell'e schedule_version FK ekle (ÖNCE BU, SONRA INDEX)
        migrations.AddField(
            model_name='programgridcell',
            name='schedule_version',
            field=models.ForeignKey(blank=True, help_text='Bu hücrenin ait olduğu program versiyonu', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grid_cells', to='academic.scheduleversion', verbose_name='Program Versiyonu'),
        ),
        # Eski constraint kaldır
        migrations.RemoveConstraint(
            model_name='programgridcell',
            name='unique_grid_cell_active',
        ),
        # Şimdi index'leri ekle
        migrations.AddIndex(
            model_name='programgridcell',
            index=models.Index(fields=['schedule_version', 'sinif'], name='idx_grid_version_sinif'),
        ),
        migrations.AddIndex(
            model_name='programgridcell',
            index=models.Index(fields=['schedule_version', 'ogretmen'], name='idx_grid_version_ogretmen'),
        ),
        migrations.AddIndex(
            model_name='programgridcell',
            index=models.Index(fields=['schedule_version', 'status'], name='idx_grid_version_status'),
        ),
        migrations.AddConstraint(
            model_name='programgridcell',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('schedule_version', 'weekly_day', 'timeslot', 'sinif'), name='unique_grid_cell_version_sinif'),
        ),
        migrations.AddConstraint(
            model_name='programgridcell',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('schedule_version__isnull', True)), fields=('schedule_template', 'weekly_cycle', 'weekly_day', 'timeslot'), name='unique_grid_cell_legacy'),
        ),
        # ScheduleVersion index'leri
        migrations.AddIndex(
            model_name='scheduleversion',
            index=models.Index(fields=['term', 'is_active'], name='idx_version_term_active'),
        ),
        migrations.AddIndex(
            model_name='scheduleversion',
            index=models.Index(fields=['egitim_yili', 'is_active'], name='idx_version_year_active'),
        ),
        migrations.AddConstraint(
            model_name='scheduleversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('term', 'schedule_template', 'weekly_cycle'), name='unique_active_version_per_term_template_cycle'),
        ),
    ]
