# Generated by Django 4.2.9 on 2026-07-24 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0015_veli_telefonlar'),
        ('term', '0001_initial'),
        ('sinif', '0002_sinif_oda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personel', '0017_sozlesme_unique_per_sube'),
        ('egitim_tanimlari', '0010_sube_scoped_catalog'),
        ('egitim_yili', '0001_initial'),
        ('academic', '0014_weekly_cycle_program_tipi'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True, verbose_name='Tarih')),
                ('start_time', models.TimeField(verbose_name='Başlangıç')),
                ('end_time', models.TimeField(verbose_name='Bitiş')),
                ('session_kind', models.CharField(choices=[('REGULAR', 'Normal Ders'), ('PRIVATE', 'Özel Ders'), ('MAKEUP', 'Telafi Dersi'), ('EXTRA', 'Ek Ders')], db_index=True, default='REGULAR', max_length=16)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planlandı'), ('IN_PROGRESS', 'Devam Ediyor'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal'), ('POSTPONED', 'Ertelendi'), ('NO_SHOW', 'Öğretmen Gelmedi')], db_index=True, default='SCHEDULED', max_length=16)),
                ('teacher_attendance', models.CharField(choices=[('PENDING', 'Bekliyor'), ('PRESENT', 'Geldi'), ('ABSENT', 'Gelmedi'), ('SUBSTITUTE', 'Yerine Başkası')], default='PENDING', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=255)),
                ('payable', models.BooleanField(default=True, help_text='Tamamlanan oturum ders ücretine sayılır mı', verbose_name='Ücrete dahil')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='0 ise timeslot süresinden hesaplanır', verbose_name='Süre (dk)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_lesson_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_sessions', to='academic.classlessonplan', verbose_name='Sınıf Ders Planı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lesson_sessions', to=settings.AUTH_USER_MODEL)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_sessions', to='egitim_tanimlari.ders', verbose_name='Ders')),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_sessions', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('ogretmen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_sessions', to='personel.personel', verbose_name='Öğretmen')),
                ('private_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_lesson_sessions', to='ogrenci.ogrenci', verbose_name='Özel Ders Öğrencisi')),
                ('replaces_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makeup_sessions', to='academic.lessonsession', verbose_name='Telafi Edilen Oturum')),
                ('schedule_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_sessions', to='academic.scheduleversion', verbose_name='Program Versiyonu')),
                ('sinif', models.ForeignKey(blank=True, help_text='Özel derslerde boş olabilir', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_sessions', to='sinif.sinif', verbose_name='Sınıf')),
                ('source_grid_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_sessions', to='academic.programgridcell', verbose_name='Kaynak Grid Hücresi')),
                ('substitute_ogretmen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_lesson_sessions', to='personel.personel', verbose_name='Yedek Öğretmen')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_sessions', to='term.term', verbose_name='Dönem')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_sessions', to='academic.timeslot', verbose_name='Ders Saati')),
            ],
            options={
                'verbose_name': 'Ders Oturumu',
                'verbose_name_plural': 'Ders Oturumları',
                'db_table': 'academic_lesson_session',
                'ordering': ['session_date', 'start_time', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='weeklycycle',
            options={'ordering': ['name'], 'verbose_name': 'Çalışma Takvimi', 'verbose_name_plural': 'Çalışma Takvimleri'},
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='gun_yapisi_label',
            field=models.CharField(blank=True, default='', help_text='Görüntüleme etiketi — örn. Hafta İçi, Hafta Sonu', max_length=100, verbose_name='Gün Yapısı Etiketi'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='primary_weekly_cycle',
            field=models.ForeignKey(blank=True, help_text='Eski bağlantı — yeni kayıtlarda kullanılmaz', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_templates', to='academic.weeklycycle', verbose_name='Gün Yapısı'),
        ),
        migrations.AlterField(
            model_name='teacheravailabilityset',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_sets', to='personel.personel', verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='weeklycycle',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='weeklycycle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi'),
        ),
        migrations.AlterField(
            model_name='weeklycycle',
            name='name',
            field=models.CharField(help_text='Örn: Normal Eğitim, Hafta Sonu Grubu', max_length=100, verbose_name='Takvim Adı'),
        ),
        migrations.AlterField(
            model_name='weeklyday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weeklyday',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Haftanın Günü'),
        ),
        migrations.AlterField(
            model_name='weeklyday',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi'),
        ),
        migrations.AlterField(
            model_name='weeklyday',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Gün Adı'),
        ),
        migrations.AlterField(
            model_name='weeklyday',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='weeklyday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='weeklyday',
            name='weekly_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_days', to='academic.weeklycycle', verbose_name='Çalışma Takvimi'),
        ),
        migrations.CreateModel(
            name='ScheduleChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CELL_FILL', 'Hücre Doldurma'), ('CELL_CLEAR', 'Hücre Temizleme'), ('CELL_MOVE', 'Hücre Taşıma'), ('VERSION_CREATE', 'Versiyon Oluşturma'), ('VERSION_ACTIVATE', 'Versiyon Aktifleştirme'), ('VERSION_LOCK', 'Versiyon Kilitleme'), ('VERSION_UNLOCK', 'Versiyon Kilit Açma'), ('SESSION_CREATE', 'Oturum Oluşturma'), ('SESSION_CANCEL', 'Oturum İptal'), ('SESSION_COMPLETE', 'Oturum Tamamlama')], max_length=32)),
                ('summary', models.CharField(max_length=500)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_change_logs', to=settings.AUTH_USER_MODEL)),
                ('egitim_yili', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_change_logs', to='egitim_yili.egitimyili')),
                ('lesson_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='academic.lessonsession')),
                ('schedule_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='academic.scheduleversion')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_change_logs', to='term.term')),
            ],
            options={
                'verbose_name': 'Program Değişiklik Kaydı',
                'verbose_name_plural': 'Program Değişiklik Kayıtları',
                'db_table': 'academic_schedule_change_log',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='weekly_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_sessions', to='academic.weeklyday'),
        ),
        migrations.CreateModel(
            name='LessonAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Var'), ('LATE', 'Geç'), ('ABSENT', 'Yok'), ('EXCUSED', 'İzinli')], default='PRESENT', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_lesson_attendance', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic.lessonsession', verbose_name='Ders Oturumu')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attendance_records', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Öğrenci Yoklama Kaydı',
                'verbose_name_plural': 'Öğrenci Yoklama Kayıtları',
                'db_table': 'academic_lesson_attendance',
                'ordering': ['student__ad', 'student__soyad', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='lessonsession',
            index=models.Index(fields=['session_date', 'status'], name='idx_ls_date_status'),
        ),
        migrations.AddIndex(
            model_name='lessonsession',
            index=models.Index(fields=['ogretmen', 'session_date'], name='idx_ls_teacher_date'),
        ),
        migrations.AddIndex(
            model_name='lessonsession',
            index=models.Index(fields=['sinif', 'session_date'], name='idx_ls_sinif_date'),
        ),
        migrations.AddIndex(
            model_name='lessonsession',
            index=models.Index(fields=['session_kind', 'session_date'], name='idx_ls_kind_date'),
        ),
        migrations.AddConstraint(
            model_name='lessonsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('schedule_version__isnull', False), ('session_kind', 'REGULAR'), ('sinif__isnull', False)), fields=('schedule_version', 'session_date', 'timeslot', 'sinif'), name='unique_regular_session_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='lessonattendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_attendance_per_session_student'),
        ),
    ]
