# Generated by Django 4.2.9 on 2026-08-08 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
        ('sinif', '0002_sinif_oda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('term', '0001_initial'),
        ('academic', '0016_classlessonplan_gorunen_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassScheduleNotifyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('veli_count', models.PositiveIntegerField(default=0)),
                ('ogrenci_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SENT', 'Gönderildi'), ('PARTIAL', 'Kısmi'), ('SKIPPED', 'Atlandı'), ('FAILED', 'Başarısız')], default='SENT', max_length=16)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedule_notify_logs', to='kurum.kurum')),
                ('schedule_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_logs', to='academic.scheduleversion')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_schedule_notify_logs', to=settings.AUTH_USER_MODEL)),
                ('sinif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_notify_logs', to='sinif.sinif')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedule_notify_logs', to='term.term')),
            ],
            options={
                'verbose_name': 'Sınıf Programı Bildirim Kaydı',
                'verbose_name_plural': 'Sınıf Programı Bildirim Kayıtları',
                'db_table': 'academic_class_schedule_notify_log',
                'ordering': ['-sent_at', '-id'],
                'indexes': [models.Index(fields=['schedule_version', 'sinif', '-sent_at'], name='acad_notify_ver_sinif_idx')],
            },
        ),
    ]
