# Generated by Django 4.2.27 on 2026-08-09 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0016_ogrenci_not_and_audit'),
        ('term', '0001_initial'),
        ('sinif', '0002_sinif_oda'),
        ('communication', '0018_birthday_media_and_wish_log'),
        ('egitim_yili', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0018_schedule_change_action_plan_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPeriodAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True)),
                ('period', models.CharField(choices=[('MORNING', 'Sabah'), ('AFTERNOON', 'Öğleden Sonra')], db_index=True, max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_period_attendance', to=settings.AUTH_USER_MODEL)),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_period_attendance_sessions', to='egitim_yili.egitimyili')),
                ('schedule_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_period_attendance_sessions', to='academic.scheduleversion')),
                ('sinif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_period_attendance_sessions', to='sinif.sinif')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_period_attendance_sessions', to='term.term')),
            ],
            options={
                'verbose_name': 'Günlük Sınıf Yoklama Oturumu',
                'verbose_name_plural': 'Günlük Sınıf Yoklama Oturumları',
                'db_table': 'academic_class_period_attendance_session',
                'ordering': ['session_date', 'period', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClassPeriodAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Var'), ('LATE', 'Geç'), ('ABSENT', 'Yok'), ('EXCUSED', 'İzinli')], default='PRESENT', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_class_period_attendance', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='academic.classperiodattendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_period_attendance_records', to='ogrenci.ogrenci')),
            ],
            options={
                'verbose_name': 'Günlük Sınıf Yoklama Kaydı',
                'verbose_name_plural': 'Günlük Sınıf Yoklama Kayıtları',
                'db_table': 'academic_class_period_attendance_record',
                'ordering': ['student__ad', 'student__soyad', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClassAttendanceNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('LESSON', 'Ders oturumu'), ('PERIOD', 'Günlük periyot')], max_length=16)),
                ('source_id', models.PositiveIntegerField(db_index=True)),
                ('recipient_type', models.CharField(max_length=16)),
                ('recipient_id', models.PositiveIntegerField()),
                ('event_key', models.CharField(max_length=64)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_attendance_notify_logs', to='communication.message')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance_notify_logs', to='ogrenci.ogrenci')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_attendance_notifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sınıf Yoklama Bildirim Logu',
                'verbose_name_plural': 'Sınıf Yoklama Bildirim Logları',
                'db_table': 'academic_class_attendance_notify_log',
                'ordering': ['-sent_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='classperiodattendancesession',
            index=models.Index(fields=['sinif', 'session_date'], name='acad_period_att_sinif_date'),
        ),
        migrations.AddConstraint(
            model_name='classperiodattendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('sinif', 'session_date', 'period'), name='unique_active_class_period_attendance'),
        ),
        migrations.AddConstraint(
            model_name='classperiodattendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_class_period_attendance_student'),
        ),
        migrations.AddIndex(
            model_name='classattendancenotificationlog',
            index=models.Index(fields=['source_type', 'source_id', 'event_key'], name='acad_att_notify_src_idx'),
        ),
        migrations.AddConstraint(
            model_name='classattendancenotificationlog',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id', 'ogrenci', 'recipient_type', 'recipient_id', 'event_key'), name='unique_class_attendance_notify'),
        ),
    ]
