# Generated by Django 4.2.9 on 2026-08-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_class_period_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulechangelog',
            name='action',
            field=models.CharField(choices=[('CELL_FILL', 'Hücre Doldurma'), ('CELL_CLEAR', 'Hücre Temizleme'), ('CELL_MOVE', 'Hücre Taşıma'), ('VERSION_CREATE', 'Program Oluşturma'), ('VERSION_ACTIVATE', 'Program Etkinleştirme'), ('VERSION_LOCK', 'Program Kilitleme'), ('VERSION_UNLOCK', 'Program Kilit Açma'), ('SESSION_CREATE', 'Oturum Oluşturma'), ('SESSION_CANCEL', 'Oturum İptal'), ('SESSION_COMPLETE', 'Oturum Tamamlama'), ('PLAN_CREATE', 'Ders Planı Oluşturma'), ('PLAN_DELETE', 'Ders Planı Silme'), ('PLAN_SEED', 'Alandan Doldurma'), ('PLAN_COPY', 'Sınıfa Kopyalama')], max_length=32),
        ),
    ]
