# Generated by Django 4.2.9 on 2026-02-20 22:01

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sube', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ogrenci', '0007_add_ek_hizmet_system'),
        ('egitim_yili', '0001_initial'),
        ('kurum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndirimTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='İndirim Türü Adı')),
                ('kod', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('max_oran', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Bu indirim türü için izin verilen maksimum yüzde', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Maksimum Oran (%)')),
                ('onay_gerektiren_oran', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Bu yüzdenin üstündeki indirimler üst onay gerektirir', max_digits=5, verbose_name='Onay Gerektiren Oran (%)')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kurum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indirim_turleri', to='kurum.kurum', verbose_name='Kurum')),
                ('sube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indirim_turleri', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'İndirim Türü',
                'verbose_name_plural': 'İndirim Türleri',
                'db_table': 'indirim_turu',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='OdemeSekli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ödeme Şekli Adı')),
                ('kod', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kurum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odeme_sekilleri', to='kurum.kurum', verbose_name='Kurum')),
                ('sube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odeme_sekilleri', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Ödeme Şekli',
                'verbose_name_plural': 'Ödeme Şekilleri',
                'db_table': 'odeme_sekli',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='Sozlesme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sozlesme_no', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Sözleşme No')),
                ('kayit_tarihi', models.DateField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(verbose_name='Bitiş Tarihi')),
                ('paket_turu', models.CharField(choices=[('grup_dersi', 'Grup Dersi'), ('ozel_ders', 'Özel Ders'), ('deneme', 'Deneme')], max_length=20, verbose_name='Paket Türü')),
                ('paket_id', models.IntegerField(verbose_name='Paket ID')),
                ('paket_adi', models.CharField(max_length=200, verbose_name='Paket Adı')),
                ('brut_tutar', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Brüt Tutar (KDV Hariç)')),
                ('kdv_orani', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Sözleşme anında sabitlenir, değiştirilemez', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='KDV Oranı (%)')),
                ('kdv_tutari', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='KDV Tutarı')),
                ('kdv_dahil_tutar', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='KDV Dahil Tutar')),
                ('toplam_indirim_tutari', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Toplam İndirim Tutarı')),
                ('net_tutar', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Öğrencinin ödemesi gereken toplam tutar', max_digits=12, verbose_name='Net Tutar (Sözleşme Borcu)')),
                ('odeme_turu', models.CharField(choices=[('pesin', 'Peşin'), ('taksitli', 'Taksitli'), ('karma', 'Karma')], default='taksitli', max_length=20, verbose_name='Ödeme Türü')),
                ('taksit_sayisi', models.PositiveIntegerField(default=1, verbose_name='Taksit Sayısı')),
                ('ilk_odeme_tarihi', models.DateField(blank=True, null=True, verbose_name='İlk Ödeme Tarihi')),
                ('taksit_periyodu', models.CharField(choices=[('aylik', 'Aylık'), ('ozel', 'Özel Plan')], default='aylik', max_length=10, verbose_name='Taksit Periyodu')),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('aktif', 'Aktif'), ('iptal', 'İptal'), ('dondurulmus', 'Dondurulmuş'), ('feshedilmis', 'Feshedilmiş'), ('tamamlandi', 'Tamamlandı')], db_index=True, default='taslak', max_length=20, verbose_name='Durum')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sozlesmeler', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sozlesmeler', to='kurum.kurum', verbose_name='Kurum')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sozlesmeler', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
                ('ogrenci_kayit', models.ForeignKey(blank=True, help_text='Hangi eğitim yılı kaydına ait', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sozlesmeler', to='ogrenci.ogrencikayit', verbose_name='Öğrenci Kaydı')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_sozlesmeler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sozlesmeler', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Sözleşme',
                'verbose_name_plural': 'Sözleşmeler',
                'db_table': 'sozlesme',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Taksit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taksit_no', models.PositiveIntegerField(verbose_name='Taksit No')),
                ('vade_tarihi', models.DateField(verbose_name='Vade Tarihi')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Taksit Tutarı')),
                ('odenen_tutar', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Ödenen Tutar')),
                ('kalan_tutar', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Kalan Tutar')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('kismi_odendi', 'Kısmi Ödendi'), ('odendi', 'Ödendi'), ('gecikti', 'Gecikti'), ('iptal', 'İptal')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('odeme_tarihi', models.DateField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sozlesme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taksitler', to='odeme_takip.sozlesme', verbose_name='Sözleşme')),
            ],
            options={
                'verbose_name': 'Taksit',
                'verbose_name_plural': 'Taksitler',
                'db_table': 'taksit',
                'ordering': ['sozlesme', 'taksit_no'],
            },
        ),
        migrations.CreateModel(
            name='Tahsilat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tutar')),
                ('tahsilat_tarihi', models.DateField(verbose_name='Tahsilat Tarihi')),
                ('referans_no', models.CharField(blank=True, help_text='POS slip no, dekont no vb.', max_length=100, verbose_name='Referans No')),
                ('tahsilat_turu', models.CharField(choices=[('normal', 'Normal'), ('mahsup', 'Mahsup'), ('iade', 'İade'), ('emanet', 'Emanet')], default='normal', max_length=20, verbose_name='Tahsilat Türü')),
                ('durum', models.CharField(choices=[('aktif', 'Aktif'), ('iptal_edildi', 'İptal Edildi')], default='aktif', max_length=20, verbose_name='Durum')),
                ('iptal_nedeni', models.TextField(blank=True, verbose_name='İptal Nedeni')),
                ('iptal_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='İptal Tarihi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iptal_eden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iptal_ettigi_tahsilatlar', to=settings.AUTH_USER_MODEL, verbose_name='İptal Eden')),
                ('islem_yapan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yaptigi_tahsilatlar', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('mahsup_kaynagi', models.ForeignKey(blank=True, help_text='Bu tahsilat bir emanetten mahsup edildiyse kaynak tahsilat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahsup_hedefleri', to='odeme_takip.tahsilat', verbose_name='Mahsup Kaynağı')),
                ('odeme_sekli', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tahsilatlar', to='odeme_takip.odemesekli', verbose_name='Ödeme Şekli')),
                ('sozlesme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tahsilatlar', to='odeme_takip.sozlesme', verbose_name='Sözleşme')),
                ('taksit', models.ForeignKey(blank=True, help_text='Emanet/fazla ödeme durumunda null olabilir', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tahsilatlar', to='odeme_takip.taksit', verbose_name='Taksit')),
            ],
            options={
                'verbose_name': 'Tahsilat',
                'verbose_name_plural': 'Tahsilatlar',
                'db_table': 'tahsilat',
                'ordering': ['-tahsilat_tarihi', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SozlesmeKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalem_turu', models.CharField(choices=[('paket', 'Paket'), ('ek_hizmet', 'Ek Hizmet')], max_length=20, verbose_name='Kalem Türü')),
                ('kalem_id', models.IntegerField(help_text='İlgili paket veya ek hizmet ID', verbose_name='Kalem ID')),
                ('kalem_adi', models.CharField(max_length=200, verbose_name='Kalem Adı')),
                ('brut_tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Brüt Tutar')),
                ('kdv_orani', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='KDV Oranı (%)')),
                ('kdv_tutari', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='KDV Tutarı')),
                ('kdv_dahil_tutar', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='KDV Dahil Tutar')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sozlesme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='odeme_takip.sozlesme', verbose_name='Sözleşme')),
            ],
            options={
                'verbose_name': 'Sözleşme Kalemi',
                'verbose_name_plural': 'Sözleşme Kalemleri',
                'db_table': 'sozlesme_kalemi',
                'ordering': ['kalem_turu', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SozlesmeIndirimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indirim_orani', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='İndirim Oranı (%)')),
                ('indirim_tutari', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='İndirim Tutarı')),
                ('onay_durumu', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='onaylandi', help_text='Eşik üstü indirimlerde "beklemede" olarak başlar', max_length=20, verbose_name='Onay Durumu')),
                ('onay_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indirim_turu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sozlesme_indirimleri', to='odeme_takip.indirimturu', verbose_name='İndirim Türü')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_indirimler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('onaylayan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onayladigi_indirimler', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('sozlesme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirimler', to='odeme_takip.sozlesme', verbose_name='Sözleşme')),
            ],
            options={
                'verbose_name': 'Sözleşme İndirimi',
                'verbose_name_plural': 'Sözleşme İndirimleri',
                'db_table': 'sozlesme_indirimi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SozlesmeGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_turu', models.CharField(choices=[('olusturma', 'Oluşturma'), ('guncelleme', 'Güncelleme'), ('durum_degisikligi', 'Durum Değişikliği'), ('indirim', 'İndirim'), ('taksit', 'Taksit'), ('tahsilat', 'Tahsilat'), ('iptal', 'İptal')], max_length=30, verbose_name='İşlem Türü')),
                ('eski_deger', models.JSONField(blank=True, null=True, verbose_name='Eski Değer')),
                ('yeni_deger', models.JSONField(blank=True, null=True, verbose_name='Yeni Değer')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('islem_yapan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sozlesme_islemleri', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('sozlesme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecmis', to='odeme_takip.sozlesme', verbose_name='Sözleşme')),
            ],
            options={
                'verbose_name': 'Sözleşme Geçmişi',
                'verbose_name_plural': 'Sözleşme Geçmişleri',
                'db_table': 'sozlesme_gecmisi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='taksit',
            index=models.Index(fields=['vade_tarihi', 'durum'], name='taksit_vade_ta_645445_idx'),
        ),
        migrations.AddIndex(
            model_name='taksit',
            index=models.Index(fields=['sozlesme', 'durum'], name='taksit_sozlesm_65daf4_idx'),
        ),
        migrations.AddConstraint(
            model_name='taksit',
            constraint=models.UniqueConstraint(fields=('sozlesme', 'taksit_no'), name='unique_sozlesme_taksit_no'),
        ),
        migrations.AddIndex(
            model_name='tahsilat',
            index=models.Index(fields=['sozlesme', 'durum'], name='tahsilat_sozlesm_c0268e_idx'),
        ),
        migrations.AddIndex(
            model_name='tahsilat',
            index=models.Index(fields=['tahsilat_tarihi'], name='tahsilat_tahsila_d75c50_idx'),
        ),
        migrations.AddIndex(
            model_name='tahsilat',
            index=models.Index(fields=['durum', 'tahsilat_turu'], name='tahsilat_durum_7b1457_idx'),
        ),
        migrations.AddIndex(
            model_name='sozlesmegecmisi',
            index=models.Index(fields=['sozlesme', 'islem_turu'], name='sozlesme_ge_sozlesm_05fb84_idx'),
        ),
        migrations.AddIndex(
            model_name='sozlesme',
            index=models.Index(fields=['kurum', 'sube', 'egitim_yili', 'durum'], name='sozlesme_kurum_i_e7c5a3_idx'),
        ),
        migrations.AddIndex(
            model_name='sozlesme',
            index=models.Index(fields=['ogrenci', 'egitim_yili'], name='sozlesme_ogrenci_da3d61_idx'),
        ),
        migrations.AddIndex(
            model_name='sozlesme',
            index=models.Index(fields=['durum', 'created_at'], name='sozlesme_durum_b2a435_idx'),
        ),
    ]
