# Generated by Django 4.2.9 on 2026-02-20 22:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0007_add_ek_hizmet_system'),
        ('odeme_takip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozlesme',
            name='odeme_sekli',
            field=models.ForeignKey(blank=True, help_text='Varsayılan ödeme yöntemi (nakit, kredi kartı, havale vb.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sozlesme_odeme_yontemi', to='odeme_takip.odemesekli', verbose_name='Ödeme Yöntemi'),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='veli',
            field=models.ForeignKey(blank=True, help_text='Sözleşmeyi imzalayan veli', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sozlesmeler', to='ogrenci.ogrenciveli', verbose_name='Veli (İmza Sahibi)'),
        ),
        migrations.AddField(
            model_name='sozlesmekalemi',
            name='indirim_orani',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='İndirim Oranı (%)'),
        ),
        migrations.AddField(
            model_name='sozlesmekalemi',
            name='indirim_tutari',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='İndirim Tutarı'),
        ),
        migrations.AddField(
            model_name='sozlesmekalemi',
            name='net_tutar',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='KDV dahil - indirim', max_digits=12, verbose_name='Net Tutar'),
        ),
    ]
