# Generated by Django 4.2.9 on 2026-02-21 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finans', '0002_add_varsayilan_mali_hesap_to_odeme_yontemi'),
        ('odeme_takip', '0002_add_veli_odeme_sekli_kalem_indirim'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozlesme',
            name='mali_hesap',
            field=models.ForeignKey(blank=True, help_text='Tahsilatın yatırılacağı mali hesap', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sozlesmeler', to='finans.malihesap', verbose_name='Mali Hesap'),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='odeme_yontemi',
            field=models.ForeignKey(blank=True, help_text='Finans tanımlarındaki ödeme yöntemi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sozlesmeler', to='finans.odemeyontemi', verbose_name='Ödeme Yöntemi'),
        ),
        migrations.AlterField(
            model_name='sozlesme',
            name='odeme_sekli',
            field=models.ForeignKey(blank=True, help_text='Eski parametrik ödeme şekli', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sozlesme_odeme_yontemi', to='odeme_takip.odemesekli', verbose_name='Ödeme Şekli'),
        ),
        migrations.AlterField(
            model_name='sozlesme',
            name='paket_turu',
            field=models.CharField(choices=[('grup_dersi', 'Grup Dersi'), ('ozel_ders', 'Özel Ders'), ('deneme', 'Deneme'), ('davranis', 'Davranış Paketi')], max_length=20, verbose_name='Paket Türü'),
        ),
        migrations.AlterField(
            model_name='sozlesme',
            name='taksit_periyodu',
            field=models.CharField(choices=[('aylik', 'Aylık'), ('iki_aylik', '2 Aylık'), ('uc_aylik', '3 Aylık'), ('ozel', 'Özel Plan')], default='aylik', max_length=10, verbose_name='Taksit Periyodu'),
        ),
    ]
