# Generated by Django 4.2.9 on 2026-02-21 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finans', '0002_add_varsayilan_mali_hesap_to_odeme_yontemi'),
        ('odeme_takip', '0003_add_odeme_yontemi_mali_hesap_to_sozlesme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sozlesme',
            name='odeme_sekli',
        ),
        migrations.RemoveField(
            model_name='tahsilat',
            name='odeme_sekli',
        ),
        migrations.AddField(
            model_name='tahsilat',
            name='odeme_yontemi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tahsilatlar', to='finans.odemeyontemi', verbose_name='Ödeme Yöntemi'),
        ),
    ]
