# Generated by Django 4.2.9 on 2026-02-21 13:29

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odeme_takip', '0004_remove_odeme_sekli_fk_use_odeme_yontemi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sozlesmegecmisi',
            name='islem_turu',
            field=models.CharField(choices=[('olusturma', 'Oluşturma'), ('guncelleme', 'Güncelleme'), ('durum_degisikligi', 'Durum Değişikliği'), ('indirim', 'İndirim'), ('taksit', 'Taksit'), ('tahsilat', 'Tahsilat'), ('iptal', 'İptal'), ('fesih', 'Fesih'), ('kalem_ekleme', 'Kalem Ekleme'), ('kalem_cikarma', 'Kalem Çıkarma')], max_length=30, verbose_name='İşlem Türü'),
        ),
        migrations.CreateModel(
            name='SozlesmeFesih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fesih_tarihi', models.DateField(verbose_name='Fesih Tarihi')),
                ('fesih_nedeni', models.CharField(choices=[('veli_talebi', 'Veli / Vasi Talebi'), ('kurum_karari', 'Kurum Kararı'), ('disiplin', 'Disiplin'), ('devamsizlik', 'Devamsızlık'), ('diger', 'Diğer')], default='veli_talebi', max_length=30, verbose_name='Fesih Nedeni')),
                ('fesih_aciklama', models.TextField(blank=True, verbose_name='Fesih Açıklama')),
                ('sozlesme_net_tutar', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Sözleşme Net Tutar')),
                ('toplam_odenen', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fesih anına kadar yapılan aktif tahsilatlar toplamı', max_digits=12, verbose_name='Toplam Ödenen')),
                ('kullanilan_gun', models.PositiveIntegerField(default=0, verbose_name='Kullanılan Gün')),
                ('toplam_gun', models.PositiveIntegerField(default=0, verbose_name='Toplam Gün')),
                ('kullanilan_tutar', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Eğitim başlangıcından fesih tarihine kadar orantılı bedel', max_digits=12, verbose_name='Kullanılan Tutar')),
                ('kesintiler', models.JSONField(blank=True, default=list, help_text='[{"ad": "Kitap bedeli", "tutar": 500}, ...]', verbose_name='Kesinti Kalemleri')),
                ('kesinti_tutari', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Toplam Kesinti Tutarı')),
                ('ceza_orani', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sözleşme bedelinin yüzdesi olarak ceza', max_digits=5, verbose_name='Ceza Oranı (%)')),
                ('ceza_tutari', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Ceza Tutarı')),
                ('iade_tutari', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Pozitif: kurum öğrenciye iade edecek. Negatif: öğrenci borçlu.', max_digits=12, verbose_name='İade Tutarı')),
                ('iade_yapildi_mi', models.BooleanField(default=False, verbose_name='İade Yapıldı')),
                ('iade_tarihi', models.DateField(blank=True, null=True, verbose_name='İade Tarihi')),
                ('iptal_edilen_taksit_sayisi', models.PositiveIntegerField(default=0, verbose_name='İptal Edilen Taksit Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fesih_eden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fesih_ettigi_sozlesmeler', to=settings.AUTH_USER_MODEL, verbose_name='Fesih Eden')),
                ('sozlesme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fesih', to='odeme_takip.sozlesme', verbose_name='Sözleşme')),
            ],
            options={
                'verbose_name': 'Sözleşme Fesih',
                'verbose_name_plural': 'Sözleşme Fesihleri',
                'db_table': 'sozlesme_fesih',
                'ordering': ['-created_at'],
            },
        ),
    ]
