# Generated by Django 4.2.9 on 2026-02-21 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odeme_takip', '0005_alter_sozlesmegecmisi_islem_turu_sozlesmefesih'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozlesme',
            name='cayma_suresi',
            field=models.PositiveIntegerField(default=14, help_text='Cayma hakkı gün sayısı (7 veya 14)', verbose_name='Cayma Süresi (Gün)'),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='egitim_turu',
            field=models.CharField(blank=True, choices=[('yks', 'YKS'), ('lgs', 'LGS'), ('ara_sinif', 'Ara Sınıf'), ('mezun', 'Mezun'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='Eğitim Türü'),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='muacceliyet_durumu',
            field=models.BooleanField(default=False, help_text='Tüm borç vadesi gelmeden muaccel olabilir mi?', verbose_name='Muacceliyet Durumu'),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='revizyon_tarihi',
            field=models.DateTimeField(blank=True, help_text='Son revizyon tarihi', null=True, verbose_name='Revizyon Tarihi'),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='versiyon',
            field=models.PositiveIntegerField(default=1, verbose_name='Versiyon'),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='yetkili_personel',
            field=models.ForeignKey(blank=True, help_text='Sözleşmeyi onaylayan yetkili personel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yetkili_sozlesmeler', to=settings.AUTH_USER_MODEL, verbose_name='Yetkili Personel'),
        ),
        migrations.AlterField(
            model_name='sozlesmegecmisi',
            name='islem_turu',
            field=models.CharField(choices=[('olusturma', 'Oluşturma'), ('guncelleme', 'Güncelleme'), ('durum_degisikligi', 'Durum Değişikliği'), ('indirim', 'İndirim'), ('taksit', 'Taksit'), ('tahsilat', 'Tahsilat'), ('iptal', 'İptal'), ('fesih', 'Fesih'), ('kalem_ekleme', 'Kalem Ekleme'), ('kalem_cikarma', 'Kalem Çıkarma'), ('revizyon', 'Revizyon')], max_length=30, verbose_name='İşlem Türü'),
        ),
        migrations.AlterField(
            model_name='sozlesmekalemi',
            name='kalem_turu',
            field=models.CharField(choices=[('paket', 'Paket'), ('ek_hizmet', 'Ek Hizmet'), ('grup_dersi', 'Grup Dersi'), ('ozel_ders', 'Özel Ders'), ('deneme', 'Deneme'), ('ek_hizmet_satisi', 'Ek Hizmet Satışı')], max_length=20, verbose_name='Kalem Türü'),
        ),
    ]
