# Generated by Django 4.2.9 on 2026-02-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme_takip', '0006_sozlesme_cayma_suresi_sozlesme_egitim_turu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tahsilat',
            name='toplam_odeme',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tek seferde yapılan toplam ödeme tutarı. Birden fazla taksit kapatıldıysa, her tahsilat kaydında aynı toplam tutarı saklar.', max_digits=12, null=True, verbose_name='Toplam Ödeme Tutarı'),
        ),
    ]
