# Generated by Django 4.2.9 on 2026-02-21 23:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odeme_takip', '0007_tahsilat_toplam_odeme'),
    ]

    operations = [
        migrations.CreateModel(
            name='TahsilatDagitim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Dağıtılan Tutar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tahsilat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dagitimlar', to='odeme_takip.tahsilat', verbose_name='Tahsilat')),
                ('taksit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tahsilat_dagitimlari', to='odeme_takip.taksit', verbose_name='Taksit')),
            ],
            options={
                'verbose_name': 'Tahsilat Dağıtımı',
                'verbose_name_plural': 'Tahsilat Dağıtımları',
                'db_table': 'tahsilat_dagitim',
                'ordering': ['tahsilat', 'taksit__taksit_no'],
                'indexes': [models.Index(fields=['tahsilat'], name='tahsilat_da_tahsila_a5289a_idx'), models.Index(fields=['taksit'], name='tahsilat_da_taksit__a0514d_idx')],
            },
        ),
    ]
