# Generated by Django 4.2.9 on 2026-02-22 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme_takip', '0008_tahsilat_dagitim_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirimturu',
            name='max_oran',
            field=models.IntegerField(default=50, help_text='Bu indirim türü için izin verilen maksimum yüzde', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Maksimum Oran (%)'),
        ),
        migrations.AlterField(
            model_name='indirimturu',
            name='onay_gerektiren_oran',
            field=models.IntegerField(default=15, help_text='Bu yüzdenin üstündeki indirimler üst onay gerektirir', verbose_name='Onay Gerektiren Oran (%)'),
        ),
        migrations.AlterField(
            model_name='sozlesme',
            name='brut_tutar',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Brüt Tutar (KDV Dahil)'),
        ),
        migrations.AlterField(
            model_name='sozlesme',
            name='kdv_dahil_tutar',
            field=models.IntegerField(default=0, help_text='brut_tutar ile aynı (geriye uyumluluk)', verbose_name='KDV Dahil Tutar'),
        ),
        migrations.AlterField(
            model_name='sozlesme',
            name='kdv_orani',
            field=models.IntegerField(default=10, help_text='Sözleşme anında sabitlenir, değiştirilemez', verbose_name='KDV Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='sozlesme',
            name='kdv_tutari',
            field=models.IntegerField(default=0, verbose_name='KDV Tutarı'),
        ),
        migrations.AlterField(
            model_name='sozlesme',
            name='net_tutar',
            field=models.IntegerField(default=0, help_text='Öğrencinin ödemesi gereken toplam tutar', verbose_name='Net Tutar (Sözleşme Borcu)'),
        ),
        migrations.AlterField(
            model_name='sozlesme',
            name='toplam_indirim_tutari',
            field=models.IntegerField(default=0, verbose_name='Toplam İndirim Tutarı'),
        ),
        migrations.AlterField(
            model_name='sozlesmefesih',
            name='ceza_orani',
            field=models.IntegerField(default=0, help_text='Sözleşme bedelinin yüzdesi olarak ceza', verbose_name='Ceza Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='sozlesmefesih',
            name='ceza_tutari',
            field=models.IntegerField(default=0, verbose_name='Ceza Tutarı'),
        ),
        migrations.AlterField(
            model_name='sozlesmefesih',
            name='iade_tutari',
            field=models.IntegerField(default=0, help_text='Pozitif: kurum öğrenciye iade edecek. Negatif: öğrenci borçlu.', verbose_name='İade Tutarı'),
        ),
        migrations.AlterField(
            model_name='sozlesmefesih',
            name='kesinti_tutari',
            field=models.IntegerField(default=0, verbose_name='Toplam Kesinti Tutarı'),
        ),
        migrations.AlterField(
            model_name='sozlesmefesih',
            name='kullanilan_tutar',
            field=models.IntegerField(default=0, help_text='Eğitim başlangıcından fesih tarihine kadar orantılı bedel', verbose_name='Kullanılan Tutar'),
        ),
        migrations.AlterField(
            model_name='sozlesmefesih',
            name='sozlesme_net_tutar',
            field=models.IntegerField(default=0, verbose_name='Sözleşme Net Tutar'),
        ),
        migrations.AlterField(
            model_name='sozlesmefesih',
            name='toplam_odenen',
            field=models.IntegerField(default=0, help_text='Fesih anına kadar yapılan aktif tahsilatlar toplamı', verbose_name='Toplam Ödenen'),
        ),
        migrations.AlterField(
            model_name='sozlesmeindirimi',
            name='indirim_orani',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='İndirim Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='sozlesmeindirimi',
            name='indirim_tutari',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='İndirim Tutarı'),
        ),
        migrations.AlterField(
            model_name='sozlesmekalemi',
            name='brut_tutar',
            field=models.IntegerField(default=0, verbose_name='Brüt Tutar (KDV Dahil)'),
        ),
        migrations.AlterField(
            model_name='sozlesmekalemi',
            name='indirim_orani',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='İndirim Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='sozlesmekalemi',
            name='indirim_tutari',
            field=models.IntegerField(default=0, verbose_name='İndirim Tutarı'),
        ),
        migrations.AlterField(
            model_name='sozlesmekalemi',
            name='kdv_dahil_tutar',
            field=models.IntegerField(default=0, help_text='brut_tutar ile aynı (geriye uyumluluk)', verbose_name='KDV Dahil Tutar'),
        ),
        migrations.AlterField(
            model_name='sozlesmekalemi',
            name='kdv_orani',
            field=models.IntegerField(default=10, verbose_name='KDV Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='sozlesmekalemi',
            name='kdv_tutari',
            field=models.IntegerField(default=0, verbose_name='KDV Tutarı'),
        ),
        migrations.AlterField(
            model_name='sozlesmekalemi',
            name='net_tutar',
            field=models.IntegerField(default=0, help_text='brut_tutar - indirim', verbose_name='Net Tutar'),
        ),
        migrations.AlterField(
            model_name='tahsilat',
            name='toplam_odeme',
            field=models.IntegerField(blank=True, help_text='Tek seferde yapılan toplam ödeme tutarı.', null=True, verbose_name='Toplam Ödeme Tutarı'),
        ),
        migrations.AlterField(
            model_name='tahsilat',
            name='tutar',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tutar'),
        ),
        migrations.AlterField(
            model_name='tahsilatdagitim',
            name='tutar',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dağıtılan Tutar'),
        ),
        migrations.AlterField(
            model_name='taksit',
            name='kalan_tutar',
            field=models.IntegerField(default=0, verbose_name='Kalan Tutar'),
        ),
        migrations.AlterField(
            model_name='taksit',
            name='odenen_tutar',
            field=models.IntegerField(default=0, verbose_name='Ödenen Tutar'),
        ),
        migrations.AlterField(
            model_name='taksit',
            name='tutar',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taksit Tutarı'),
        ),
    ]
