# Generated by Django 4.2.27 on 2026-03-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme_takip', '0009_alter_indirimturu_max_oran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sozlesme',
            name='paket_adi',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Paket Adı'),
        ),
        migrations.AlterField(
            model_name='sozlesme',
            name='paket_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Paket ID'),
        ),
        migrations.AlterField(
            model_name='sozlesme',
            name='paket_turu',
            field=models.CharField(blank=True, choices=[('grup_dersi', 'Grup Dersi'), ('ozel_ders', 'Özel Ders'), ('deneme', 'Deneme'), ('davranis', 'Davranış Paketi'), ('ek_hizmet', 'Ek Hizmet')], default='', max_length=20, verbose_name='Paket Türü'),
        ),
    ]
