# Generated by Django 4.2.27 on 2026-06-29 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odeme_takip', '0010_allow_null_paket_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CekSenetDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cek_senet_no', models.CharField(max_length=50, verbose_name='Çek/Senet No')),
                ('banka_adi', models.CharField(blank=True, default='', max_length=100, verbose_name='Banka Adı')),
                ('vade_tarihi', models.DateField(verbose_name='Vade Tarihi')),
                ('durum', models.CharField(choices=[('portfoyde', 'Portföyde'), ('tahsil', 'Tahsil Edildi'), ('karsiliksiz', 'Karşılıksız'), ('iptal', 'İptal')], default='portfoyde', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tahsilat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cek_senet_detay', to='odeme_takip.tahsilat', verbose_name='Tahsilat')),
                ('taksit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cek_senet_detay', to='odeme_takip.taksit', verbose_name='Taksit')),
            ],
            options={
                'verbose_name': 'Çek/Senet Detay',
                'verbose_name_plural': 'Çek/Senet Detayları',
                'db_table': 'cek_senet_detay',
            },
        ),
        migrations.AddConstraint(
            model_name='ceksenetdetay',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('tahsilat__isnull', True), ('taksit__isnull', False)), models.Q(('tahsilat__isnull', False), ('taksit__isnull', True)), _connector='OR'), name='cek_senet_detay_single_parent'),
        ),
    ]
