# Generated by Django 4.2.27 on 2026-07-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme_takip', '0012_tahsilat_mali_hesap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sozlesmegecmisi',
            name='islem_turu',
            field=models.CharField(choices=[('olusturma', 'Oluşturma'), ('guncelleme', 'Güncelleme'), ('durum_degisikligi', 'Durum Değişikliği'), ('indirim', 'İndirim'), ('taksit', 'Taksit'), ('tahsilat', 'Tahsilat'), ('iptal', 'İptal'), ('iade', 'İade'), ('fesih', 'Fesih'), ('kalem_ekleme', 'Kalem Ekleme'), ('kalem_cikarma', 'Kalem Çıkarma'), ('revizyon', 'Revizyon')], max_length=30, verbose_name='İşlem Türü'),
        ),
    ]
