# Generated by Django 4.2.27 on 2026-07-03 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
        ('finans', '0025_cek_senet_v2'),
        ('sube', '0002_sube_extended_profile'),
        ('odeme_takip', '0013_alter_sozlesmegecmisi_islem_turu'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ceksenetdetay',
            name='cek_senet_detay_single_parent',
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='aciklama',
            field=models.TextField(blank=True, default='', verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='arac_tipi',
            field=models.CharField(choices=[('cek', 'Çek'), ('senet', 'Senet')], default='cek', max_length=10, verbose_name='Araç Tipi'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='belge_gorsel',
            field=models.FileField(blank=True, null=True, upload_to='cek_senet/', verbose_name='Belge Görseli'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='cari_hesap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cek_senet_kayitlari', to='finans.carihesap'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='hesap_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Hesap No'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='keside_eden',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Keşide Eden'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='keside_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Keşide Tarihi'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='kurum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cek_senet_kayitlari', to='kurum.kurum'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='odeme_yontemi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cek_senet_kayitlari', to='finans.odemeyontemi'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='olusturma_tarihi',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='sube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cek_senet_kayitlari', to='sube.sube'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='sube_adi',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Şube'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='tahsilat_mali_hesap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cek_senet_tahsilatlari', to='finans.malihesap', verbose_name='Tahsil/Ödeme Mali Hesabı'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='tutar',
            field=models.IntegerField(default=0, verbose_name='Tutar (TL)'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='yon',
            field=models.CharField(choices=[('alinan', 'Alınan'), ('verilen', 'Verilen')], default='alinan', max_length=10, verbose_name='Yön'),
        ),
        migrations.AddField(
            model_name='taksit',
            name='odeme_yontemi',
            field=models.ForeignKey(blank=True, help_text='Planlanan ödeme yöntemi (çek/senet için portföy kaydı tetikler)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taksitler', to='finans.odemeyontemi', verbose_name='Ödeme Yöntemi'),
        ),
        migrations.AlterField(
            model_name='ceksenetdetay',
            name='cek_senet_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Çek/Senet No'),
        ),
        migrations.AlterField(
            model_name='ceksenetdetay',
            name='durum',
            field=models.CharField(choices=[('bekliyor', 'Bekleniyor'), ('portfoyde', 'Portföyde'), ('tahsilde', 'Tahsilde'), ('tahsil_edildi', 'Tahsil Edildi'), ('iade', 'İade'), ('karsiliksiz', 'Karşılıksız'), ('iptal', 'İptal'), ('hazirlandi', 'Hazırlandı'), ('verildi', 'Verildi'), ('odendi', 'Ödendi'), ('tahsil', 'Tahsil Edildi (eski)')], default='bekliyor', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='ceksenetdetay',
            name='tahsilat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cek_senet_detay', to='odeme_takip.tahsilat'),
        ),
        migrations.AlterField(
            model_name='ceksenetdetay',
            name='taksit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cek_senet_detay', to='odeme_takip.taksit'),
        ),
        migrations.AddIndex(
            model_name='ceksenetdetay',
            index=models.Index(fields=['kurum', 'durum', 'vade_tarihi'], name='cek_senet_d_kurum_i_d65924_idx'),
        ),
        migrations.AddIndex(
            model_name='ceksenetdetay',
            index=models.Index(fields=['yon', 'durum'], name='cek_senet_d_yon_8b0330_idx'),
        ),
    ]
