# Generated by Django 4.2.9 on 2026-07-08 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finans', '0032_seed_masraf_turleri'),
        ('odeme_takip', '0018_sozlesme_notlar_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='CekSenetDosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurum_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kurum ID')),
                ('dosya', models.FileField(upload_to='cek_senet/dosyalar/%Y/%m/', verbose_name='Dosya')),
                ('dosya_adi', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('dosya_turu', models.CharField(choices=[('gorsel', 'Çek/Senet Görseli'), ('dekont', 'Dekont / Makbuz'), ('sozlesme', 'Sözleşme'), ('tarama', 'Tarama'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='Dosya Türü')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('dosya_boyutu', models.PositiveIntegerField(default=0, verbose_name='Boyut (byte)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Çek/Senet Dosya',
                'verbose_name_plural': 'Çek/Senet Dosyalar',
                'db_table': 'cek_senet_dosya',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CekSenetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eylem', models.CharField(max_length=40, verbose_name='Eylem')),
                ('onceki_durum', models.CharField(blank=True, default='', max_length=20, verbose_name='Önceki Durum')),
                ('yeni_durum', models.CharField(blank=True, default='', max_length=20, verbose_name='Yeni Durum')),
                ('tutar', models.IntegerField(blank=True, null=True, verbose_name='Tutar (TL)')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('kullanici_adi', models.CharField(blank=True, default='', max_length=150, verbose_name='Kullanıcı Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Çek/Senet Log',
                'verbose_name_plural': 'Çek/Senet Logları',
                'db_table': 'cek_senet_log',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='ciro_edilen_cari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciro_edilen_cek_senetler', to='finans.carihesap', verbose_name='Ciro Edilen Cari'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='ciro_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Ciro Tarihi'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='durum_aciklamasi',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Durum Notu'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='iade_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='İade Tarihi'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='protesto_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Protesto Tarihi'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='seri_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Seri No'),
        ),
        migrations.AddField(
            model_name='ceksenetdetay',
            name='tahsil_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Tahsil/Ödeme Tarihi'),
        ),
        migrations.AlterField(
            model_name='ceksenetdetay',
            name='durum',
            field=models.CharField(choices=[('bekliyor', 'Bekleniyor'), ('portfoyde', 'Portföyde'), ('tahsilde', 'Tahsilde'), ('tahsil_edildi', 'Tahsil Edildi'), ('ciro', 'Ciro Edildi'), ('iade', 'İade Edildi'), ('protesto', 'Protestolu'), ('karsiliksiz', 'Karşılıksız'), ('iptal', 'İptal'), ('hazirlandi', 'Hazırlandı'), ('verildi', 'Verildi'), ('odendi', 'Ödendi'), ('tahsil', 'Tahsil Edildi (eski)')], default='bekliyor', max_length=20, verbose_name='Durum'),
        ),
        migrations.AddIndex(
            model_name='ceksenetdetay',
            index=models.Index(fields=['kurum', 'yon', 'arac_tipi'], name='cek_senet_d_kurum_i_495e2c_idx'),
        ),
        migrations.AddField(
            model_name='ceksenetlog',
            name='detay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loglar', to='odeme_takip.ceksenetdetay'),
        ),
        migrations.AddField(
            model_name='ceksenetlog',
            name='kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cek_senet_loglari', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ceksenetdosya',
            name='detay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='odeme_takip.ceksenetdetay'),
        ),
        migrations.AddField(
            model_name='ceksenetdosya',
            name='yukleyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cek_senet_dosyalari', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ceksenetlog',
            index=models.Index(fields=['detay', '-created_at'], name='cek_senet_l_detay_i_d3bbc5_idx'),
        ),
    ]
