# Generated by Django 4.2.27 on 2026-07-19 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finans', '0033_hesaptransferi_iptal_eden_and_more'),
        ('odeme_takip', '0019_ceksenetdosya_ceksenetlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceksenetdetay',
            name='cari_hareket',
            field=models.OneToOneField(blank=True, help_text='Serbest ödeme ile oluşturulan verilen çek/senet için cari hareket bağlantısı', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cek_senet_detay', to='finans.carihareket', verbose_name='Bağlı Cari Hareket'),
        ),
        migrations.AlterField(
            model_name='sozlesme',
            name='paket_turu',
            field=models.CharField(blank=True, choices=[('grup_dersi', 'Grup Dersi'), ('ozel_ders', 'Özel Ders'), ('premium', 'Premium Paket'), ('yayin', 'Yayın Paketi'), ('deneme', 'Deneme'), ('davranis', 'Davranış Paketi'), ('ek_hizmet', 'Ek Hizmet')], default='', max_length=20, verbose_name='Paket Türü'),
        ),
        migrations.AlterField(
            model_name='sozlesmekalemi',
            name='kalem_turu',
            field=models.CharField(choices=[('paket', 'Paket'), ('ek_hizmet', 'Ek Hizmet'), ('grup_dersi', 'Grup Dersi'), ('ozel_ders', 'Özel Ders'), ('premium', 'Premium Paket'), ('yayin', 'Yayın Paketi'), ('deneme', 'Deneme'), ('ek_hizmet_satisi', 'Ek Hizmet Satışı')], max_length=20, verbose_name='Kalem Türü'),
        ),
    ]
