"""
Öğrenci gelişim analizi — kilitli eşikler.

İlk sürüm modül sabiti; sonra settings'e taşınabilir.
"""

DEVELOPMENT_EXAM_TYPE_GROUPS = {
    'TYT': ('YKS_TYT',),
    'AYT': ('YKS_AYT',),
    'LGS': ('LGS',),
    'manuel': ('DENEME', 'KURUM_ICI', 'KONU_TARAMA', 'KAZANIM', 'OZEL'),
}

DEVELOPMENT_MAIN_ONLY_TYPES = ('YKS_TYT', 'DENEME', 'LGS')

DEVELOPMENT_WINDOWS = ('1', '3', '5', '10', 'all')
DEVELOPMENT_DEFAULT_WINDOW = '5'

# Ders slope (C)
DEVELOPMENT_SLOPE_STRONG = 3.0
DEVELOPMENT_SLOPE_UP = 1.0
DEVELOPMENT_SLOPE_NEUTRAL = 0.99
DEVELOPMENT_SLOPE_DOWN = -1.0
DEVELOPMENT_SLOPE_STRONG_DOWN = -3.0

# Ders A/B yüzde puan
DEVELOPMENT_AB_STRONG = 10.0
DEVELOPMENT_AB_UP = 5.0
DEVELOPMENT_AB_NEUTRAL = 4.99
DEVELOPMENT_AB_DOWN = -5.0
DEVELOPMENT_AB_STRONG_DOWN = -10.0
DEVELOPMENT_PERIOD_STRONG = 8.0

# Dalgalanma
DEVELOPMENT_VOLATILITY_LOW = 5.0
DEVELOPMENT_VOLATILITY_MID = 10.0
DEVELOPMENT_VOLATILITY_FLAG = 15.0

# Başarı seviyesi (gelişim değil)
DEVELOPMENT_LEVEL_VERY_HIGH = 85.0
DEVELOPMENT_LEVEL_HIGH = 70.0
DEVELOPMENT_LEVEL_MID = 55.0
DEVELOPMENT_LEVEL_DEVELOP = 40.0

# Kazanım değişimi
DEVELOPMENT_OUTCOME_CHANGE_STRONG = 15.0
DEVELOPMENT_OUTCOME_CHANGE_UP = 7.0
DEVELOPMENT_OUTCOME_CHANGE_NEUTRAL = 6.99
DEVELOPMENT_OUTCOME_CHANGE_DOWN = -7.0
DEVELOPMENT_OUTCOME_CHANGE_STRONG_DOWN = -15.0

# Kazanım veri eşiği
DEVELOPMENT_OUTCOME_DATA_MIN = 3
DEVELOPMENT_OUTCOME_DATA_LOW = 4
DEVELOPMENT_OUTCOME_DATA_MID = 9

# Öncelik ağırlıkları + kova skorları
DEVELOPMENT_PRIORITY_LOW_W = 0.35
DEVELOPMENT_PRIORITY_DECLINE_W = 0.30
DEVELOPMENT_PRIORITY_RECENT_W = 0.20
DEVELOPMENT_PRIORITY_PERSIST_W = 0.15

DEVELOPMENT_PRIORITY_CRITICAL = 80.0
DEVELOPMENT_PRIORITY_HIGH = 60.0
DEVELOPMENT_PRIORITY_MID = 40.0
DEVELOPMENT_PRIORITY_LIMIT = 8
DEVELOPMENT_PRIORITY_MASTERED = 80.0

DEVELOPMENT_PERSIST_LOW = 60.0

# Güçlü alan
DEVELOPMENT_STRONG_AREA_MASTERY = 70.0
DEVELOPMENT_STRONG_AREA_MIN_Q = 5
