# Generated by Django 4.2.9 on 2026-01-30 22:37

import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EgitimYili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_yil', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Başlangıç Yılı')),
                ('bitis_yil', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Bitiş Yılı')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Eğitim Yılı',
                'verbose_name_plural': 'Eğitim Yılları',
                'db_table': 'egitim_yili',
                'ordering': ['-baslangic_yil'],
                'indexes': [models.Index(fields=['aktif_mi'], name='egitim_yili_aktif_m_903ac7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='egitimyili',
            constraint=models.UniqueConstraint(fields=('baslangic_yil', 'bitis_yil'), name='unique_egitim_yili'),
        ),
        migrations.AddConstraint(
            model_name='egitimyili',
            constraint=models.CheckConstraint(check=models.Q(('bitis_yil', django.db.models.expressions.CombinedExpression(models.F('baslangic_yil'), '+', models.Value(1)))), name='bitis_yil_check'),
        ),
    ]
