# Generated by Django 4.2.27 on 2026-02-10 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ogrenci', '0005_add_profil_foto'),
        ('egitim_tanimlari', '0009_merge_20260201_0154'),
        ('resources', '0003_add_zorluk_seviyesi'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Derslerin gösterim sırası', verbose_name='Sıra')),
                ('content_mode', models.CharField(choices=[('TOPIC', 'Konu Bazlı'), ('PAGE_RANGE', 'Sayfa Aralığı'), ('TEST_NUMBER', 'Test Numarası')], default='TOPIC', max_length=20, verbose_name='İçerik Seçim Modu')),
                ('topic_name', models.CharField(blank=True, max_length=255, verbose_name='Konu Adı')),
                ('page_start', models.IntegerField(blank=True, null=True, verbose_name='Başlangıç Sayfası')),
                ('page_end', models.IntegerField(blank=True, null=True, verbose_name='Bitiş Sayfası')),
                ('test_number', models.CharField(blank=True, max_length=50, verbose_name='Test Numarası')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ödev Dersi',
                'verbose_name_plural': 'Ödev Dersleri',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManualAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ödevin genel açıklaması', max_length=255, verbose_name='Ödev Başlığı')),
                ('description', models.TextField(blank=True, help_text='Ödev hakkında ek bilgiler', verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('ASSIGNED', 'Atandı'), ('IN_PROGRESS', 'Devam Ediyor'), ('COMPLETED', 'Tamamlandı'), ('OVERDUE', 'Süresi Geçti'), ('CANCELLED', 'İptal Edildi')], default='DRAFT', max_length=20, verbose_name='Durum')),
                ('risk_status', models.CharField(choices=[('PENDING', 'Beklemede'), ('PENDING_START', 'Başlamadı'), ('ON_TRACK', 'Yolunda'), ('AT_RISK', 'Risk Altında'), ('DELAYED', 'Gecikmiş'), ('LOW_ACCURACY', 'Düşük Doğruluk'), ('CRITICAL', 'Kritik')], db_index=True, default='PENDING', max_length=20, verbose_name='Risk Durumu')),
                ('priority', models.CharField(choices=[('LOW', 'Düşük'), ('MEDIUM', 'Orta'), ('HIGH', 'Yüksek'), ('URGENT', 'Acil')], default='MEDIUM', max_length=20, verbose_name='Öncelik Seviyesi')),
                ('assigned_date', models.DateTimeField(blank=True, null=True, verbose_name='Atanma Tarihi')),
                ('due_date', models.DateTimeField(verbose_name='Son Teslim Tarihi')),
                ('reminder_date', models.DateTimeField(blank=True, null=True, verbose_name='Hatırlatma Tarihi')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('expected_accuracy_percent', models.IntegerField(blank=True, help_text='Beklenen doğruluk yüzdesi', null=True, verbose_name='Hedef Doğruluk %')),
                ('minimum_completion_percent', models.IntegerField(default=100, help_text='En az ne kadar tamamlanmalı', verbose_name='Minimum Tamamlanma %')),
                ('estimated_duration_minutes', models.IntegerField(blank=True, help_text='Ödevi tamamlamak için tahmini süre', null=True, verbose_name='Tahmini Süre (dk)')),
                ('difficulty_level', models.IntegerField(default=3, help_text='1-5 arası zorluk seviyesi', verbose_name='Zorluk Seviyesi')),
                ('actual_accuracy_percent', models.FloatField(blank=True, null=True, verbose_name='Gerçek Doğruluk %')),
                ('completion_percent', models.IntegerField(default=0, verbose_name='Tamamlanma %')),
                ('actual_duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='Gerçek Süre (dk)')),
                ('template_id', models.IntegerField(blank=True, help_text='Ödev paket sistemi için', null=True, verbose_name='Şablon ID')),
                ('coach_notes', models.TextField(blank=True, help_text='Sadece koçun görebileceği notlar', verbose_name='Koç Notları')),
                ('student_notes', models.TextField(blank=True, help_text='Öğrencinin ekleyebileceği notlar', verbose_name='Öğrenci Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Koç')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_assignments', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Manuel Ödev Ataması',
                'verbose_name_plural': 'Manuel Ödev Atamaları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('SOLVE_TEST', 'Test Çöz'), ('WATCH_VIDEO', 'Video İzle'), ('REVIEW_TOPIC', 'Konu Tekrar Et'), ('SOLVE_EXAM', 'Deneme Çöz'), ('ANALYZE_MISTAKES', 'Yanlış Analiz Yap'), ('TAKE_NOTES', 'Not Çıkar'), ('SOLVE_PDF', 'PDF Çöz'), ('CUSTOM', 'Özel Görev')], max_length=20, verbose_name='Görev Tipi')),
                ('title', models.CharField(max_length=255, verbose_name='Görev Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_required', models.BooleanField(default=True, verbose_name='Zorunlu mu?')),
                ('estimated_duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='Tahmini Süre (dk)')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Başlanmadı'), ('IN_PROGRESS', 'Devam Ediyor'), ('COMPLETED', 'Tamamlandı'), ('SKIPPED', 'Atlandı')], default='NOT_STARTED', max_length=20, verbose_name='Durum')),
                ('actual_duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='Gerçek Süre (dk)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Zamanı')),
                ('student_feedback', models.TextField(blank=True, verbose_name='Öğrenci Geri Bildirimi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='assignment_manual.assignmentlesson', verbose_name='Ders Bloğu')),
            ],
            options={
                'verbose_name': 'Ödev Görevi',
                'verbose_name_plural': 'Ödev Görevleri',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='assignmentlesson',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='assignment_manual.manualassignment', verbose_name='Ödev'),
        ),
        migrations.AddField(
            model_name='assignmentlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_assignment_lessons', to='egitim_tanimlari.ders', verbose_name='Ders'),
        ),
        migrations.AddField(
            model_name='assignmentlesson',
            name='resource_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_assignment_lessons', to='resources.resourcebook', verbose_name='Kaynak Kitap'),
        ),
        migrations.AddIndex(
            model_name='manualassignment',
            index=models.Index(fields=['student', 'status'], name='assignment__student_1a6a16_idx'),
        ),
        migrations.AddIndex(
            model_name='manualassignment',
            index=models.Index(fields=['coach', 'assigned_date'], name='assignment__coach_i_7e4893_idx'),
        ),
        migrations.AddIndex(
            model_name='manualassignment',
            index=models.Index(fields=['due_date'], name='assignment__due_dat_b5218f_idx'),
        ),
        migrations.AddIndex(
            model_name='manualassignment',
            index=models.Index(fields=['risk_status', 'status'], name='assignment__risk_st_35bfc2_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmenttask',
            index=models.Index(fields=['lesson_block', 'status'], name='assignment__lesson__00bb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentlesson',
            index=models.Index(fields=['assignment', 'order'], name='assignment__assignm_21799c_idx'),
        ),
    ]
