# Generated by Django 4.2.9 on 2026-02-10 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment_manual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualassignment',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Koç'),
        ),
    ]
