# Generated by Django 4.2.9 on 2026-02-10 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_tanimlari', '0009_merge_20260201_0154'),
        ('assignment_manual', '0002_coach_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentlesson',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_assignment_lessons', to='egitim_tanimlari.ders', verbose_name='Ders'),
        ),
    ]
