# Generated by Django 4.2.9 on 2026-02-13 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_resources', '0003_add_list_type'),
        ('resources', '0003_add_zorluk_seviyesi'),
        ('assignment_manual', '0003_lesson_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttask',
            name='content',
            field=models.ForeignKey(blank=True, help_text='Görevin ait olduğu kaynak içerik', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_tasks', to='resources.resourcecontent', verbose_name='Kaynak İçerik'),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, help_text='Atama anındaki sayfa sayısı', null=True, verbose_name='Sayfa Sayısı'),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='question_count',
            field=models.PositiveIntegerField(blank=True, help_text='Atama anındaki soru sayısı', null=True, verbose_name='Soru Sayısı'),
        ),
        migrations.AddField(
            model_name='manualassignment',
            name='source_assignment',
            field=models.ForeignKey(blank=True, help_text='Ödevin hangi kaynak atamasından oluşturulduğu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_assignments', to='student_resources.studentresourceassignment', verbose_name='Kaynak Ataması'),
        ),
    ]
