# Generated by Django 4.2.9 on 2026-02-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_manual', '0005_add_completion_evaluation_postpone_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualassignment',
            name='late_submission_note',
            field=models.TextField(blank=True, help_text='Ödev teslim tarihinden sonra getirildiğinde koçun eklediği not', verbose_name='Geç Teslim Notu'),
        ),
    ]
