# Generated by Django 4.2.9 on 2026-02-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_manual', '0006_add_late_submission_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualassignment',
            name='non_submission_note',
            field=models.TextField(blank=True, help_text='Ek açıklama', verbose_name='Ödev Getirilmeme Notu'),
        ),
        migrations.AddField(
            model_name='manualassignment',
            name='non_submission_reason',
            field=models.CharField(blank=True, choices=[('STUDENT_ABSENT', 'Öğrenci derse gelmedi'), ('NOT_BROUGHT', 'Öğrenci ödevi getirmedi'), ('NOT_DONE', 'Öğrenci ödevi yapmamış'), ('OTHER', 'Diğer')], help_text='Öğrenci gelmedi / ödev getirilmedi / yapılmadı vb.', max_length=50, verbose_name='Ödev Getirilmeme Sebebi'),
        ),
    ]
