# Generated by Django 4.2.9 on 2026-02-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_manual', '0007_add_non_submission_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttask',
            name='is_completion_task',
            field=models.BooleanField(default=False, help_text='Bu görev, daha önceki bir ödevdeki eksik içeriğin tamamlanması için mi verildi?', verbose_name='Eksik Tamamlama mı?'),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='previous_assignment_title',
            field=models.CharField(blank=True, help_text='Önceki ödevin başlığı (eksik tamamlama görevlerinde)', max_length=255, verbose_name='Önceki Ödev Başlığı'),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='previous_task_completion_percent',
            field=models.PositiveIntegerField(blank=True, help_text='Önceki ödevdeki tamamlanma yüzdesi (eksik tamamlama görevlerinde)', null=True, verbose_name='Önceki Tamamlanma %'),
        ),
        migrations.AlterField(
            model_name='manualassignment',
            name='non_submission_reason',
            field=models.CharField(blank=True, choices=[('CONTROL_NOT_POSSIBLE', 'Ödev kontrolü yapılamadı'), ('NOT_BROUGHT', 'Öğrenci ödevi getirmedi'), ('NOT_DONE', 'Öğrenci ödevi yapmamış'), ('OTHER', 'Diğer')], help_text='Öğrenci gelmedi / ödev getirilmedi / yapılmadı vb.', max_length=50, verbose_name='Ödev Getirilmeme Sebebi'),
        ),
    ]
