# Generated by Django 4.2.9 on 2026-02-14 19:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_add_zorluk_seviyesi'),
        ('assignment_manual', '0008_add_completion_task_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentlesson',
            name='resource_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_assignment_lessons', to='resources.resourcebook', verbose_name='Kaynak Kitap'),
        ),
        migrations.AlterField(
            model_name='manualassignment',
            name='difficulty_level',
            field=models.IntegerField(default=3, help_text='1-5 arası zorluk seviyesi', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Zorluk Seviyesi'),
        ),
    ]
