# Generated by Django 4.2.27 on 2026-06-24 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment_manual', '0009_fix_resource_book_set_null_and_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Paket Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('ders_ad', models.CharField(blank=True, max_length=255, verbose_name='Ders Adı')),
                ('sinif_seviyesi', models.CharField(blank=True, max_length=100, verbose_name='Sınıf Seviyesi')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Kullanım Sayısı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_packages_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Ödev Paketi',
                'verbose_name_plural': 'Ödev Paketleri',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='manualassignment',
            name='template_id',
        ),
        migrations.CreateModel(
            name='AssignmentPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.PositiveIntegerField(verbose_name='Kitap ID')),
                ('book_name', models.CharField(max_length=255, verbose_name='Kitap Adı')),
                ('content_id', models.PositiveIntegerField(verbose_name='İçerik ID')),
                ('content_name', models.CharField(max_length=255, verbose_name='İçerik Adı')),
                ('content_type', models.CharField(max_length=50, verbose_name='İçerik Tipi')),
                ('topic_name', models.CharField(blank=True, max_length=255, verbose_name='Konu Adı')),
                ('unit_name', models.CharField(blank=True, max_length=255, verbose_name='Ünite Adı')),
                ('question_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Soru Sayısı')),
                ('page_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='Başlangıç Sayfası')),
                ('page_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bitiş Sayfası')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assignment_manual.assignmentpackage', verbose_name='Paket')),
            ],
            options={
                'verbose_name': 'Ödev Paketi Kalemi',
                'verbose_name_plural': 'Ödev Paketi Kalemleri',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='manualassignment',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Bu ödevin oluşturulduğu ödev paketi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_from_template', to='assignment_manual.assignmentpackage', verbose_name='Ödev Paketi Şablonu'),
        ),
    ]
