# Generated by Django 4.2.9 on 2026-08-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_manual', '0014_assignment_notify_meta_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentpackageitem',
            name='topic_id',
            field=models.PositiveIntegerField(blank=True, help_text='Kitap yapısındaki konu ID — Ödev Ver sepetine yüklenirken doğru gruplama için kullanılır.', null=True, verbose_name='Konu ID'),
        ),
        migrations.AddField(
            model_name='assignmentpackageitem',
            name='unit_id',
            field=models.PositiveIntegerField(blank=True, help_text='Kitap yapısındaki ünite ID — Ödev Ver sepetine yüklenirken doğru gruplama için kullanılır.', null=True, verbose_name='Ünite ID'),
        ),
    ]
