# Generated by Django 4.2.9 on 2026-08-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_manual', '0015_assignment_package_item_topic_unit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentpackage',
            name='kurum_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Oluşturulduğu kurum — çoklu kurum izolasyonu için. Bu alan boş olan eski kayıtlar geriye dönük uyumluluk için tüm kurumlarda görünür.', null=True, verbose_name='Kurum ID'),
        ),
    ]
