# Generated by Django 4.2.9 on 2026-08-09 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment_manual', '0016_assignment_package_kurum_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualassignment',
            name='restored_at',
            field=models.DateTimeField(blank=True, help_text='Silindikten sonra geri yüklendiyse — silme kaydı (deleted_at/deleted_by/deletion_reason) audit için korunur, sadece is_active tekrar True yapılır.', null=True, verbose_name='Geri Yükleme Tarihi'),
        ),
        migrations.AddField(
            model_name='manualassignment',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_assignments_restored', to=settings.AUTH_USER_MODEL, verbose_name='Geri Yükleyen Kullanıcı'),
        ),
    ]
