# Generated by Django 4.2.9 on 2026-09-18 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egitim_tanimlari', '0011_ders_kisa_ad'),
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ogrenci', '0016_ogrenci_not_and_audit'),
        ('assignment_manual', '0020_assignment_k3_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_date', models.DateField(verbose_name='Tarih')),
                ('weekday', models.PositiveSmallIntegerField(verbose_name='Gün (0=Pzt)')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Kilitli')),
                ('target_minutes', models.PositiveIntegerField(default=0, verbose_name='Hedef süre')),
                ('planned_tests', models.PositiveIntegerField(default=0, verbose_name='Planlanan test')),
                ('planned_questions', models.PositiveIntegerField(default=0, verbose_name='Planlanan soru')),
                ('planned_minutes', models.PositiveIntegerField(default=0, verbose_name='Planlanan süre')),
                ('planned_slots', models.PositiveIntegerField(default=0, verbose_name='Planlanan slot')),
                ('completed_tests', models.PositiveIntegerField(default=0, verbose_name='Bitmiş test')),
                ('completed_questions', models.PositiveIntegerField(default=0, verbose_name='Bitmiş soru')),
                ('completed_minutes', models.PositiveIntegerField(default=0, verbose_name='Bitmiş süre')),
                ('completed_slots', models.PositiveIntegerField(default=0, verbose_name='Bitmiş slot')),
                ('load_level', models.CharField(choices=[('IDEAL', 'İdeal'), ('YOGUN', 'Yoğun'), ('TASTI', 'Taştı')], default='IDEAL', max_length=10, verbose_name='Yük')),
                ('cap_tests', models.PositiveIntegerField(default=0, verbose_name='Test tavanı')),
                ('cap_questions', models.PositiveIntegerField(default=0, verbose_name='Soru tavanı')),
                ('cap_minutes', models.PositiveIntegerField(default=0, verbose_name='Süre tavanı')),
                ('cap_slots', models.PositiveIntegerField(default=0, verbose_name='Slot tavanı')),
            ],
            options={
                'verbose_name': 'Çalışma günü',
                'verbose_name_plural': 'Çalışma günleri',
                'db_table': 'study_plan_day',
                'ordering': ['day_date'],
            },
        ),
        migrations.CreateModel(
            name='StudyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('scenario', models.CharField(choices=[('STANDART', 'Standart'), ('YOGUN', 'Yoğun'), ('SINAV_HAFTASI', 'Sınav Haftası'), ('ZAYIF_KONU', 'Zayıf Konu'), ('TYT_GUNLUK', 'TYT Günlük'), ('OZEL', 'Özel')], default='STANDART', max_length=20, verbose_name='Senaryo')),
                ('scope', models.CharField(choices=[('KURUM', 'Kurum'), ('KOC', 'Koç')], default='KURUM', max_length=10, verbose_name='Kapsam')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='Hazır şablon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('active_weekdays', models.JSONField(default=list, verbose_name='Aktif günler')),
                ('day_weights', models.JSONField(default=dict, verbose_name='Gün ağırlıkları')),
                ('weekend_policy', models.CharField(choices=[('off', 'Kapalı'), ('light', 'Hafif'), ('same', 'Aynı')], default='off', max_length=10, verbose_name='Hafta sonu')),
                ('intensify_weekdays', models.JSONField(default=list, verbose_name='Yoğunlaştırılacak günler')),
                ('strategy', models.CharField(choices=[('BY_TEST', 'Teste göre'), ('BY_QUESTION', 'Soruya göre'), ('EQUAL', 'Eşit'), ('WEIGHTED', 'Ağırlıklı')], default='BY_TEST', max_length=20, verbose_name='Dağıtım')),
                ('unit_priority', models.JSONField(default=list, help_text='örn. ["test", "exam", "question", "review"]', verbose_name='Birim önceliği')),
                ('max_questions_per_day', models.PositiveIntegerField(default=20, verbose_name='Günlük soru tavanı')),
                ('max_tests_per_day', models.PositiveIntegerField(default=2, verbose_name='Günlük test tavanı')),
                ('max_minutes_per_day', models.PositiveIntegerField(default=90, verbose_name='Günlük süre tavanı')),
                ('max_slots_per_day', models.PositiveIntegerField(default=6, verbose_name='Günlük slot tavanı')),
                ('overflow', models.CharField(choices=[('leftover', 'Bekleyen kutu'), ('next_day', 'Sonraki gün'), ('next_week', 'Sonraki hafta')], default='leftover', max_length=16, verbose_name='Taşma')),
                ('lock_past_days', models.BooleanField(default=True, verbose_name='Geçmiş günleri kilitle')),
                ('respect_due_date', models.BooleanField(default=True, verbose_name='Teslim tarihine uy')),
                ('honor_calendar', models.BooleanField(default=True, verbose_name='Takvim tatillerini say')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_templates', to='kurum.kurum', verbose_name='Kurum')),
            ],
            options={
                'verbose_name': 'Çalışma şablonu',
                'verbose_name_plural': 'Çalışma şablonları',
                'db_table': 'study_plan_template',
                'ordering': ['scenario', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('HOMEWORK', 'Ödev'), ('GOAL', 'Hedef'), ('REVIEW', 'Tekrar'), ('EXAM_ANALYSIS', 'Deneme analizi')], default='HOMEWORK', max_length=20, verbose_name='Kaynak türü')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('topic_name', models.CharField(blank=True, max_length=255, verbose_name='Konu')),
                ('resource_name', models.CharField(blank=True, max_length=255, verbose_name='Kaynak')),
                ('planned_tests', models.PositiveIntegerField(default=0, verbose_name='Planlanan test')),
                ('planned_questions', models.PositiveIntegerField(default=0, verbose_name='Planlanan soru')),
                ('planned_minutes', models.PositiveIntegerField(default=0, verbose_name='Planlanan süre')),
                ('completed_tests', models.PositiveIntegerField(default=0, verbose_name='Bitmiş test')),
                ('completed_questions', models.PositiveIntegerField(default=0, verbose_name='Bitmiş soru')),
                ('completed_minutes', models.PositiveIntegerField(default=0, verbose_name='Bitmiş süre')),
                ('is_done', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Kilitli')),
                ('is_orphaned', models.BooleanField(default=False, verbose_name='Yetim')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='study_plans.studyday', verbose_name='Gün')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plan_slots', to='egitim_tanimlari.ders', verbose_name='Ders')),
                ('source_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plan_slots', to='assignment_manual.manualassignment', verbose_name='Kaynak ödev')),
                ('source_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plan_slots', to='assignment_manual.assignmentlesson', verbose_name='Kaynak ödev dersi')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plan_slots', to='assignment_manual.assignmenttask', verbose_name='Kaynak görev')),
            ],
            options={
                'verbose_name': 'Çalışma slotu',
                'verbose_name_plural': 'Çalışma slotları',
                'db_table': 'study_plan_slot',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Hafta başlangıcı')),
                ('week_end', models.DateField(verbose_name='Hafta bitişi')),
                ('generation_version', models.PositiveIntegerField(default=1, verbose_name='Üretim sürümü')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('ARCHIVED', 'Arşiv'), ('SUPERSEDED', 'Üzerine yazıldı')], default='ACTIVE', max_length=16, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plan_programs', to=settings.AUTH_USER_MODEL, verbose_name='Koç')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan_programs', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='study_plans.studytemplate', verbose_name='Şablon')),
            ],
            options={
                'verbose_name': 'Çalışma programı',
                'verbose_name_plural': 'Çalışma programları',
                'db_table': 'study_plan_program',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='StudyLeftover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('HOMEWORK', 'Ödev'), ('GOAL', 'Hedef'), ('REVIEW', 'Tekrar'), ('EXAM_ANALYSIS', 'Deneme analizi')], default='HOMEWORK', max_length=20, verbose_name='Kaynak türü')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('lesson_name', models.CharField(blank=True, max_length=120, verbose_name='Ders')),
                ('remaining_tests', models.PositiveIntegerField(default=0, verbose_name='Kalan test')),
                ('remaining_questions', models.PositiveIntegerField(default=0, verbose_name='Kalan soru')),
                ('remaining_minutes', models.PositiveIntegerField(default=0, verbose_name='Kalan süre')),
                ('reason', models.CharField(choices=[('OVER_CAP', 'Tavan aşıldı'), ('NO_DAY', 'Uygun gün yok'), ('DUE_PASSED', 'Teslim geçti')], default='OVER_CAP', max_length=16, verbose_name='Neden')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leftovers', to='study_plans.studyprogram', verbose_name='Program')),
                ('source_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plan_leftovers', to='assignment_manual.manualassignment')),
                ('source_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plan_leftovers', to='assignment_manual.assignmentlesson')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plan_leftovers', to='assignment_manual.assignmenttask')),
            ],
            options={
                'verbose_name': 'Bekleyen birim',
                'verbose_name_plural': 'Bekleyen birimler',
                'db_table': 'study_plan_leftover',
            },
        ),
        migrations.CreateModel(
            name='StudyGenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_snapshot', models.JSONField(default=dict, verbose_name='Girdi')),
                ('warnings', models.JSONField(default=list, verbose_name='Uyarılar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plan_generation_runs', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_runs', to='study_plans.studyprogram', verbose_name='Program')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_runs', to='study_plans.studytemplate')),
            ],
            options={
                'verbose_name': 'Üretim kaydı',
                'verbose_name_plural': 'Üretim kayıtları',
                'db_table': 'study_plan_generation_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studyday',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='study_plans.studyprogram', verbose_name='Program'),
        ),
        migrations.CreateModel(
            name='StudentStudyWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(verbose_name='Gün (0=Pzt)')),
                ('available_minutes', models.PositiveIntegerField(default=90, verbose_name='Müsait dakika')),
                ('is_available', models.BooleanField(default=True, verbose_name='Çalışılabilir')),
                ('exception_dates', models.JSONField(default=list, verbose_name='Kapalı tarihler')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_windows', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Öğrenci çalışma penceresi',
                'verbose_name_plural': 'Öğrenci çalışma pencereleri',
                'db_table': 'study_plan_window',
            },
        ),
        migrations.AddIndex(
            model_name='studytemplate',
            index=models.Index(fields=['kurum', 'is_active'], name='spt_kurum_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='studytemplate',
            constraint=models.UniqueConstraint(fields=('kurum', 'name'), name='unique_study_template_kurum_name'),
        ),
        migrations.AddIndex(
            model_name='studyprogram',
            index=models.Index(fields=['student', 'week_start'], name='spp_student_week_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyprogram',
            constraint=models.UniqueConstraint(fields=('student', 'week_start'), name='unique_study_plan_student_week'),
        ),
        migrations.AddConstraint(
            model_name='studyday',
            constraint=models.UniqueConstraint(fields=('program', 'day_date'), name='unique_study_plan_day'),
        ),
        migrations.AddConstraint(
            model_name='studentstudywindow',
            constraint=models.UniqueConstraint(fields=('student', 'weekday'), name='unique_study_window_student_weekday'),
        ),
    ]
