# Generated by Django 4.2.9 on 2026-01-30 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, verbose_name='Kurum Adı')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Kurum Kodu')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kurum',
                'verbose_name_plural': 'Kurumlar',
                'db_table': 'kurumlar',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Sube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, verbose_name='Şube Adı')),
                ('kod', models.CharField(max_length=50, verbose_name='Şube Kodu')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subeler', to='kurum_yonetimi.kurum', verbose_name='Kurum')),
            ],
            options={
                'verbose_name': 'Şube',
                'verbose_name_plural': 'Şubeler',
                'db_table': 'subeler',
                'ordering': ['kurum', 'ad'],
                'unique_together': {('kurum', 'kod')},
            },
        ),
        migrations.CreateModel(
            name='EgitimYili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.CharField(help_text='Örnek: 2024-2025', max_length=20, verbose_name='Eğitim Yılı')),
                ('schema_adi', models.CharField(help_text='PostgreSQL schema adı', max_length=100, unique=True, verbose_name='Schema Adı')),
                ('aktif_mi', models.BooleanField(default=False, verbose_name='Aktif Mi?')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(verbose_name='Bitiş Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egitim_yillari', to='kurum_yonetimi.kurum', verbose_name='Kurum')),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egitim_yillari', to='kurum_yonetimi.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Eğitim Yılı',
                'verbose_name_plural': 'Eğitim Yılları',
                'db_table': 'egitim_yillari',
                'ordering': ['-yil'],
                'unique_together': {('kurum', 'sube', 'yil')},
            },
        ),
    ]
