# Generated by Django 4.2.9 on 2026-01-31 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egitim_tanimlari', '0008_populate_sira_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='OzelDers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Paket Adı')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('saat_ucreti', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saat Ücreti')),
                ('min_saat', models.PositiveIntegerField(default=1, verbose_name='Minimum Saat')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('alan', models.ForeignKey(blank=True, help_text='Opsiyonel - belirli bir alana ait ise seçin', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ozel_dersler', to='egitim_tanimlari.alan', verbose_name='Alan')),
                ('dersler', models.ManyToManyField(help_text='Bu pakete dahil dersler', related_name='ozel_ders_paketleri', to='egitim_tanimlari.ders', verbose_name='Dersler')),
                ('sinif_seviyesi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ozel_dersler', to='egitim_tanimlari.sinifseviyesi', verbose_name='Sınıf Seviyesi')),
            ],
            options={
                'verbose_name': 'Özel Ders',
                'verbose_name_plural': 'Özel Dersler',
                'db_table': 'ozel_ders',
                'ordering': ['sinif_seviyesi__sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='GrupDersi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Paket Adı')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fiyat')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('alan', models.ForeignKey(blank=True, help_text='Opsiyonel - belirli bir alana ait ise seçin', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grup_dersleri', to='egitim_tanimlari.alan', verbose_name='Alan')),
                ('dersler', models.ManyToManyField(help_text='Bu pakete dahil dersler', related_name='grup_dersi_paketleri', to='egitim_tanimlari.ders', verbose_name='Dersler')),
                ('sinif_seviyesi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grup_dersleri', to='egitim_tanimlari.sinifseviyesi', verbose_name='Sınıf Seviyesi')),
            ],
            options={
                'verbose_name': 'Grup Dersi',
                'verbose_name_plural': 'Grup Dersleri',
                'db_table': 'grup_dersi',
                'ordering': ['sinif_seviyesi__sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='Deneme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Deneme Adı')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('deneme_sayisi', models.PositiveIntegerField(default=1, verbose_name='Deneme Sayısı')),
                ('fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fiyat')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('sinif_seviyeleri', models.ManyToManyField(help_text='Bu deneme hangi sınıf seviyelerine uygulanır?', related_name='denemeler', to='egitim_tanimlari.sinifseviyesi', verbose_name='Sınıf Seviyeleri')),
            ],
            options={
                'verbose_name': 'Deneme',
                'verbose_name_plural': 'Denemeler',
                'db_table': 'deneme',
                'ordering': ['ad'],
            },
        ),
    ]
