# Generated by Django 4.2.9 on 2026-01-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_paketleri', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ozelders',
            name='min_saat',
        ),
        migrations.RemoveField(
            model_name='ozelders',
            name='saat_ucreti',
        ),
        migrations.AddField(
            model_name='ozelders',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fiyat'),
        ),
    ]
