# Generated by Django 4.2.9 on 2026-01-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_tanimlari', '0008_populate_sira_values'),
        ('egitim_paketleri', '0002_remove_ozelders_min_saat_remove_ozelders_saat_ucreti_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ozelders',
            options={'ordering': ['ad'], 'verbose_name': 'Özel Ders', 'verbose_name_plural': 'Özel Dersler'},
        ),
        migrations.RemoveField(
            model_name='ozelders',
            name='sinif_seviyesi',
        ),
        migrations.AddField(
            model_name='ozelders',
            name='sinif_seviyeleri',
            field=models.ManyToManyField(help_text='Bu pakete dahil sınıf seviyeleri', related_name='ozel_dersler', to='egitim_tanimlari.sinifseviyesi', verbose_name='Sınıf Seviyeleri'),
        ),
    ]
