# Generated by Django 4.2.9 on 2026-01-31 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_paketleri', '0002_davranis_paketi'),
        ('egitim_paketleri', '0003_alter_ozelders_options_and_more'),
    ]

    operations = [
    ]
