# Generated by Django 4.2.27 on 2026-02-02 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_yili', '0001_initial'),
        ('egitim_paketleri', '0004_merge_20260201_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='davranispaketi',
            name='egitim_yili',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='davranis_paketleri', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deneme',
            name='egitim_yili',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='denemeler', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupdersi',
            name='egitim_yili',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='grup_dersleri', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ozelders',
            name='egitim_yili',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='ozel_dersler', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='davranispaketi',
            name='kod',
            field=models.CharField(max_length=50, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='deneme',
            name='kod',
            field=models.CharField(max_length=50, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='grupdersi',
            name='kod',
            field=models.CharField(max_length=50, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='ozelders',
            name='kod',
            field=models.CharField(max_length=50, verbose_name='Kod'),
        ),
        migrations.AddConstraint(
            model_name='davranispaketi',
            constraint=models.UniqueConstraint(fields=('kod', 'egitim_yili'), name='unique_davranis_kod_yil'),
        ),
        migrations.AddConstraint(
            model_name='deneme',
            constraint=models.UniqueConstraint(fields=('kod', 'egitim_yili'), name='unique_deneme_kod_yil'),
        ),
        migrations.AddConstraint(
            model_name='grupdersi',
            constraint=models.UniqueConstraint(fields=('kod', 'egitim_yili'), name='unique_grup_dersi_kod_yil'),
        ),
        migrations.AddConstraint(
            model_name='ozelders',
            constraint=models.UniqueConstraint(fields=('kod', 'egitim_yili'), name='unique_ozel_ders_kod_yil'),
        ),
    ]
