# Generated by Django 4.2.27 on 2026-02-02 21:25

from django.db import migrations, models
import django.db.models.deletion


def set_default_kurum_sube(apps, schema_editor):
    """Mevcut kayıtlara ilk kurum ve şubeyi ata"""
    Kurum = apps.get_model('kurum', 'Kurum')
    Sube = apps.get_model('sube', 'Sube')
    
    # İlk aktif kurum ve şubeyi bul
    kurum = Kurum.objects.filter(aktif_mi=True).first()
    sube = None
    if kurum:
        sube = Sube.objects.filter(kurum=kurum, aktif_mi=True).first()
    
    if not kurum or not sube:
        # Hiç kurum/şube yoksa işlem yapma
        return
    
    # Tüm paketleri güncelle
    GrupDersi = apps.get_model('egitim_paketleri', 'GrupDersi')
    OzelDers = apps.get_model('egitim_paketleri', 'OzelDers')
    Deneme = apps.get_model('egitim_paketleri', 'Deneme')
    DavranisPaketi = apps.get_model('egitim_paketleri', 'DavranisPaketi')
    
    GrupDersi.objects.filter(kurum__isnull=True).update(kurum=kurum, sube=sube)
    OzelDers.objects.filter(kurum__isnull=True).update(kurum=kurum, sube=sube)
    Deneme.objects.filter(kurum__isnull=True).update(kurum=kurum, sube=sube)
    DavranisPaketi.objects.filter(kurum__isnull=True).update(kurum=kurum, sube=sube)


def reverse_kurum_sube(apps, schema_editor):
    """Geri alma işlemi - kurum/şube'yi null yap"""
    GrupDersi = apps.get_model('egitim_paketleri', 'GrupDersi')
    OzelDers = apps.get_model('egitim_paketleri', 'OzelDers')
    Deneme = apps.get_model('egitim_paketleri', 'Deneme')
    DavranisPaketi = apps.get_model('egitim_paketleri', 'DavranisPaketi')
    
    GrupDersi.objects.all().update(kurum=None, sube=None)
    OzelDers.objects.all().update(kurum=None, sube=None)
    Deneme.objects.all().update(kurum=None, sube=None)
    DavranisPaketi.objects.all().update(kurum=None, sube=None)


class Migration(migrations.Migration):

    dependencies = [
        ('sube', '0001_initial'),
        ('kurum', '0001_initial'),
        ('egitim_paketleri', '0005_add_egitim_yili_to_paketler'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='davranispaketi',
            name='unique_davranis_kod_yil',
        ),
        migrations.RemoveConstraint(
            model_name='deneme',
            name='unique_deneme_kod_yil',
        ),
        migrations.RemoveConstraint(
            model_name='grupdersi',
            name='unique_grup_dersi_kod_yil',
        ),
        migrations.RemoveConstraint(
            model_name='ozelders',
            name='unique_ozel_ders_kod_yil',
        ),
        migrations.AddField(
            model_name='davranispaketi',
            name='kurum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='davranis_paketleri', to='kurum.kurum', verbose_name='Kurum'),
        ),
        migrations.AddField(
            model_name='davranispaketi',
            name='sube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='davranis_paketleri', to='sube.sube', verbose_name='Şube'),
        ),
        migrations.AddField(
            model_name='deneme',
            name='kurum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denemeler', to='kurum.kurum', verbose_name='Kurum'),
        ),
        migrations.AddField(
            model_name='deneme',
            name='sube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denemeler', to='sube.sube', verbose_name='Şube'),
        ),
        migrations.AddField(
            model_name='grupdersi',
            name='kurum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grup_dersleri', to='kurum.kurum', verbose_name='Kurum'),
        ),
        migrations.AddField(
            model_name='grupdersi',
            name='sube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grup_dersleri', to='sube.sube', verbose_name='Şube'),
        ),
        migrations.AddField(
            model_name='ozelders',
            name='kurum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ozel_dersler', to='kurum.kurum', verbose_name='Kurum'),
        ),
        migrations.AddField(
            model_name='ozelders',
            name='sube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ozel_dersler', to='sube.sube', verbose_name='Şube'),
        ),
        # Mevcut kayıtlara kurum/şube ata
        migrations.RunPython(set_default_kurum_sube, reverse_kurum_sube),
        migrations.AddIndex(
            model_name='davranispaketi',
            index=models.Index(fields=['kurum', 'sube', 'egitim_yili'], name='davranis_pa_kurum_i_0100f4_idx'),
        ),
        migrations.AddIndex(
            model_name='deneme',
            index=models.Index(fields=['kurum', 'sube', 'egitim_yili'], name='deneme_kurum_i_801883_idx'),
        ),
        migrations.AddIndex(
            model_name='grupdersi',
            index=models.Index(fields=['kurum', 'sube', 'egitim_yili'], name='grup_dersi_kurum_i_e743b3_idx'),
        ),
        migrations.AddIndex(
            model_name='ozelders',
            index=models.Index(fields=['kurum', 'sube', 'egitim_yili'], name='ozel_ders_kurum_i_f139ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='davranispaketi',
            constraint=models.UniqueConstraint(fields=('kod', 'sube', 'egitim_yili'), name='unique_davranis_kod_sube_yil'),
        ),
        migrations.AddConstraint(
            model_name='deneme',
            constraint=models.UniqueConstraint(fields=('kod', 'sube', 'egitim_yili'), name='unique_deneme_kod_sube_yil'),
        ),
        migrations.AddConstraint(
            model_name='grupdersi',
            constraint=models.UniqueConstraint(fields=('kod', 'sube', 'egitim_yili'), name='unique_grup_dersi_kod_sube_yil'),
        ),
        migrations.AddConstraint(
            model_name='ozelders',
            constraint=models.UniqueConstraint(fields=('kod', 'sube', 'egitim_yili'), name='unique_ozel_ders_kod_sube_yil'),
        ),
    ]
