# Generated by Django 4.2.9 on 2026-02-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_tanimlari', '0009_merge_20260201_0154'),
        ('egitim_paketleri', '0006_add_kurum_sube_to_paketler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupdersi',
            options={'ordering': ['ad'], 'verbose_name': 'Grup Dersi', 'verbose_name_plural': 'Grup Dersleri'},
        ),
        migrations.RemoveField(
            model_name='grupdersi',
            name='sinif_seviyesi',
        ),
        migrations.AddField(
            model_name='grupdersi',
            name='sinif_seviyeleri',
            field=models.ManyToManyField(blank=True, help_text='Bu pakete dahil sınıf seviyeleri', related_name='grup_dersleri', to='egitim_tanimlari.sinifseviyesi', verbose_name='Sınıf Seviyeleri'),
        ),
    ]
