# Generated by Django 4.2.9 on 2026-02-19 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sube', '0001_initial'),
        ('egitim_tanimlari', '0009_merge_20260201_0154'),
        ('egitim_yili', '0001_initial'),
        ('kurum', '0001_initial'),
        ('egitim_paketleri', '0007_alter_grupdersi_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkHizmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Hizmet Adı')),
                ('kod', models.CharField(max_length=50, verbose_name='Kod')),
                ('hizmet_turu', models.CharField(choices=[('kutuphane', 'Kütüphane'), ('kocluk', 'Koçluk'), ('deneme', 'Deneme')], help_text='Bu hizmetin türü — modül entegrasyonları için kullanılır', max_length=20, verbose_name='Hizmet Türü')),
                ('fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fiyat')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ek_hizmetler', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('kurum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ek_hizmetler', to='kurum.kurum', verbose_name='Kurum')),
                ('sinif_seviyeleri', models.ManyToManyField(blank=True, help_text='Bu hizmet hangi sınıf seviyelerine uygulanır?', related_name='ek_hizmetler', to='egitim_tanimlari.sinifseviyesi', verbose_name='Sınıf Seviyeleri')),
                ('sube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ek_hizmetler', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Ek Hizmet',
                'verbose_name_plural': 'Ek Hizmetler',
                'db_table': 'ek_hizmet',
                'ordering': ['hizmet_turu', 'ad'],
            },
        ),
        migrations.AddField(
            model_name='grupdersi',
            name='dahil_ek_hizmetler',
            field=models.ManyToManyField(blank=True, help_text='Bu grup dersine ücretsiz dahil olan ek hizmetler', related_name='dahil_oldugu_grup_dersleri', to='egitim_paketleri.ekhizmet', verbose_name='Dahil Ek Hizmetler'),
        ),
        migrations.AddIndex(
            model_name='ekhizmet',
            index=models.Index(fields=['kurum', 'sube', 'egitim_yili'], name='ek_hizmet_kurum_i_d590a9_idx'),
        ),
        migrations.AddIndex(
            model_name='ekhizmet',
            index=models.Index(fields=['hizmet_turu', 'aktif_mi'], name='ek_hizmet_hizmet__a95d56_idx'),
        ),
        migrations.AddConstraint(
            model_name='ekhizmet',
            constraint=models.UniqueConstraint(fields=('kod', 'sube', 'egitim_yili'), name='unique_ek_hizmet_kod_sube_yil'),
        ),
    ]
