# Generated by Django 4.2.9 on 2026-02-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_paketleri', '0009_kdv_orani_ve_deneme_paketi_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='deneme',
            name='dahil_ek_hizmetler',
            field=models.ManyToManyField(blank=True, help_text='Bu deneme paketine ücretsiz dahil olan ek hizmetler', related_name='dahil_oldugu_denemeler', to='egitim_paketleri.ekhizmet', verbose_name='Dahil Ek Hizmetler'),
        ),
    ]
