# Generated by Django 4.2.9 on 2026-02-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_paketleri', '0011_integer_only_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davranispaketi',
            name='brut_fiyat',
            field=models.IntegerField(default=0, help_text="KDV dahil fiyat (TL). 100 TL'nin katı olmalıdır.", verbose_name='Brüt Fiyat (KDV Dahil)'),
        ),
        migrations.AlterField(
            model_name='davranispaketi',
            name='kdv_orani',
            field=models.IntegerField(default=10, help_text='KDV oranı yüzde olarak (0, 10, 20)', verbose_name='KDV Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='davranispaketi',
            name='kdv_tutari',
            field=models.IntegerField(default=0, help_text='Otomatik hesaplanır.', verbose_name='KDV Tutarı'),
        ),
        migrations.AlterField(
            model_name='davranispaketi',
            name='net_fiyat',
            field=models.IntegerField(default=0, help_text='Otomatik hesaplanır.', verbose_name='Net Fiyat (KDV Hariç)'),
        ),
        migrations.AlterField(
            model_name='deneme',
            name='brut_fiyat',
            field=models.IntegerField(default=0, help_text="KDV dahil fiyat (TL). 100 TL'nin katı olmalıdır.", verbose_name='Brüt Fiyat (KDV Dahil)'),
        ),
        migrations.AlterField(
            model_name='deneme',
            name='kdv_orani',
            field=models.IntegerField(default=10, help_text='KDV oranı yüzde olarak (0, 10, 20)', verbose_name='KDV Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='deneme',
            name='kdv_tutari',
            field=models.IntegerField(default=0, help_text='Otomatik hesaplanır.', verbose_name='KDV Tutarı'),
        ),
        migrations.AlterField(
            model_name='deneme',
            name='net_fiyat',
            field=models.IntegerField(default=0, help_text='Otomatik hesaplanır.', verbose_name='Net Fiyat (KDV Hariç)'),
        ),
        migrations.AlterField(
            model_name='ekhizmet',
            name='brut_fiyat',
            field=models.IntegerField(default=0, help_text="KDV dahil fiyat (TL). 100 TL'nin katı olmalıdır.", verbose_name='Brüt Fiyat (KDV Dahil)'),
        ),
        migrations.AlterField(
            model_name='ekhizmet',
            name='kdv_orani',
            field=models.IntegerField(default=10, help_text='KDV oranı yüzde olarak (0, 10, 20)', verbose_name='KDV Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='ekhizmet',
            name='kdv_tutari',
            field=models.IntegerField(default=0, help_text='Otomatik hesaplanır.', verbose_name='KDV Tutarı'),
        ),
        migrations.AlterField(
            model_name='ekhizmet',
            name='net_fiyat',
            field=models.IntegerField(default=0, help_text='Otomatik hesaplanır.', verbose_name='Net Fiyat (KDV Hariç)'),
        ),
        migrations.AlterField(
            model_name='grupdersi',
            name='brut_fiyat',
            field=models.IntegerField(default=0, help_text="KDV dahil fiyat (TL). 100 TL'nin katı olmalıdır.", verbose_name='Brüt Fiyat (KDV Dahil)'),
        ),
        migrations.AlterField(
            model_name='grupdersi',
            name='kdv_orani',
            field=models.IntegerField(default=10, help_text='KDV oranı yüzde olarak (0, 10, 20)', verbose_name='KDV Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='grupdersi',
            name='kdv_tutari',
            field=models.IntegerField(default=0, help_text='Otomatik hesaplanır.', verbose_name='KDV Tutarı'),
        ),
        migrations.AlterField(
            model_name='grupdersi',
            name='net_fiyat',
            field=models.IntegerField(default=0, help_text='Otomatik hesaplanır.', verbose_name='Net Fiyat (KDV Hariç)'),
        ),
        migrations.AlterField(
            model_name='ozelders',
            name='brut_fiyat',
            field=models.IntegerField(default=0, help_text="KDV dahil fiyat (TL). 100 TL'nin katı olmalıdır.", verbose_name='Brüt Fiyat (KDV Dahil)'),
        ),
        migrations.AlterField(
            model_name='ozelders',
            name='kdv_orani',
            field=models.IntegerField(default=10, help_text='KDV oranı yüzde olarak (0, 10, 20)', verbose_name='KDV Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='ozelders',
            name='kdv_tutari',
            field=models.IntegerField(default=0, help_text='Otomatik hesaplanır.', verbose_name='KDV Tutarı'),
        ),
        migrations.AlterField(
            model_name='ozelders',
            name='net_fiyat',
            field=models.IntegerField(default=0, help_text='Otomatik hesaplanır.', verbose_name='Net Fiyat (KDV Hariç)'),
        ),
    ]
