# Generated by Django 4.2.9 on 2026-07-08 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
        ('egitim_yili', '0001_initial'),
        ('sube', '0003_sube_branding'),
        ('egitim_tanimlari', '0010_sube_scoped_catalog'),
        ('egitim_paketleri', '0014_fix_kocluk_hizmet_turu'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPaket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Paket Adı')),
                ('kod', models.CharField(max_length=50, verbose_name='Kod')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('brut_fiyat', models.IntegerField(default=0, help_text="KDV dahil fiyat (TL). 100 TL'nin katı olmalıdır.", verbose_name='Brüt Fiyat (KDV Dahil)')),
                ('kdv_orani', models.IntegerField(default=10, help_text='KDV oranı yüzde olarak (0, 10, 20)', verbose_name='KDV Oranı (%)')),
                ('net_fiyat', models.IntegerField(default=0, help_text='Otomatik hesaplanır.', verbose_name='Net Fiyat (KDV Hariç)')),
                ('kdv_tutari', models.IntegerField(default=0, help_text='Otomatik hesaplanır.', verbose_name='KDV Tutarı')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('dahil_denemeler', models.ManyToManyField(blank=True, help_text='Bu premium pakete ücretsiz dahil olan deneme paketleri', related_name='dahil_oldugu_premium_paketler', to='egitim_paketleri.deneme', verbose_name='Dahil Deneme Paketleri')),
                ('dahil_ek_hizmetler', models.ManyToManyField(blank=True, help_text='Bu premium pakete ücretsiz dahil olan ek hizmetler', related_name='dahil_oldugu_premium_paketler', to='egitim_paketleri.ekhizmet', verbose_name='Dahil Ek Hizmetler')),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premium_paketler', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('kurum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_paketler', to='kurum.kurum', verbose_name='Kurum')),
                ('sinif_seviyeleri', models.ManyToManyField(blank=True, help_text='Bu paket hangi sınıf seviyelerine uygulanır?', related_name='premium_paketler', to='egitim_tanimlari.sinifseviyesi', verbose_name='Sınıf Seviyeleri')),
                ('sube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_paketler', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Premium Paket',
                'verbose_name_plural': 'Premium Paketler',
                'db_table': 'premium_paket',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='YayinPaketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Paket Adı')),
                ('kod', models.CharField(max_length=50, verbose_name='Kod')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('brut_fiyat', models.IntegerField(default=0, help_text="KDV dahil fiyat (TL). 100 TL'nin katı olmalıdır.", verbose_name='Brüt Fiyat (KDV Dahil)')),
                ('kdv_orani', models.IntegerField(default=10, help_text='KDV oranı yüzde olarak (0, 10, 20)', verbose_name='KDV Oranı (%)')),
                ('net_fiyat', models.IntegerField(default=0, help_text='Otomatik hesaplanır.', verbose_name='Net Fiyat (KDV Hariç)')),
                ('kdv_tutari', models.IntegerField(default=0, help_text='Otomatik hesaplanır.', verbose_name='KDV Tutarı')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('dahil_grup_dersleri', models.ManyToManyField(blank=True, help_text='Bu yayın paketine ücretsiz dahil olan grup dersleri', related_name='dahil_oldugu_yayin_paketleri', to='egitim_paketleri.grupdersi', verbose_name='Dahil Grup Dersleri')),
                ('dahil_premium_paketler', models.ManyToManyField(blank=True, help_text='Bu yayın paketine ücretsiz dahil olan premium paketler', related_name='dahil_oldugu_yayin_paketleri', to='egitim_paketleri.premiumpaket', verbose_name='Dahil Premium Paketler')),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yayin_paketleri', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('kurum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yayin_paketleri', to='kurum.kurum', verbose_name='Kurum')),
                ('sinif_seviyeleri', models.ManyToManyField(blank=True, help_text='Bu paket hangi sınıf seviyelerine uygulanır?', related_name='yayin_paketleri', to='egitim_tanimlari.sinifseviyesi', verbose_name='Sınıf Seviyeleri')),
                ('sube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yayin_paketleri', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Yayın Paketi',
                'verbose_name_plural': 'Yayın Paketleri',
                'db_table': 'yayin_paketi',
                'ordering': ['ad'],
                'indexes': [models.Index(fields=['kurum', 'sube', 'egitim_yili'], name='yayin_paket_kurum_i_8ad85d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='yayinpaketi',
            constraint=models.UniqueConstraint(fields=('kod', 'sube', 'egitim_yili'), name='unique_yayin_paketi_kod_sube_yil'),
        ),
        migrations.AddIndex(
            model_name='premiumpaket',
            index=models.Index(fields=['kurum', 'sube', 'egitim_yili'], name='premium_pak_kurum_i_484c6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='premiumpaket',
            constraint=models.UniqueConstraint(fields=('kod', 'sube', 'egitim_yili'), name='unique_premium_paket_kod_sube_yil'),
        ),
    ]
