# Generated by Django 4.2.9 on 2026-07-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_paketleri', '0015_premiumpaket_yayinpaketi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yayinpaketi',
            name='dahil_denemeler',
            field=models.ManyToManyField(blank=True, help_text='Bu yayın paketine ücretsiz dahil olan deneme paketleri', related_name='dahil_oldugu_yayin_paketleri', to='egitim_paketleri.deneme', verbose_name='Dahil Deneme Paketleri'),
        ),
        migrations.AddField(
            model_name='yayinpaketi',
            name='dahil_ek_hizmetler',
            field=models.ManyToManyField(blank=True, help_text='Bu yayın paketine ücretsiz dahil olan ek hizmetler', related_name='dahil_oldugu_yayin_paketleri', to='egitim_paketleri.ekhizmet', verbose_name='Dahil Ek Hizmetler'),
        ),
    ]
