# Generated by Django 4.2.9 on 2026-07-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_paketleri', '0016_yayinpaketi_dahil_denemeler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yayinpaketi',
            name='dahil_denemeler',
        ),
        migrations.RemoveField(
            model_name='yayinpaketi',
            name='dahil_ek_hizmetler',
        ),
        migrations.RemoveField(
            model_name='yayinpaketi',
            name='dahil_grup_dersleri',
        ),
        migrations.RemoveField(
            model_name='yayinpaketi',
            name='dahil_premium_paketler',
        ),
        migrations.AddField(
            model_name='grupdersi',
            name='dahil_yayin_paketleri',
            field=models.ManyToManyField(blank=True, help_text='Bu grup dersine ücretsiz dahil olan yayın paketleri', related_name='dahil_oldugu_grup_dersleri', to='egitim_paketleri.yayinpaketi', verbose_name='Dahil Yayın Paketleri'),
        ),
        migrations.AddField(
            model_name='premiumpaket',
            name='dahil_yayin_paketleri',
            field=models.ManyToManyField(blank=True, help_text='Bu premium pakete ücretsiz dahil olan yayın paketleri', related_name='dahil_oldugu_premium_paketler', to='egitim_paketleri.yayinpaketi', verbose_name='Dahil Yayın Paketleri'),
        ),
    ]
