# Generated by Django 4.2.27 on 2026-09-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_paketleri', '0017_remove_yayinpaketi_dahil_denemeler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekhizmet',
            name='hizmet_turu',
            field=models.CharField(choices=[('kutuphane', 'Kütüphane'), ('kocluk', 'Koçluk')], help_text='Bu hizmetin türü — modül entegrasyonları için kullanılır', max_length=20, verbose_name='Hizmet Türü'),
        ),
    ]
