# Generated by Django 4.2.27 on 2026-02-07 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ogrenci', '0005_add_profil_foto'),
        ('personel', '0009_personel_aktivite_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(default=30, help_text='Koçun aynı anda sorumlu olabileceği maksimum öğrenci sayısı', verbose_name='Öğrenci Kapasitesi')),
                ('is_active', models.BooleanField(default=True, help_text='Koçluk yapıp yapamayacağını belirler', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to='personel.personel', verbose_name='Öğretmen')),
            ],
            options={
                'verbose_name': 'Koç Profili',
                'verbose_name_plural': 'Koç Profilleri',
                'db_table': 'coaching_coach_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('MEETING', 'Görüşme'), ('ASSIGNMENT', 'Ödev'), ('GOAL', 'Hedef'), ('RISK', 'Risk Bildirimi')], max_length=20, verbose_name='Etkinlik Türü')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('event_date', models.DateTimeField(verbose_name='Etkinlik Tarihi')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='coaching.coachprofile', verbose_name='Koç')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_events', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Koçluk Etkinliği',
                'verbose_name_plural': 'Koçluk Etkinlikleri',
                'db_table': 'coaching_event',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachStudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, help_text='Boş bırakılırsa atama aktif kabul edilir', null=True, verbose_name='Bitiş Tarihi')),
                ('is_primary', models.BooleanField(default=True, help_text='Öğrencinin ana koçu olup olmadığını belirler', verbose_name='Birincil Koç')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='coaching.coachprofile', verbose_name='Koç')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coach_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_assignments', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Koç-Öğrenci Ataması',
                'verbose_name_plural': 'Koç-Öğrenci Atamaları',
                'db_table': 'coaching_student_assignment',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'is_primary'], name='coach_assign_student_idx'), models.Index(fields=['coach', 'is_primary'], name='coach_assign_coach_idx'), models.Index(fields=['start_date', 'end_date'], name='coach_assign_dates_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='coachstudentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_primary', True)), fields=('student',), name='unique_active_primary_coach_per_student'),
        ),
        migrations.AddIndex(
            model_name='coachprofile',
            index=models.Index(fields=['is_active'], name='coach_profile_active_idx'),
        ),
        migrations.AddIndex(
            model_name='coachprofile',
            index=models.Index(fields=['teacher'], name='coach_profile_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='coachingevent',
            index=models.Index(fields=['student', 'event_type'], name='coach_event_student_idx'),
        ),
        migrations.AddIndex(
            model_name='coachingevent',
            index=models.Index(fields=['coach', 'event_type'], name='coach_event_coach_idx'),
        ),
        migrations.AddIndex(
            model_name='coachingevent',
            index=models.Index(fields=['event_date'], name='coach_event_date_idx'),
        ),
        migrations.AddIndex(
            model_name='coachingevent',
            index=models.Index(fields=['status'], name='coach_event_status_idx'),
        ),
    ]
