# Generated by Django 4.2.27 on 2026-02-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Etkinliğe özel ek veriler (homework detayları, meeting notları vb.)', verbose_name='Ek Bilgiler'),
        ),
        migrations.AddField(
            model_name='coachingevent',
            name='reference_id',
            field=models.IntegerField(blank=True, help_text='İlişkili kayıt ID (homework, meeting, goal, risk tabloları için)', null=True, verbose_name='Referans ID'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='is_coach',
            field=models.BooleanField(default=True, help_text='Koç rolü aktif mi? İleride rehber öğretmen, branş öğretmeni ayrımı için', verbose_name='Koç Rolü'),
        ),
        migrations.AddIndex(
            model_name='coachingevent',
            index=models.Index(fields=['reference_id', 'event_type'], name='coach_event_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='coachprofile',
            index=models.Index(fields=['is_coach'], name='coach_profile_is_coach_idx'),
        ),
        migrations.AddIndex(
            model_name='coachstudentassignment',
            index=models.Index(fields=['student'], name='coach_assign_student_solo_idx'),
        ),
        migrations.AddIndex(
            model_name='coachstudentassignment',
            index=models.Index(fields=['coach'], name='coach_assign_coach_solo_idx'),
        ),
        migrations.AddIndex(
            model_name='coachstudentassignment',
            index=models.Index(fields=['is_primary'], name='coach_assign_primary_idx'),
        ),
        migrations.AddIndex(
            model_name='coachstudentassignment',
            index=models.Index(fields=['student', 'end_date'], name='coach_assign_active_idx'),
        ),
    ]
