# Generated by Django 4.2.27 on 2026-02-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_coachingevent_metadata_coachingevent_reference_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coachingevent',
            name='coach_event_ref_idx',
        ),
        migrations.AddField(
            model_name='coachingevent',
            name='event_source',
            field=models.CharField(blank=True, help_text='Etkinlik kaynağı: homework, meeting, goal, risk, system', max_length=50, null=True, verbose_name='Kaynak Tablo'),
        ),
        migrations.AlterField(
            model_name='coachingevent',
            name='reference_id',
            field=models.IntegerField(blank=True, help_text='İlişkili kayıt ID (event_source tablosundaki kayıt)', null=True, verbose_name='Referans ID'),
        ),
        migrations.AddIndex(
            model_name='coachingevent',
            index=models.Index(fields=['event_source', 'reference_id'], name='coach_event_source_ref_idx'),
        ),
    ]
