# Generated by Django 4.2.27 on 2026-02-08 01:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0005_add_profil_foto'),
        ('coaching', '0003_remove_coachingevent_coach_event_ref_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveCache',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='predictive_cache', serialize=False, to='ogrenci.ogrenci', verbose_name='Öğrenci')),
                ('dropout_score', models.IntegerField(db_index=True, default=0, verbose_name='Dropout Skoru')),
                ('dropout_level', models.CharField(default='low', max_length=20, verbose_name='Dropout Seviyesi')),
                ('success_score', models.IntegerField(db_index=True, default=0, verbose_name='Başarı Skoru')),
                ('engagement_score', models.IntegerField(default=0, verbose_name='Etkileşim Skoru')),
                ('weekly_plan', models.JSONField(default=dict, verbose_name='Haftalık Plan Önerisi')),
                ('intervention_required', models.BooleanField(db_index=True, default=False, verbose_name='Müdahale Gerekli')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Tahminsel Cache',
                'verbose_name_plural': "Tahminsel Cache'ler",
                'db_table': 'coaching_predictive_cache',
                'indexes': [models.Index(fields=['dropout_score'], name='coaching_pr_dropout_5e5450_idx'), models.Index(fields=['success_score'], name='coaching_pr_success_b62ad7_idx'), models.Index(fields=['intervention_required'], name='coaching_pr_interve_8ae810_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentFeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Snapshot Tarihi')),
                ('features', models.JSONField(default=dict, verbose_name='Özellikler')),
                ('scores', models.JSONField(default=dict, help_text='dropout_score, success_score, vb.', verbose_name='Skorlar')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_snapshots', to='coaching.coachstudentassignment', verbose_name='Atama')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_snapshots', to='coaching.coachprofile', verbose_name='Koç')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_snapshots', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Öğrenci Özellik Snapshot',
                'verbose_name_plural': "Öğrenci Özellik Snapshot'ları",
                'db_table': 'coaching_student_feature_snapshot',
                'ordering': ['-snapshot_date', '-generated_at'],
                'indexes': [models.Index(fields=['student', 'snapshot_date'], name='coaching_st_student_9180b6_idx'), models.Index(fields=['coach', 'snapshot_date'], name='coaching_st_coach_i_72d375_idx'), models.Index(fields=['snapshot_date'], name='coaching_st_snapsho_5928b1_idx')],
                'unique_together': {('student', 'snapshot_date')},
            },
        ),
    ]
