# Generated by Django 4.2.9 on 2026-03-12 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0009_personel_aktivite_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ogrenci', '0007_add_ek_hizmet_system'),
        ('kurum', '0001_initial'),
        ('coaching', '0004_predictive_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='GorusmeKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorusme_turu', models.CharField(choices=[('ogrenci', 'Öğrenci Görüşmesi'), ('veli', 'Veli Görüşmesi'), ('ic_degerlendirme', 'Koç İç Değerlendirme'), ('motivasyon', 'Motivasyon Görüşmesi'), ('akademik_analiz', 'Akademik Analiz'), ('disiplin', 'Disiplin Görüşmesi'), ('diger', 'Diğer')], default='ogrenci', max_length=30, verbose_name='Görüşme Türü')),
                ('diger_tur_aciklama', models.CharField(blank=True, default='', help_text='Görüşme türü "Diğer" seçildiğinde açıklama', max_length=100, verbose_name='Diğer Tür Açıklaması')),
                ('durum', models.CharField(choices=[('planlandi', 'Planlandı'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi'), ('ertelendi', 'Ertelendi')], default='planlandi', max_length=20, verbose_name='Durum')),
                ('yontem', models.CharField(choices=[('yuz_yuze', 'Yüz Yüze'), ('telefon', 'Telefon'), ('online', 'Online')], default='yuz_yuze', max_length=20, verbose_name='Görüşme Yöntemi')),
                ('oncelik', models.CharField(choices=[('acil', 'Acil'), ('normal', 'Normal'), ('rutin', 'Rutin Takip')], default='normal', max_length=10, verbose_name='Öncelik')),
                ('gorusme_tarihi', models.DateField(verbose_name='Görüşme Tarihi')),
                ('gorusme_saati', models.TimeField(blank=True, null=True, verbose_name='Görüşme Saati')),
                ('sure_dakika', models.PositiveIntegerField(blank=True, help_text='Görüşme süresi dakika cinsinden', null=True, verbose_name='Süre (dk)')),
                ('konu', models.CharField(help_text='Görüşmenin ana konusu / başlığı', max_length=500, verbose_name='Görüşme Konusu')),
                ('notlar', models.TextField(blank=True, default='', help_text='Koçun görüşme sırasında aldığı detaylı notlar', verbose_name='Görüşme Notları')),
                ('motivasyon_skoru', models.PositiveSmallIntegerField(blank=True, help_text='1-5 arası', null=True, verbose_name='Motivasyon Skoru')),
                ('akademik_ozguven_skoru', models.PositiveSmallIntegerField(blank=True, help_text='1-5 arası', null=True, verbose_name='Akademik Özgüven Skoru')),
                ('stres_seviyesi', models.PositiveSmallIntegerField(blank=True, help_text='1-5 arası (1=düşük, 5=yüksek)', null=True, verbose_name='Stres Seviyesi')),
                ('etiketler', models.JSONField(blank=True, default=list, help_text='["dikkat-eksikliği", "uyku-düzeni", "sınav-kaygısı"] gibi', verbose_name='Etiketler')),
                ('veli_ile_paylasilsin', models.BooleanField(default=False, verbose_name='Veli ile Paylaşılsın')),
                ('veli_ozet', models.TextField(blank=True, default='', help_text='Veliye gösterilecek özel özet notu (iç notlar paylaşılmaz)', verbose_name='Veli İçin Özet')),
                ('veli_paylasim_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Veli Paylaşım Tarihi')),
                ('sonraki_gorusme_tarihi', models.DateField(blank=True, help_text='Takip görüşmesi planlandıysa tarihi', null=True, verbose_name='Sonraki Görüşme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('koc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorusme_kayitlari', to='coaching.coachprofile', verbose_name='Koç')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorusme_kayitlari', to='kurum.kurum', verbose_name='Kurum')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorusme_kayitlari', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_gorusmeler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Görüşme Kaydı',
                'verbose_name_plural': 'Görüşme Kayıtları',
                'db_table': 'coaching_gorusme_kaydi',
                'ordering': ['-gorusme_tarihi', '-gorusme_saati'],
            },
        ),
        migrations.CreateModel(
            name='GorusmeKatilimci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('rol', models.CharField(choices=[('veli', 'Veli'), ('rehber', 'Rehber Öğretmen'), ('idareci', 'İdareci'), ('brans_ogretmeni', 'Branş Öğretmeni'), ('diger', 'Diğer')], max_length=30, verbose_name='Katılımcı Rolü')),
                ('gorusme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='katilimcilar', to='coaching.gorusmekaydi', verbose_name='Görüşme')),
                ('personel', models.ForeignKey(blank=True, help_text='Sistemde kayıtlı personel ise bağla', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='katilim_gorusmeleri', to='personel.personel', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Görüşme Katılımcısı',
                'verbose_name_plural': 'Görüşme Katılımcıları',
                'db_table': 'coaching_gorusme_katilimci',
            },
        ),
        migrations.CreateModel(
            name='GorusmeHatirlatma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatirlatma_tarihi', models.DateField(verbose_name='Hatırlatma Tarihi')),
                ('mesaj', models.CharField(max_length=500, verbose_name='Hatırlatma Mesajı')),
                ('tip', models.CharField(choices=[('takip_gorusmesi', 'Takip Görüşmesi'), ('aksiyon_kontrol', 'Aksiyon Kontrol'), ('genel', 'Genel Hatırlatma')], default='genel', max_length=30, verbose_name='Hatırlatma Tipi')),
                ('gonderildi', models.BooleanField(default=False, verbose_name='Gönderildi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gorusme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hatirlatmalar', to='coaching.gorusmekaydi', verbose_name='Görüşme')),
            ],
            options={
                'verbose_name': 'Görüşme Hatırlatması',
                'verbose_name_plural': 'Görüşme Hatırlatmaları',
                'db_table': 'coaching_gorusme_hatirlatma',
                'ordering': ['hatirlatma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='GorusmeDosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='coaching/gorusme_dosyalari/%Y/%m/', verbose_name='Dosya')),
                ('aciklama', models.CharField(blank=True, default='', max_length=255, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gorusme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='coaching.gorusmekaydi', verbose_name='Görüşme')),
            ],
            options={
                'verbose_name': 'Görüşme Dosyası',
                'verbose_name_plural': 'Görüşme Dosyaları',
                'db_table': 'coaching_gorusme_dosya',
            },
        ),
        migrations.CreateModel(
            name='GorusmeAksiyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.CharField(max_length=500, verbose_name='Aksiyon Açıklaması')),
                ('sorumlu', models.CharField(choices=[('ogrenci', 'Öğrenci'), ('koc', 'Koç'), ('veli', 'Veli'), ('idare', 'İdare')], default='ogrenci', max_length=20, verbose_name='Sorumlu')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('tamamlandi', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('tamamlanma_tarihi', models.DateField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gorusme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aksiyonlar', to='coaching.gorusmekaydi', verbose_name='Görüşme')),
            ],
            options={
                'verbose_name': 'Görüşme Aksiyonu',
                'verbose_name_plural': 'Görüşme Aksiyonları',
                'db_table': 'coaching_gorusme_aksiyon',
                'ordering': ['deadline', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gorusmekaydi',
            index=models.Index(fields=['kurum', 'gorusme_tarihi'], name='gorusme_kurum_tarih_idx'),
        ),
        migrations.AddIndex(
            model_name='gorusmekaydi',
            index=models.Index(fields=['ogrenci', 'gorusme_tarihi'], name='gorusme_ogrenci_tarih_idx'),
        ),
        migrations.AddIndex(
            model_name='gorusmekaydi',
            index=models.Index(fields=['koc', 'gorusme_tarihi'], name='gorusme_koc_tarih_idx'),
        ),
        migrations.AddIndex(
            model_name='gorusmekaydi',
            index=models.Index(fields=['durum'], name='gorusme_durum_idx'),
        ),
        migrations.AddIndex(
            model_name='gorusmekaydi',
            index=models.Index(fields=['gorusme_turu'], name='gorusme_tur_idx'),
        ),
        migrations.AddIndex(
            model_name='gorusmekaydi',
            index=models.Index(fields=['oncelik'], name='gorusme_oncelik_idx'),
        ),
    ]
