# Generated by Django 4.2.9 on 2026-02-05 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kurum', '0001_initial'),
        ('egitim_yili', '0001_initial'),
        ('sube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Dönem Adı')),
                ('code', models.CharField(max_length=20, verbose_name='Kısa Kod')),
                ('term_type', models.CharField(choices=[('regular', 'Normal Dönem'), ('summer', 'Yaz Okulu'), ('camp', 'Kamp'), ('exam', 'Sınav Dönemi'), ('coaching', 'Koçluk Dönemi')], default='regular', max_length=20, verbose_name='Dönem Türü')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('order_no', models.IntegerField(default=1, verbose_name='Sıra No')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('program_olusturulabilir', models.BooleanField(default=True, verbose_name='Program Oluşturulabilir')),
                ('yoklama_acik', models.BooleanField(default=True, verbose_name='Yoklama Açık')),
                ('not_girisi_acik', models.BooleanField(default=False, verbose_name='Not Girişi Açık')),
                ('ogrenci_kayit_acik', models.BooleanField(default=True, verbose_name='Öğrenci Kayıt Açık')),
                ('schedule_locked', models.BooleanField(default=False, verbose_name='Program Kilitli')),
                ('auto_generate_enabled', models.BooleanField(default=True, verbose_name='Otomatik Oluşturma Aktif')),
                ('allow_conflict_override', models.BooleanField(default=False, verbose_name='Çakışma Geçersiz Kılma İzni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='kurum.kurum', verbose_name='Kurum')),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Eğitim Dönemi',
                'verbose_name_plural': 'Eğitim Dönemleri',
                'db_table': 'term',
                'ordering': ['order_no', 'start_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('kurum', 'sube', 'egitim_yili', 'code'), name='unique_term_code_per_year'),
        ),
    ]
