# Generated by Django 4.2.9 on 2026-02-26 00:51

import apps.coaching.olcme_degerlendirme.models.session
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ogrenci', '0007_add_ek_hizmet_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sınav Adı')),
                ('exam_type', models.CharField(choices=[('YKS_TYT', 'YKS – TYT (Temel Yeterlilik)'), ('YKS_AYT', 'YKS – AYT (Alan Yeterlilik)'), ('LGS', 'LGS (Liselere Geçiş)'), ('DENEME', 'Deneme Sınavı'), ('KURUM_ICI', 'Kurum İçi Sınav'), ('KONU_TARAMA', 'Konu Tarama'), ('KAZANIM', 'Kazanım Sınavı'), ('OZEL', 'Özel Sınav')], max_length=20, verbose_name='Sınav Türü')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('ANSWER_KEY_READY', 'Cevap Anahtarı Hazır'), ('RESULTS_UPLOADED', 'Sonuçlar Yüklendi'), ('COMPLETED', 'Tamamlandı')], default='DRAFT', max_length=25, verbose_name='Durum')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('akademik_donem', models.CharField(blank=True, help_text='Örn: 2025-2026 / 1. Dönem', max_length=50, verbose_name='Akademik Dönem')),
                ('kampus', models.CharField(blank=True, max_length=100, verbose_name='Kampüs / Şube')),
                ('sinif_grup', models.CharField(blank=True, help_text='Örn: 12-A, TYT Grubu, Tüm Sınıflar', max_length=100, verbose_name='Sınıf / Grup')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='Sınav Tarihi')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Süre (dakika)')),
                ('result_publish_date', models.DateTimeField(blank=True, help_text='Sonuçların öğrencilere görünür olacağı tarih', null=True, verbose_name='Sonuç Yayın Tarihi')),
                ('wrong_answer_penalty', models.DecimalField(decimal_places=2, default='0.25', help_text="0 → ceza yok | 0.25 → 4'te 1 | 0.33 → 3'te 1", max_digits=4, verbose_name='Yanlış Ceza Katsayısı')),
                ('per_section_penalty', models.BooleanField(default=True, help_text='True → yanlışlar sadece kendi bölümündeki doğruları etkiler', verbose_name='Bölüm İçi Ceza')),
                ('score_coefficients', models.JSONField(blank=True, default=dict, help_text='ÖSYM katsayılarını geçersiz kılmak için kullanılır', verbose_name='Puan Katsayıları')),
                ('booklet_type', models.CharField(choices=[('NONE', 'Kitapçık Yok'), ('AB', 'A-B'), ('ABCD', 'A-B-C-D')], default='NONE', max_length=4, verbose_name='Kitapçık Türü')),
                ('booklet_auto_detect', models.BooleanField(default=True, help_text='DAT dosyasından kitapçık harfini otomatik oku', verbose_name='Kitapçık Otomatik Tespit')),
                ('is_locked', models.BooleanField(default=False, help_text='Kilitli sınavda bölüm yapısı ve puanlama değiştirilemez', verbose_name='Kilitli')),
                ('is_template', models.BooleanField(default=False, help_text='Yeni sınavlar oluşturulurken temel olarak kullanılabilir', verbose_name='Şablon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('linked_tyt_exam', models.OneToOneField(blank=True, help_text='AYT sınavı için ÖSYM puan formülünde kullanılacak TYT sınavı', limit_choices_to={'exam_type': 'YKS_TYT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_ayt_exam', to='olcme_degerlendirme.exam', verbose_name='Bağlı TYT Sınavı')),
            ],
            options={
                'verbose_name': 'Sınav',
                'verbose_name_plural': 'Sınavlar',
                'ordering': ['-exam_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_file', models.FileField(blank=True, null=True, upload_to=apps.coaching.olcme_degerlendirme.models.session._session_upload_path, verbose_name='DAT Dosyası')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Orijinal Dosya Adı')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('PROCESSING', 'İşleniyor'), ('COMPLETED', 'Tamamlandı'), ('ERROR', 'Hata')], default='PENDING', max_length=15, verbose_name='Durum')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('first_line_is_header', models.BooleanField(default=True, verbose_name='İlk Satır Başlık')),
                ('delimiter', models.CharField(blank=True, max_length=5, verbose_name='Ayırıcı')),
                ('empty_char', models.CharField(default=' ', max_length=5, verbose_name='Boş Karakter')),
                ('student_id_start', models.PositiveSmallIntegerField(default=0, verbose_name='Öğrenci No Başlangıç')),
                ('student_id_end', models.PositiveSmallIntegerField(default=10, verbose_name='Öğrenci No Bitiş')),
                ('answers_start', models.PositiveSmallIntegerField(default=10, verbose_name='Cevap Başlangıç')),
                ('student_id_field', models.CharField(default='okul_no', max_length=20, verbose_name='Öğrenci No Alanı')),
                ('field_mappings', models.JSONField(blank=True, default=list, verbose_name='Alan Eşleştirmeleri')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Toplam Satır')),
                ('matched_count', models.PositiveIntegerField(default=0, verbose_name='Eşleşen')),
                ('unmatched_count', models.PositiveIntegerField(default=0, verbose_name='Eşleşmeyen')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Hatalı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='olcme_degerlendirme.exam', verbose_name='Sınav')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_exam_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'DAT Oturumu',
                'verbose_name_plural': 'DAT Oturumları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_student_id', models.CharField(blank=True, max_length=50, verbose_name='Ham Öğrenci No')),
                ('raw_student_name', models.CharField(blank=True, max_length=200, verbose_name='Ham Ad Soyad')),
                ('booklet', models.CharField(blank=True, max_length=1, verbose_name='Kitapçık')),
                ('answers', models.JSONField(default=dict, help_text='{soru_no: verilen_cevap} — örn: {"1":"A","2":"C"}', verbose_name='Cevaplar')),
                ('comparison', models.JSONField(default=dict, help_text='{soru_no: {"given":"A","correct":"B","result":"wrong"}}', verbose_name='Karşılaştırma')),
                ('total_correct', models.PositiveSmallIntegerField(default=0, verbose_name='Toplam Doğru')),
                ('total_wrong', models.PositiveSmallIntegerField(default=0, verbose_name='Toplam Yanlış')),
                ('total_empty', models.PositiveSmallIntegerField(default=0, verbose_name='Toplam Boş')),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Toplam Net')),
                ('is_processed', models.BooleanField(default=False, verbose_name='İşlendi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='olcme_degerlendirme.examsession', verbose_name='Oturum')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_answers', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Öğrenci Cevabı',
                'verbose_name_plural': 'Öğrenci Cevapları',
                'ordering': ['session', 'raw_student_id'],
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Ders Kodu')),
                ('name', models.CharField(max_length=100, verbose_name='Ders Adı')),
                ('display_name', models.CharField(blank=True, help_text='Boş bırakılırsa name kullanılır.', max_length=100, verbose_name='Görünen Ad')),
                ('exam_type_filter', models.CharField(choices=[('ALL', 'Tüm Sınav Türleri'), ('YKS_TYT', 'YKS – TYT'), ('YKS_AYT', 'YKS – AYT'), ('LGS', 'LGS')], default='ALL', max_length=20, verbose_name='Sınav Türü')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ünite Adı')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='olcme_degerlendirme.subject', verbose_name='Ders')),
            ],
            options={
                'verbose_name': 'Ünite',
                'verbose_name_plural': 'Üniteler',
                'ordering': ['subject', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Konu Adı')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='olcme_degerlendirme.unit', verbose_name='Ünite')),
            ],
            options={
                'verbose_name': 'Konu',
                'verbose_name_plural': 'Konular',
                'ordering': ['unit', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Kazanım Kodu')),
                ('text', models.TextField(verbose_name='Kazanım Metni')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='olcme_degerlendirme.topic', verbose_name='Konu')),
            ],
            options={
                'verbose_name': 'Kazanım',
                'verbose_name_plural': 'Kazanımlar',
                'ordering': ['topic', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bölüm Adı')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('question_start', models.PositiveSmallIntegerField(default=1, verbose_name='Başlangıç Sorusu')),
                ('question_end', models.PositiveSmallIntegerField(default=1, verbose_name='Bitiş Sorusu')),
                ('question_count', models.PositiveSmallIntegerField(default=0, verbose_name='Soru Sayısı')),
                ('is_sub_section', models.BooleanField(default=False, verbose_name='Alt Bölüm mü?')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='olcme_degerlendirme.exam', verbose_name='Sınav')),
                ('parent_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='olcme_degerlendirme.examsection', verbose_name='Üst Bölüm')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sections', to='olcme_degerlendirme.subject', verbose_name='Kazanım Dersi')),
            ],
            options={
                'verbose_name': 'Sınav Bölümü',
                'verbose_name_plural': 'Sınav Bölümleri',
                'ordering': ['exam', 'order'],
                'unique_together': {('exam', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booklet', models.CharField(blank=True, choices=[('', 'Kitapçıksız'), ('A', 'A Kitapçığı'), ('B', 'B Kitapçığı'), ('C', 'C Kitapçığı'), ('D', 'D Kitapçığı')], default='', max_length=1, verbose_name='Kitapçık')),
                ('is_primary', models.BooleanField(default=True, help_text='Kitapçıksız sınavlarda tek anahtar.', verbose_name='Ana Cevap Anahtarı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_keys', to='olcme_degerlendirme.exam', verbose_name='Sınav')),
            ],
            options={
                'verbose_name': 'Cevap Anahtarı',
                'verbose_name_plural': 'Cevap Anahtarları',
                'unique_together': {('exam', 'booklet')},
            },
        ),
        migrations.CreateModel(
            name='StudentSectionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.PositiveSmallIntegerField(default=0, verbose_name='Doğru')),
                ('wrong', models.PositiveSmallIntegerField(default=0, verbose_name='Yanlış')),
                ('empty', models.PositiveSmallIntegerField(default=0, verbose_name='Boş')),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Net')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='olcme_degerlendirme.examsection', verbose_name='Bölüm')),
                ('student_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_scores', to='olcme_degerlendirme.studentanswer', verbose_name='Öğrenci Cevabı')),
            ],
            options={
                'verbose_name': 'Bölüm Skoru',
                'verbose_name_plural': 'Bölüm Skorları',
                'ordering': ['section__order'],
                'unique_together': {('student_answer', 'section')},
            },
        ),
        migrations.CreateModel(
            name='AnswerKeyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveSmallIntegerField(verbose_name='Soru No')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('EMPTY', 'Boş'), ('INVALID', 'İptal')], max_length=10, verbose_name='Doğru Cevap')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='İptal')),
                ('answer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='olcme_degerlendirme.answerkey', verbose_name='Cevap Anahtarı')),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_key_items', to='olcme_degerlendirme.outcome', verbose_name='Kazanım')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_key_items', to='olcme_degerlendirme.examsection', verbose_name='Bölüm')),
            ],
            options={
                'verbose_name': 'Cevap Anahtarı Satırı',
                'verbose_name_plural': 'Cevap Anahtarı Satırları',
                'ordering': ['answer_key', 'question_number'],
                'unique_together': {('answer_key', 'question_number')},
            },
        ),
    ]
