# Generated by Django 4.2.9 on 2026-02-26 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_yili', '0001_initial'),
        ('kurum', '0001_initial'),
        ('sinif', '0002_sinif_oda'),
        ('sube', '0001_initial'),
        ('egitim_paketleri', '0012_alter_davranispaketi_brut_fiyat_and_more'),
        ('olcme_degerlendirme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='akademik_donem',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='kampus',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='sinif_grup',
        ),
        migrations.AddField(
            model_name='exam',
            name='deneme_hizmeti',
            field=models.ForeignKey(blank=True, limit_choices_to={'hizmet_turu': 'deneme'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olcme_sinavlari', to='egitim_paketleri.ekhizmet', verbose_name='Deneme Hizmeti'),
        ),
        migrations.AddField(
            model_name='exam',
            name='deneme_paketi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olcme_sinavlari', to='egitim_paketleri.deneme', verbose_name='Deneme Paketi'),
        ),
        migrations.AddField(
            model_name='exam',
            name='egitim_yili',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olcme_sinavlari', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='kurum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olcme_sinavlari', to='kurum.kurum', verbose_name='Kurum'),
        ),
        migrations.AddField(
            model_name='exam',
            name='siniflar',
            field=models.ManyToManyField(blank=True, related_name='olcme_sinavlari', to='sinif.sinif', verbose_name='Sınıflar'),
        ),
        migrations.AddField(
            model_name='exam',
            name='sube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olcme_sinavlari', to='sube.sube', verbose_name='Şube'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='booklet_auto_detect',
            field=models.BooleanField(default=True, verbose_name='Kitapçık Otomatik Tespit'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Kilitli'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='Şablon'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='linked_tyt_exam',
            field=models.OneToOneField(blank=True, limit_choices_to={'exam_type': 'YKS_TYT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_ayt_exam', to='olcme_degerlendirme.exam'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='per_section_penalty',
            field=models.BooleanField(default=True, verbose_name='Bölüm İçi Ceza'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='result_publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sonuç Yayın Tarihi'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='score_coefficients',
            field=models.JSONField(blank=True, default=dict, verbose_name='Puan Katsayıları'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='wrong_answer_penalty',
            field=models.DecimalField(decimal_places=2, default='0.25', max_digits=4, verbose_name='Yanlış Ceza Katsayısı'),
        ),
        migrations.AlterField(
            model_name='examsection',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='olcme_degerlendirme.exam'),
        ),
        migrations.AlterField(
            model_name='examsection',
            name='parent_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='olcme_degerlendirme.examsection'),
        ),
        migrations.AlterField(
            model_name='examsection',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sections', to='olcme_degerlendirme.subject'),
        ),
        migrations.CreateModel(
            name='ExamSessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örn: 1. Oturum, Sabah Oturumu', max_length=100, verbose_name='Oturum Adı')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Süre (dakika)')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Başlangıç Saati')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='olcme_degerlendirme.exam', verbose_name='Sınav')),
                ('sections', models.ManyToManyField(blank=True, help_text='Bu oturuma ait ders bölümleri', related_name='session_assignments', to='olcme_degerlendirme.examsection', verbose_name='Bölümler')),
            ],
            options={
                'verbose_name': 'Sınav Oturumu',
                'verbose_name_plural': 'Sınav Oturumları',
                'ordering': ['exam', 'order'],
                'unique_together': {('exam', 'name')},
            },
        ),
    ]
