# Generated by Django 4.2.9 on 2026-02-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcme_degerlendirme', '0002_remove_exam_akademik_donem_remove_exam_kampus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='wrong_answer_penalty',
        ),
        migrations.AddField(
            model_name='exam',
            name='wrong_answer_count',
            field=models.PositiveSmallIntegerField(default=4, help_text='Kaç yanlış cevap 1 doğruyu götürür? (Örn: 4 → 4 yanlış 1 doğruyu götürür, 0 → ceza yok)', verbose_name='Yanlış Düzeltme Sayısı'),
        ),
        migrations.AddField(
            model_name='examsessionmodel',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Bitiş Saati'),
        ),
        migrations.AddField(
            model_name='examsessionmodel',
            name='schedule_preference',
            field=models.CharField(choices=[('HAFTA_ICI', 'Hafta İçi'), ('HAFTA_SONU', 'Hafta Sonu'), ('FARKETMEZ', 'Farketmez')], default='FARKETMEZ', help_text='Öğrenci bu oturumu hafta içi mi, hafta sonu mu tercih edebilir?', max_length=12, verbose_name='Zaman Tercihi'),
        ),
        migrations.AddField(
            model_name='examsessionmodel',
            name='session_date',
            field=models.DateField(blank=True, help_text='Bu oturumun yapılacağı gün', null=True, verbose_name='Oturum Tarihi'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='per_section_penalty',
            field=models.BooleanField(default=True, verbose_name='Bölüm Bazlı Düzeltme'),
        ),
        migrations.AlterField(
            model_name='examsessionmodel',
            name='name',
            field=models.CharField(help_text='Örn: 1. Oturum, Cumartesi Sabah', max_length=100, verbose_name='Oturum Adı'),
        ),
    ]
