# Generated by Django 4.2.9 on 2026-02-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcme_degerlendirme', '0003_session_date_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='answer_key_publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cevap Anahtarı Yayın Tarihi'),
        ),
    ]
