# Generated by Django 4.2.9 on 2026-02-27 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olcme_degerlendirme', '0004_answer_key_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Şablon Adı')),
                ('exam_type', models.CharField(choices=[('YKS_TYT', 'YKS – TYT'), ('YKS_AYT', 'YKS – AYT'), ('LGS', 'LGS'), ('DENEME', 'Deneme Sınavı'), ('KURUM_ICI', 'Kurum İçi Sınav'), ('KONU_TARAMA', 'Konu Tarama'), ('KAZANIM', 'Kazanım Sınavı'), ('OZEL', 'Özel Sınav')], max_length=20, verbose_name='Sınav Türü')),
                ('mappings', models.JSONField(default=list, help_text='FieldMapping dizisi: [{field, start, end, label}, ...]', verbose_name='Alan Eşleştirmeleri')),
                ('first_line_is_header', models.BooleanField(default=False, verbose_name='İlk Satır Başlık')),
                ('student_id_field', models.CharField(default='ogrenci_no', max_length=20, verbose_name='Kimlik Alanı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_templates', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Eşleştirme Şablonu',
                'verbose_name_plural': 'Eşleştirme Şablonları',
                'ordering': ['-updated_at'],
            },
        ),
    ]
