# Generated by Django 4.2.9 on 2026-02-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcme_degerlendirme', '0005_mapping_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkeyitem',
            name='b_question_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Bu sorunun B kitapçığındaki soru numarası', null=True, verbose_name='B Kitapçığı Soru No'),
        ),
    ]
