# Generated by Django 4.2.9 on 2026-02-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcme_degerlendirme', '0006_answer_key_item_b_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='booklet_auto_detected',
            field=models.BooleanField(default=False, help_text="Kitapçık bilgisi DAT dosyasında yoksa, en yüksek net'e göre otomatik seçildi.", verbose_name='Kitapçık Otomatik Tespit'),
        ),
    ]
