# Generated by Django 4.2.9 on 2026-02-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcme_degerlendirme', '0007_student_answer_booklet_auto_detected'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('session', 'student'), name='unique_session_student'),
        ),
    ]
