# Generated by Django 4.2.9 on 2026-02-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcme_degerlendirme', '0008_alter_studentanswer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='match_method',
            field=models.CharField(blank=True, help_text='tc, name_exact, id, name, manual', max_length=20, verbose_name='Eşleşme Yöntemi'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='match_score',
            field=models.FloatField(default=0.0, help_text='0.0-1.0 arası', verbose_name='Eşleşme Skoru'),
        ),
    ]
