# Generated by Django 4.2.9 on 2026-03-01 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olcme_degerlendirme', '0010_restructure_curriculum_add_suboutcome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outcome',
            options={'ordering': ['topic', 'order'], 'verbose_name': 'Kazanim', 'verbose_name_plural': 'Kazanimlar'},
        ),
        migrations.AlterModelOptions(
            name='suboutcome',
            options={'ordering': ['outcome', 'order'], 'verbose_name': 'Alt Kazanim', 'verbose_name_plural': 'Alt Kazanimlar'},
        ),
        migrations.AddField(
            model_name='answerkeyitem',
            name='imported_outcome_text',
            field=models.CharField(blank=True, default='', help_text='Cevap anahtarı import edilirken yapıştırılan orijinal kazanım kodu veya metni', max_length=500, verbose_name='Girilen Kazanım Metni'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kazanim Kodu'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sira'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='text',
            field=models.TextField(verbose_name='Kazanim Metni'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='display_name',
            field=models.CharField(blank=True, help_text='Bos birakilirsa name kullanilir.', max_length=100, verbose_name='Gorunen Ad'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='exam_type_filter',
            field=models.CharField(choices=[('ALL', 'Tum Sinav Turleri'), ('YKS_TYT', 'YKS - TYT'), ('YKS_AYT', 'YKS - AYT'), ('LGS', 'LGS')], default='ALL', max_length=20, verbose_name='Sinav Turu'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ders Adi'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sira'),
        ),
        migrations.AlterField(
            model_name='suboutcome',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Alt Kazanim Kodu'),
        ),
        migrations.AlterField(
            model_name='suboutcome',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sira'),
        ),
        migrations.AlterField(
            model_name='suboutcome',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_outcomes', to='olcme_degerlendirme.outcome', verbose_name='Kazanim'),
        ),
        migrations.AlterField(
            model_name='suboutcome',
            name='text',
            field=models.TextField(verbose_name='Alt Kazanim Metni'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='code',
            field=models.CharField(blank=True, help_text='Or: 9.1, 9.2', max_length=30, verbose_name='Konu Kodu'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Konu Adi'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sira'),
        ),
    ]
