# Generated by Django 4.2.9 on 2026-03-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcme_degerlendirme', '0011_add_imported_outcome_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examsection',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='examsection',
            constraint=models.UniqueConstraint(fields=('exam', 'name', 'parent_section'), name='unique_section_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='examsection',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_section__isnull', True)), fields=('exam', 'name'), name='unique_main_section_name'),
        ),
    ]
