# Generated by Django 4.2.9 on 2026-08-28 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_tanimlari', '0011_ders_kisa_ad'),
        ('egitim_paketleri', '0017_remove_yayinpaketi_dahil_denemeler_and_more'),
        ('ogrenci', '0016_ogrenci_not_and_audit'),
        ('olcme_degerlendirme', '0013_olcme_puan_ayar_and_exam_puan_yili'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Salon Adı')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='Kapasite')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='olcme_degerlendirme.exam')),
            ],
            options={
                'verbose_name': 'Sınav Salonu',
                'verbose_name_plural': 'Sınav Salonları',
                'ordering': ['exam', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('auto', 'Otomatik'), ('manual', 'Manuel')], default='auto', max_length=10)),
                ('seat_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sıra')),
                ('desk_no', models.CharField(blank=True, max_length=20, verbose_name='Masa / Koltuk')),
                ('attendance', models.CharField(blank=True, choices=[('', 'Belirsiz'), ('present', 'Geldi'), ('absent', 'Gelmedi')], default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deneme_paketi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='egitim_paketleri.deneme')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='olcme_degerlendirme.exam')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='olcme_degerlendirme.examroom')),
                ('sinif_seviyesi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='egitim_tanimlari.sinifseviyesi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olcme_exam_participations', to='ogrenci.ogrenci')),
            ],
            options={
                'verbose_name': 'Sınav Katılımcısı',
                'verbose_name_plural': 'Sınav Katılımcıları',
                'ordering': ['room__order', 'seat_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deneme_paketi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olcme_audiences', to='egitim_paketleri.deneme')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='olcme_degerlendirme.exam')),
                ('sinif_seviyesi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olcme_audiences', to='egitim_tanimlari.sinifseviyesi')),
            ],
            options={
                'verbose_name': 'Sınav Kitle Kuralı',
                'verbose_name_plural': 'Sınav Kitle Kuralları',
            },
        ),
        migrations.AddConstraint(
            model_name='examroom',
            constraint=models.UniqueConstraint(fields=('exam', 'name'), name='unique_exam_room_name'),
        ),
        migrations.AddConstraint(
            model_name='examparticipant',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_exam_participant'),
        ),
        migrations.AddConstraint(
            model_name='examparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False), ('seat_no__isnull', False)), fields=('exam', 'room', 'seat_no'), name='unique_exam_room_seat'),
        ),
        migrations.AddConstraint(
            model_name='examaudience',
            constraint=models.UniqueConstraint(fields=('exam', 'sinif_seviyesi', 'deneme_paketi'), name='unique_exam_audience_row'),
        ),
    ]
