# Generated by Django 4.2.27 on 2026-09-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcme_degerlendirme', '0028_lgs_booklet_coefficients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='curriculum_band',
            field=models.CharField(blank=True, choices=[('YKS', 'YKS (9–12)'), ('LGS', 'LGS (5–8)')], default='', help_text='YKS 9–12 veya LGS 5–8. TYT/AYT/LGS/LGS_7 türünde otomatik kilitlenir.', max_length=8, verbose_name='Müfredat düzeyi'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='include_optional_philosophy',
            field=models.BooleanField(default=True, help_text='TYT ve AYT’de Din Kültürü’nden hemen sonra gelen 5 soruluk seçmeli felsefe. Varsayılan: dahil. Sözel puan hesaplamasında kullanılır.', verbose_name='Felsefe (Seçmeli)'),
        ),
    ]
