# Generated by Django 4.2.27 on 2026-09-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcme_degerlendirme', '0035_booklet_type_default_ab'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscheduleddispatch',
            name='send_options',
            field=models.JSONField(blank=True, default=dict, help_text='Arka plan gönderimi için seçim: answer_ids, include_veli, include_student.'),
        ),
    ]
