# Generated by Django 4.2.9 on 2026-01-30 22:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egitim_yili', '0001_initial'),
        ('kurum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_kimlik_no', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='TC Kimlik No 11 haneli olmalıdır', regex='^\\d{11}$')], verbose_name='TC Kimlik No')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyad')),
                ('dogum_tarihi', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('cinsiyet', models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kadın')], max_length=1, null=True, verbose_name='Cinsiyet')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('adres', models.TextField(blank=True, verbose_name='Adres')),
                ('veli_ad_soyad', models.CharField(blank=True, max_length=200, verbose_name='Veli Ad Soyad')),
                ('veli_telefon', models.CharField(blank=True, max_length=20, verbose_name='Veli Telefon')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
                'db_table': 'ogrenci',
                'ordering': ['soyad', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='OgrenciKayit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kayit_tarihi', models.DateField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogrenci_kayitlari', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogrenci_kayitlari', to='kurum.kurum', verbose_name='Kurum')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kayitlar', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Öğrenci Kaydı',
                'verbose_name_plural': 'Öğrenci Kayıtları',
                'db_table': 'ogrenci_kayit',
                'ordering': ['-egitim_yili', 'ogrenci__soyad', 'ogrenci__ad'],
            },
        ),
    ]
