# Generated by Django 4.2.9 on 2026-01-30 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sinif', '0001_initial'),
        ('sube', '0001_initial'),
        ('ogrenci', '0001_initial'),
        ('kurum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrencikayit',
            name='sinif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kayitlar', to='sinif.sinif', verbose_name='Sınıf'),
        ),
        migrations.AddField(
            model_name='ogrencikayit',
            name='sube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogrenci_kayitlari', to='sube.sube', verbose_name='Şube'),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='kurum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogrenciler', to='kurum.kurum', verbose_name='Kurum'),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='sube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogrenciler', to='sube.sube', verbose_name='Şube'),
        ),
        migrations.AddIndex(
            model_name='ogrencikayit',
            index=models.Index(fields=['kurum', 'sube', 'egitim_yili', 'aktif_mi'], name='ogrenci_kay_kurum_i_827f61_idx'),
        ),
        migrations.AddIndex(
            model_name='ogrencikayit',
            index=models.Index(fields=['sinif', 'aktif_mi'], name='ogrenci_kay_sinif_i_0a9ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='ogrencikayit',
            index=models.Index(fields=['ogrenci', 'egitim_yili'], name='ogrenci_kay_ogrenci_b610e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='ogrencikayit',
            constraint=models.UniqueConstraint(fields=('ogrenci', 'egitim_yili'), name='unique_ogrenci_per_year'),
        ),
        migrations.AddIndex(
            model_name='ogrenci',
            index=models.Index(fields=['kurum', 'sube', 'aktif_mi'], name='ogrenci_kurum_i_bb40c7_idx'),
        ),
        migrations.AddIndex(
            model_name='ogrenci',
            index=models.Index(fields=['tc_kimlik_no'], name='ogrenci_tc_kiml_41fe2d_idx'),
        ),
        migrations.AddIndex(
            model_name='ogrenci',
            index=models.Index(fields=['ad', 'soyad'], name='ogrenci_ad_4b99e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='ogrenci',
            constraint=models.UniqueConstraint(condition=models.Q(('tc_kimlik_no__isnull', False)), fields=('kurum', 'tc_kimlik_no'), name='unique_kurum_tc'),
        ),
    ]
