# Generated by Django 4.2.27 on 2026-01-31 19:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ogrenci', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='kayit_turu',
            field=models.CharField(choices=[('asil', 'Asil'), ('misafir', 'Misafir'), ('yaz', 'Yaz Programı')], default='asil', max_length=20, verbose_name='Kayıt Türü'),
        ),
        migrations.AddField(
            model_name='ogrencikayit',
            name='geldigi_okul',
            field=models.CharField(blank=True, max_length=200, verbose_name='Geldiği Okul'),
        ),
        migrations.AddField(
            model_name='ogrencikayit',
            name='giris_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Giriş Tarihi'),
        ),
        migrations.AddField(
            model_name='ogrencikayit',
            name='giris_turu',
            field=models.CharField(choices=[('yeni_kayit', 'Yeni Kayıt'), ('kayit_yenileme', 'Kayıt Yenileme'), ('zorunlu_kayit', 'Zorunlu Kayıt'), ('on_kayit', 'Ön Kayıt'), ('kayit_gorusmesi', 'Kayıt Görüşmesi')], default='yeni_kayit', max_length=20, verbose_name='Giriş Türü'),
        ),
        migrations.AddField(
            model_name='ogrencikayit',
            name='kaydi_alan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaydettiği_ogrenciler', to=settings.AUTH_USER_MODEL, verbose_name='Kaydı Alan'),
        ),
        migrations.AddField(
            model_name='ogrencikayit',
            name='okul_no',
            field=models.CharField(blank=True, max_length=5, verbose_name='Okul Numarası'),
        ),
        migrations.AddField(
            model_name='ogrencikayit',
            name='referans',
            field=models.CharField(blank=True, max_length=200, verbose_name='Referans Kişi/Kurum'),
        ),
        migrations.CreateModel(
            name='OgrenciVeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veli_turu', models.CharField(choices=[('anne', 'Anne'), ('baba', 'Baba'), ('kiz_kardes', 'Kız Kardeş'), ('erkek_kardes', 'Erkek Kardeş'), ('dayi_amca', 'Dayı / Amca'), ('hala_teyze', 'Hala / Teyze'), ('egitim_masraf', 'Eğitim Masraflarını Karşılayan'), ('diger', 'Diğer')], max_length=20, verbose_name='Veli Türü')),
                ('tc_kimlik_no', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='TC Kimlik No 11 haneli olmalıdır', regex='^\\d{11}$')], verbose_name='TC Kimlik No')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyad')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('sms_bildirimleri', models.JSONField(blank=True, default=list, help_text='Hangi konularda SMS alacak: devamsizlik, odeme, duyuru vs.', verbose_name='SMS Bildirimleri')),
                ('egitim_seviyesi', models.CharField(blank=True, max_length=100, verbose_name='Eğitim Seviyesi')),
                ('meslek', models.CharField(blank=True, max_length=100, verbose_name='Meslek')),
                ('calistigi_kurum', models.CharField(blank=True, max_length=200, verbose_name='Çalıştığı Kurum')),
                ('ogrenci_kendi_velisi', models.BooleanField(default=False, verbose_name='Öğrenci Kendi Velisi')),
                ('varsayilan', models.BooleanField(default=False, verbose_name='Varsayılan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veliler', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Öğrenci Velisi',
                'verbose_name_plural': 'Öğrenci Velileri',
                'db_table': 'ogrenci_veli',
                'ordering': ['-varsayilan', 'veli_turu'],
            },
        ),
        migrations.CreateModel(
            name='OgrenciEgitimPaketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paket_turu', models.CharField(choices=[('grup_dersi', 'Grup Dersi'), ('ozel_ders', 'Özel Ders'), ('deneme', 'Deneme')], max_length=20, verbose_name='Paket Türü')),
                ('paket_id', models.IntegerField(verbose_name='Paket ID')),
                ('paket_adi', models.CharField(blank=True, max_length=200, verbose_name='Paket Adı')),
                ('kayit_tarihi', models.DateField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('baslangic_tarihi', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egitim_paketleri_kayit', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Öğrenci Eğitim Paketi',
                'verbose_name_plural': 'Öğrenci Eğitim Paketleri',
                'db_table': 'ogrenci_egitim_paketi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OgrenciAdres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres_turu', models.CharField(choices=[('ev', 'Ev'), ('is', 'İş'), ('diger', 'Diğer')], default='ev', max_length=10, verbose_name='Adres Türü')),
                ('adres', models.TextField(verbose_name='Adres')),
                ('il', models.CharField(blank=True, max_length=50, verbose_name='İl')),
                ('ilce', models.CharField(blank=True, max_length=50, verbose_name='İlçe')),
                ('posta_kodu', models.CharField(blank=True, max_length=10, verbose_name='Posta Kodu')),
                ('varsayilan', models.BooleanField(default=False, verbose_name='Varsayılan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresler', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Öğrenci Adresi',
                'verbose_name_plural': 'Öğrenci Adresleri',
                'db_table': 'ogrenci_adres',
                'ordering': ['-varsayilan', '-created_at'],
            },
        ),
    ]
