# Generated by Django 4.2.27 on 2026-02-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0003_ogrenci_kayit_turu_ogrencikayit_geldigi_okul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='veli_yakinlik',
            field=models.CharField(blank=True, choices=[('anne', 'Anne'), ('baba', 'Baba'), ('kardes', 'Kardeş'), ('dede', 'Dede'), ('nine', 'Nine'), ('amca', 'Amca'), ('dayi', 'Dayı'), ('hala', 'Hala'), ('teyze', 'Teyze'), ('vasi', 'Vasi'), ('diger', 'Diğer')], max_length=20, verbose_name='Yakınlık Derecesi'),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='kayit_turu',
            field=models.CharField(choices=[('asil', 'Asil'), ('misafir', 'Misafir'), ('yaz_programi', 'Yaz Programı')], default='asil', max_length=20, verbose_name='Kayıt Türü'),
        ),
        migrations.AlterField(
            model_name='ogrenciegitimpaketi',
            name='paket_turu',
            field=models.CharField(choices=[('grup_dersi', 'Grup Dersi'), ('ozel_ders', 'Özel Ders'), ('deneme', 'Deneme'), ('davranis', 'Davranış')], max_length=20, verbose_name='Paket Türü'),
        ),
    ]
