# Generated by Django 4.2.27 on 2026-02-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0004_add_veli_yakinlik'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='profil_foto',
            field=models.ImageField(blank=True, null=True, upload_to='ogrenci/profil/', verbose_name='Profil Fotoğrafı'),
        ),
    ]
