# Generated by Django 4.2.9 on 2026-02-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0005_add_profil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrencikayit',
            name='okul_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Okul Numarası'),
        ),
    ]
