# Generated by Django 4.2.9 on 2026-02-19 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_paketleri', '0008_add_ek_hizmet_system'),
        ('egitim_yili', '0001_initial'),
        ('ogrenci', '0006_increase_okul_no_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OgrenciEkHizmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiyat', models.DecimalField(decimal_places=2, default=0, help_text='Satış anındaki fiyat. Dahil ise 0.', max_digits=10, verbose_name='Fiyat')),
                ('dahil_mi', models.BooleanField(default=False, help_text='True ise ücretsiz — eğitim paketine (grup dersi) dahildir', verbose_name='Pakete Dahil')),
                ('kaynak_paket_turu', models.CharField(blank=True, help_text='Dahil olduğu paket türü: grup_dersi, ozel_ders vb.', max_length=20, verbose_name='Kaynak Paket Türü')),
                ('kaynak_paket_id', models.IntegerField(blank=True, help_text="Dahil olduğu paketin DB ID'si", null=True, verbose_name='Kaynak Paket ID')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('baslangic_tarihi', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('egitim_yili', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ogrenci_ek_hizmetleri', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('ek_hizmet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ogrenci_kayitlari', to='egitim_paketleri.ekhizmet', verbose_name='Ek Hizmet')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ek_hizmetler', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Öğrenci Ek Hizmet',
                'verbose_name_plural': 'Öğrenci Ek Hizmetleri',
                'db_table': 'ogrenci_ek_hizmet',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ogrenci', 'aktif_mi'], name='ogrenci_ek__ogrenci_635882_idx'), models.Index(fields=['ek_hizmet', 'aktif_mi'], name='ogrenci_ek__ek_hizm_6af278_idx'), models.Index(fields=['egitim_yili', 'aktif_mi'], name='ogrenci_ek__egitim__e69a0e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ogrenciekhizmet',
            constraint=models.UniqueConstraint(condition=models.Q(('aktif_mi', True)), fields=('ogrenci', 'ek_hizmet'), name='unique_ogrenci_ek_hizmet_aktif'),
        ),
    ]
