# Generated by Django 4.2.27 on 2026-06-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0007_add_ek_hizmet_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='kayit_turu',
            field=models.CharField(default='asil', help_text='Kurum Yönetimi > Kayıt Tanımları lookup kodu', max_length=50, verbose_name='Kayıt Türü'),
        ),
    ]
