# Generated by Django 4.2.27 on 2026-07-02 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinif', '0002_sinif_oda'),
        ('ogrenci', '0008_kayit_turu_lookup_flexible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrencikayit',
            name='sinif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kayitlar', to='sinif.sinif', verbose_name='Sınıf'),
        ),
    ]
