# Generated by Django 4.2.27 on 2026-07-06 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kimlik', '0001_initial'),
        ('ogrenci', '0010_ogrencikayit_sinif_seviyesi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='kisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ogrenci_kayitlari_kisi', to='kimlik.kisi', verbose_name='Merkezi Kişi'),
        ),
        migrations.AddField(
            model_name='ogrenciveli',
            name='kisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veli_kayitlari', to='kimlik.kisi', verbose_name='Merkezi Kişi'),
        ),
    ]
