# Generated by Django 4.2.9 on 2026-07-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0012_ogrencikayit_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenciegitimpaketi',
            name='dahil_mi',
            field=models.BooleanField(default=False, help_text='True ise ücretsiz — bir grup dersi/premium pakete dahildir', verbose_name='Pakete Dahil'),
        ),
        migrations.AddField(
            model_name='ogrenciegitimpaketi',
            name='kaynak_paket_id',
            field=models.IntegerField(blank=True, help_text="Dahil olduğu paketin DB ID'si", null=True, verbose_name='Kaynak Paket ID'),
        ),
        migrations.AddField(
            model_name='ogrenciegitimpaketi',
            name='kaynak_paket_turu',
            field=models.CharField(blank=True, help_text='Dahil olduğu paket türü: grup_dersi, premium vb.', max_length=20, verbose_name='Kaynak Paket Türü'),
        ),
        migrations.AlterField(
            model_name='ogrenciegitimpaketi',
            name='paket_turu',
            field=models.CharField(choices=[('grup_dersi', 'Grup Dersi'), ('ozel_ders', 'Özel Ders'), ('premium', 'Premium Paket'), ('yayin', 'Yayın Paketi'), ('deneme', 'Deneme'), ('davranis', 'Davranış')], max_length=20, verbose_name='Paket Türü'),
        ),
    ]
