# Generated by Django 4.2.27 on 2026-07-13 19:02

from django.db import migrations, models


def backfill_telefonlar(apps, schema_editor):
    OgrenciVeli = apps.get_model('ogrenci', 'OgrenciVeli')
    for veli in OgrenciVeli.objects.all().iterator():
        phone = (veli.telefon or '').strip()
        if not phone:
            continue
        if veli.telefonlar:
            continue
        veli.telefonlar = [{
            'numara': phone,
            'etiket': 'Cep',
            'whatsapp_varsayilan': True,
        }]
        veli.save(update_fields=['telefonlar'])


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0014_ogrencikayit_alan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenciveli',
            name='telefonlar',
            field=models.JSONField(blank=True, default=list, help_text='[{"numara":"05xx","etiket":"Cep","whatsapp_varsayilan":true}] — telefon alanı WhatsApp varsayılanıdır.', verbose_name='Telefon Numaraları'),
        ),
        migrations.RunPython(backfill_telefonlar, migrations.RunPython.noop),
    ]
