# Generated by Django 4.2.9 on 2026-08-07 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ogrenci', '0015_veli_telefonlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='OgrenciNot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Başlık')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('kategori', models.CharField(choices=[('finans', 'Finans'), ('egitim', 'Eğitim'), ('kocluk', 'Koçluk'), ('veli_iletisimi', 'Veli İletişimi'), ('devamsizlik', 'Devamsızlık'), ('sozlesme', 'Sözleşme'), ('genel', 'Genel'), ('diger', 'Diğer')], db_index=True, default='genel', max_length=32, verbose_name='Kategori')),
                ('not_zamani', models.DateTimeField(db_index=True, help_text='Kullanıcı tarafından düzenlenebilir olay tarihi/saati', verbose_name='Not Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Düzenleme Tarihi')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Silindi')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ogrenci_notlari_created', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ogrenci_notlari_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Silen')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notlar', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ogrenci_notlari_updated', to=settings.AUTH_USER_MODEL, verbose_name='Son Düzenleyen')),
            ],
            options={
                'verbose_name': 'Öğrenci Notu',
                'verbose_name_plural': 'Öğrenci Notları',
                'db_table': 'ogrenci_not',
                'ordering': ['-not_zamani', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OgrenciNotAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.IntegerField(db_index=True, verbose_name='Not ID')),
                ('baslik_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Başlık (anlık)')),
                ('action', models.CharField(choices=[('created', 'Oluşturuldu'), ('updated', 'Düzenlendi'), ('deleted', 'Silindi')], max_length=20, verbose_name='İşlem')),
                ('performed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='İşlem Zamanı')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Eski Değerler')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Yeni Değerler')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Açıklama')),
                ('not_kaydi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ogrenci.ogrencinot', verbose_name='Not')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_audit_logs', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ogrenci_not_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
            ],
            options={
                'verbose_name': 'Öğrenci Not Audit',
                'verbose_name_plural': 'Öğrenci Not Audit Logları',
                'db_table': 'ogrenci_not_audit_log',
                'ordering': ['-performed_at', '-id'],
                'indexes': [models.Index(fields=['note_id', '-performed_at'], name='ogrenci_not_note_id_0d8785_idx'), models.Index(fields=['ogrenci', '-performed_at'], name='ogrenci_not_ogrenci_aca349_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ogrencinot',
            index=models.Index(fields=['ogrenci', 'is_deleted', '-not_zamani'], name='ogrenci_not_ogrenci_fdca01_idx'),
        ),
        migrations.AddIndex(
            model_name='ogrencinot',
            index=models.Index(fields=['ogrenci', 'kategori', 'is_deleted'], name='ogrenci_not_ogrenci_fe7ee4_idx'),
        ),
    ]
