# Generated by Django 4.2.27 on 2026-07-25 18:59

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
        ('egitim_yili', '0001_initial'),
        ('egitim_tanimlari', '0011_ders_kisa_ad'),
        ('sube', '0003_sube_branding'),
        ('oda', '0001_initial'),
        ('personel', '0018_ozel_ders_module'),
        ('ogrenci', '0015_veli_telefonlar'),
        ('egitim_paketleri', '0017_remove_yayinpaketi_dahil_denemeler_and_more'),
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirebirDersOturumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('oturum_turu', models.CharField(choices=[('OZEL', 'Özel Ders'), ('TELAFI', 'Telafi'), ('EK', 'Ek Ders'), ('ETUT', 'Etüt')], db_index=True, default='OZEL', max_length=16)),
                ('durum', models.CharField(choices=[('PLANLANDI', 'Planlandı'), ('ISLENDI', 'İşlendi'), ('IPTAL', 'İptal'), ('TELAFI_EDILECEK', 'Telafi Edilecek'), ('OGRENCI_GELMEDI', 'Öğrenci Gelmedi'), ('OGRETMEN_GELMEDI', 'Öğretmen Gelmedi'), ('ONLINE', 'Online')], db_index=True, default='PLANLANDI', max_length=24)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_birebir_oturumlar', to=settings.AUTH_USER_MODEL)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='birebir_oturumlar', to='egitim_tanimlari.ders')),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birebir_oturumlar', to='egitim_yili.egitimyili')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birebir_oturumlar', to='kurum.kurum')),
                ('oda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birebir_oturumlar', to='oda.oda')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birebir_oturumlar', to='ogrenci.ogrenci')),
                ('ogretmen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='birebir_oturumlar', to='personel.personel')),
            ],
            options={
                'verbose_name': 'Birebir Ders Oturumu',
                'verbose_name_plural': 'Birebir Ders Oturumları',
                'db_table': 'ozel_ders_birebir_oturum',
                'ordering': ['session_date', 'start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UcretKurali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oturum_turu', models.CharField(choices=[('OZEL', 'Özel Ders'), ('TELAFI', 'Telafi'), ('EK', 'Ek Ders'), ('ETUT', 'Etüt')], max_length=16)),
                ('sozlesme_turu', models.CharField(help_text='TAM_ZAMANLI / DERS_UCRETLI / KARMA', max_length=20)),
                ('mesai_modu', models.CharField(choices=[('MESAI_DISI_SADECE', 'Sadece mesai dışı'), ('HER_ZAMAN', 'Her zaman ücretlendir'), ('HICBIR_ZAMAN', 'Hiçbir zaman ücretlendirme')], max_length=24)),
                ('online_ucretlendir', models.BooleanField(default=True, help_text='ONLINE durumundaki oturumlar ücretlendirilsin mi')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kurum', models.ForeignKey(blank=True, help_text='Boş = global varsayılan', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ozel_ders_ucret_kurallari', to='kurum.kurum')),
                ('sube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ozel_ders_ucret_kurallari', to='sube.sube')),
            ],
            options={
                'verbose_name': 'Ücret Kuralı',
                'verbose_name_plural': 'Ücret Kuralları',
                'db_table': 'ozel_ders_ucret_kurali',
                'ordering': ['kurum_id', 'sube_id', 'oturum_turu', 'sozlesme_turu'],
            },
        ),
        migrations.CreateModel(
            name='PremiumPaketDersKota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haftalik_adet', models.PositiveSmallIntegerField(default=1)),
                ('varsayilan_sure_dk', models.PositiveIntegerField(default=60)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_ders_kotalari', to='egitim_tanimlari.ders')),
                ('premium_paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ders_kotalari', to='egitim_paketleri.premiumpaket')),
            ],
            options={
                'verbose_name': 'Premium Paket Ders Kotası',
                'verbose_name_plural': 'Premium Paket Ders Kotaları',
                'db_table': 'ozel_ders_premium_ders_kota',
                'ordering': ['premium_paket_id', 'ders_id'],
            },
        ),
        migrations.CreateModel(
            name='BirebirOgrenciProgrami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField(blank=True, null=True)),
                ('durum', models.CharField(choices=[('AKTIF', 'Aktif'), ('PASIF', 'Pasif')], db_index=True, default='AKTIF', max_length=16)),
                ('notlar', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_birebir_programlar', to=settings.AUTH_USER_MODEL)),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birebir_programlar', to='egitim_yili.egitimyili')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birebir_programlar', to='kurum.kurum')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birebir_programlar', to='ogrenci.ogrenci')),
                ('ogrenci_egitim_paketi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birebir_programlar', to='ogrenci.ogrenciegitimpaketi')),
                ('ozel_ders_paket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birebir_programlar', to='egitim_paketleri.ozelders')),
                ('premium_paket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birebir_programlar', to='egitim_paketleri.premiumpaket')),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birebir_programlar', to='sube.sube')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birebir_programlar', to='term.term')),
            ],
            options={
                'verbose_name': 'Birebir Öğrenci Programı',
                'verbose_name_plural': 'Birebir Öğrenci Programları',
                'db_table': 'ozel_ders_birebir_program',
                'ordering': ['-baslangic_tarihi', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BirebirHakedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(db_index=True)),
                ('sure_dk', models.PositiveIntegerField(default=0)),
                ('birim_ucret', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tutar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('aciklama', models.CharField(blank=True, default='', max_length=255)),
                ('durum', models.CharField(choices=[('TASLAK', 'Taslak'), ('ONAYLANDI', 'Onaylandı'), ('BORDOYA_ISLENDI', 'Bordroya İşlendi'), ('IPTAL', 'İptal')], db_index=True, default='TASLAK', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aylik_hakedis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birebir_hakedisler', to='personel.aylikhakedis')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='birebir_hakedisler', to='egitim_tanimlari.ders')),
                ('ogretmen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='birebir_hakedisler', to='personel.personel')),
                ('oturum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hakedis', to='ozel_ders.birebirdersoturumu')),
            ],
            options={
                'verbose_name': 'Birebir Hakediş',
                'verbose_name_plural': 'Birebir Hakedişler',
                'db_table': 'ozel_ders_birebir_hakedis',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BirebirHaftalikSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.PositiveSmallIntegerField(help_text='1=Pazartesi … 7=Pazar')),
                ('baslangic', models.TimeField()),
                ('bitis', models.TimeField()),
                ('sure_dk', models.PositiveIntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
                ('baslangic_tarihi', models.DateField(blank=True, help_text='Boşsa program başlangıcı kullanılır', null=True)),
                ('bitis_tarihi', models.DateField(blank=True, help_text='Boşsa program bitişi kullanılır', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='birebir_slots', to='egitim_tanimlari.ders')),
                ('oda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birebir_slots', to='oda.oda')),
                ('ogretmen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='birebir_slots', to='personel.personel')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='ozel_ders.birebirogrenciprogrami')),
            ],
            options={
                'verbose_name': 'Birebir Haftalık Slot',
                'verbose_name_plural': 'Birebir Haftalık Slotlar',
                'db_table': 'ozel_ders_birebir_slot',
                'ordering': ['gun', 'baslangic', 'id'],
            },
        ),
        migrations.AddField(
            model_name='birebirdersoturumu',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oturumlar', to='ozel_ders.birebirogrenciprogrami'),
        ),
        migrations.AddField(
            model_name='birebirdersoturumu',
            name='replaces_oturum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telafi_oturumlari', to='ozel_ders.birebirdersoturumu'),
        ),
        migrations.AddField(
            model_name='birebirdersoturumu',
            name='source_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oturumlar', to='ozel_ders.birebirhaftalikslot'),
        ),
        migrations.AddField(
            model_name='birebirdersoturumu',
            name='sube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birebir_oturumlar', to='sube.sube'),
        ),
        migrations.AddConstraint(
            model_name='ucretkurali',
            constraint=models.UniqueConstraint(fields=('kurum', 'sube', 'oturum_turu', 'sozlesme_turu'), name='unique_ucret_kurali_scope'),
        ),
        migrations.AddConstraint(
            model_name='premiumpaketderskota',
            constraint=models.UniqueConstraint(fields=('premium_paket', 'ders'), name='unique_premium_paket_ders_kota'),
        ),
        migrations.AddIndex(
            model_name='birebirogrenciprogrami',
            index=models.Index(fields=['kurum', 'sube', 'egitim_yili', 'durum'], name='ozel_ders_b_kurum_i_a3a8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='birebirogrenciprogrami',
            index=models.Index(fields=['ogrenci', 'durum'], name='ozel_ders_b_ogrenci_dddfa0_idx'),
        ),
        migrations.AddIndex(
            model_name='birebirhakedis',
            index=models.Index(fields=['ogretmen', 'tarih', 'durum'], name='ozel_ders_b_ogretme_263a27_idx'),
        ),
        migrations.AddIndex(
            model_name='birebirhakedis',
            index=models.Index(fields=['durum', 'tarih'], name='ozel_ders_b_durum_5da8a8_idx'),
        ),
        migrations.AddIndex(
            model_name='birebirhaftalikslot',
            index=models.Index(fields=['program', 'gun', 'aktif'], name='ozel_ders_b_program_e05df5_idx'),
        ),
        migrations.AddIndex(
            model_name='birebirhaftalikslot',
            index=models.Index(fields=['ogretmen', 'gun'], name='ozel_ders_b_ogretme_f3ca7a_idx'),
        ),
        migrations.AddIndex(
            model_name='birebirdersoturumu',
            index=models.Index(fields=['session_date', 'durum'], name='ozel_ders_b_session_86988e_idx'),
        ),
        migrations.AddIndex(
            model_name='birebirdersoturumu',
            index=models.Index(fields=['ogretmen', 'session_date'], name='ozel_ders_b_ogretme_4438ab_idx'),
        ),
        migrations.AddIndex(
            model_name='birebirdersoturumu',
            index=models.Index(fields=['ogrenci', 'session_date'], name='ozel_ders_b_ogrenci_0f112f_idx'),
        ),
        migrations.AddIndex(
            model_name='birebirdersoturumu',
            index=models.Index(fields=['kurum', 'sube', 'session_date'], name='ozel_ders_b_kurum_i_6fb4a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='birebirdersoturumu',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('source_slot__isnull', False)), fields=('source_slot', 'session_date'), name='unique_active_slot_session_date'),
        ),
    ]
