# Generated by Django 4.2.27 on 2026-09-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozel_ders', '0005_slot_hedef_dakika'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='birebirdersoturumu',
            new_name='ozel_ders_b_telafi__bdc40a_idx',
            old_name='ozel_ders_oturum_telafi_tarih_idx',
        ),
    ]
