# Generated by Django 4.2.9 on 2026-01-30 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurum_id', models.BigIntegerField(db_index=True, verbose_name='Kurum ID')),
                ('sube_id', models.BigIntegerField(db_index=True, verbose_name='Şube ID')),
                ('egitim_yili_id', models.BigIntegerField(db_index=True, verbose_name='Eğitim Yılı ID')),
                ('tc_kimlik_no', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='TC Kimlik No 11 haneli olmalıdır', regex='^\\d{11}$')], verbose_name='TC Kimlik No')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyad')),
                ('dogum_tarihi', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('cinsiyet', models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kadın')], max_length=1, null=True, verbose_name='Cinsiyet')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
                'db_table': 'ogrenciler',
                'ordering': ['soyad', 'ad'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OgrenciSinifAtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurum_id', models.BigIntegerField(db_index=True, verbose_name='Kurum ID')),
                ('sube_id', models.BigIntegerField(db_index=True, verbose_name='Şube ID')),
                ('egitim_yili_id', models.BigIntegerField(db_index=True, verbose_name='Eğitim Yılı ID')),
                ('ogrenci_id', models.BigIntegerField(verbose_name='Öğrenci ID')),
                ('sinif_id', models.BigIntegerField(verbose_name='Sınıf ID')),
                ('atama_tarihi', models.DateField(verbose_name='Atama Tarihi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Öğrenci-Sınıf Atama',
                'verbose_name_plural': 'Öğrenci-Sınıf Atamaları',
                'db_table': 'ogrenci_sinif_atamalari',
                'ordering': ['-atama_tarihi'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sinif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurum_id', models.BigIntegerField(db_index=True, verbose_name='Kurum ID')),
                ('sube_id', models.BigIntegerField(db_index=True, verbose_name='Şube ID')),
                ('egitim_yili_id', models.BigIntegerField(db_index=True, verbose_name='Eğitim Yılı ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Sınıf Adı')),
                ('kod', models.CharField(max_length=50, verbose_name='Sınıf Kodu')),
                ('kapasite', models.IntegerField(default=30, verbose_name='Kapasite')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Sınıf',
                'verbose_name_plural': 'Sınıflar',
                'db_table': 'siniflar',
                'ordering': ['ad'],
                'managed': False,
            },
        ),
    ]
