# Generated by Django 4.2.9 on 2026-02-20 23:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sube', '0001_initial'),
        ('kurum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaliHesap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='Örn: Merkez Kasa, Ziraat Vadesiz, Garanti POS', max_length=200, verbose_name='Hesap Adı')),
                ('tip', models.CharField(choices=[('kasa', 'Kasa'), ('banka', 'Banka Hesabı'), ('pos', 'POS Cihazı'), ('sanal_pos', 'Sanal POS')], default='kasa', help_text='Hesabın türü', max_length=20, verbose_name='Hesap Tipi')),
                ('iban', models.CharField(blank=True, default='', help_text='Banka hesabı için IBAN numarası (TR ile başlamalı)', max_length=34, verbose_name='IBAN')),
                ('banka_adi', models.CharField(blank=True, default='', help_text='Banka/finans kuruluşu adı', max_length=100, verbose_name='Banka Adı')),
                ('baslangic_bakiye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hesabın açılış bakiyesi', max_digits=15, verbose_name='Başlangıç Bakiye')),
                ('para_birimi', models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'ABD Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini')], default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('siralama', models.PositiveIntegerField(default=0, help_text='Listeleme sırası (küçükten büyüğe)', verbose_name='Sıralama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('silindi_mi', models.BooleanField(db_index=True, default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mali_hesaplar', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Mali Hesap',
                'verbose_name_plural': 'Mali Hesaplar',
                'db_table': 'finans_mali_hesap',
                'ordering': ['siralama', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='OdemeYontemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='Örn: Nakit, Ziraat POS, Garanti Havale', max_length=150, verbose_name='Ödeme Yöntemi Adı')),
                ('tip', models.CharField(choices=[('nakit', 'Nakit'), ('pos', 'POS Cihazı'), ('havale_eft', 'Havale / EFT'), ('online', 'Online Ödeme')], default='nakit', help_text='Ödeme kanalı türü', max_length=20, verbose_name='Tip')),
                ('komisyon_orani', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ödeme yönteminin komisyon yüzdesi', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Komisyon Oranı (%)')),
                ('valor_gun', models.PositiveIntegerField(default=0, help_text='Paranın hesaba geçme süresi (gün)', verbose_name='Valör Gün')),
                ('siralama', models.PositiveIntegerField(default=0, help_text='Listeleme sırası (küçükten büyüğe)', verbose_name='Sıralama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('silindi_mi', models.BooleanField(db_index=True, default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odeme_yontemleri', to='kurum.kurum', verbose_name='Kurum')),
            ],
            options={
                'verbose_name': 'Ödeme Yöntemi',
                'verbose_name_plural': 'Ödeme Yöntemleri',
                'db_table': 'finans_odeme_yontemi',
                'ordering': ['siralama', 'ad'],
                'indexes': [models.Index(fields=['kurum', 'aktif_mi', 'silindi_mi'], name='finans_odem_kurum_i_c6105a_idx'), models.Index(fields=['tip'], name='finans_odem_tip_91d3c4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='odemeyontemi',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi_mi', False)), fields=('kurum', 'ad'), name='unique_kurum_odeme_yontemi_ad'),
        ),
        migrations.AddIndex(
            model_name='malihesap',
            index=models.Index(fields=['sube', 'aktif_mi', 'silindi_mi'], name='finans_mali_sube_id_d74f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='malihesap',
            index=models.Index(fields=['tip'], name='finans_mali_tip_c2a141_idx'),
        ),
        migrations.AddConstraint(
            model_name='malihesap',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi_mi', False)), fields=('sube', 'ad'), name='unique_sube_mali_hesap_ad'),
        ),
    ]
