# Generated by Django 4.2.9 on 2026-02-21 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odemeyontemi',
            name='varsayilan_mali_hesap',
            field=models.ForeignKey(blank=True, help_text='Tahsilat ekranında bu yöntem seçildiğinde otomatik dolacak hesap', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='varsayilan_odeme_yontemleri', to='finans.malihesap', verbose_name='Varsayılan Mali Hesap'),
        ),
    ]
