# Generated by Django 4.2.9 on 2026-03-07 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurum', '0001_initial'),
        ('finans', '0002_add_varsayilan_mali_hesap_to_odeme_yontemi'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiderKategorisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150, verbose_name='Kategori Adı')),
                ('ikon', models.CharField(blank=True, default='', help_text='Emoji ikon (opsiyonel)', max_length=10, verbose_name='İkon')),
                ('renk', models.CharField(blank=True, default='', help_text='Hex renk kodu, örn: #3b82f6', max_length=7, verbose_name='Renk')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('siralama', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('silindi_mi', models.BooleanField(db_index=True, default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gider_kategorileri', to='kurum.kurum', verbose_name='Kurum')),
                ('parent', models.ForeignKey(blank=True, help_text='Boş ise ana kategoridir', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategoriler', to='finans.giderkategorisi', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Gider Kategorisi',
                'verbose_name_plural': 'Gider Kategorileri',
                'db_table': 'finans_gider_kategorisi',
                'ordering': ['siralama', 'ad'],
                'indexes': [models.Index(fields=['kurum', 'parent', 'aktif_mi', 'silindi_mi'], name='finans_gide_kurum_i_5e44af_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='giderkategorisi',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi_mi', False)), fields=('kurum', 'parent', 'ad'), name='unique_kurum_gider_kategori_ad'),
        ),
    ]
