# Generated by Django 4.2.9 on 2026-03-07 01:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('egitim_yili', '0001_initial'),
        ('kurum', '0001_initial'),
        ('sube', '0001_initial'),
        ('finans', '0003_gider_kategorisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakiyeHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yon', models.CharField(choices=[('giris', 'Giriş (+)'), ('cikis', 'Çıkış (-)')], help_text='Giriş (+) veya Çıkış (-)', max_length=10, verbose_name='Hareket Yönü')),
                ('tutar', models.IntegerField(help_text='Hareket tutarı — her zaman pozitif, yön ayrı alan', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tutar (TL)')),
                ('kaynak', models.CharField(choices=[('tahsilat', 'Tahsilat'), ('tahsilat_iptal', 'Tahsilat İptal'), ('iade', 'İade'), ('gider', 'Gider'), ('gider_iptal', 'Gider İptal'), ('devir', 'Dönem Devri'), ('manuel', 'Manuel Düzeltme'), ('acilis', 'Açılış Bakiyesi')], help_text='Bu hareketin nedeni (tahsilat, gider, devir vb.)', max_length=20, verbose_name='Hareket Kaynağı')),
                ('kaynak_tip', models.CharField(blank=True, default='', help_text='Orijinal işlemin model adı (tahsilat, gider_kaydi, donem_bakiye)', max_length=50, verbose_name='Kaynak Tipi')),
                ('kaynak_id', models.PositiveIntegerField(blank=True, help_text='Orijinal işlemin PK değeri', null=True, verbose_name='Kaynak ID')),
                ('bakiye_oncesi', models.IntegerField(default=0, help_text='Bu hareket öncesi hesap bakiyesi', verbose_name='İşlem Öncesi Bakiye')),
                ('bakiye_sonrasi', models.IntegerField(default=0, help_text='Bu hareket sonrası hesap bakiyesi', verbose_name='İşlem Sonrası Bakiye')),
                ('islem_tarihi', models.DateField(help_text='Hareketin gerçekleştiği tarih', verbose_name='İşlem Tarihi')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bakiye_hareketleri', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('islem_yapan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bakiye_hareketleri', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bakiye_hareketleri', to='kurum.kurum', verbose_name='Kurum')),
                ('mali_hesap', models.ForeignKey(help_text='Hareketin gerçekleştiği kasa/banka hesabı', on_delete=django.db.models.deletion.PROTECT, related_name='hareketler', to='finans.malihesap', verbose_name='Mali Hesap')),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bakiye_hareketleri', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Bakiye Hareketi',
                'verbose_name_plural': 'Bakiye Hareketleri',
                'db_table': 'finans_bakiye_hareketi',
                'ordering': ['-islem_tarihi', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonemBakiye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donem_basi_bakiye', models.IntegerField(default=0, help_text='Dönem açıldığında başlangıç bakiyesi. İlk yılda 0, sonraki yıllarda önceki yılın devir tutarı.', verbose_name='Dönem Başı Bakiye (TL)')),
                ('toplam_gelir', models.IntegerField(default=0, help_text='Dönem içi tüm giriş hareketleri toplamı (devir hariç)', verbose_name='Toplam Gelir (TL)')),
                ('toplam_gider', models.IntegerField(default=0, help_text='Dönem içi tüm çıkış hareketleri toplamı (devir hariç)', verbose_name='Toplam Gider (TL)')),
                ('donem_sonu_bakiye', models.IntegerField(default=0, help_text='donem_basi_bakiye + toplam_gelir - toplam_gider', verbose_name='Dönem Sonu Bakiye (TL)')),
                ('devir_tutari', models.IntegerField(default=0, help_text='Sonraki eğitim yılına devredilecek tutar', verbose_name='Devir Tutarı (TL)')),
                ('durum', models.CharField(choices=[('acik', 'Açık'), ('kapandi', 'Kapandı'), ('devredildi', 'Devredildi')], db_index=True, default='acik', max_length=15, verbose_name='Durum')),
                ('kapanma_tarihi', models.DateTimeField(blank=True, help_text='Dönemin kapandığı an', null=True, verbose_name='Kapanma Tarihi')),
                ('devir_tarihi', models.DateTimeField(blank=True, help_text='Bakiyenin sonraki döneme devredildiği an', null=True, verbose_name='Devir Tarihi')),
                ('notlar', models.TextField(blank=True, default='', help_text='Dönem kapanışı ile ilgili notlar', verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donem_bakiyeleri', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('kapatan_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kapattigi_donemler', to=settings.AUTH_USER_MODEL, verbose_name='Kapatan Kullanıcı')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donem_bakiyeleri', to='kurum.kurum', verbose_name='Kurum')),
                ('mali_hesap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donem_bakiyeleri', to='finans.malihesap', verbose_name='Mali Hesap')),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donem_bakiyeleri', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Dönem Bakiye',
                'verbose_name_plural': 'Dönem Bakiyeleri',
                'db_table': 'finans_donem_bakiye',
                'ordering': ['-egitim_yili__baslangic_yil', 'mali_hesap__ad'],
                'indexes': [models.Index(fields=['kurum', 'sube', 'egitim_yili', 'durum'], name='finans_done_kurum_i_c695f7_idx'), models.Index(fields=['mali_hesap', 'durum'], name='finans_done_mali_he_936e0e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='donembakiye',
            constraint=models.UniqueConstraint(fields=('mali_hesap', 'egitim_yili'), name='unique_mali_hesap_egitim_yili'),
        ),
        migrations.AddIndex(
            model_name='bakiyehareketi',
            index=models.Index(fields=['mali_hesap', 'egitim_yili', 'islem_tarihi'], name='finans_baki_mali_he_5843a2_idx'),
        ),
        migrations.AddIndex(
            model_name='bakiyehareketi',
            index=models.Index(fields=['kurum', 'sube', 'egitim_yili'], name='finans_baki_kurum_i_bc0fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='bakiyehareketi',
            index=models.Index(fields=['kaynak', 'kaynak_tip', 'kaynak_id'], name='finans_baki_kaynak_62f632_idx'),
        ),
        migrations.AddIndex(
            model_name='bakiyehareketi',
            index=models.Index(fields=['islem_tarihi'], name='finans_baki_islem_t_e442e6_idx'),
        ),
        migrations.AddIndex(
            model_name='bakiyehareketi',
            index=models.Index(fields=['yon'], name='finans_baki_yon_55ac82_idx'),
        ),
    ]
