# Generated by Django 4.2.27 on 2026-03-07 22:37

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kurum', '0001_initial'),
        ('egitim_yili', '0001_initial'),
        ('sube', '0001_initial'),
        ('finans', '0004_bakiye_hareketi_ve_donem_bakiye'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiderKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_no', models.CharField(blank=True, default='', max_length=50, verbose_name='Fatura / Belge No')),
                ('fatura_tarihi', models.DateField(verbose_name='Fatura Tarihi')),
                ('vade_tarihi', models.DateField(help_text='Son ödeme tarihi', verbose_name='Vade Tarihi')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('brut_tutar', models.DecimalField(decimal_places=2, help_text='KDV hariç tutar', max_digits=15, verbose_name='Brüt Tutar')),
                ('kdv_orani', models.IntegerField(choices=[(0, '%0'), (1, '%1'), (10, '%10'), (20, '%20')], default=20, verbose_name='KDV Oranı (%)')),
                ('kdv_tutar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Otomatik hesaplanır', max_digits=15, verbose_name='KDV Tutarı')),
                ('net_tutar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='brut_tutar + kdv_tutar', max_digits=15, verbose_name='Net Tutar (KDV Dahil)')),
                ('odenen_toplam', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Yapılmış ödemelerin toplamı', max_digits=15, verbose_name='Ödenen Toplam')),
                ('taksit_sayisi', models.PositiveSmallIntegerField(default=1, help_text='1 = peşin, N = N taksit', verbose_name='Taksit Sayısı')),
                ('tekrar_mi', models.BooleanField(default=False, help_text='Periyodik olarak tekrar eden gider mi?', verbose_name='Tekrarlayan Gider')),
                ('tekrar_sikligi', models.CharField(blank=True, choices=[('aylik', 'Aylık'), ('uc_aylik', '3 Aylık'), ('alti_aylik', '6 Aylık'), ('yillik', 'Yıllık')], default='', max_length=15, verbose_name='Tekrar Sıklığı')),
                ('tekrar_bitis_tarihi', models.DateField(blank=True, help_text='Tekrarlayan gider için son tarih', null=True, verbose_name='Tekrar Bitiş Tarihi')),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('onay_bekliyor', 'Onay Bekliyor'), ('onaylandi', 'Onaylandı'), ('kismi_odendi', 'Kısmi Ödendi'), ('odendi', 'Ödendi'), ('iptal', 'İptal')], default='taslak', max_length=20, verbose_name='Durum')),
                ('belge', models.FileField(blank=True, null=True, upload_to='finans/gider_belgeleri/%Y/%m/', verbose_name='Fatura / Belge')),
                ('onay_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('silindi_mi', models.BooleanField(db_index=True, default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('egitim_yili', models.ForeignKey(blank=True, help_text='İlişkili eğitim dönemi', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gider_kayitlari', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('gider_kategorisi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gider_kayitlari', to='finans.giderkategorisi', verbose_name='Gider Kategorisi')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gider_kayitlari', to='kurum.kurum', verbose_name='Kurum')),
                ('mali_hesap', models.ForeignKey(blank=True, help_text='Varsayılan ödeme hesabı', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gider_kayitlari', to='finans.malihesap', verbose_name='Mali Hesap')),
                ('odeme_yontemi', models.ForeignKey(blank=True, help_text='Varsayılan ödeme yöntemi', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gider_kayitlari', to='finans.odemeyontemi', verbose_name='Ödeme Yöntemi')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_giderler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('onaylayan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onaylanan_giderler', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('sube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gider_kayitlari', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Gider Kaydı',
                'verbose_name_plural': 'Gider Kayıtları',
                'db_table': 'finans_gider_kaydi',
                'ordering': ['-fatura_tarihi', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tedarikci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unvan', models.CharField(help_text='Resmi firma ünvanı', max_length=300, verbose_name='Firma Ünvanı')),
                ('kisa_ad', models.CharField(blank=True, default='', help_text='Listede görünecek kısa isim (opsiyonel)', max_length=100, verbose_name='Kısa Ad')),
                ('vergi_no', models.CharField(blank=True, default='', help_text='10 haneli vergi no veya 11 haneli TC kimlik no', max_length=11, verbose_name='Vergi No / TC Kimlik No')),
                ('vergi_dairesi', models.CharField(blank=True, default='', max_length=150, verbose_name='Vergi Dairesi')),
                ('kategori', models.CharField(choices=[('hizmet', 'Hizmet'), ('mal', 'Mal / Malzeme'), ('kira', 'Kira'), ('bakim_onarim', 'Bakım & Onarım'), ('teknoloji', 'Teknoloji'), ('egitim', 'Eğitim Materyali'), ('yemek', 'Yemek / Catering'), ('temizlik', 'Temizlik'), ('sigorta', 'Sigorta'), ('diger', 'Diğer')], default='hizmet', max_length=20, verbose_name='Kategori')),
                ('telefon', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-posta')),
                ('adres', models.TextField(blank=True, default='', verbose_name='Adres')),
                ('ilgili_kisi', models.CharField(blank=True, default='', help_text='İrtibat kişisi adı soyadı', max_length=150, verbose_name='İlgili Kişi')),
                ('iban', models.CharField(blank=True, default='', help_text='Ödeme yapılacak IBAN', max_length=34, verbose_name='IBAN')),
                ('banka_adi', models.CharField(blank=True, default='', max_length=100, verbose_name='Banka Adı')),
                ('hesap_sahibi', models.CharField(blank=True, default='', help_text='Banka hesap sahibi adı', max_length=200, verbose_name='Hesap Sahibi')),
                ('toplam_borc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tüm gider kayıtlarının toplamı', max_digits=15, verbose_name='Toplam Borç')),
                ('toplam_odeme', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tüm ödemelerin toplamı', max_digits=15, verbose_name='Toplam Ödeme')),
                ('not_field', models.TextField(blank=True, default='', help_text='Yönetici notu / değerlendirme', verbose_name='Değerlendirme Notu')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('silindi_mi', models.BooleanField(db_index=True, default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tedarikciler', to='kurum.kurum', verbose_name='Kurum')),
            ],
            options={
                'verbose_name': 'Tedarikçi',
                'verbose_name_plural': 'Tedarikçiler',
                'db_table': 'finans_tedarikci',
                'ordering': ['unvan'],
            },
        ),
        migrations.CreateModel(
            name='GiderTaksit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taksit_no', models.PositiveSmallIntegerField(help_text='1-based sıra numarası', verbose_name='Taksit No')),
                ('vade_tarihi', models.DateField(verbose_name='Vade Tarihi')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Taksit Tutarı')),
                ('odenen_tutar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Ödenen Tutar')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('kismi_odendi', 'Kısmi Ödendi'), ('odendi', 'Ödendi'), ('gecikti', 'Gecikti'), ('iptal', 'İptal')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('gider_kaydi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taksitler', to='finans.giderkaydi', verbose_name='Gider Kaydı')),
            ],
            options={
                'verbose_name': 'Gider Taksit',
                'verbose_name_plural': 'Gider Taksitler',
                'db_table': 'finans_gider_taksit',
                'ordering': ['gider_kaydi', 'taksit_no'],
            },
        ),
        migrations.CreateModel(
            name='GiderOdeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ödeme Tutarı')),
                ('odeme_tarihi', models.DateField(verbose_name='Ödeme Tarihi')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('dekont', models.FileField(blank=True, null=True, upload_to='finans/gider_dekontlari/%Y/%m/', verbose_name='Dekont / Makbuz')),
                ('bakiye_hareketi_id', models.PositiveBigIntegerField(blank=True, help_text="İlgili BakiyeHareketi kaydının ID'si (referans amaçlı)", null=True, verbose_name='Bakiye Hareketi ID')),
                ('durum', models.CharField(choices=[('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='tamamlandi', max_length=15, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('gider_kaydi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odemeler', to='finans.giderkaydi', verbose_name='Gider Kaydı')),
                ('gider_taksit', models.ForeignKey(blank=True, help_text='Hangi taksit için ödeme yapılıyor (opsiyonel)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='odemeler', to='finans.gidertaksit', verbose_name='Gider Taksit')),
                ('islem_yapan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yapilan_gider_odemeleri', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('mali_hesap', models.ForeignKey(help_text='Ödemenin çıkacağı hesap', on_delete=django.db.models.deletion.PROTECT, related_name='gider_odemeleri', to='finans.malihesap', verbose_name='Mali Hesap')),
                ('odeme_yontemi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gider_odemeleri', to='finans.odemeyontemi', verbose_name='Ödeme Yöntemi')),
            ],
            options={
                'verbose_name': 'Gider Ödeme',
                'verbose_name_plural': 'Gider Ödemeler',
                'db_table': 'finans_gider_odeme',
                'ordering': ['-odeme_tarihi', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='giderkaydi',
            name='tedarikci',
            field=models.ForeignKey(help_text='Giderin ait olduğu tedarikçi', on_delete=django.db.models.deletion.PROTECT, related_name='gider_kayitlari', to='finans.tedarikci', verbose_name='Tedarikçi'),
        ),
        migrations.AddIndex(
            model_name='tedarikci',
            index=models.Index(fields=['kurum', 'aktif_mi', 'silindi_mi'], name='finans_teda_kurum_i_3ca7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='tedarikci',
            index=models.Index(fields=['kategori'], name='finans_teda_kategor_68f5ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='tedarikci',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi_mi', False), ('vergi_no__gt', '')), fields=('kurum', 'vergi_no'), name='unique_kurum_tedarikci_vergi_no'),
        ),
        migrations.AddIndex(
            model_name='gidertaksit',
            index=models.Index(fields=['vade_tarihi', 'durum'], name='finans_gide_vade_ta_24e647_idx'),
        ),
        migrations.AddConstraint(
            model_name='gidertaksit',
            constraint=models.UniqueConstraint(fields=('gider_kaydi', 'taksit_no'), name='unique_gider_taksit_no'),
        ),
        migrations.AddIndex(
            model_name='giderodeme',
            index=models.Index(fields=['gider_kaydi', 'durum'], name='finans_gide_gider_k_0af388_idx'),
        ),
        migrations.AddIndex(
            model_name='giderodeme',
            index=models.Index(fields=['odeme_tarihi'], name='finans_gide_odeme_t_a485cd_idx'),
        ),
        migrations.AddIndex(
            model_name='giderodeme',
            index=models.Index(fields=['mali_hesap'], name='finans_gide_mali_he_eb755f_idx'),
        ),
        migrations.AddIndex(
            model_name='giderkaydi',
            index=models.Index(fields=['kurum', 'durum', 'silindi_mi'], name='finans_gide_kurum_i_6e50c7_idx'),
        ),
        migrations.AddIndex(
            model_name='giderkaydi',
            index=models.Index(fields=['tedarikci', 'durum'], name='finans_gide_tedarik_156ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='giderkaydi',
            index=models.Index(fields=['fatura_tarihi'], name='finans_gide_fatura__ffc634_idx'),
        ),
        migrations.AddIndex(
            model_name='giderkaydi',
            index=models.Index(fields=['vade_tarihi'], name='finans_gide_vade_ta_c601a9_idx'),
        ),
        migrations.AddIndex(
            model_name='giderkaydi',
            index=models.Index(fields=['gider_kategorisi'], name='finans_gide_gider_k_ecc880_idx'),
        ),
    ]
