# Generated by Django 4.2.9 on 2026-03-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finans', '0005_tedarikci_gider_odeme'),
    ]

    operations = [
        migrations.AddField(
            model_name='giderkaydi',
            name='taksit_plani_json',
            field=models.JSONField(blank=True, default=None, help_text='Kullanıcının manuel ayarladığı taksit planı. [{taksit_no, vade_tarihi, tutar}, ...]', null=True, verbose_name='Özel Taksit Planı'),
        ),
        migrations.AddField(
            model_name='tedarikci',
            name='gider_kategorileri',
            field=models.ManyToManyField(blank=True, help_text='Tedarikçinin ilişkili olduğu gider kategorileri', related_name='tedarikciler', to='finans.giderkategorisi', verbose_name='Gider Kategorileri'),
        ),
    ]
