# Generated by Django 4.2.9 on 2026-03-08 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sube', '0001_initial'),
        ('egitim_yili', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kurum', '0001_initial'),
        ('finans', '0006_add_taksit_plani_json_and_tedarikci_gider_kategorileri'),
    ]

    operations = [
        migrations.CreateModel(
            name='CariHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_turu', models.CharField(choices=[('satis', 'Satış'), ('alis', 'Alış'), ('tahsilat', 'Tahsilat'), ('odeme', 'Ödeme'), ('avans', 'Avans'), ('iade', 'İade'), ('duzeltme', 'Düzeltme'), ('devir', 'Devir'), ('acilis', 'Açılış Bakiyesi')], max_length=20, verbose_name='İşlem Türü')),
                ('yon', models.CharField(choices=[('borc', 'Borç'), ('alacak', 'Alacak')], max_length=10, verbose_name='Yön')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar')),
                ('borc_oncesi', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Borç Öncesi')),
                ('alacak_oncesi', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Alacak Öncesi')),
                ('borc_sonrasi', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Borç Sonrası')),
                ('alacak_sonrasi', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Alacak Sonrası')),
                ('kaynak_tip', models.CharField(blank=True, default='', help_text='GiderKaydi, GelirKaydi, GiderOdeme, vb.', max_length=50, verbose_name='Kaynak Tipi')),
                ('kaynak_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kaynak ID')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('belge_no', models.CharField(blank=True, default='', max_length=50, verbose_name='Belge No')),
                ('islem_tarihi', models.DateField(verbose_name='İşlem Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cari Hareket',
                'verbose_name_plural': 'Cari Hareketler',
                'db_table': 'finans_cari_hareket',
                'ordering': ['-islem_tarihi', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CariHesap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unvan', models.CharField(max_length=300, verbose_name='Ünvan / Ad Soyad')),
                ('kisa_ad', models.CharField(blank=True, default='', max_length=100, verbose_name='Kısa Ad')),
                ('hesap_turu', models.CharField(choices=[('musteri', 'Müşteri'), ('tedarikci', 'Tedarikçi'), ('karma', 'Karma')], default='tedarikci', max_length=20, verbose_name='Hesap Türü')),
                ('hesap_kodu', models.CharField(blank=True, default='', help_text='Muhasebe entegrasyonu için (opsiyonel)', max_length=50, verbose_name='Hesap Kodu')),
                ('vergi_no', models.CharField(blank=True, default='', max_length=20, verbose_name='Vergi No / TC')),
                ('vergi_dairesi', models.CharField(blank=True, default='', max_length=100, verbose_name='Vergi Dairesi')),
                ('telefon', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-posta')),
                ('adres', models.TextField(blank=True, default='', verbose_name='Adres')),
                ('il', models.CharField(blank=True, default='', max_length=50, verbose_name='İl')),
                ('ilce', models.CharField(blank=True, default='', max_length=50, verbose_name='İlçe')),
                ('yetkili_kisi', models.CharField(blank=True, default='', max_length=200, verbose_name='Yetkili Kişi')),
                ('yetkili_telefon', models.CharField(blank=True, default='', max_length=20, verbose_name='Yetkili Telefon')),
                ('banka_adi', models.CharField(blank=True, default='', max_length=100, verbose_name='Banka Adı')),
                ('iban', models.CharField(blank=True, default='', max_length=34, verbose_name='IBAN')),
                ('hesap_sahibi', models.CharField(blank=True, default='', max_length=200, verbose_name='Hesap Sahibi')),
                ('toplam_borc', models.DecimalField(decimal_places=2, default=0, help_text='Karşı tarafın bize toplam borcu', max_digits=15, verbose_name='Toplam Borç')),
                ('toplam_alacak', models.DecimalField(decimal_places=2, default=0, help_text='Bizim karşı tarafa toplam borcumuz', max_digits=15, verbose_name='Toplam Alacak')),
                ('notlar', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('silindi_mi', models.BooleanField(default=False)),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cari Hesap',
                'verbose_name_plural': 'Cari Hesaplar',
                'db_table': 'finans_cari_hesap',
                'ordering': ['unvan'],
            },
        ),
        migrations.CreateModel(
            name='GelirKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_no', models.CharField(blank=True, default='', max_length=50, verbose_name='Fatura No')),
                ('fatura_tarihi', models.DateField(verbose_name='Fatura Tarihi')),
                ('vade_tarihi', models.DateField(verbose_name='Vade Tarihi')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('brut_tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Brüt Tutar')),
                ('kdv_orani', models.IntegerField(choices=[(0, '%0'), (1, '%1'), (10, '%10'), (20, '%20')], default=20, verbose_name='KDV Oranı (%)')),
                ('kdv_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='KDV Tutar')),
                ('net_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Net Tutar (KDV dahil)')),
                ('tahsil_edilen', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tahsil Edilen')),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('onaylandi', 'Onaylandı'), ('kismi_tahsil', 'Kısmi Tahsil'), ('tahsil_edildi', 'Tahsil Edildi'), ('iptal', 'İptal')], default='taslak', max_length=20, verbose_name='Durum')),
                ('belge', models.FileField(blank=True, null=True, upload_to='finans/gelir_belgeleri/%Y/%m/', verbose_name='Belge')),
                ('silindi_mi', models.BooleanField(default=False)),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gelir Kaydı',
                'verbose_name_plural': 'Gelir Kayıtları',
                'db_table': 'finans_gelir_kaydi',
                'ordering': ['-fatura_tarihi', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='tedarikci',
            name='gider_kategorileri',
        ),
        migrations.RemoveField(
            model_name='tedarikci',
            name='kurum',
        ),
        migrations.RemoveIndex(
            model_name='giderkaydi',
            name='finans_gide_tedarik_156ba0_idx',
        ),
        migrations.RemoveField(
            model_name='giderkaydi',
            name='tedarikci',
        ),
        migrations.AlterField(
            model_name='bakiyehareketi',
            name='kaynak',
            field=models.CharField(choices=[('tahsilat', 'Tahsilat'), ('tahsilat_iptal', 'Tahsilat İptal'), ('iade', 'İade'), ('gider', 'Gider'), ('gider_iptal', 'Gider İptal'), ('gelir', 'Gelir'), ('gelir_iptal', 'Gelir İptal'), ('avans', 'Avans'), ('devir', 'Dönem Devri'), ('manuel', 'Manuel Düzeltme'), ('acilis', 'Açılış Bakiyesi')], help_text='Bu hareketin nedeni (tahsilat, gider, devir vb.)', max_length=20, verbose_name='Hareket Kaynağı'),
        ),
        migrations.DeleteModel(
            name='Tedarikci',
        ),
        migrations.AddField(
            model_name='gelirkaydi',
            name='cari_hesap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gelir_kayitlari', to='finans.carihesap', verbose_name='Cari Hesap (Müşteri)'),
        ),
        migrations.AddField(
            model_name='gelirkaydi',
            name='egitim_yili',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gelir_kayitlari', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı'),
        ),
        migrations.AddField(
            model_name='gelirkaydi',
            name='kurum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gelir_kayitlari', to='kurum.kurum', verbose_name='Kurum'),
        ),
        migrations.AddField(
            model_name='gelirkaydi',
            name='mali_hesap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gelir_kayitlari', to='finans.malihesap', verbose_name='Mali Hesap'),
        ),
        migrations.AddField(
            model_name='gelirkaydi',
            name='odeme_yontemi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gelir_kayitlari', to='finans.odemeyontemi', verbose_name='Ödeme Yöntemi'),
        ),
        migrations.AddField(
            model_name='gelirkaydi',
            name='olusturan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_gelirler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='gelirkaydi',
            name='sube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gelir_kayitlari', to='sube.sube', verbose_name='Şube'),
        ),
        migrations.AddField(
            model_name='carihesap',
            name='gider_kategorileri',
            field=models.ManyToManyField(blank=True, related_name='cari_hesaplar', to='finans.giderkategorisi', verbose_name='İlişkili Gider Kategorileri'),
        ),
        migrations.AddField(
            model_name='carihesap',
            name='kurum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cari_hesaplar', to='kurum.kurum', verbose_name='Kurum'),
        ),
        migrations.AddField(
            model_name='carihareket',
            name='cari_hesap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hareketler', to='finans.carihesap', verbose_name='Cari Hesap'),
        ),
        migrations.AddField(
            model_name='carihareket',
            name='egitim_yili',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cari_hareketler', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı'),
        ),
        migrations.AddField(
            model_name='carihareket',
            name='islem_yapan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cari_hareketleri', to=settings.AUTH_USER_MODEL, verbose_name='İşlem Yapan'),
        ),
        migrations.AddField(
            model_name='carihareket',
            name='kurum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cari_hareketler', to='kurum.kurum', verbose_name='Kurum'),
        ),
        migrations.AddField(
            model_name='carihareket',
            name='sube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cari_hareketler', to='sube.sube', verbose_name='Şube'),
        ),
        migrations.AddField(
            model_name='giderkaydi',
            name='cari_hesap',
            field=models.ForeignKey(blank=True, help_text='Giderin ait olduğu cari hesap', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gider_kayitlari', to='finans.carihesap', verbose_name='Cari Hesap'),
        ),
        migrations.AddIndex(
            model_name='giderkaydi',
            index=models.Index(fields=['cari_hesap', 'durum'], name='finans_gide_cari_he_1d4895_idx'),
        ),
        migrations.AddIndex(
            model_name='gelirkaydi',
            index=models.Index(fields=['kurum', '-fatura_tarihi'], name='finans_geli_kurum_i_56db27_idx'),
        ),
        migrations.AddIndex(
            model_name='gelirkaydi',
            index=models.Index(fields=['cari_hesap'], name='finans_geli_cari_he_5aa928_idx'),
        ),
        migrations.AddIndex(
            model_name='gelirkaydi',
            index=models.Index(fields=['durum'], name='finans_geli_durum_517ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='carihesap',
            index=models.Index(fields=['kurum', 'hesap_turu'], name='finans_cari_kurum_i_198f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='carihesap',
            index=models.Index(fields=['kurum', 'aktif_mi'], name='finans_cari_kurum_i_1ce708_idx'),
        ),
        migrations.AddIndex(
            model_name='carihesap',
            index=models.Index(fields=['vergi_no'], name='finans_cari_vergi_n_98f34d_idx'),
        ),
        migrations.AddIndex(
            model_name='carihareket',
            index=models.Index(fields=['cari_hesap', '-islem_tarihi'], name='finans_cari_cari_he_3a26ea_idx'),
        ),
        migrations.AddIndex(
            model_name='carihareket',
            index=models.Index(fields=['kurum', '-islem_tarihi'], name='finans_cari_kurum_i_f46a82_idx'),
        ),
        migrations.AddIndex(
            model_name='carihareket',
            index=models.Index(fields=['islem_turu'], name='finans_cari_islem_t_1f9488_idx'),
        ),
        migrations.AddIndex(
            model_name='carihareket',
            index=models.Index(fields=['kaynak_tip', 'kaynak_id'], name='finans_cari_kaynak__e2e9fd_idx'),
        ),
    ]
