# Generated by Django 4.2.9 on 2026-03-09 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finans', '0007_cari_hesap_cari_hareket_gelir_kaydi'),
    ]

    operations = [
        migrations.CreateModel(
            name='CariDosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurum_id', models.PositiveIntegerField(verbose_name='Kurum ID')),
                ('dosya', models.FileField(upload_to='finans/cari_dosyalar/%Y/%m/', verbose_name='Dosya')),
                ('dosya_adi', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('dosya_turu', models.CharField(choices=[('sozlesme', 'Sözleşme'), ('fatura', 'Fatura'), ('teklif', 'Teklif'), ('dekont', 'Dekont / Makbuz'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='Dosya Türü')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('dosya_boyutu', models.PositiveIntegerField(default=0, verbose_name='Boyut (byte)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cari_hesap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='finans.carihesap', verbose_name='Cari Hesap')),
                ('yukleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'Cari Dosya',
                'verbose_name_plural': 'Cari Dosyalar',
                'db_table': 'finans_cari_dosya',
                'ordering': ['-created_at'],
            },
        ),
    ]
