# Generated by Django 4.2.9 on 2026-03-09 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sube', '0001_initial'),
        ('egitim_yili', '0001_initial'),
        ('finans', '0008_cari_dosya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakiyehareketi',
            name='egitim_yili',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bakiye_hareketleri', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı'),
        ),
        migrations.AlterField(
            model_name='bakiyehareketi',
            name='sube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bakiye_hareketleri', to='sube.sube', verbose_name='Şube'),
        ),
        migrations.AlterField(
            model_name='donembakiye',
            name='egitim_yili',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donem_bakiyeleri', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı'),
        ),
        migrations.AlterField(
            model_name='donembakiye',
            name='sube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donem_bakiyeleri', to='sube.sube', verbose_name='Şube'),
        ),
    ]
