# Generated by Django 4.2.9 on 2026-03-11 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finans', '0009_allow_null_sube_egitim_yili_on_bakiye'),
    ]

    operations = [
        migrations.AddField(
            model_name='giderodeme',
            name='bakiyeden_mahsup',
            field=models.BooleanField(default=False, help_text='True ise mali hesaptan para çıkmamış, cari bakiyeden düşülmüştür.', verbose_name='Bakiyeden Mahsup'),
        ),
        migrations.AlterField(
            model_name='bakiyehareketi',
            name='kaynak',
            field=models.CharField(choices=[('tahsilat', 'Tahsilat'), ('tahsilat_iptal', 'Tahsilat İptal'), ('iade', 'İade'), ('gider', 'Gider'), ('gider_iptal', 'Gider İptal'), ('gelir', 'Gelir'), ('gelir_iptal', 'Gelir İptal'), ('avans', 'Avans'), ('mahsup', 'Cari Bakiye Mahsubu'), ('devir', 'Dönem Devri'), ('manuel', 'Manuel Düzeltme'), ('acilis', 'Açılış Bakiyesi')], help_text='Bu hareketin nedeni (tahsilat, gider, devir vb.)', max_length=20, verbose_name='Hareket Kaynağı'),
        ),
        migrations.AlterField(
            model_name='carihareket',
            name='islem_turu',
            field=models.CharField(choices=[('satis', 'Satış'), ('alis', 'Alış'), ('tahsilat', 'Tahsilat'), ('odeme', 'Ödeme'), ('avans', 'Avans'), ('iade', 'İade'), ('duzeltme', 'Düzeltme'), ('mahsup', 'Bakiye Mahsubu'), ('devir', 'Devir'), ('acilis', 'Açılış Bakiyesi')], max_length=20, verbose_name='İşlem Türü'),
        ),
        migrations.AlterField(
            model_name='giderodeme',
            name='mali_hesap',
            field=models.ForeignKey(blank=True, help_text='Ödemenin çıkacağı hesap (bakiye mahsubunda boş kalabilir)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gider_odemeleri', to='finans.malihesap', verbose_name='Mali Hesap'),
        ),
        migrations.AlterField(
            model_name='giderodeme',
            name='odeme_yontemi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gider_odemeleri', to='finans.odemeyontemi', verbose_name='Ödeme Yöntemi'),
        ),
    ]
