# Generated by Django 4.2.9 on 2026-03-11 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finans', '0010_add_bakiyeden_mahsup_to_gider_odeme'),
    ]

    operations = [
        migrations.CreateModel(
            name='GelirTahsilat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tahsilat Tutarı')),
                ('tahsilat_tarihi', models.DateField(verbose_name='Tahsilat Tarihi')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('dekont', models.FileField(blank=True, null=True, upload_to='finans/gelir_dekontlari/%Y/%m/', verbose_name='Dekont / Makbuz')),
                ('bakiye_hareketi_id', models.PositiveBigIntegerField(blank=True, help_text="İlgili BakiyeHareketi kaydının ID'si (referans amaçlı)", null=True, verbose_name='Bakiye Hareketi ID')),
                ('durum', models.CharField(choices=[('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='tamamlandi', max_length=15, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('gelir_kaydi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tahsilatlar', to='finans.gelirkaydi', verbose_name='Gelir Kaydı')),
                ('islem_yapan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yapilan_gelir_tahsilatlari', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('mali_hesap', models.ForeignKey(blank=True, help_text='Tahsilatın yatırılacağı hesap (kasa/banka)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gelir_tahsilatlari', to='finans.malihesap', verbose_name='Mali Hesap')),
                ('odeme_yontemi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gelir_tahsilatlari', to='finans.odemeyontemi', verbose_name='Ödeme Yöntemi')),
            ],
            options={
                'verbose_name': 'Gelir Tahsilat',
                'verbose_name_plural': 'Gelir Tahsilatlar',
                'db_table': 'finans_gelir_tahsilat',
                'ordering': ['-tahsilat_tarihi', '-created_at'],
                'indexes': [models.Index(fields=['gelir_kaydi', 'durum'], name='finans_geli_gelir_k_50c61a_idx'), models.Index(fields=['tahsilat_tarihi'], name='finans_geli_tahsila_9f2543_idx'), models.Index(fields=['mali_hesap'], name='finans_geli_mali_he_5b9780_idx')],
            },
        ),
    ]
