# Generated by Django 4.2.27 on 2026-07-01 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
        ('sube', '0002_sube_extended_profile'),
        ('egitim_yili', '0001_initial'),
        ('finans', '0011_gelir_tahsilat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakiyehareketi',
            name='kaynak',
            field=models.CharField(choices=[('tahsilat', 'Tahsilat'), ('tahsilat_iptal', 'Tahsilat İptal'), ('iade', 'İade'), ('gider', 'Gider'), ('gider_iptal', 'Gider İptal'), ('gelir', 'Gelir'), ('gelir_iptal', 'Gelir İptal'), ('avans', 'Avans'), ('mahsup', 'Cari Bakiye Mahsubu'), ('devir', 'Dönem Devri'), ('manuel', 'Manuel Düzeltme'), ('acilis', 'Açılış Bakiyesi'), ('transfer', 'Hesaplar Arası Transfer')], help_text='Bu hareketin nedeni (tahsilat, gider, devir vb.)', max_length=20, verbose_name='Hareket Kaynağı'),
        ),
        migrations.AlterField(
            model_name='odemeyontemi',
            name='tip',
            field=models.CharField(choices=[('nakit', 'Nakit'), ('pos', 'POS Cihazı'), ('havale_eft', 'Havale / EFT'), ('online', 'Online Ödeme'), ('cek', 'Çek'), ('senet', 'Senet')], default='nakit', help_text='Ödeme kanalı türü', max_length=20, verbose_name='Tip'),
        ),
        migrations.CreateModel(
            name='HesapTransferi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.IntegerField(help_text='Transfer tutarı — her zaman pozitif', verbose_name='Tutar (TL)')),
                ('transfer_turu', models.CharField(choices=[('virman', 'Virman'), ('kasadan_bankaya', 'Bankaya Para Yatırma'), ('bankadan_kasaya', 'Bankadan Kasaya Çekme')], default='virman', max_length=20, verbose_name='Transfer Türü')),
                ('transfer_tarihi', models.DateField(verbose_name='Transfer Tarihi')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('kaynak_hareket_id', models.PositiveBigIntegerField(blank=True, help_text="Kaynak hesaptaki ÇIKIŞ hareketinin ID'si", null=True, verbose_name='Kaynak Bakiye Hareketi ID')),
                ('hedef_hareket_id', models.PositiveBigIntegerField(blank=True, help_text="Hedef hesaptaki GİRİŞ hareketinin ID'si", null=True, verbose_name='Hedef Bakiye Hareketi ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('egitim_yili', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hesap_transferleri', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('hedef_hesap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gelen_transferler', to='finans.malihesap', verbose_name='Hedef Hesap')),
                ('islem_yapan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hesap_transferleri', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('kaynak_hesap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giden_transferler', to='finans.malihesap', verbose_name='Kaynak Hesap')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hesap_transferleri', to='kurum.kurum', verbose_name='Kurum')),
                ('sube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hesap_transferleri', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Hesap Transferi',
                'verbose_name_plural': 'Hesap Transferleri',
                'db_table': 'finans_hesap_transferi',
                'ordering': ['-transfer_tarihi', '-created_at'],
                'indexes': [models.Index(fields=['kurum', 'sube', 'egitim_yili'], name='finans_hesa_kurum_i_5538e8_idx'), models.Index(fields=['kaynak_hesap', 'transfer_tarihi'], name='finans_hesa_kaynak__e170eb_idx'), models.Index(fields=['hedef_hesap', 'transfer_tarihi'], name='finans_hesa_hedef_h_bf657e_idx'), models.Index(fields=['transfer_tarihi'], name='finans_hesa_transfe_43da78_idx')],
            },
        ),
    ]
