# Generated by Django 4.2.27 on 2026-07-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sube', '0002_sube_extended_profile'),
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
        ('finans', '0020_backfill_cari_gelir_sube'),
    ]

    operations = [
        migrations.CreateModel(
            name='GelirKategorisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150, verbose_name='Kategori Adı')),
                ('ikon', models.CharField(blank=True, default='', max_length=10, verbose_name='İkon')),
                ('renk', models.CharField(blank=True, default='', max_length=7, verbose_name='Renk')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('siralama', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('silindi_mi', models.BooleanField(db_index=True, default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Gelir Kategorisi',
                'verbose_name_plural': 'Gelir Kategorileri',
                'db_table': 'finans_gelir_kategorisi',
                'ordering': ['siralama', 'ad'],
            },
        ),
        migrations.RenameIndex(
            model_name='carihesap',
            new_name='finans_cari_kurum_i_0fe3e9_idx',
            old_name='finans_cari_kurum_s_hesap_idx',
        ),
        migrations.RenameIndex(
            model_name='carihesap',
            new_name='finans_cari_kurum_i_ee4789_idx',
            old_name='finans_cari_kurum_s_aktif_idx',
        ),
        migrations.RenameIndex(
            model_name='carihesap',
            new_name='finans_cari_sube_id_a4bac2_idx',
            old_name='finans_cari_sube_v_idx',
        ),
        migrations.RenameIndex(
            model_name='giderkategorisi',
            new_name='finans_gide_kurum_i_9ed325_idx',
            old_name='finans_gide_kurum_s_7c1b2a_idx',
        ),
        migrations.AddField(
            model_name='gelirkategorisi',
            name='kurum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gelir_kategorileri', to='kurum.kurum', verbose_name='Kurum'),
        ),
        migrations.AddField(
            model_name='gelirkategorisi',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategoriler', to='finans.gelirkategorisi', verbose_name='Üst Kategori'),
        ),
        migrations.AddField(
            model_name='gelirkategorisi',
            name='sube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gelir_kategorileri', to='sube.sube', verbose_name='Şube'),
        ),
        migrations.AddField(
            model_name='carihesap',
            name='gelir_kategorileri',
            field=models.ManyToManyField(blank=True, related_name='cari_hesaplar', to='finans.gelirkategorisi', verbose_name='İlişkili Gelir Kategorileri'),
        ),
        migrations.AddField(
            model_name='gelirkaydi',
            name='gelir_kategorisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gelir_kayitlari', to='finans.gelirkategorisi', verbose_name='Gelir Kategorisi'),
        ),
        migrations.AddIndex(
            model_name='gelirkategorisi',
            index=models.Index(fields=['kurum', 'sube', 'parent', 'aktif_mi', 'silindi_mi'], name='finans_geli_kurum_i_ab514c_idx'),
        ),
        migrations.AddConstraint(
            model_name='gelirkategorisi',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi_mi', False)), fields=('sube', 'parent', 'ad'), name='unique_sube_gelir_kategori_ad'),
        ),
    ]
