# Generated by Django 4.2.27 on 2026-07-02 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
        ('sube', '0002_sube_extended_profile'),
        ('finans', '0022_mali_hesap_banka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malihesap',
            name='ad',
            field=models.CharField(help_text='Kullanıcıya görünen isim — örn: Vakıfbank Merkez, Merkez Nakit Kasası', max_length=200, verbose_name='Hesap Adı'),
        ),
        migrations.AlterField(
            model_name='malihesap',
            name='banka_adi',
            field=models.CharField(blank=True, default='', help_text='Banka seçiminin görünen adı (banka alanından türetilir)', max_length=100, verbose_name='Banka Adı'),
        ),
        migrations.AlterField(
            model_name='malihesap',
            name='tip',
            field=models.CharField(choices=[('banka', 'Banka Hesabı'), ('kasa', 'Nakit Kasa'), ('pos', 'POS Hesabı'), ('sanal_pos', 'Sanal POS'), ('e_cuzdan', 'E-Cüzdan'), ('diger', 'Diğer')], default='kasa', help_text='Hesabın türü', max_length=20, verbose_name='Hesap Tipi'),
        ),
        migrations.CreateModel(
            name='IslemMasrafi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaynak_tip', models.CharField(choices=[('tahsilat', 'Sözleşme Tahsilatı'), ('gelir_tahsilat', 'Gelir Tahsilatı'), ('gider_odeme', 'Gider Ödemesi')], max_length=30, verbose_name='Kaynak Tipi')),
                ('kaynak_id', models.PositiveIntegerField(verbose_name='Kaynak Kayıt ID')),
                ('kesinti_turu', models.CharField(choices=[('havale_masrafi', 'Havale Masrafı'), ('eft_masrafi', 'EFT Masrafı'), ('fast_ucreti', 'FAST Ücreti'), ('pos_komisyonu', 'POS Komisyonu'), ('sanal_pos_komisyonu', 'Sanal POS Komisyonu'), ('online_odeme_komisyonu', 'Online Ödeme Komisyonu'), ('hesap_isletim_ucreti', 'Hesap İşletim Ücreti'), ('doviz_cevrim_masrafi', 'Döviz Çevrim Masrafı'), ('diger_banka_masraflari', 'Diğer Banka Masrafları')], max_length=40, verbose_name='Kesinti Türü')),
                ('kesinti_tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Kesinti Tutarı')),
                ('kesinti_aciklama', models.CharField(blank=True, default='', max_length=500, verbose_name='Kesinti Açıklaması')),
                ('durum', models.CharField(choices=[('aktif', 'Aktif'), ('iptal', 'İptal')], default='aktif', max_length=10, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bakiye_hareketi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='islem_masraflari', to='finans.bakiyehareketi', verbose_name='Bakiye Hareketi')),
                ('gider_kaydi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='islem_masraflari', to='finans.giderkaydi', verbose_name='Gider Kaydı')),
                ('gider_odeme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='islem_masrafi', to='finans.giderodeme', verbose_name='Gider Ödeme')),
                ('islem_yapan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islem_masraflari', to=settings.AUTH_USER_MODEL)),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islem_masraflari', to='kurum.kurum')),
                ('sube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islem_masraflari', to='sube.sube')),
            ],
            options={
                'verbose_name': 'İşlem Masrafı',
                'verbose_name_plural': 'İşlem Masrafları',
                'db_table': 'finans_islem_masrafi',
                'indexes': [models.Index(fields=['kaynak_tip', 'kaynak_id'], name='finans_isle_kaynak__9d6564_idx'), models.Index(fields=['kurum', 'durum'], name='finans_isle_kurum_i_050250_idx')],
            },
        ),
    ]
