# Generated by Django 4.2.27 on 2026-07-03 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finans', '0024_seed_banka_giderleri'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='odemeyontemi',
            name='unique_mali_hesap_odeme_yontemi_ad',
        ),
        migrations.AlterField(
            model_name='islemmasrafi',
            name='kaynak_tip',
            field=models.CharField(choices=[('tahsilat', 'Sözleşme Tahsilatı'), ('gelir_tahsilat', 'Gelir Tahsilatı'), ('gider_odeme', 'Gider Ödemesi'), ('cari_odeme', 'Serbest Cari Ödeme'), ('hesap_transferi', 'Hesap Transferi')], max_length=30, verbose_name='Kaynak Tipi'),
        ),
        migrations.AlterField(
            model_name='odemeyontemi',
            name='mali_hesap',
            field=models.ForeignKey(blank=True, help_text='Çek/senet tipinde boş bırakılır; diğer tiplerde zorunludur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odeme_yontemleri', to='finans.malihesap', verbose_name='Mali Hesap'),
        ),
        migrations.AddConstraint(
            model_name='odemeyontemi',
            constraint=models.UniqueConstraint(condition=models.Q(('mali_hesap__isnull', False), ('silindi_mi', False)), fields=('mali_hesap', 'ad'), name='unique_mali_hesap_odeme_yontemi_ad'),
        ),
        migrations.AddConstraint(
            model_name='odemeyontemi',
            constraint=models.UniqueConstraint(condition=models.Q(('mali_hesap__isnull', True), ('silindi_mi', False)), fields=('kurum', 'ad'), name='unique_kurum_odeme_yontemi_ad_no_mali'),
        ),
    ]
