# Generated by Django 4.2.9 on 2026-07-07 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sube', '0003_sube_branding'),
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finans', '0026_gider_taksit_odeme_yontemi'),
    ]

    operations = [
        migrations.AddField(
            model_name='carihesap',
            name='kategori',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='carihesap',
            name='para_birimi',
            field=models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi'),
        ),
        migrations.AddField(
            model_name='carihesap',
            name='risk_limiti',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 = limit yok. Açık bakiye bu limiti aşarsa risk uyarısı verilir.', max_digits=15, verbose_name='Risk Limiti'),
        ),
        migrations.AddField(
            model_name='carihesap',
            name='varsayilan_vade_gun',
            field=models.PositiveIntegerField(default=0, help_text='İşlemler için varsayılan vade süresi (gün).', verbose_name='Varsayılan Vade (gün)'),
        ),
        migrations.AlterField(
            model_name='carihesap',
            name='hesap_turu',
            field=models.CharField(choices=[('musteri', 'Müşteri'), ('tedarikci', 'Tedarikçi'), ('karma', 'Karma'), ('gelir_hesabi', 'Gelir Hesabı'), ('gider_hesabi', 'Gider Hesabı'), ('diger', 'Diğer')], default='tedarikci', max_length=20, verbose_name='Hesap Türü'),
        ),
        migrations.CreateModel(
            name='CariEtiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=60, verbose_name='Etiket Adı')),
                ('renk', models.CharField(blank=True, default='#0262a7', max_length=20, verbose_name='Renk')),
                ('silindi_mi', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cari_etiketleri', to='kurum.kurum', verbose_name='Kurum')),
                ('sube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cari_etiketleri', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Cari Etiket',
                'verbose_name_plural': 'Cari Etiketler',
                'db_table': 'finans_cari_etiket',
                'ordering': ['ad'],
            },
        ),
        migrations.AddField(
            model_name='carihesap',
            name='etiketler',
            field=models.ManyToManyField(blank=True, related_name='cari_hesaplar', to='finans.carietiket', verbose_name='Etiketler'),
        ),
        migrations.CreateModel(
            name='CariKayitliGorunum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Görünüm Adı')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Yapılandırma')),
                ('varsayilan_mi', models.BooleanField(default=False, verbose_name='Varsayılan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cari_gorunumleri', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cari_gorunumleri', to='kurum.kurum', verbose_name='Kurum')),
                ('sube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cari_gorunumleri', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Cari Kayıtlı Görünüm',
                'verbose_name_plural': 'Cari Kayıtlı Görünümler',
                'db_table': 'finans_cari_kayitli_gorunum',
                'ordering': ['ad'],
                'indexes': [models.Index(fields=['kurum', 'kullanici'], name='finans_cari_kurum_i_32950f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='carietiket',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi_mi', False)), fields=('kurum', 'sube', 'ad'), name='uq_cari_etiket_kurum_sube_ad'),
        ),
    ]
