# Generated by Django 4.2.9 on 2026-07-07 22:50

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sube', '0003_sube_branding'),
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
        ('finans', '0027_carihesap_kategori_carihesap_para_birimi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelirkaydi',
            name='etiketler',
            field=models.ManyToManyField(blank=True, related_name='gelir_kayitlari', to='finans.carietiket', verbose_name='Etiketler'),
        ),
        migrations.AddField(
            model_name='giderkaydi',
            name='etiketler',
            field=models.ManyToManyField(blank=True, related_name='gider_kayitlari', to='finans.carietiket', verbose_name='Etiketler'),
        ),
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150, verbose_name='Ad')),
                ('kod', models.CharField(blank=True, default='', max_length=40, verbose_name='Kod')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('siralama', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('silindi_mi', models.BooleanField(db_index=True, default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('baslangic_tarihi', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('butce', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Bütçe')),
                ('durum', models.CharField(choices=[('aktif', 'Aktif'), ('tamamlandi', 'Tamamlandı'), ('beklemede', 'Beklemede'), ('iptal', 'İptal')], default='aktif', max_length=15, verbose_name='Durum')),
                ('renk', models.CharField(blank=True, default='#0262a7', max_length=20, verbose_name='Renk')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='kurum.kurum', verbose_name='Kurum')),
                ('sube', models.ForeignKey(blank=True, help_text='Boş bırakılırsa kurum geneli tanım olur.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'db_table': 'finans_proje',
                'ordering': ['siralama', 'ad'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaliyetMerkezi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150, verbose_name='Ad')),
                ('kod', models.CharField(blank=True, default='', max_length=40, verbose_name='Kod')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('siralama', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('silindi_mi', models.BooleanField(db_index=True, default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('tip', models.CharField(choices=[('maliyet', 'Maliyet Merkezi'), ('gider', 'Gider Merkezi')], default='maliyet', max_length=10, verbose_name='Tip')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='kurum.kurum', verbose_name='Kurum')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_merkezler', to='finans.maliyetmerkezi', verbose_name='Üst Merkez')),
                ('sube', models.ForeignKey(blank=True, help_text='Boş bırakılırsa kurum geneli tanım olur.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Maliyet/Gider Merkezi',
                'verbose_name_plural': 'Maliyet/Gider Merkezleri',
                'db_table': 'finans_maliyet_merkezi',
                'ordering': ['siralama', 'ad'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GelirKaynagi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150, verbose_name='Ad')),
                ('kod', models.CharField(blank=True, default='', max_length=40, verbose_name='Kod')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('siralama', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('silindi_mi', models.BooleanField(db_index=True, default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='kurum.kurum', verbose_name='Kurum')),
                ('sube', models.ForeignKey(blank=True, help_text='Boş bırakılırsa kurum geneli tanım olur.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Gelir Kaynağı',
                'verbose_name_plural': 'Gelir Kaynakları',
                'db_table': 'finans_gelir_kaynagi',
                'ordering': ['siralama', 'ad'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AciklamaSablonu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150, verbose_name='Ad')),
                ('kod', models.CharField(blank=True, default='', max_length=40, verbose_name='Kod')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('siralama', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('silindi_mi', models.BooleanField(db_index=True, default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('icerik', models.TextField(blank=True, default='', verbose_name='Şablon İçeriği')),
                ('kapsam', models.CharField(choices=[('genel', 'Genel'), ('gelir', 'Gelir'), ('gider', 'Gider')], default='genel', max_length=10, verbose_name='Kapsam')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='kurum.kurum', verbose_name='Kurum')),
                ('sube', models.ForeignKey(blank=True, help_text='Boş bırakılırsa kurum geneli tanım olur.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Açıklama Şablonu',
                'verbose_name_plural': 'Açıklama Şablonları',
                'db_table': 'finans_aciklama_sablonu',
                'ordering': ['siralama', 'ad'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gelirkaydi',
            name='gelir_kaynagi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gelir_kayitlari', to='finans.gelirkaynagi', verbose_name='Gelir Kaynağı'),
        ),
        migrations.AddField(
            model_name='gelirkaydi',
            name='proje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gelir_kayitlari', to='finans.proje', verbose_name='Proje'),
        ),
        migrations.AddField(
            model_name='giderkaydi',
            name='maliyet_merkezi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gider_kayitlari', to='finans.maliyetmerkezi', verbose_name='Maliyet/Gider Merkezi'),
        ),
        migrations.AddField(
            model_name='giderkaydi',
            name='proje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gider_kayitlari', to='finans.proje', verbose_name='Proje'),
        ),
        migrations.AddIndex(
            model_name='proje',
            index=models.Index(fields=['kurum', 'sube', 'durum', 'aktif_mi', 'silindi_mi'], name='finans_proj_kurum_i_f16aef_idx'),
        ),
        migrations.AddConstraint(
            model_name='proje',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi_mi', False)), fields=('kurum', 'sube', 'ad'), name='uq_proje_kurum_sube_ad'),
        ),
        migrations.AddIndex(
            model_name='maliyetmerkezi',
            index=models.Index(fields=['kurum', 'sube', 'tip', 'aktif_mi', 'silindi_mi'], name='finans_mali_kurum_i_90d01a_idx'),
        ),
        migrations.AddConstraint(
            model_name='maliyetmerkezi',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi_mi', False)), fields=('kurum', 'sube', 'tip', 'parent', 'ad'), name='uq_maliyet_merkezi_kurum_sube_tip_ad'),
        ),
        migrations.AddIndex(
            model_name='gelirkaynagi',
            index=models.Index(fields=['kurum', 'sube', 'aktif_mi', 'silindi_mi'], name='finans_geli_kurum_i_b16bfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='gelirkaynagi',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi_mi', False)), fields=('kurum', 'sube', 'ad'), name='uq_gelir_kaynagi_kurum_sube_ad'),
        ),
        migrations.AddIndex(
            model_name='aciklamasablonu',
            index=models.Index(fields=['kurum', 'sube', 'kapsam', 'aktif_mi', 'silindi_mi'], name='finans_acik_kurum_i_85345c_idx'),
        ),
        migrations.AddConstraint(
            model_name='aciklamasablonu',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi_mi', False)), fields=('kurum', 'sube', 'kapsam', 'ad'), name='uq_aciklama_sablonu_kurum_sube_kapsam_ad'),
        ),
    ]
