# Generated by Django 4.2.9 on 2026-07-07 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
        ('sube', '0003_sube_branding'),
        ('finans', '0028_gelirkaydi_etiketler_giderkaydi_etiketler_proje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinansIslemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modul', models.CharField(choices=[('gelir', 'Gelir'), ('gider', 'Gider'), ('tahsilat', 'Tahsilat'), ('odeme', 'Ödeme'), ('tanim', 'Tanım'), ('cari', 'Cari'), ('kasa', 'Kasa/Banka'), ('rapor', 'Rapor')], max_length=20, verbose_name='Modül')),
                ('eylem', models.CharField(choices=[('olustur', 'Oluşturma'), ('guncelle', 'Güncelleme'), ('onayla', 'Onaylama'), ('iptal', 'İptal'), ('sil', 'Silme'), ('odeme', 'Ödeme'), ('tahsilat', 'Tahsilat'), ('export', 'Dışa Aktarma')], max_length=20, verbose_name='Eylem')),
                ('kayit_tip', models.CharField(blank=True, default='', max_length=50, verbose_name='Kayıt Tipi')),
                ('kayit_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kayıt ID')),
                ('aciklama', models.CharField(blank=True, default='', max_length=255, verbose_name='Açıklama')),
                ('tutar', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Tutar')),
                ('detay', models.JSONField(blank=True, default=None, null=True, verbose_name='Detay')),
                ('ip_adresi', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finans_islem_loglari', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finans_islem_loglari', to='kurum.kurum', verbose_name='Kurum')),
                ('sube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finans_islem_loglari', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Finans İşlem Logu',
                'verbose_name_plural': 'Finans İşlem Logları',
                'db_table': 'finans_islem_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kurum', 'sube', '-created_at'], name='finans_isle_kurum_i_689212_idx'), models.Index(fields=['modul', 'eylem'], name='finans_isle_modul_984389_idx'), models.Index(fields=['kayit_tip', 'kayit_id'], name='finans_isle_kayit_t_cb9427_idx'), models.Index(fields=['kullanici', '-created_at'], name='finans_isle_kullani_469a6a_idx')],
            },
        ),
    ]
