# Generated by Django 4.2.27 on 2026-07-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finans', '0029_finansislemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelirkaydi',
            name='kdv_mod',
            field=models.CharField(default='haric', help_text='haric | dahil | muaf — brüt/net hesaplama modu', max_length=10, verbose_name='KDV Modu'),
        ),
        migrations.AddField(
            model_name='giderkaydi',
            name='kdv_mod',
            field=models.CharField(default='haric', help_text='haric | dahil | muaf — brüt/net hesaplama modu', max_length=10, verbose_name='KDV Modu'),
        ),
        migrations.AddField(
            model_name='gidertaksit',
            name='aciklama',
            field=models.CharField(blank=True, default='', help_text='Manuel taksit planında satır açıklaması', max_length=255, verbose_name='Açıklama'),
        ),
    ]
