# Generated by Django 4.2.27 on 2026-07-08 01:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
        ('sube', '0003_sube_branding'),
        ('finans', '0030_gelirkaydi_kdv_mod_giderkaydi_kdv_mod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasrafTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150, verbose_name='Ad')),
                ('kod', models.CharField(blank=True, default='', max_length=40, verbose_name='Kod')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('siralama', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('silindi_mi', models.BooleanField(db_index=True, default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('odeme_tipi', models.CharField(blank=True, default='', help_text="Boşsa tüm yöntemler; dolu ise ör. 'eft', 'havale', 'pos'.", max_length=30, verbose_name='İlgili Ödeme Tipi')),
                ('kesinti_turu', models.CharField(blank=True, default='diger_banka_masraflari', help_text='Banka gider kategorisi eşlemesi için KesintiTuru değeri.', max_length=40, verbose_name='Muhasebe Kesinti Türü')),
                ('varsayilan_tutar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Önerilen/otomatik dolan masraf tutarı (0 = yok).', max_digits=15, verbose_name='Varsayılan Tutar')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='kurum.kurum', verbose_name='Kurum')),
                ('sube', models.ForeignKey(blank=True, help_text='Boş bırakılırsa kurum geneli tanım olur.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Masraf Türü',
                'verbose_name_plural': 'Masraf Türleri',
                'db_table': 'finans_masraf_turu',
                'ordering': ['siralama', 'ad'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='islemmasrafi',
            name='masraf_turu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islem_masraflari', to='finans.masrafturu', verbose_name='Masraf Türü'),
        ),
        migrations.AddIndex(
            model_name='masrafturu',
            index=models.Index(fields=['kurum', 'sube', 'aktif_mi', 'silindi_mi'], name='finans_masr_kurum_i_82da0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='masrafturu',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi_mi', False)), fields=('kurum', 'sube', 'ad'), name='uq_masraf_turu_kurum_sube_ad'),
        ),
    ]
