# Generated by Django 4.2.27 on 2026-07-09 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finans', '0032_seed_masraf_turleri'),
    ]

    operations = [
        migrations.AddField(
            model_name='hesaptransferi',
            name='iptal_eden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iptal_ettigi_hesap_transferleri', to=settings.AUTH_USER_MODEL, verbose_name='İptal Eden'),
        ),
        migrations.AddField(
            model_name='hesaptransferi',
            name='iptal_edildi',
            field=models.BooleanField(default=False, verbose_name='İptal Edildi'),
        ),
        migrations.AddField(
            model_name='hesaptransferi',
            name='iptal_nedeni',
            field=models.TextField(blank=True, default='', verbose_name='İptal Nedeni'),
        ),
        migrations.AddField(
            model_name='hesaptransferi',
            name='iptal_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İptal Tarihi'),
        ),
    ]
