from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _column_exists(cursor, table, column):
    cursor.execute(
        """
        SELECT 1 FROM information_schema.columns
        WHERE table_name = %s AND column_name = %s
        """,
        [table, column],
    )
    return cursor.fetchone() is not None


def _table_exists(cursor, table):
    cursor.execute(
        """
        SELECT 1 FROM information_schema.tables
        WHERE table_name = %s
        """,
        [table],
    )
    return cursor.fetchone() is not None


def _index_exists(cursor, index_name):
    cursor.execute(
        """
        SELECT 1 FROM pg_indexes
        WHERE indexname = %s
        """,
        [index_name],
    )
    return cursor.fetchone() is not None


def ensure_gider_belge_odeme_plani(apps, schema_editor):
    """Feature dalındaki 0035 kolonları canlıda olabilir; yoksa ekle."""
    with schema_editor.connection.cursor() as cursor:
        if not _column_exists(cursor, 'finans_gider_odeme', 'odeme_belge_no'):
            cursor.execute(
                """
                ALTER TABLE finans_gider_odeme
                ADD COLUMN odeme_belge_no varchar(30) NOT NULL DEFAULT ''
                """
            )
        else:
            cursor.execute(
                "UPDATE finans_gider_odeme SET odeme_belge_no = '' WHERE odeme_belge_no IS NULL"
            )
            cursor.execute(
                "ALTER TABLE finans_gider_odeme ALTER COLUMN odeme_belge_no SET DEFAULT ''"
            )
            cursor.execute(
                "ALTER TABLE finans_gider_odeme ALTER COLUMN odeme_belge_no SET NOT NULL"
            )

        if not _column_exists(cursor, 'finans_gider_taksit', 'mali_hesap_id'):
            cursor.execute(
                """
                ALTER TABLE finans_gider_taksit
                ADD COLUMN mali_hesap_id bigint NULL
                """
            )
            cursor.execute(
                """
                ALTER TABLE finans_gider_taksit
                ADD CONSTRAINT finans_gidertaksit_mali_hesap_fk
                FOREIGN KEY (mali_hesap_id) REFERENCES finans_mali_hesap(id)
                ON DELETE SET NULL
                """
            )

        if not _column_exists(cursor, 'finans_gider_taksit', 'odeme_tarihi'):
            cursor.execute(
                """
                ALTER TABLE finans_gider_taksit
                ADD COLUMN odeme_tarihi date NULL
                """
            )

        if not _table_exists(cursor, 'finans_gider_ekli_belge'):
            cursor.execute(
                """
                CREATE TABLE finans_gider_ekli_belge (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    dosya varchar(100) NOT NULL,
                    dosya_adi varchar(255) NOT NULL,
                    dosya_turu varchar(20) NOT NULL DEFAULT 'fatura_fis',
                    aciklama varchar(255) NOT NULL DEFAULT '',
                    dosya_boyutu integer NOT NULL DEFAULT 0,
                    created_at timestamp with time zone NOT NULL,
                    gider_kaydi_id bigint NOT NULL
                        REFERENCES finans_gider_kaydi(id) ON DELETE CASCADE,
                    yukleyen_id integer NULL
                        REFERENCES auth_user(id) ON DELETE SET NULL
                )
                """
            )

        if not _index_exists(cursor, 'finans_gide_kurum_i_belge_idx'):
            cursor.execute(
                """
                CREATE INDEX finans_gide_kurum_i_belge_idx
                ON finans_gider_kaydi (kurum_id, islem_belge_no)
                """
            )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finans', '0035_giderkaydi_islem_belge_no'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_gider_belge_odeme_plani, noop_reverse),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='giderodeme',
                    name='odeme_belge_no',
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        default='',
                        help_text='Yalnızca gerçekleşen ödeme için: ODM-YYYY-000001',
                        max_length=30,
                        verbose_name='Ödeme Belge No',
                    ),
                ),
                migrations.AddField(
                    model_name='gidertaksit',
                    name='mali_hesap',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='Son gerçekleşen ödemenin çıktığı hesap',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='gider_taksitleri',
                        to='finans.malihesap',
                        verbose_name='Mali Hesap',
                    ),
                ),
                migrations.AddField(
                    model_name='gidertaksit',
                    name='odeme_tarihi',
                    field=models.DateField(
                        blank=True,
                        help_text='Son gerçekleşen ödeme tarihi',
                        null=True,
                        verbose_name='Ödeme Tarihi',
                    ),
                ),
                migrations.CreateModel(
                    name='GiderEkliBelge',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('dosya', models.FileField(upload_to='finans/gider_ekleri/%Y/%m/', verbose_name='Dosya')),
                        ('dosya_adi', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                        ('dosya_turu', models.CharField(
                            choices=[
                                ('fatura_fis', 'Ekli Fatura / Fiş'),
                                ('dekont', 'Dekont'),
                                ('diger', 'Diğer'),
                            ],
                            default='fatura_fis',
                            max_length=20,
                            verbose_name='Dosya Türü',
                        )),
                        ('aciklama', models.CharField(blank=True, default='', max_length=255, verbose_name='Açıklama')),
                        ('dosya_boyutu', models.PositiveIntegerField(default=0, verbose_name='Boyut (byte)')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('gider_kaydi', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='ekli_belgeler',
                            to='finans.giderkaydi',
                            verbose_name='Gider Kaydı',
                        )),
                        ('yukleyen', models.ForeignKey(
                            blank=True,
                            null=True,
                            on_delete=django.db.models.deletion.SET_NULL,
                            to=settings.AUTH_USER_MODEL,
                            verbose_name='Yükleyen',
                        )),
                    ],
                    options={
                        'verbose_name': 'Gider Ekli Belge',
                        'verbose_name_plural': 'Gider Ekli Belgeler',
                        'db_table': 'finans_gider_ekli_belge',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.AddIndex(
                    model_name='giderkaydi',
                    index=models.Index(fields=['kurum', 'islem_belge_no'], name='finans_gide_kurum_i_belge_idx'),
                ),
            ],
        ),
    ]
