# Generated by Django 4.2.27 on 2026-09-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finans', '0036_gider_belge_odeme_plani'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='giderkaydi',
            new_name='finans_gide_kurum_i_9a35a4_idx',
            old_name='finans_gide_kurum_i_belge_idx',
        ),
        migrations.AlterField(
            model_name='giderkaydi',
            name='fatura_no',
            field=models.CharField(blank=True, default='', help_text='Tedarikçinin fatura / fiş numarası (opsiyonel)', max_length=50, verbose_name='Fatura / Belge No'),
        ),
        migrations.AlterField(
            model_name='gidertaksit',
            name='durum',
            field=models.CharField(choices=[('beklemede', 'Bekliyor'), ('ileri_tarihli', 'İleri Tarihli'), ('kismi_odendi', 'Kısmi Ödendi'), ('odendi', 'Ödendi'), ('gecikti', 'Gecikmiş'), ('iptal', 'İptal')], default='beklemede', max_length=20, verbose_name='Durum'),
        ),
    ]
