# Generated by Django 4.2.27 on 2026-07-12 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlertState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('severity', models.CharField(default='warning', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'sistem_yonetimi_alert',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_interval_sec', models.PositiveIntegerField(default=20)),
                ('disk_warn_percent', models.PositiveSmallIntegerField(default=85)),
                ('disk_critical_percent', models.PositiveSmallIntegerField(default=90)),
                ('error_rate_warn_per_min', models.PositiveIntegerField(default=10)),
                ('scheduler_stale_minutes', models.PositiveIntegerField(default=15)),
                ('ops_enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sistem_yonetimi_settings',
            },
        ),
        migrations.CreateModel(
            name='SystemTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('level', models.CharField(default='info', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'sistem_yonetimi_timeline',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(db_index=True)),
                ('cpu_percent', models.FloatField(default=0)),
                ('ram_percent', models.FloatField(default=0)),
                ('ram_used_bytes', models.BigIntegerField(default=0)),
                ('ram_total_bytes', models.BigIntegerField(default=0)),
                ('disk_percent', models.FloatField(default=0)),
                ('disk_used_bytes', models.BigIntegerField(default=0)),
                ('disk_total_bytes', models.BigIntegerField(default=0)),
                ('disk_read_bytes', models.BigIntegerField(default=0)),
                ('disk_write_bytes', models.BigIntegerField(default=0)),
                ('net_bytes_sent', models.BigIntegerField(default=0)),
                ('net_bytes_recv', models.BigIntegerField(default=0)),
                ('pg_connections', models.PositiveIntegerField(default=0)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'sistem_yonetimi_metric',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['-collected_at'], name='sistem_metric_at_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('result_message', models.TextField(blank=True, default='')),
                ('output', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sistem_yonetimi_job_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('module', models.CharField(blank=True, default='', max_length=64)),
                ('error_type', models.CharField(blank=True, default='', max_length=128)),
                ('message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, default='')),
                ('request_url', models.TextField(blank=True, default='')),
                ('http_method', models.CharField(blank=True, default='', max_length=16)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('request_params', models.JSONField(blank=True, default=dict)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='open', max_length=20)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sistem_yonetimi_error',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('module', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sistem_yonetimi_audit',
                'ordering': ['-created_at'],
            },
        ),
    ]
