# Generated by Django 4.2.9 on 2026-03-14 00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kurum_id', models.IntegerField(verbose_name='Kurum ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Başlık')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('durum', models.CharField(choices=[('DRAFT', 'Taslak'), ('SCHEDULED', 'Planlandı'), ('IN_PROGRESS', 'Devam Ediyor'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi')], default='SCHEDULED', max_length=20, verbose_name='Durum')),
                ('baslangic', models.DateTimeField(verbose_name='Başlangıç Zamanı')),
                ('bitis', models.DateTimeField(verbose_name='Bitiş Zamanı')),
                ('tum_gun', models.BooleanField(default=False, verbose_name='Tüm Gün')),
                ('tekrar_tipi', models.CharField(choices=[('NONE', 'Tekrar Yok'), ('DAILY', 'Her Gün'), ('WEEKLY', 'Her Hafta'), ('BIWEEKLY', 'İki Haftada Bir'), ('MONTHLY', 'Her Ay')], default='NONE', max_length=20, verbose_name='Tekrar Tipi')),
                ('tekrar_bitis', models.DateField(blank=True, null=True, verbose_name='Tekrar Bitiş Tarihi')),
                ('salon_id', models.UUIDField(blank=True, null=True, verbose_name='Salon ID')),
                ('salon_adi', models.CharField(blank=True, default='', max_length=200, verbose_name='Salon Adı')),
                ('konum', models.CharField(blank=True, default='', max_length=300, verbose_name='Konum')),
                ('sinif_ids', models.JSONField(blank=True, default=list, verbose_name='Sınıf ID listesi')),
                ('ogretmen_id', models.IntegerField(blank=True, null=True, verbose_name='Öğretmen/Koç ID')),
                ('ogrenci_ids', models.JSONField(blank=True, default=list, verbose_name='Öğrenci ID listesi')),
                ('kaynak_modul', models.CharField(blank=True, default='', help_text='coaching, olcme, etut vb.', max_length=50, verbose_name='Kaynak Modül')),
                ('kaynak_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Kaynak ID')),
                ('renk', models.CharField(blank=True, default='', max_length=7, verbose_name='Özel Renk')),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='Oluşturan')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Güncelleyen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Etkinlik',
                'verbose_name_plural': 'Etkinlikler',
                'db_table': 'takvim_etkinlik',
                'ordering': ['baslangic'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kurum_id', models.IntegerField(verbose_name='Kurum ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Tür Adı')),
                ('kategori', models.CharField(choices=[('DENEME', 'Deneme Sınavı'), ('ETUT', 'Etüt'), ('GORUSME', 'Koç Görüşmesi'), ('DERS', 'Ders'), ('TOPLANTI', 'Toplantı'), ('ETKINLIK', 'Kurum Etkinliği'), ('TATIL', 'Tatil / İzin'), ('DIGER', 'Diğer')], default='DIGER', max_length=20, verbose_name='Kategori')),
                ('renk', models.CharField(default='#3B82F6', max_length=7, verbose_name='Renk Kodu')),
                ('ikon', models.CharField(default='📅', max_length=10, verbose_name='İkon')),
                ('varsayilan_sure_dk', models.PositiveIntegerField(default=60, verbose_name='Varsayılan Süre (dk)')),
                ('is_system', models.BooleanField(default=False, verbose_name='Sistem Türü')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Etkinlik Türü',
                'verbose_name_plural': 'Etkinlik Türleri',
                'db_table': 'takvim_etkinlik_turu',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='ReminderSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kurum_id', models.IntegerField(verbose_name='Kurum ID')),
                ('miktar', models.PositiveIntegerField(verbose_name='Miktar')),
                ('birim', models.CharField(choices=[('MINUTES', 'Dakika'), ('HOURS', 'Saat'), ('DAYS', 'Gün')], default='MINUTES', max_length=10, verbose_name='Birim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to='takvim.eventtype', verbose_name='Etkinlik Türü')),
            ],
            options={
                'verbose_name': 'Hatırlatma Ayarı',
                'verbose_name_plural': 'Hatırlatma Ayarları',
                'db_table': 'takvim_hatirlatma_ayari',
                'ordering': ['event_type', 'miktar'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('miktar', models.PositiveIntegerField(verbose_name='Miktar')),
                ('birim', models.CharField(choices=[('MINUTES', 'Dakika'), ('HOURS', 'Saat'), ('DAYS', 'Gün')], default='MINUTES', max_length=10, verbose_name='Birim')),
                ('hatirlatma_zamani', models.DateTimeField(verbose_name='Hatırlatma Zamanı')),
                ('durum', models.CharField(choices=[('PENDING', 'Bekliyor'), ('SENT', 'Gönderildi'), ('FAILED', 'Başarısız')], default='PENDING', max_length=10, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='takvim.event', verbose_name='Etkinlik')),
            ],
            options={
                'verbose_name': 'Hatırlatma',
                'verbose_name_plural': 'Hatırlatmalar',
                'db_table': 'takvim_hatirlatma',
                'ordering': ['hatirlatma_zamani'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('kurum_id', 'ad'), name='unique_event_type_per_kurum'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='takvim.eventtype', verbose_name='Etkinlik Türü'),
        ),
        migrations.AddField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='takvim.event', verbose_name='Ana Etkinlik'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['kurum_id', 'baslangic', 'bitis'], name='idx_event_kurum_zaman'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['kurum_id', 'durum'], name='idx_event_kurum_durum'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['salon_id'], name='idx_event_salon'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['ogretmen_id'], name='idx_event_ogretmen'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['kaynak_modul', 'kaynak_id'], name='idx_event_kaynak'),
        ),
    ]
