# Generated by Django 4.2.9 on 2026-03-14 01:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='kanal',
            field=models.CharField(choices=[('APP', 'Uygulama Bildirimi'), ('SMS', 'SMS'), ('EMAIL', 'E-posta')], default='APP', max_length=10, verbose_name='Bildirim Kanalı'),
        ),
        migrations.AddField(
            model_name='remindersetting',
            name='alici_tipler',
            field=models.JSONField(blank=True, default=list, help_text='["OGRENCI", "OGRETMEN", "VELI"] — Boşsa tüm ilgililer', verbose_name='Alıcı Tipleri'),
        ),
        migrations.AddField(
            model_name='remindersetting',
            name='kanallar',
            field=models.JSONField(blank=True, default=list, help_text='["APP", "SMS", "EMAIL"] — Boşsa sadece APP', verbose_name='Bildirim Kanalları'),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kurum_id', models.IntegerField(verbose_name='Kurum ID')),
                ('user_id', models.IntegerField(verbose_name='Alıcı Kullanıcı ID')),
                ('alici_tip', models.CharField(choices=[('OGRENCI', 'Öğrenci'), ('OGRETMEN', 'Öğretmen / Koç'), ('VELI', 'Veli'), ('PERSONEL', 'Personel')], default='OGRENCI', max_length=20, verbose_name='Alıcı Tipi')),
                ('kanal', models.CharField(choices=[('APP', 'Uygulama Bildirimi'), ('SMS', 'SMS'), ('EMAIL', 'E-posta')], max_length=10, verbose_name='Bildirim Kanalı')),
                ('durum', models.CharField(choices=[('PENDING', 'Bekliyor'), ('SENT', 'Gönderildi'), ('DELIVERED', 'İletildi'), ('READ', 'Okundu'), ('FAILED', 'Başarısız')], default='PENDING', max_length=15, verbose_name='Durum')),
                ('baslik', models.CharField(max_length=255, verbose_name='Başlık')),
                ('mesaj', models.TextField(blank=True, default='', verbose_name='Mesaj')),
                ('hata_mesaji', models.TextField(blank=True, default='', verbose_name='Hata Mesajı')),
                ('deneme_sayisi', models.PositiveIntegerField(default=0, verbose_name='Deneme Sayısı')),
                ('max_deneme', models.PositiveIntegerField(default=3, verbose_name='Maks Deneme')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderim Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='takvim.event', verbose_name='Etkinlik')),
                ('reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='takvim.reminder', verbose_name='Hatırlatma')),
            ],
            options={
                'verbose_name': 'Bildirim Logu',
                'verbose_name_plural': 'Bildirim Logları',
                'db_table': 'takvim_bildirim_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kurum_id', models.IntegerField(verbose_name='Kurum ID')),
                ('user_id', models.IntegerField(verbose_name='Alıcı Kullanıcı ID')),
                ('alici_tip', models.CharField(choices=[('OGRENCI', 'Öğrenci'), ('OGRETMEN', 'Öğretmen / Koç'), ('VELI', 'Veli'), ('PERSONEL', 'Personel')], default='OGRENCI', max_length=20, verbose_name='Alıcı Tipi')),
                ('baslik', models.CharField(max_length=255, verbose_name='Başlık')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('ikon', models.CharField(default='🔔', max_length=10, verbose_name='İkon')),
                ('renk', models.CharField(default='#3B82F6', max_length=7, verbose_name='Renk')),
                ('url', models.CharField(blank=True, default='', help_text='/admin/takvim/genel gibi', max_length=500, verbose_name='Yönlendirme URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='takvim.event', verbose_name='İlişkili Etkinlik')),
                ('reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='takvim.reminder', verbose_name='İlişkili Hatırlatma')),
            ],
            options={
                'verbose_name': 'Uygulama Bildirimi',
                'verbose_name_plural': 'Uygulama Bildirimleri',
                'db_table': 'takvim_bildirim',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kurum_id', models.IntegerField(verbose_name='Kurum ID')),
                ('user_id', models.IntegerField(verbose_name='Kullanıcı ID')),
                ('app_enabled', models.BooleanField(default=True, verbose_name='Uygulama Bildirimi')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS Bildirimi')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='E-posta Bildirimi')),
                ('sessiz_baslangic', models.TimeField(blank=True, help_text='Bu saatten itibaren bildirim gönderilmez', null=True, verbose_name='Sessiz Saat Başlangıç')),
                ('sessiz_bitis', models.TimeField(blank=True, null=True, verbose_name='Sessiz Saat Bitiş')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='takvim.eventtype', verbose_name='Etkinlik Türü')),
            ],
            options={
                'verbose_name': 'Kullanıcı Bildirim Tercihi',
                'verbose_name_plural': 'Kullanıcı Bildirim Tercihleri',
                'db_table': 'takvim_kullanici_bildirim_tercihi',
                'indexes': [models.Index(fields=['kurum_id', 'user_id'], name='idx_userpref_kurum_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='usernotificationpreference',
            constraint=models.UniqueConstraint(fields=('user_id', 'event_type'), name='unique_user_notification_pref'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['kanal', 'durum'], name='idx_notiflog_kanal_durum'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user_id', '-created_at'], name='idx_notiflog_user'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['event_id'], name='idx_notiflog_event'),
        ),
        migrations.AddIndex(
            model_name='appnotification',
            index=models.Index(fields=['user_id', 'is_read'], name='idx_notif_user_read'),
        ),
        migrations.AddIndex(
            model_name='appnotification',
            index=models.Index(fields=['kurum_id', 'user_id', '-created_at'], name='idx_notif_kurum_user'),
        ),
    ]
