# Generated by Django 4.2.9 on 2026-03-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takvim', '0002_add_notification_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='donem_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dönem ID'),
        ),
        migrations.AddField(
            model_name='event',
            name='egitim_yili_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Eğitim Yılı ID'),
        ),
        migrations.AddField(
            model_name='event',
            name='sube_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Şube ID'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='kategori',
            field=models.CharField(choices=[('DENEME', 'Deneme Sınavı'), ('ETUT', 'Etüt'), ('GORUSME', 'Koç Görüşmesi'), ('DERS', 'Ders'), ('TOPLANTI', 'Toplantı'), ('ETKINLIK', 'Kurum Etkinliği'), ('TATIL', 'Tatil / İzin'), ('ODEV', 'Ödev'), ('CALISMA', 'Çalışma Programı'), ('DIGER', 'Diğer')], default='DIGER', max_length=20, verbose_name='Kategori'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['kurum_id', 'sube_id', 'egitim_yili_id'], name='idx_event_context'),
        ),
    ]
