# Generated by Django 4.2.27 on 2026-09-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takvim', '0007_backfill_event_sube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='kategori',
            field=models.CharField(choices=[('DENEME', 'Deneme Sınavı'), ('ETUT', 'Etüt'), ('GORUSME', 'Koç Görüşmesi'), ('DERS', 'Ders'), ('TOPLANTI', 'Toplantı'), ('ETKINLIK', 'Kurum Etkinliği'), ('TATIL', 'Tatil / İzin'), ('ODEV', 'Ödev'), ('CALISMA', 'Çalışma Programı'), ('GOREV', 'Görev'), ('DIGER', 'Diğer')], default='DIGER', max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='kanal',
            field=models.CharField(choices=[('APP', 'Uygulama Bildirimi'), ('SMS', 'SMS'), ('EMAIL', 'E-posta'), ('WHATSAPP', 'WhatsApp')], max_length=10, verbose_name='Bildirim Kanalı'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='kanal',
            field=models.CharField(choices=[('APP', 'Uygulama Bildirimi'), ('SMS', 'SMS'), ('EMAIL', 'E-posta'), ('WHATSAPP', 'WhatsApp')], default='APP', max_length=10, verbose_name='Bildirim Kanalı'),
        ),
    ]
