# Generated by Django 4.2.9 on 2026-02-09 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ogrenci', '0005_add_profil_foto'),
        ('resources', '0003_add_zorluk_seviyesi'),
        ('egitim_tanimlari', '0009_merge_20260201_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResourceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level_snapshot', models.CharField(blank=True, help_text='Atama anındaki zorluk seviyesi', max_length=20, verbose_name='Zorluk Seviyesi (Snapshot)')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Atandı'), ('IN_PROGRESS', 'Devam Ediyor'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi'), ('OVERDUE', 'Süresi Geçti')], default='ASSIGNED', max_length=20, verbose_name='Durum')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, help_text='0-100 arası ilerleme yüzdesi', verbose_name='İlerleme %')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Atanma Tarihi')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Son Tarih')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_resources', to=settings.AUTH_USER_MODEL, verbose_name='Koç')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_resource_assignments', to='egitim_tanimlari.ders', verbose_name='Ders')),
                ('resource_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='resources.resourcebook', verbose_name='Kaynak Kitap')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Öğrenci Kaynak Ataması',
                'verbose_name_plural': 'Öğrenci Kaynak Atamaları',
                'db_table': 'student_resource_assignment',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['student'], name='student_res_student_c6f16d_idx'), models.Index(fields=['coach'], name='student_res_coach_i_668ab4_idx'), models.Index(fields=['lesson'], name='student_res_lesson__98a66e_idx'), models.Index(fields=['resource_book'], name='student_res_resourc_f3720b_idx'), models.Index(fields=['status'], name='student_res_status_65ed83_idx'), models.Index(fields=['is_active'], name='student_res_is_acti_6dea4b_idx')],
                'unique_together': {('student', 'resource_book')},
            },
        ),
    ]
