# Generated by Django 4.2.27 on 2026-02-09 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ogrenci', '0005_add_profil_foto'),
        ('student_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePurchaseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('FINALIZED', 'Kesinleşti'), ('DELIVERED', 'Teslim Edildi'), ('CANCELLED', 'İptal Edildi')], default='DRAFT', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='Kesinleşme Tarihi')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('stationery_name', models.CharField(blank=True, max_length=200, verbose_name='Kırtasiye Adı')),
                ('stationery_address', models.TextField(blank=True, verbose_name='Kırtasiye Adresi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_lists', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_lists', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Satın Alma Listesi',
                'verbose_name_plural': 'Satın Alma Listeleri',
                'db_table': 'resource_purchase_list',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studentresourceassignment',
            name='ownership_type',
            field=models.CharField(choices=[('STUDENT_OWNED', 'Öğrencide Var'), ('TO_PURCHASE', 'Satın Alınacak'), ('INSTITUTION_PROVIDED', 'Kurum Verecek')], default='TO_PURCHASE', help_text='Kaynağın temin şekli', max_length=25, verbose_name='Sahiplik Durumu'),
        ),
        migrations.CreateModel(
            name='ResourcePurchaseListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Adet')),
                ('book_name_snapshot', models.CharField(blank=True, max_length=300, verbose_name='Kaynak Adı')),
                ('book_publisher_snapshot', models.CharField(blank=True, max_length=200, verbose_name='Yayınevi')),
                ('lesson_name_snapshot', models.CharField(blank=True, max_length=200, verbose_name='Ders Adı')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_list_items', to='student_resources.studentresourceassignment', verbose_name='Kaynak Ataması')),
                ('purchase_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='student_resources.resourcepurchaselist', verbose_name='Satın Alma Listesi')),
            ],
            options={
                'verbose_name': 'Satın Alma Kalemi',
                'verbose_name_plural': 'Satın Alma Kalemleri',
                'db_table': 'resource_purchase_list_item',
                'unique_together': {('purchase_list', 'assignment')},
            },
        ),
        migrations.AddIndex(
            model_name='resourcepurchaselist',
            index=models.Index(fields=['student'], name='resource_pu_student_8efb89_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcepurchaselist',
            index=models.Index(fields=['status'], name='resource_pu_status_f6ff27_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcepurchaselist',
            index=models.Index(fields=['created_at'], name='resource_pu_created_5c277f_idx'),
        ),
    ]
