# Generated by Django 4.2.27 on 2026-02-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_resources', '0002_add_ownership_and_purchase_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepurchaselist',
            name='list_type',
            field=models.CharField(choices=[('PURCHASE', 'Kırtasiye Listesi'), ('INSTITUTION', 'Kurum Verecek Listesi')], default='PURCHASE', max_length=20, verbose_name='Liste Türü'),
        ),
    ]
