# Generated by Django 4.2.27 on 2026-06-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_resources', '0003_add_list_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentresourceassignment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='studentresourceassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'resource_book'), name='unique_active_student_resource'),
        ),
    ]
