# Generated by Django 4.2.27 on 2026-09-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_resources', '0007_student_routine_quota'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentroutinequota',
            new_name='student_rou_student_aed0b5_idx',
            old_name='student_rou_student_6c4b1a_idx',
        ),
        migrations.RenameIndex(
            model_name='studentroutinequota',
            new_name='student_rou_student_dfa5e0_idx',
            old_name='student_rou_student_8a12c0_idx',
        ),
    ]
