# Generated by Django 4.2.27 on 2026-06-30 00:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gorev',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kurum_id', models.IntegerField(verbose_name='Kurum ID')),
                ('sube_id', models.IntegerField(blank=True, null=True, verbose_name='Şube ID')),
                ('egitim_yili_id', models.IntegerField(blank=True, null=True, verbose_name='Eğitim Yılı ID')),
                ('donem_id', models.IntegerField(blank=True, null=True, verbose_name='Dönem ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Başlık')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('oncelik', models.CharField(choices=[('KRITIK', 'Kritik'), ('YUKSEK', 'Yüksek'), ('NORMAL', 'Normal'), ('DUSUK', 'Düşük')], default='NORMAL', max_length=10, verbose_name='Öncelik')),
                ('son_tarih', models.DateTimeField(verbose_name='Son Tarih')),
                ('tahmini_sure_dk', models.PositiveIntegerField(default=30, verbose_name='Tahmini Süre (dk)')),
                ('tum_gun', models.BooleanField(default=False, verbose_name='Tüm Gün')),
                ('hedef_tipi', models.CharField(choices=[('KULLANICI', 'Kullanıcı'), ('ROL', 'Rol'), ('TUM_PERSONEL', 'Tüm Personel'), ('GRUP', 'Grup')], default='KULLANICI', max_length=20, verbose_name='Hedef Tipi')),
                ('hedef_rol_kodu', models.CharField(blank=True, default='', max_length=50, verbose_name='Hedef Rol Kodu')),
                ('hedef_user_ids', models.JSONField(blank=True, default=list, verbose_name='Hedef Kullanıcı ID listesi')),
                ('hedef_grup_id', models.UUIDField(blank=True, null=True, verbose_name='Hedef Grup ID')),
                ('kaynak_modul', models.CharField(blank=True, default='', max_length=50, verbose_name='Kaynak Modül')),
                ('kaynak_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Kaynak ID')),
                ('aksiyon_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Aksiyon URL')),
                ('olusturan_id', models.IntegerField(blank=True, null=True, verbose_name='Oluşturan')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Güncelleyen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
                'db_table': 'gorev',
                'ordering': ['son_tarih'],
            },
        ),
        migrations.CreateModel(
            name='GorevAtama',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('atanan_user_id', models.IntegerField(verbose_name='Atanan Kullanıcı ID')),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('BASLADI', 'Başladı'), ('DEVAM_EDIYOR', 'Devam Ediyor'), ('TAMAMLANDI', 'Tamamlandı'), ('IPTAL', 'İptal')], default='BEKLIYOR', max_length=20, verbose_name='Durum')),
                ('ilk_acilma_at', models.DateTimeField(blank=True, null=True, verbose_name='İlk Açılma')),
                ('baslama_at', models.DateTimeField(blank=True, null=True, verbose_name='Başlama')),
                ('tamamlanma_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma')),
                ('notlar', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('gorusuldu', models.BooleanField(default=False, verbose_name='Görüşüldü')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Görev Ataması',
                'verbose_name_plural': 'Görev Atamaları',
                'db_table': 'gorev_atama',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GorevTipi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kurum_id', models.IntegerField(verbose_name='Kurum ID')),
                ('kod', models.CharField(max_length=30, verbose_name='Kod')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('renk', models.CharField(default='#3B82F6', max_length=7, verbose_name='Renk')),
                ('ikon', models.CharField(default='📋', max_length=10, verbose_name='İkon')),
                ('is_system', models.BooleanField(default=False, verbose_name='Sistem Tipi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Görev Tipi',
                'verbose_name_plural': 'Görev Tipleri',
                'db_table': 'gorev_tipi',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.AddConstraint(
            model_name='gorevtipi',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('kurum_id', 'kod'), name='unique_gorev_tipi_per_kurum'),
        ),
        migrations.AddField(
            model_name='gorevatama',
            name='gorev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atamalar', to='gorev.gorev', verbose_name='Görev'),
        ),
        migrations.AddField(
            model_name='gorev',
            name='gorev_tipi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gorevler', to='gorev.gorevtipi', verbose_name='Görev Tipi'),
        ),
        migrations.AddIndex(
            model_name='gorevatama',
            index=models.Index(fields=['atanan_user_id', 'durum'], name='idx_gorev_atama_user_durum'),
        ),
        migrations.AddConstraint(
            model_name='gorevatama',
            constraint=models.UniqueConstraint(fields=('gorev', 'atanan_user_id'), name='unique_gorev_atama_per_user'),
        ),
        migrations.AddIndex(
            model_name='gorev',
            index=models.Index(fields=['kurum_id', 'son_tarih'], name='idx_gorev_kurum_tarih'),
        ),
        migrations.AddIndex(
            model_name='gorev',
            index=models.Index(fields=['kurum_id', 'oncelik'], name='idx_gorev_kurum_oncelik'),
        ),
        migrations.AddIndex(
            model_name='gorev',
            index=models.Index(fields=['kaynak_modul', 'kaynak_id'], name='idx_gorev_kaynak'),
        ),
    ]
