# Generated by Django 4.2.27 on 2026-06-30 00:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gorev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GorevTekrarSablonu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kurum_id', models.IntegerField(verbose_name='Kurum ID')),
                ('sube_id', models.IntegerField(blank=True, null=True, verbose_name='Şube ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Başlık')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('oncelik', models.CharField(choices=[('KRITIK', 'Kritik'), ('YUKSEK', 'Yüksek'), ('NORMAL', 'Normal'), ('DUSUK', 'Düşük')], default='NORMAL', max_length=10, verbose_name='Öncelik')),
                ('tahmini_sure_dk', models.PositiveIntegerField(default=30, verbose_name='Tahmini Süre (dk)')),
                ('tum_gun', models.BooleanField(default=False, verbose_name='Tüm Gün')),
                ('hedef_tipi', models.CharField(choices=[('KULLANICI', 'Kullanıcı'), ('ROL', 'Rol'), ('TUM_PERSONEL', 'Tüm Personel'), ('GRUP', 'Grup')], default='ROL', max_length=20, verbose_name='Hedef Tipi')),
                ('hedef_rol_kodu', models.CharField(blank=True, default='', max_length=50, verbose_name='Hedef Rol Kodu')),
                ('hedef_user_ids', models.JSONField(blank=True, default=list, verbose_name='Hedef Kullanıcı ID listesi')),
                ('tekrar_tipi', models.CharField(choices=[('GUNLUK', 'Her Gün'), ('HAFTALIK_PAZARTESI', 'Her Pazartesi'), ('HAFTALIK_CUMA', 'Her Cuma'), ('HAFTALIK', 'Her Hafta (belirli gün)'), ('AYLIK_GUN', 'Her Ayın Belirli Günü'), ('AY_SONU', 'Her Ay Sonu')], default='GUNLUK', max_length=30, verbose_name='Tekrar Tipi')),
                ('tekrar_gun', models.PositiveSmallIntegerField(blank=True, help_text='Haftalık: 0=Pazartesi; Aylık: ayın günü (1-28)', null=True, verbose_name='Tekrar Günü')),
                ('sonraki_uretim_tarihi', models.DateField(verbose_name='Sonraki Üretim Tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturan_id', models.IntegerField(blank=True, null=True, verbose_name='Oluşturan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('gorev_tipi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tekrar_sablonlari', to='gorev.gorevtipi', verbose_name='Görev Tipi')),
            ],
            options={
                'verbose_name': 'Görev Tekrar Şablonu',
                'verbose_name_plural': 'Görev Tekrar Şablonları',
                'db_table': 'gorev_tekrar_sablonu',
                'ordering': ['baslik'],
            },
        ),
    ]
