# Generated by Django 4.2.27 on 2026-09-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorev', '0005_gorev_ekran_mesaji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorevatama',
            name='durum',
            field=models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('BASLADI', 'Başladı'), ('DEVAM_EDIYOR', 'Devam Ediyor'), ('TAMAMLANDI', 'Tamamlandı'), ('TAMAMLANMADI', 'Tamamlanamadı'), ('IPTAL', 'İptal')], default='BEKLIYOR', max_length=20, verbose_name='Durum'),
        ),
    ]
