# Generated by Django 4.2.9 on 2026-01-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Alan Adı')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Alan',
                'verbose_name_plural': 'Alanlar',
                'db_table': 'alan',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='SinifSeviyesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Sınıf Seviyesi')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('seviye', models.IntegerField(help_text='0: Anaokulu, 1-12: İlk-Orta-Lise', verbose_name='Seviye Sırası')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('alanlar', models.ManyToManyField(blank=True, related_name='sinif_seviyeleri', to='egitim_tanimlari.alan', verbose_name='Alanlar')),
            ],
            options={
                'verbose_name': 'Sınıf Seviyesi',
                'verbose_name_plural': 'Sınıf Seviyeleri',
                'db_table': 'sinif_seviyesi',
                'ordering': ['seviye'],
            },
        ),
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ders Adı')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('haftalik_ders_saati', models.IntegerField(default=0, verbose_name='Haftalık Ders Saati')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('alanlar', models.ManyToManyField(blank=True, help_text='Bu ders hangi alanlara aittir?', related_name='dersler', to='egitim_tanimlari.alan', verbose_name='Alanlar')),
                ('sinif_seviyeleri', models.ManyToManyField(blank=True, help_text='Bu ders hangi sınıf seviyelerinde okutulur?', related_name='dersler', to='egitim_tanimlari.sinifseviyesi', verbose_name='Sınıf Seviyeleri')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'db_table': 'ders',
                'ordering': ['ad'],
            },
        ),
    ]
