# Generated by Django 4.2.9 on 2026-01-31 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_tanimlari', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ders',
            name='haftalik_ders_saati',
        ),
    ]
