# Generated by ChatGPT on 2026-01-31
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egitim_tanimlari", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sinifseviyesi",
            name="ogrenci_no_prefix",
            field=models.CharField(blank=True, max_length=2, verbose_name="Öğrenci No Prefix"),
        ),
    ]
