# Generated by Django 4.2.9 on 2026-01-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_tanimlari', '0003_remove_haftalik_ders_saati'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Branş Adı')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Branş',
                'verbose_name_plural': 'Branşlar',
                'db_table': 'brans',
                'ordering': ['ad'],
            },
        ),
    ]
