# Generated by Django 4.2.9 on 2026-01-31 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_tanimlari', '0004_brans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sinifseviyesi',
            options={'ordering': ['ad'], 'verbose_name': 'Sınıf Seviyesi', 'verbose_name_plural': 'Sınıf Seviyeleri'},
        ),
        migrations.RemoveField(
            model_name='sinifseviyesi',
            name='seviye',
        ),
    ]
