# Generated by Django 4.2.9 on 2026-01-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_tanimlari', '0005_remove_sinif_seviyesi_seviye_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alan',
            options={'ordering': ['sira', 'ad'], 'verbose_name': 'Alan', 'verbose_name_plural': 'Alanlar'},
        ),
        migrations.AlterModelOptions(
            name='sinifseviyesi',
            options={'ordering': ['sira', 'ad'], 'verbose_name': 'Sınıf Seviyesi', 'verbose_name_plural': 'Sınıf Seviyeleri'},
        ),
        migrations.AddField(
            model_name='alan',
            name='sira',
            field=models.IntegerField(default=0, verbose_name='Sıra'),
        ),
        migrations.AddField(
            model_name='sinifseviyesi',
            name='sira',
            field=models.IntegerField(default=0, verbose_name='Sıra'),
        ),
    ]
