# Generated by Django 4.2.9 on 2026-01-31 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_tanimlari', '0006_add_sira_field'),
    ]

    operations = [
    ]
