# Generated by Django 4.2.9 on 2026-01-31 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_tanimlari', '0002_sinif_seviyesi_ogrenci_no_prefix'),
        ('egitim_tanimlari', '0008_populate_sira_values'),
    ]

    operations = [
    ]
