# Generated by Django 4.2.27 on 2026-09-23 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sube', '0003_sube_branding'),
        ('kurum', '0003_alter_kurum_app_logo_alter_kurum_favicon_and_more'),
        ('egitim_tanimlari', '0011_ders_kisa_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alan',
            name='kurum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='kurum.kurum', verbose_name='Kurum'),
        ),
        migrations.AlterField(
            model_name='alan',
            name='sube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='sube.sube', verbose_name='Şube'),
        ),
        migrations.AlterField(
            model_name='brans',
            name='kurum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='kurum.kurum', verbose_name='Kurum'),
        ),
        migrations.AlterField(
            model_name='brans',
            name='sube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='sube.sube', verbose_name='Şube'),
        ),
        migrations.AlterField(
            model_name='ders',
            name='kurum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='kurum.kurum', verbose_name='Kurum'),
        ),
        migrations.AlterField(
            model_name='ders',
            name='sube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='sube.sube', verbose_name='Şube'),
        ),
        migrations.AlterField(
            model_name='sinifseviyesi',
            name='kurum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='kurum.kurum', verbose_name='Kurum'),
        ),
        migrations.AlterField(
            model_name='sinifseviyesi',
            name='sube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='sube.sube', verbose_name='Şube'),
        ),
    ]
