# Generated by Django 4.2.27 on 2026-02-08 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egitim_tanimlari', '0009_merge_20260201_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Kitap Adı')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('book_type', models.CharField(choices=[('TEST_BOOK', 'Test Kitabı'), ('SUBJECT_BOOK', 'Konu Kitabı'), ('MIXED_BOOK', 'Karışık Kitap'), ('PRACTICE_BOOK', 'Çalışma Kitabı')], default='MIXED_BOOK', max_length=20, verbose_name='Kitap Türü')),
                ('yayinevi', models.CharField(blank=True, max_length=200, verbose_name='Yayınevi')),
                ('yazar', models.CharField(blank=True, max_length=200, verbose_name='Yazar')),
                ('yayin_yili', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yayın Yılı')),
                ('toplam_sayfa', models.PositiveIntegerField(blank=True, null=True, verbose_name='Toplam Sayfa')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('kapak_url', models.URLField(blank=True, verbose_name='Kapak URL')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_books', to='egitim_tanimlari.ders', verbose_name='Ders')),
                ('sinif_seviyesi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_books', to='egitim_tanimlari.sinifseviyesi', verbose_name='Sınıf Seviyesi')),
            ],
            options={
                'verbose_name': 'Kaynak Kitap',
                'verbose_name_plural': 'Kaynak Kitaplar',
                'db_table': 'resource_book',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='ResourceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Ünite Adı')),
                ('kod', models.CharField(max_length=50, verbose_name='Kod')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='resources.resourcebook', verbose_name='Kitap')),
            ],
            options={
                'verbose_name': 'Ünite',
                'verbose_name_plural': 'Üniteler',
                'db_table': 'resource_unit',
                'ordering': ['sira', 'ad'],
                'unique_together': {('book', 'kod')},
            },
        ),
        migrations.CreateModel(
            name='ResourceTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Konu Adı')),
                ('kod', models.CharField(max_length=50, verbose_name='Kod')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='resources.resourceunit', verbose_name='Ünite')),
            ],
            options={
                'verbose_name': 'Konu',
                'verbose_name_plural': 'Konular',
                'db_table': 'resource_topic',
                'ordering': ['sira', 'ad'],
                'unique_together': {('unit', 'kod')},
            },
        ),
        migrations.CreateModel(
            name='ResourceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='İçerik Adı')),
                ('content_type', models.CharField(choices=[('TEST_SET', 'Test Seti'), ('SUBJECT_SECTION', 'Konu Anlatımı'), ('PAGE_RANGE', 'Sayfa Aralığı'), ('EXERCISE', 'Alıştırma'), ('VIDEO', 'Video'), ('CUSTOM', 'Özel İçerik')], default='CUSTOM', max_length=20, verbose_name='İçerik Türü')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('question_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Soru Sayısı')),
                ('difficulty', models.CharField(blank=True, choices=[('EASY', 'Kolay'), ('MEDIUM', 'Orta'), ('HARD', 'Zor'), ('MIXED', 'Karışık')], default='MIXED', max_length=10, verbose_name='Zorluk')),
                ('page_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='Başlangıç Sayfa')),
                ('page_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bitiş Sayfa')),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tahmini Süre (dk)')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('video_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Video Süresi (sn)')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='resources.resourcetopic', verbose_name='Konu')),
            ],
            options={
                'verbose_name': 'İçerik',
                'verbose_name_plural': 'İçerikler',
                'db_table': 'resource_content',
                'ordering': ['sira', 'ad'],
            },
        ),
    ]
