# Generated by Django 4.2.27 on 2026-02-08 16:13

from django.db import migrations, models
import django.db.models.deletion


def create_default_book_types(apps, schema_editor):
    """Varsayılan kitap türlerini oluştur"""
    BookType = apps.get_model('resources', 'BookType')
    
    default_types = [
        {'kod': 'TEST_BOOK', 'ad': 'Test Kitabı', 'renk': 'danger', 'ikon': '📝', 'sira': 1},
        {'kod': 'SUBJECT_BOOK', 'ad': 'Konu Kitabı', 'renk': 'info', 'ikon': '📚', 'sira': 2},
        {'kod': 'MIXED_BOOK', 'ad': 'Karışık Kitap', 'renk': 'warning', 'ikon': '📖', 'sira': 3},
        {'kod': 'PRACTICE_BOOK', 'ad': 'Çalışma Kitabı', 'renk': 'success', 'ikon': '✏️', 'sira': 4},
    ]
    
    for bt in default_types:
        BookType.objects.get_or_create(kod=bt['kod'], defaults=bt)


def migrate_book_types(apps, schema_editor):
    """Mevcut book_type string değerlerini ForeignKey'e dönüştür"""
    ResourceBook = apps.get_model('resources', 'ResourceBook')
    BookType = apps.get_model('resources', 'BookType')
    
    # String → ID mapping
    type_mapping = {}
    for bt in BookType.objects.all():
        type_mapping[bt.kod] = bt.id
    
    # Varsayılan tür (MIXED_BOOK)
    default_type = BookType.objects.filter(kod='MIXED_BOOK').first()
    default_id = default_type.id if default_type else 1
    
    # Tüm kitapları güncelle
    for book in ResourceBook.objects.all():
        old_type = book.book_type_old if hasattr(book, 'book_type_old') else 'MIXED_BOOK'
        book.book_type_id = type_mapping.get(old_type, default_id)
        book.save()


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        # 1. BookType modelini oluştur
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('ad', models.CharField(max_length=100, verbose_name='Tür Adı')),
                ('renk', models.CharField(default='secondary', help_text='primary, success, warning, danger, info, secondary', max_length=20, verbose_name='Badge Rengi')),
                ('ikon', models.CharField(blank=True, help_text='Emoji veya ikon kodu', max_length=50, verbose_name='İkon')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Kitap Türü',
                'verbose_name_plural': 'Kitap Türleri',
                'db_table': 'resource_book_type',
                'ordering': ['sira', 'ad'],
            },
        ),
        
        # 2. Varsayılan türleri oluştur
        migrations.RunPython(create_default_book_types),
        
        # 3. Mevcut book_type alanını yeniden adlandır
        migrations.RenameField(
            model_name='resourcebook',
            old_name='book_type',
            new_name='book_type_old',
        ),
        
        # 4. Yeni ForeignKey alanını ekle (nullable)
        migrations.AddField(
            model_name='resourcebook',
            name='book_type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='books',
                to='resources.booktype',
                verbose_name='Kitap Türü'
            ),
        ),
        
        # 5. Mevcut verileri migrate et
        migrations.RunPython(migrate_book_types),
        
        # 6. Eski alanı sil
        migrations.RemoveField(
            model_name='resourcebook',
            name='book_type_old',
        ),
        
        # 7. Yeni alanı zorunlu yap
        migrations.AlterField(
            model_name='resourcebook',
            name='book_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='books',
                to='resources.booktype',
                verbose_name='Kitap Türü'
            ),
        ),
    ]
