# Generated by Django 4.2.9 on 2026-02-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_booktype_alter_resourcebook_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebook',
            name='zorluk_max',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-10 arası maksimum zorluk seviyesi', null=True, verbose_name='Maksimum Zorluk'),
        ),
        migrations.AddField(
            model_name='resourcebook',
            name='zorluk_min',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-10 arası minimum zorluk seviyesi', null=True, verbose_name='Minimum Zorluk'),
        ),
    ]
