# Generated by Django 4.2.27 on 2026-07-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_resourcebook_kapak'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebook',
            name='icerik_tamamlandi_mi',
            field=models.BooleanField(default=False, verbose_name='İçerik Tamamlandı'),
        ),
        migrations.AlterField(
            model_name='resourcebook',
            name='zorluk_max',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0-10 arası maksimum zorluk seviyesi', null=True, verbose_name='Maksimum Zorluk'),
        ),
        migrations.AlterField(
            model_name='resourcebook',
            name='zorluk_min',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0-10 arası minimum zorluk seviyesi', null=True, verbose_name='Minimum Zorluk'),
        ),
    ]
