# Generated by Django 4.2.9 on 2026-01-30 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egitim_yili', '0001_initial'),
        ('egitim_tanimlari', '0001_initial'),
        ('sube', '0001_initial'),
        ('kurum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='Örn: 9-A, 10-B', max_length=100, verbose_name='Sınıf Adı')),
                ('kod', models.CharField(blank=True, max_length=50, verbose_name='Sınıf Kodu')),
                ('kapasite', models.IntegerField(default=30, verbose_name='Kapasite')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('alan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siniflar', to='egitim_tanimlari.alan', verbose_name='Alan')),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniflar', to='egitim_yili.egitimyili', verbose_name='Eğitim Yılı')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniflar', to='kurum.kurum', verbose_name='Kurum')),
                ('sinif_seviyesi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siniflar', to='egitim_tanimlari.sinifseviyesi', verbose_name='Sınıf Seviyesi')),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniflar', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Sınıf',
                'verbose_name_plural': 'Sınıflar',
                'db_table': 'sinif',
                'ordering': ['egitim_yili', 'ad'],
                'indexes': [models.Index(fields=['kurum', 'sube', 'egitim_yili', 'aktif_mi'], name='sinif_kurum_i_e6d177_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sinif',
            constraint=models.UniqueConstraint(fields=('kurum', 'sube', 'egitim_yili', 'ad'), name='unique_sinif_per_year'),
        ),
    ]
