# Generated by Django 4.2.27 on 2026-02-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oda', '0001_initial'),
        ('sinif', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinif',
            name='oda',
            field=models.ForeignKey(blank=True, help_text='Sınıfın kullandığı fiziksel oda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siniflar', to='oda.oda', verbose_name='Atanan Oda'),
        ),
    ]
