# Generated by Django 4.2.27 on 2026-02-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sube', '0001_initial'),
        ('kurum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='Örn: A-101, Laboratuvar 1, Toplantı Odası', max_length=100, verbose_name='Oda Adı')),
                ('kapasite', models.PositiveIntegerField(default=30, help_text='Odanın maksimum kişi kapasitesi', verbose_name='Kapasite (Kişi)')),
                ('oda_turu', models.CharField(blank=True, choices=[('derslik', 'Derslik'), ('laboratuvar', 'Laboratuvar'), ('toplanti', 'Toplantı Salonu'), ('kutuphane', 'Kütüphane'), ('spor', 'Spor Salonu'), ('yemekhane', 'Yemekhane'), ('ofis', 'Ofis'), ('diger', 'Diğer')], default='derslik', max_length=20, verbose_name='Oda Türü')),
                ('aciklama', models.TextField(blank=True, help_text='Oda hakkında ek bilgiler', verbose_name='Açıklama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odalar', to='kurum.kurum', verbose_name='Kurum')),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odalar', to='sube.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Oda',
                'verbose_name_plural': 'Odalar',
                'db_table': 'oda',
                'ordering': ['sube', 'ad'],
                'indexes': [models.Index(fields=['kurum', 'sube', 'aktif_mi'], name='oda_kurum_i_3a6a0f_idx'), models.Index(fields=['oda_turu'], name='oda_oda_tur_d601c0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='oda',
            constraint=models.UniqueConstraint(fields=('kurum', 'sube', 'ad'), name='unique_oda_per_sube'),
        ),
    ]
